### ISSUE TITLE
Nukkit support

### ISSUE THREAD

**Issue by Russia9** [plan-player-analytics/Plan#1020]
### Is your feature request related to a problem? Please describe.
I would like to use Plan on the Nukkit core. Nukkit - core for Pocket Edition Servers.

### Describe the solution you'd like
I would like to see the same Plan, as on spigot and sponge, for nukkit

### Describe alternatives you've considered
I can not find other alternatives, except how to look at a large number of entries in the logs

**Comment by JourneyPlayz** [comment]
I'd love ot see this feature aswell.
