### ISSUE TITLE
Server site 

### ISSUE THREAD

**Issue by xXSchrandXx** [plan-player-analytics/Plan#1037]
### Describe the bug

Need to see it by yourself: [Lobby](https://leaderboard.ragebears.de:8804/server/Lobby)

### Server information

[Debugpage](https://leaderboard.ragebears.de:8804/debug)

### Additional information

Running spigot servers local.

**Comment by Rsl1122** [comment]
You have HTTPS enabled so I can not access the site. Please describe the issue and include a screenshot if necessary.

**Comment by xXSchrandXx** [comment]
SSL disabled

**Comment by xXSchrandXx** [comment]
http://leaderboard.ragebears.de:8804/server/Lobby

**Comment by Rsl1122** [comment]
Your BungeeCord is running 4.8.2 while the other server is running 4.8.1, leading to this issue.

**Comment by xXSchrandXx** [comment]
woops doing it now...

**Comment by xXSchrandXx** [comment]
done... sry

**Comment by Rsl1122** [comment]
No Problemo 👌
