### ISSUE TITLE
Issues with bungee commands

### ISSUE THREAD

**Issue by MrLightningBlaze** [plan-player-analytics/Plan#1038]
### Describe the bug
It works fine on my spigot/bukkit servers directly, but doesn't properly load on the Bungee server for them. The webserver works and it seems to gather data, but all of the plan commands say they do not exist, and provided a java.lang.NoClassDefFoundError on startup

### Server Information
**Plan Version:** 4.8.2
**Server:** BungeeCord git:BungeeCord-Bootstrap:1.14-SNAPSHOT:086eb84:1411 (git:BungeeCord-Bootstrap:1.14-SNAPSHOT:086eb84:1411)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 5.0.10-arch1-1-ARCH
**Java Version:** 1.8.0_212, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.212-b01, Oracle Corporation

### Exceptions & Other Logs
Error from startup:
https://pastebin.com/daQSpfG1

### Additional information
Happens every startup, works perfectly except for the lack of commands meaning I can't link the Bukkit and Bungee plugins, should also note that the Bukkit/Spigot server works perfectly, including commands.

**Comment by Rsl1122** [comment]
Looks like one of your other plugins has Vault included inside it (This is a bad practice). You can find the culprit by looking for net/milkbowl/vault folder inside the jar files. The deletion of the Vault files should stop the error (until a fix) 

On Bungee /plan command is not available, use /planbungee instead. It might also be possible that the error stops the plugin from starting up.

**Comment by MrLightningBlaze** [comment]
I am aware that bungee has planbungee, that is what I meant by the commands, sorry if that wasn't clear.
Found and removed the vault files, and it resolved and commands now work, thank you.

**Comment by Rsl1122** [comment]
I'll reopen this since I can prevent the error in the future.

I also recommend notifying the author of that plugin about Vault classes being shaded in.
