### ISSUE TITLE
First time players do not appear on /server Players tab

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1045]
### Describe the bug

First time players do not appear on Players tab of /server page until they have logged out and their first session is stored in the database.

This occurs because the query for the players table will fetch *x most recent* players and uses `plan_sessions` for this information - which is not stored until the player logs out.

**Comment by Rsl1122** [comment]
BungeeCord should not store ongoing session in the database, and only should store the session if another server has not stored the ongoing session when the session ends.

**Comment by AuroraLS3** [comment]
Considering that #1481 will also sort this out.
