### ISSUE TITLE
Plan Error

### ISSUE THREAD

**Issue by lukemango** [plan-player-analytics/Plan#1057]
### Describe the bug

Trying to /plan analyze and click the link presents this error on the webserver https://pastebin.com/aAujAkZa

### Server information

git-Paper-55 - 1.14.2
Plan 4.8.5

### Exceptions & Other Logs

https://pastebin.com/aAujAkZa

### Additional information

N/a
**Frequency of occurrence**: <>
Every time
**Other:**

**Comment by Rsl1122** [comment]
It sounds like one of your servers that is connected to the bungee shares the address with another server.

Ensure that all servers have an unique address:

- Go to web: `<bungee plan address>/debug` and locate `Servers` section. Ensure that all servers have an unique port
or
- Check that all servers have unique port from their configs on `<Bungee folder>/plugins/Plan/serverConfiguration`
