### ISSUE TITLE
H2 init failure (Error 90030)

### ISSUE THREAD

**Issue by 1LiterZinalco** [plan-player-analytics/Plan#1070]
### Describe the bug
Plan was running for about 6 days now. It suddenly stopped working altough nothing (except the world ofc) changed on the server.

### Server information
Forge 1.12.2 – 14.23.5.2836
SpongeForge 1.12.2 – 2768-7.1.6-RC3616
Plan 4.8.5

### Exceptions & Other Logs
Console: https://pastebin.com/raw/Ny6WQscP
_Plan's log: Not existing. Folder is empty._

**Comment by Rsl1122** [comment]
Looks like the H2 database file is corrupted

> FILE_CORRUPTED_1 = 90030
The error with code 90030 is thrown when the database engine has detected a checksum mismatch in the data or index. To solve this problem, restore a backup or use the Recovery tool (org.h2.tools.Recover).
> 
> https://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90030

**Comment by Rsl1122** [comment]
You might be able to fix this with a H2 recovery tool, but it is outside of code influence, thus the label above.

Another option is starting fresh with another database type (SQLite / MySQL) or restoring from a backup

**Comment by 1LiterZinalco** [comment]
Yeah, I wasn't assuming you could "help me fix" my database. But since Plan is probably causing the issue (at least I can't find another reason) I felt like letting you know that there might be a problem with Plan causing corrupted databases.
