### ISSUE TITLE
Spam in Console on startup

### ISSUE THREAD

**Issue by Cosido** [plan-player-analytics/Plan#1075]
https://gist.githubusercontent.com/Cosido/b20216c84414586aa5fbcced4a49ac37/raw/8ee28616a1f4892f87c11f4308c248d05a247017/gistfile1.txt

### Server information

MC 1.12.2
Forge 2838
SpongeForge 3785
Plan 4.8.6

**Comment by Rsl1122** [comment]
Another person was having this issue as well, it went away on second enable

My message from Discord

> I can't find this error reported, so I guess it's a new issue.
>
>Plan is involved in the error because Plan has a `DataExtension` for Nucleus, that uses Nucleus API. 
The error occurs very deep in the Nucleus internals, so I'd assume it has something to do with how Nucleus works. Plan calls `WarpService#getAllWarps`
>
> ```
>at >io.github.nucleuspowered.nucleus.modules.warp.services.WarpHandler.getAllWarps(WarpHandler.java:55)
>```
>
>If it keeps occurring you can disable the interaction in Plan config under Plugins.Nucleus.Enabled - You can try reporting the issue on their github
Something seems to be null on this line https://github.com/NucleusPowered/Nucleus/blob/sponge-api/7/src/main/java/io/github/nucleuspowered/nucleus/dataservices/modular/DataModule.java#L75
It might be a configuration issue with Nucleus.

It definitely sounds like an issue with one of the human readable configuration files, do you have a `warps` file of some kind?

**Comment by Cosido** [comment]
https://gist.github.com/Cosido/e66d63a70740b346b857ed846d3444a1

I use Nucleus for my warps, that would be my file that contains their info. Unsure if thats the one your looking for or the file in the mySQL if there is one, I dont go into that unless I have to so im assuming you want that

**Comment by Rsl1122** [comment]
I have opened a pull request to Nucleus repository with a potential fix.

**Comment by dualspiral** [comment]
Are your warps working otherwise?

**Comment by dualspiral** [comment]
I spotted it. This is a Nucleus issue, not a Plan issue. I load the general data file during the server started event.

Basically, Nucleus has an option to tell it when world UUIDs change in Sponge. As the data file contains UUIDs for worlds (for the warps, no less!) I load the file after the server has started to enable the UUIDs to be translated... which means a null node.

I'll just load the file earlier and then ask it to migrate after.

**Comment by Rsl1122** [comment]
Nice! Thank you & well spotted :)

**Comment by dualspiral** [comment]
https://github.com/NucleusPowered/Nucleus/commit/370432db1386f9cbb4536aba0ae94ab5456412da
