### ISSUE TITLE
AntiVPN/AltFinder Support Issue

### ISSUE THREAD

**Issue by Cosido** [plan-player-analytics/Plan#1076]
### Describe the bug

https://i.imgur.com/tXgLKjA.png

### Server information

Waterfall (Proxy) Build 284
Plan 4.8.6

### Additional information
Contacted the author awhile back and suggested it could have been a change on Plans end, Get these errors on startup on proxy
https://gist.github.com/Cosido/c7c4cac654e377d3c50cfb2c9450e4d1

**Frequency of occurrence**: 
Occurs at startup

**Comment by Rsl1122** [comment]
I was not able to reproduce the issue using Plan 4.8.6, AltFinder (Bungee) v3.4.23 and Waterfall build 284

**Comment by Rsl1122** [comment]
Alright so this was caused by other plugins (tested with them after you sent them on Dicord) - I'll close this since I can't really do anything about it

> I can't really do anything about the issue since it's caused by Bungee enabling AntiVPN before Plan even though softdepend has Plan in it
> ~ me on discord
