### ISSUE TITLE
Add a way to disable ping

### ISSUE THREAD

**Issue by lucas2107** [plan-player-analytics/Plan#1080]
### Is your feature request related to a problem? Please describe.

The ping feature is adding a million of entries per day on my server, it's overloading the database.

### Describe the solution you'd like

Add a line in config to remove ping option.

### Describe alternatives you've considered

/

### Additional context

/

**Comment by Rsl1122** [comment]
You can do this by setting `DataGathering.Ping` to `false`.

This setting was added in 4.8.2 - I recommend the latest version.
