### ISSUE TITLE
Missing API specification with 1.14.

### ISSUE THREAD

**Issue by mibby** [plan-player-analytics/Plan#1086]
```
[13:22:54] [Server thread/WARN]: Plugin Plan v4.8.6 does not specify an api-version.
```

**Comment by Aurelien30000** [comment]
Not important, just a warning, but Plan can't specify that because it's a plugin available for 1.8-1.14 (multi-version support) :)

**Comment by Rsl1122** [comment]
Hmm, I wonder if it would work on all versions even with api version of 1
13 :thinking:

**Comment by Aurelien30000** [comment]
🤔 Some docs from spigot website : https://imgur.com/a/shWLov9

**Comment by Rsl1122** [comment]
Damn, that's going to complicate things in the future

**Comment by Rsl1122** [comment]
I have added `api-version: 1.13` to the plugin.yml.

I hope I am reading the docs from Spigot correctly in that plugin stops working if api-version is unknown, or higher than current version (eg 1.15 would not work on 1.14, but 1.14 would work on 1.15)
