### ISSUE TITLE
Full external website support

### ISSUE THREAD

**Issue by lucas2107** [plan-player-analytics/Plan#1091]
### Is your feature request related to a problem? Please describe.

Yes, I'm going to run PLAN on a large network, and having the PLAN web interface running on my bungee isn't the best way for performances...

### Describe the solution you'd like

Maybe you could add a full external website. Connected to the database.

### Describe alternatives you've considered

/

### Additional context

/

**Comment by Rsl1122** [comment]
Do you mean running Plan standalone? ;)

**Comment by lucas2107** [comment]
I mean, running Plan on bungee/spigot servers and running the web interface on a an apache server instead of running the web interface on the plugin itself ^^

**Comment by Rsl1122** [comment]
That is unfortunately not possible since most of the SQL queries are done with Java.
To port to pure JavaScript / PHP solution would take too much work.

Standalone version is a more manageable goal, and is planned to be the next long term goal after removal of Bungee-Server connection requirement.

**Comment by Rsl1122** [comment]
That said the export functionality will improve with the removal of Bungee-Server connection system, allowing export on Bungee without the webservers running.
