### ISSUE TITLE
Random server crash with console error

### ISSUE THREAD

**Issue by Leonardo-Fiori** [plan-player-analytics/Plan#1099]
### Describe the bug
I got this random crash, could not reproduce it or could not find an explanation. I think that Plan is involved.

### Server information
Plan Version: 4.8.6
Server is running Paper version git-Paper-97 (MC: 1.14.2)

### Exceptions & Other Logs
https://pastebin.com/BWWhSYAb

**Frequency of occurrence**:
Very rare? Never happened before, i installed Plan some weeks ago.

**Comment by Rsl1122** [comment]
Looks like your server thread was performing a chunk save at the time of the crash.

```
Server thread dump (Look for plugins here before reporting to Paper!):
------------------------------
Current Thread: Server thread
 PID: 21 | Suspended: false | Native: false | State: RUNNABLE
  Stack:
      java.base@11.0.3/java.io.RandomAccessFile.writeBytes(Native Method)
      java.base@11.0.3/java.io.RandomAccessFile.write(RandomAccessFile.java:559)
      app//net.minecraft.server.v1_14_R1.RegionFile.writeIntAndByte(RegionFile.java:384)
      app//net.minecraft.server.v1_14_R1.RegionFile.a(RegionFile.java:322)
      app//net.minecraft.server.v1_14_R1.RegionFile.writeChunkData(RegionFile.java:319)
      app//net.minecraft.server.v1_14_R1.RegionFile.writeChunk(RegionFile.java:390)
      app//net.minecraft.server.v1_14_R1.RegionFile.a(RegionFile.java:292)
      app//net.minecraft.server.v1_14_R1.RegionFile$ChunkBuffer.close(RegionFile.java:562)
      java.base@11.0.3/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
      ...
```

One Plan thread is in execution gathering data from CoreProtect API on an async thread, other Plan threads are waiting. - This should not be the cause of the crash.

**Comment by Leonardo-Fiori** [comment]
> Looks like your server thread was performing a chunk save at the time of the crash.
> 
> ```
> Server thread dump (Look for plugins here before reporting to Paper!):
> ------------------------------
> Current Thread: Server thread
>  PID: 21 | Suspended: false | Native: false | State: RUNNABLE
>   Stack:
>       java.base@11.0.3/java.io.RandomAccessFile.writeBytes(Native Method)
>       java.base@11.0.3/java.io.RandomAccessFile.write(RandomAccessFile.java:559)
>       app//net.minecraft.server.v1_14_R1.RegionFile.writeIntAndByte(RegionFile.java:384)
>       app//net.minecraft.server.v1_14_R1.RegionFile.a(RegionFile.java:322)
>       app//net.minecraft.server.v1_14_R1.RegionFile.writeChunkData(RegionFile.java:319)
>       app//net.minecraft.server.v1_14_R1.RegionFile.writeChunk(RegionFile.java:390)
>       app//net.minecraft.server.v1_14_R1.RegionFile.a(RegionFile.java:292)
>       app//net.minecraft.server.v1_14_R1.RegionFile$ChunkBuffer.close(RegionFile.java:562)
>       java.base@11.0.3/java.io.FilterOutputStream.close(FilterOutputStream.java:188)
>       ...
> ```
> 
> One Plan thread is in execution gathering data from CoreProtect API on an async thread, other Plan threads are waiting. - This should not be the cause of the crash.

Ok.. so should i report it to paper? When reporting a crash they explicitly state to **do not report** issues stating "DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH" like this one

**Comment by Rsl1122** [comment]
I think those refer to the thread dumps above the crash dump - crash dump starts on line 106
