### ISSUE TITLE
Add Navigation Links to 403 Forbidden page

### ISSUE THREAD

**Issue by FatalBlade** [plan-player-analytics/Plan#1100]
### Is your feature request related to a problem? Please describe.
When a player runs /plan register <password> the link they are given takes them to the /server page by default which most players don't have access to so it gives them a 404 forbidden error and there isn't anything they can click on to get them to their player tab or the players tab from that interface. Instead, they have to manually remove /server from the url to be redirected.

### Describe the solution you'd like
Add some way to navigate back to an area of Plan the user has access to. 

### Describe alternatives you've considered
Have the "click me" link take them to the base URL/IP for Plan
![click me](https://user-images.githubusercontent.com/22067704/61187630-ebc2ad80-a641-11e9-9d43-da8730badeb0.png)

**Comment by Rsl1122** [comment]
Hmm, that's odd - the address that is used is already the base url.

```
> plan register test2 test2 2
[12:55:35 INFO]: [Plan] [DEBUG] [SQL] Executing: RegisterWebUserTransaction
[12:55:35 INFO]: Added a new user (test2) successfully! You can view the web panel in the following link.
[12:55:35 INFO]:   Link: https://localhost:8804
[12:55:35 INFO]: [Plan] [DEBUG] [] Registered new user: 'test2' Perm level: 2
[12:55:35 INFO]: [Plan] Registered new user: 'test2' Perm level: 2
```

----

Are you using the latest version (4.8.7)?

**Comment by Rsl1122** [comment]
Please note that if the user does not have the correct permissions, they will be assigned a permission level 100, which doesn't allow them to access any pages (In this case any page will be 403 Forbidden)

**Comment by FatalBlade** [comment]
My apologies I had been away for a few days on vacation and for some reason wasn't notified of your response. I had given the users the permission "plan.inspect.other" Which should have given them permission level 1. I will have to do a bit of testing tomorrow once I get everything set back up. Once again sorry for the late reply.

**Comment by Rsl1122** [comment]
No worries :)

**Comment by Rsl1122** [comment]
How did the testing go? :)
