### ISSUE TITLE
Non-proprietary certificate format support

### ISSUE THREAD

**Issue by Brycey92** [plan-player-analytics/Plan#1102]
### Is your feature request related to a problem? Please describe.

Converting from widely used certificate formats to Java keystores makes me wish encryption was never invented.

### Describe the solution you'd like

I would love it if Plan supported PEM or PKCS12 or P7B files, or any other easy-to-export certificate format.

### Describe alternatives you've considered

I could make Plan use a proxy's encryption instead of its own, but it would still be more work than slapping a PKCS12 file into Plan's config folder.

**Comment by Rsl1122** [comment]
Good news, Java 8 supports PKCS12
https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#KeyStore

I assume it would be "easy" to change wanted keystore based on file extension
https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/system/webserver/WebServer.java#L182

Of course there might be a lot of unseen difficulties, so this remains in low priority for now.
I'll post a comment when I know more.

**Comment by Brycey92** [comment]
Thanks for looking into it!

**Comment by Rsl1122** [comment]
Looks like it was more painless than I expected!
I made old https test more abstract so I was able to test the pcks12 support automatically :o

It'll definitely make it easier to install https, dropping needed commands down to 2 from 6.

Next version will have support for this. I'll probably get dev release out tomorrow.
