### ISSUE TITLE
Error 500 Internal Error occurred on player page

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1119]
### Describe the bug

When clicking on a playername to see some information about the account there is a error500 shown

### Server information

bungeecord build#1418
Plan version 4.8.8

### Exceptions & Other Logs

https://gist.github.com/thunderlight411/c7e2e3e3c0ea5a4c0834ffe0a47ee4de

### Additional information

**Frequency of occurrence**: Everytime you request player information

**Comment by Rsl1122** [comment]
I suspect there is a world name with something odd going on - could you send `World_aliases` in your config.yml?

**Comment by thunderlight411** [comment]
`World_aliases:
    world: world
    bskyblock_world_nether: bskyblock_world_nether
    bskyblock_world_the_end: bskyblock_world_the_end
    bskyblock_world: bskyblock_world
    pretpark: pretpark
    world_the_end: world_the_end
    world_nether: world_nether
    CreA2: CreA2
    CreA: CreA
    acidisland_world: acidisland_world
    City: City`

**Comment by thunderlight411** [comment]
to make it more clear

full config files without private information
https://gist.github.com/thunderlight411/5fc77fb8684f0c6194416fc906f38556

**Comment by Rsl1122** [comment]
Seems like this error is caused when the code is figuring out the current world on Bungee (Current world is used for longest played world if session has not ended), but the code doesn't take into account that Bungee doesn't have world information for online sessions.

You can prevent this exception (until the fix arrives) by changing settings:
```
Display_options:
    Sessions:
        Show_most_played_world_in_title: false
```

**Comment by thunderlight411** [comment]
Thanks for your reply going to check that out after the nightly reboot.
keep you posted


Op zo 28 jul. 2019 om 18:22 schreef Risto Lahtela <notifications@github.com
