### ISSUE TITLE
Console error when new players join (ProtocolSupport integration) 

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1124]
### Describe the bug
When a player joins my server for the first time Plan sends an error in console.

### Server information
Paper 1.12.2, Plan 4.9.1

### Exceptions & Other Logs
[https://pastebin.com/4ETy5RgY](https://pastebin.com/4ETy5RgY)

### Additional information
Nope

**Frequency of occurrence**:
Depends on when new players join.

**Comment by Rsl1122** [comment]
You can prevent the error temporarily by disabling ProtocolSupport integration in the Plan config

**Comment by Rsl1122** [comment]
I'm trying to figure out this error, but I don't understand why it occurred yet.

One possible cause would be two different tasks trying to store information about the same player - Do you have both ProtocolSupport and ViaVersion installed?

**Comment by DrakePork** [comment]
Yeah

**Comment by Rsl1122** [comment]
I decided to go with a workaround that disables the join listener for ProtocolSupport version if ViaVersion is also present.
The fix will be available in the next version.
