### ISSUE TITLE
Plan Velocity does not cancel recurring tasks on plugin reload

### ISSUE THREAD

**Issue by zsn741656478** [plan-player-analytics/Plan#1125]
### Describe the bug
Velocity can't read TPS data.

### Server information
Velocity 1.0.3 with Plan 4.9.1

### Exceptions & Other Logs
https://i.loli.net/2019/08/04/XF1YUObABSf5hky.png
https://i.loli.net/2019/08/04/ZOt8HouA1eqjs4i.png

### Additional information
Config: https://paste.ubuntu.com/p/vtBxYfjDQY/

**Frequency of occurrence**: <Always>

**Other:**

**Comment by Rsl1122** [comment]
Database is closed. Could you send what Plan says when it enables

**Comment by zsn741656478** [comment]
> Database is closed. Could you send what Plan says when it enables

Plan log: https://paste.ubuntu.com/p/pnFKnpkJ9v/
Velocity log: https://paste.ubuntu.com/p/FBKj54kVtv/

**Comment by Rsl1122** [comment]
I think it might be an issue with Plan not cancelling recurring tasks on a reload - Does the issue occur before reloading the plugin?

**Comment by zsn741656478** [comment]
> I think it might be an issue with Plan not cancelling recurring tasks on a reload - Does the issue occur before reloading the plugin?

I am going to test, please wait a moment.

**Comment by zsn741656478** [comment]
> I think it might be an issue with Plan not cancelling recurring tasks on a reload - Does the issue occur before reloading the plugin?

Successful, thank a lot!

**Comment by Rsl1122** [comment]
### Dev note

Location of the buggy code was found:
https://github.com/Rsl1122/Abstract-Plugin-Framework/blob/master/AbstractPluginFramework/velocity/src/main/java/com/djrapitops/plugin/task/velocity/VelocityRunnableFactory.java#L73

`tasks` Collection is supposed to have running tasks, but the tasks are not placed there, so nothing is cancelled on a reload on velocity.
