### ISSUE TITLE
Votifier error on startup bungee

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1134]
### Describe the issue
During startup plan gives a error when looking for votifierEvent

### Server information
Plan version : 4.9.2
BungeeCord Version : Build 1419

### Exceptions & Other Logs
https://pastebin.com/3tH0XLW6

**Comment by Rsl1122** [comment]
What version of nuvotifier do you have?

**Comment by Rsl1122** [comment]
Could not be reproduced with nuVotifier 3.0.0-SNAPSHOT (2.7.3)
https://www.spigotmc.org/resources/nuvotifier.13449/update?update=280814

**Comment by thunderlight411** [comment]
Sorry i have seen that i'm not yet using nuVotifier at this time.
instead of that i'm using BungeeVote (https://www.spigotmc.org/resources/bungeevote.929/) becase ultimate vote is not yet supporting nuVotifier.

My mistake sorry for that.
Will go to the developer of UltameteVotes first to see what his progress is in switchting to nuVotifier.

Sorry again for your time to investigate

**Comment by Rsl1122** [comment]
No worries, it exposed that the extension registering is not yet exception resistant, so I'll have to do some changes in response :)
