### ISSUE TITLE
Page generation fail

### ISSUE THREAD

**Issue by 1stian** [plan-player-analytics/Plan#1142]
It told me to post this here...
It happens when I try to open up the analyse page for my server, from the Server network page.

`com.djrapitops.plan.api.exceptions.connection.BadRequestException: Bad Request: http://play.ohneemc.com:8806/info/generateanalysispagerequest | sender=b8ea0987-d80d-4afd-9dee-52877c4911f7;&variable;type=GenerateAnalysisPageRequest;&variable;server=1b24b453-480f-4aca-bcb6-a198b1aa0273 | Failed to generate Analysis Page
    com.djrapitops.plan.system.info.connection.ConnectionOut.handleResult(ConnectionOut.java:133)
    com.djrapitops.plan.system.info.connection.ConnectionOut.sendRequest(ConnectionOut.java:110)
    com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:87)
    com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:79)
    com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:117)
    com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(InfoSystem.java:98)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.lambda$refreshNow$3(ServerPageHandler.java:107)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler$$Lambda$814.00000000781132E0.run(Unknown Source)
    com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73)
    com.djrapitops.plan.system.processing.Processing$$Lambda$307.0000000080892180.get(Unknown Source)
    java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.lang.Thread.run(Unknown Source)`

**Comment by Rsl1122** [comment]
This error suggests that you have two servers with same port, or one of them is running under wrong address

Make sure each of your bukkit servers and bungee server has different address

**Comment by 1stian** [comment]
Velocity server is running on 8804, first server 8805, the one with the error 8806. Everything else is the exact same. On those 3 servers.

**Comment by Rsl1122** [comment]
What does `planvelocity con` command say?

**Comment by 1stian** [comment]
[20:25:42 INFO]: http://play.ohneemc.com:8806: HTTP : External : To:OK : From:OK
[20:25:42 INFO]: http://play.ohneemc.com:8805: HTTP : External : To:OK : From:OK

**Comment by Rsl1122** [comment]
Alright looking at the debug page it seems that there might be a duplicate server entry in the database.

You might need to set the duplicate as uninstalled:
- `planvelocity servers` To find the id of the duplicate server
- `planvelocity uninstalled [id]` to set the server as uninstalled.

Don't worry if you set the wrong one uninstalled, as they are set back as 'installed' when Plan enables again on that server.

**Comment by 1stian** [comment]
Yup that fixed it. Thank you!
