### ISSUE TITLE
Problem with Plan and NuVotifier

### ISSUE THREAD

**Issue by Tonysp** [plan-player-analytics/Plan#1144]
### Describe the issue

Plan shuts down on Bungeecord start. I tried disabling the NuVotifier integration in all config files, but still the same error. Only thing that helps is reverting to Plan 4.8.1

### Server information

Plan 4.9.4
NuVotifier 2.5.3
Server: git-Paper-643 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Bungee: git:BungeeCord-Bootstrap:1.14-SNAPSHOT:34febec:1419

### Exceptions & Other Logs

https://pastebin.com/wkw6G49T

**Comment by Rsl1122** [comment]
I'll try to get this fixed and will link a build with a fix before Saturday.

**Comment by Rsl1122** [comment]
Hmm, it looks like one of your plugins has Bukkit code shaded in it.
Please check any large plugin jars for `org/bukkit` folder inside it when opened with an archive manager (like a .zip file)

**Comment by Rsl1122** [comment]
Build with a fixed catch block can be found here once the job finishes (runtime ~8 minutes)
https://plan.djrapitops.com/job/Player%20Analytics/job/development/46/

**Comment by Tonysp** [comment]
Yea, i have one universal plugin in my bungee plugins folder.

**Comment by Tonysp** [comment]
Thanks, now it works, just this error in console on startup. https://pastebin.com/M2xPRWWn

**Comment by Rsl1122** [comment]
That is intentional, you can fix this error by removing org.bukkit classes from the plugin that includes entire bukkit code inside it.
