### ISSUE TITLE
Vanish Support

### ISSUE THREAD

**Issue by fahlur** [plan-player-analytics/Plan#1148]
### Is your feature request related to a problem? Please describe.
Vanished staff would be visible with the online status when they are "Vanished" on plugins like SuperVanish and Essentials Vanish.

### I would like to be able to..
Essentially to have the online status to deal with a vanish state such as with super vanish or essentials vanish. So players with access wont know if a staff member is visible online when they are vanished.

**Comment by Rsl1122** [comment]
Due to networks it is not really possible to maintain state of vanish status for players on Plan in a simple enough way.

This is unfortunately a corner case that won't be fixed.
