### ISSUE TITLE
Extension data transactions take a long time (kickall on shutdown)

### ISSUE THREAD

**Issue by larssieboy18** [plan-player-analytics/Plan#1152]
### Describe the issue

Hi,
During a shutdown of my server, Plan send out warnings which it asked me to report, so here I am :) The console can be found at: [https://pastebin.com/qcrY1RWp](https://pastebin.com/qcrY1RWp).

### Server information

Information can be found at: [https://1drv.ms/u/s!Ap5PczqG3rEUhPkUlmAskW2K5AlEgA?e=oZhAYM](https://1drv.ms/u/s!Ap5PczqG3rEUhPkUlmAskW2K5AlEgA?e=oZhAYM)

### Additional information

I did not experience any negative effects of this, but because I like this plugin and want it to be even better, I complied and reported it :)

**Comment by Rsl1122** [comment]
The kickall during shutdown triggers many leave events -> All extensions with leave event update their data, which might be a large amount of transactions.

You can prevent the exceptions by increasing db wait delay in the Plan config

In the future (when I fix this) I will try to ignore extension update transactions on shutdown.
