### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by Russia9** [plan-player-analytics/Plan#1160]
### Is your feature request related to a problem? Please describe.
For external applications, it would be cool to use the REST API to get player statistics instead of connecting to the database.

### I would like to be able to..
I would like to be able to get all `Plan` information using API.

**Comment by Rsl1122** [comment]
Implemented in 5.0 (See json_endpoints.md on `interface-redesign` branch)

**Comment by Russia9** [comment]
Ok, thank you!
