### ISSUE TITLE
CoreProtect + Plan causing server crashes when player disconnects from server.

### ISSUE THREAD

**Issue by Jayfree94** [plan-player-analytics/Plan#1161]
### Describe the issue

If a person has a lot of CoreProtect entries, (such as world editing a lot) when they disconnect from the server, the server CPU usage will hit 100% and can cause server crashes.

### Additional information

If you disable CoreProtect integration in Plan config, it will not cause CPU usage to increase on disconnect.

**Comment by Rsl1122** [comment]
Anyone with this issue can disable CoreProtect integration in Plan config until the issue has been resolved.

**Comment by Rsl1122** [comment]
Fixed in build 229
https://plan.djrapitops.com/job/Player%20Analytics/job/master/
