### ISSUE TITLE
Conflict with Essentials geo locator?

### ISSUE THREAD

**Issue by whisperer195** [plan-player-analytics/Plan#1165]
After installation, the essentials geolocator has stopped displaying a message that says "this player has joined from ____ country" and throws an error in the console. 

Server Information:
Paper 1.14.4

Exceptions & Other Logs
![image](https://user-images.githubusercontent.com/55124157/65399678-0aed6200-dd8c-11e9-9ce4-64ceca9cf2b8.png)

Thank you!

**Comment by Rsl1122** [comment]
This conflict is likely caused by another plugin, not Plan:
- Plan and EssentialsX use the same version of GeoIP database (If not relocated, this error would not appear)
- Plan relocates com.fasterxml to plan.com.fasterxml (Specifically to avoid this kind of error)

**Comment by whisperer195** [comment]
Hmmm, strange, I haven't made any other changes...

**Comment by Rsl1122** [comment]
Whoops wrong issue number
