### ISSUE TITLE
Applying for reprint permission. 

### ISSUE THREAD

**Issue by Jovel-G** [plan-player-analytics/Plan#1166]
Thanks for your contribute! The plugin is awesome and it really helps me a lot. I'm curious about whether can I reprint the plugin to another Chinese Minecraft forum with all copyright information?  I will make a redirect to the Ore page. Waiting for your reply :)

**Comment by Rsl1122** [comment]
Please clarify what you mean by reprint (bad translation maybe?)

**Comment by Jovel-G** [comment]
Apologize for unclear statements. What i mean is, can I reprint this plugin to the Chinese forum while preserving copyright information and Ore address?

**Comment by Rsl1122** [comment]
Sorry, I do not understand - you have said the exact same thing again

Do you want to make a post on a forum?
If so go ahead, please post link here afterwards :)

**Comment by Jovel-G** [comment]
Yeah, that's what I mean and yes I will post the link here after I finished the translation :)

**Comment by Rsl1122** [comment]
Hi, have you posted a link somewhere? :)
