### ISSUE TITLE
When certain players join the server crashes

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1177]
### Describe the issue
Sometimes when a player joins and then leaves, after he leaves the CPU and Memory usage instantly starts climbing up till Memory hits max and the server crashes. 

### Server information
Server version: 1.14.4, Paper v207
Plan version: 5.0, Build 224 (Happened on version 4 too)

### Exceptions & Other Logs
I get no crash reports, no errors of any kind anywhere. I have tried resetting Plan but the crash still occurs so I'm guessing it might be from data the plan plugin gets? The only thing I know right now is that it stops after I remove Plan.

**Comment by Rsl1122** [comment]
Possible cause: CoreProtect integration https://github.com/plan-player-analytics/Plan/issues/1161
Disable CoreProtect integration by setting `Plugins.CoreProtect.Enabled` to `false` in Plan config

**Comment by DrakePork** [comment]
I'll check if that works

**Comment by DrakePork** [comment]
Disabling CoreProtect does seem to fix it

**Comment by Rsl1122** [comment]
I'll close this and reopen the original issue, you can follow that issue for a resolution
