### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by KyroOW** [plan-player-analytics/Plan#1188]
Would be nice to have leaderboards which would show TOP 10 (or configureable number) PVP eliminations, or (configureable) PVE eliminations as well if people want it that way.

**Comment by Rsl1122** [comment]
Closing this as 'Out of Scope' because implementing this feature would bring a large number of additional suggestions on all sorts of leaderboards.

Implementing a configurable all-in-one leaderboard is unfortunately also too large in scope to maintain.
