### ISSUE TITLE
ServerName not properly sanitized in browser

### ISSUE THREAD

**Issue by RalphORama** [plan-player-analytics/Plan#1191]
### Describe the issue

If I set the `ServerName` directive to something like `"Ralph's Server"`, I get the following error in my browser: `SyntaxError: missing ) after argument list`.  After this, the webpage doesn't load.

Peeking in developer console, it appears the following line of JavaScript was generated:

```javascript
$('.server-name').text('Ralph's Server');
```

This is not remediated by setting `ServerName` to `Ralph\'s Server` or `Ralph\\'s Server`.

### Server Information
**Plan Version:** 5.0 build 224
**Server:** Paper 1.14.4-R0.1-SNAPSHOT (git-Paper-209 (MC: 1.14.4))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-65-generic
**Java Version:** 1.8.0_212, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.212-b01, Oracle Corporation

### Benchmarks
```
581 ms     -39 MB  Enable
```

### Exceptions & Other Logs

As mentioned earlier: `SyntaxError: missing ) after argument list` appears in the browser console.

### Additional information

As mentioned earlier:

Peeking in developer console, it appears the following line of JavaScript was generated:

```javascript
$('.server-name').text('Ralph's Server');
```

**Comment by Rsl1122** [comment]
Yep not sanitized at all since 5.0 - I thought I removed all occurrences of ${serverName} from the javascript code, but I guess not.
