### ISSUE TITLE
AdvancedBans errors

### ISSUE THREAD

**Issue by KyroOW** [plan-player-analytics/Plan#1192]
### Describe the issue
When i use AdvancedBans to kick or ban etc a player, an error appears in the console.

### Server information
PaperSpigot 1.12.2 Build 1614
Plan 5.0 Build 236

### Exceptions & Other Logs
Error i got on build 224 when using /kick
https://pastebin.com/XKNyBTkE

Error i got on new build 236 when using /kick
https://pastebin.com/EWkpBFHV

**Comment by Rsl1122** [comment]
Disabling AdvancedBan integration in the Plan config prevents the exceptions until a fix arrives.
