### ISSUE TITLE
Defined web link missing sub-directory in multi-server

### ISSUE THREAD

**Issue by TripleNothing** [plan-player-analytics/Plan#1195]
When viewing the page from the 'network' folder of the website, it lists the multiple servers present. So far all links seem to have run fine, so hopefully this is a single line.

Line referenced on Servers - Overview page: Server Analysis
Current page address: domain.com/player-analytics/network/#tab-servers
Expected link address: domain.com/player-analytics/server/main
Provided link address: domain.com/server/main

**Comment by TripleNothing** [comment]
Depending on the reference, I do have the config set for the external web server (Apache), but am letting it keep its files local, and just referencing that directory from Apache.

Links successfully work at the same level, as well as step FROM '.com/player-analytics/server/(serverName)' TO '.com/player-analytics/networks', but I did now find more, so I'm assuming its a multi-referenced item.

So far it seems any link stepping from the global 'networks' to a 'server' is missing the sub-directory after .com/ while any stepping from a server's details to the 'networks' page seem fine.

http://minecraft.hellzoneinc.com/ (Image/Link at bottom right jumps first to a defined server)

**Comment by Rsl1122** [comment]
I looked into it and miiiight have found the issue (It is in the code that changes links in exported html)

Link from the network page
```html
<a class="btn col-light-green ml-2" href="../../../../../../../../../../../../../../../../../../../../../../../server/Main"><i class="fa fa-fw fa-chart-line"></i> Server Analysis</a>
```

It's supposed to be something like `../server/Main`

**Comment by TripleNothing** [comment]
The initial item looks to be corrected. Sorry for this not being a new issue...

2 more links need to be looked at in 'network/#tab-sessions-overview'
Server Analysis
Player Page

**Comment by Rsl1122** [comment]
Are you ny any chance exporting to `plugins/Plan/web`?

**Comment by TripleNothing** [comment]
I was. Renamed to 'web_public' and so far all seems good.
