### ISSUE TITLE
NucleusExtension error on join

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#1196]
### Describe the issue
The error happens when a player joins the server and this been happening since the new release (Plan-5.0.build.224.jar)

### Server information
forge-1.12.2-14.23.5.2838
spongeforge-1.12.2-2825-7.1.6
Nucleus-1.14.0-S7.1
Plan-5.0.build.224

### Exceptions & Other Logs
https://paste.ee/p/yxm8Y (Error1 is Errors-2019_10_16.txt and Error2 is from console)

### Additional information
None

**Comment by Rsl1122** [comment]
You can prevent this exception by disabling nucleus extension in the Plan config until tma fix arrives

**Comment by poqdavid** [comment]
Oh ok ty i will

**Comment by poqdavid** [comment]
Updated to Plan-5.0.build.249 but still getting https://paste.ee/p/Y1jzh

**Comment by poqdavid** [comment]
Well i check and we are using the updated version of nucleus still getting the same error

**Comment by Rsl1122** [comment]
:thinking: Hmm, maybe another plugin has old Nucleus version shaded in by accident? (You can check this by looking for `io/github/nucleuspowered` folder inside jars of plugins)

**Comment by poqdavid** [comment]
Nope I checked everything few times all are ok

**Comment by Rsl1122** [comment]
Looks like the issue is caused by Plan relocating its own Google classes while Nucleus tries to return `com/google/common/collect/ImmutableList` Plan expects `plan/com/google/common/collect/ImmutableList` leading to this issue

**Comment by poqdavid** [comment]
Oh its fine i understand it happens
