### ISSUE TITLE
PostgreSQL support as db driver

### ISSUE THREAD

**Issue by Lgmrszd** [plan-player-analytics/Plan#1197]
It would be nice for Plan to have PostgreSQL support as storage. Lots of other plugins support it already, so this would be beneficial to have one database for everything instead of having two.

**Comment by Vankka** [comment]
Maybe make  seperate sql queries for each engine (or mysql + sqlite could probably be combined)? (LuckPerms does this)

**Comment by Rsl1122** [comment]
> 
> 
> Maybe make seperate sql queries for each engine (or mysql + sqlite could probably be combined)? (LuckPerms does this)

While that works for LuckPerms I don't think that is a viable solution here, as LuckPerms seems to have [32 Queries](https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/SqlStorage.java#L84) while Plan has ~350 different SQL queries (Methods that return/Classes that extend `Query` and `Executable` interfaces)

**Comment by Rsl1122** [comment]
Closing this issue as implementing this feature is unfortunately too much work to implement and maintain afterwards.
