### ISSUE TITLE
Server sorting

### ISSUE THREAD

**Issue by Maxsimuss** [plan-player-analytics/Plan#1205]
### I would like to be able to..
Sort servers in /network#tab-servers by:

-   New players
-   Unique players
-   Player retention
-   Downtime
-   Avg TPS
-   Current player count
-   Best peak
-   Avg player count
-   Playtime

**Comment by Rsl1122** [comment]
I did some prototyping and it seems to be possible to add a client side sorting thing with some of the listed variables. (Player retention and playtime are currently not in the quick view so they are not yet possible)

I'll put these here for implementing this when I have more time.

The position of the sorting needs some more work - It is difficult to find a spot that doesn't make the list look stupid. I'm thinking final version will have the sort button on the same level as the page title
![image](https://user-images.githubusercontent.com/24460436/70374222-f9cae080-18f8-11ea-968c-ccc7b18c2398.png)

```
<div class="dropdown mb-3">
  <button type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn"><i class="fa fa-sort"></i> Alphabetical</button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 40px, 0px);">
    <a class="dropdown-item" href="#">Alphabetical</a>
    <a class="dropdown-item" href="#">Online Players</a>
    <a class="dropdown-item" href="#">Downtime</a>
  </div>
</div>
```
