### ISSUE TITLE
Plan keeps redirecting when put behind a reverse proxy

### ISSUE THREAD

**Issue by database64128** [plan-player-analytics/Plan#1207]
### Describe the issue

I'm trying to get Plan working behind a nginx reverse proxy. I followed the wiki and changed the config:

```
Webserver:
    Port: 8804
    Alternative_IP: true
        # %port% is replaced automatically with Webserver.Port
        Address: cn1.cube64128.xyz:666/mc-java/plan
    # InternalIP usually does not need to be changed, only change it if you know what you're doing!
    # 0.0.0.0 allocates Internal (local) IP automatically for the WebServer.
    Internal_IP: 0.0.0.0
    Security:
        SSL_certificate:
            KeyStore_path: proxy
            Key_pass: default
            Store_pass: default
            Alias: alias
    Disable_Webserver: false
    External_Webserver_address: https://www.example.address
```

But when I visit https://cn1.cube64128.xyz:666/mc-java/plan/ , after logging in, I'm redirected to https://cn1.cube64128.xyz:666/server , which would be a 404 page returned by nginx.

Here's the location block in my nginx configuration:
```
location /mc-java/plan/ {
            proxy_pass http://[::1]:8804/;
            
            proxy_pass_request_headers on;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
        }
```

### Server information

Forge 2847
SpongeForge 3928

```
[11:11:17] [Server thread/INFO] [nucleus]: Server ran the command: /plan info
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: > Player Analytics
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Version: 5.0 build 260
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Update Available: No
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Active Database: MySQL (OPEN)
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Connected to Proxy: No
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 
[11:11:17] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: >
```

```
[11:19:01] [Server thread/INFO] [nucleus]: Server ran the command: /plan a
[11:19:01] [Plan Non critical-pool-4/INFO] [net.minecraft.server.dedicated.DedicatedServer]: > Analysis Results
[11:19:01] [Plan Non critical-pool-4/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Link: https://cn1.cube64128.xyz:666/mc-java/plan/server/Server+1
[11:19:01] [Plan Non critical-pool-4/INFO] [net.minecraft.server.dedicated.DedicatedServer]: >
```

```
[11:01:04] [Server thread/INFO] [nucleus]: Server ran the command: /plan network
[11:01:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: > Network Page
[11:01:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]:   Link: https://cn1.cube64128.xyz:666/mc-java/plan/network/
[11:01:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: >
```

**Comment by Rsl1122** [comment]
If you have the reverse proxy set in a subdirectory you need to also set up rewrites - it is easier to have on a subdomain

**Comment by database64128** [comment]
> If you have the reverse proxy set in a subdirectory you need to also set up rewrites - it is easier to have on a subdomain

My configuration already implicitly rewrites the URI. I'm using the same configuration for dynmap and it's working fine:
```
location /mc-java/dynmap/ {
            # The / at the end is significant.
            proxy_pass http://[::1]:8123/;
            
            proxy_pass_request_headers on;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
        }
```
nginx redirects requests from https://cn1.cube64128.xyz:666/mc-java/dynmap/ to http://[::1]:8123/ . The URI rewrite is done implicitly by nginx.

**Comment by Rsl1122** [comment]
You might need to do rewrites for the redirect responses Plan uses to move the user from some unexisting pages to existing ones (Like root directs to server or network page)

**Comment by database64128** [comment]
> You might need to do rewrites for the redirect responses Plan uses to move the user from some unexisting pages to existing ones (Like root directs to server or network page)

![image](https://user-images.githubusercontent.com/18757988/67629641-af932000-f8b3-11e9-8213-e9f230733054.png)
The cause of the problem is, Plan is redirecting me to `/server` instead of `server`.

**Comment by Rsl1122** [comment]
Fixed in build 262 onwards <https://plan.djrapitops.com/job/Player%20Analytics/job/master/>

**Comment by database64128** [comment]
Thanks for the quick response! Just updated to 263. Despite being able to login to the main page, all data failed to load because the relative paths were incorrect, as shown in the image below:
![image](https://user-images.githubusercontent.com/18757988/67760766-e0728100-fa7c-11e9-941f-ec14128b4301.png)
![image](https://user-images.githubusercontent.com/18757988/67760838-013ad680-fa7d-11e9-998b-a8a8677b413b.png)
![image](https://user-images.githubusercontent.com/18757988/67760906-29c2d080-fa7d-11e9-90d4-065631411c72.png)
The correct path would be `v1/serverOverview?server=63852e72-ec0c-493e-aba1-94089429f2bd` but instead `/mc-java/v1/serverOverview?server=63852e72-ec0c-493e-aba1-94089429f2bd` was used.

**Comment by Rsl1122** [comment]
Looks like this just got a whole lot more complicated.

`server.html` has `../v1/-----` addresses for the data.

This means that the addresses would work with `/server/ServerName`, but not for `/server` (Which is the same page in this case)

Since the rendering part does not know where the request is coming from it's not possible to serve different links to different URLs without large changes.

Different approach would be to avoid ever routing to /server, which is likely what approach will have to be taken here.

----

Temporary solution:
Redirect `/server` to `/server/ServerName` (Replacing ServerName with the name of the server)
