### ISSUE TITLE
Make server specific playtime placeholders update realtime

### ISSUE THREAD

**Issue by GwnDaan** [plan-player-analytics/Plan#1209]
Could you add the active session playtime onto the totalled sessions playtime which is in the database. I understand that you cant display the active session on other servers because theres no data available yet in the database. So my question is for the placeholders (plan_player_server_time_<stuff>) as these are local on the same server where the active session is stored. I hope this makes sense xd

**Comment by Rsl1122** [comment]
Implementation requires call to [SessionCache#refreshActiveSessionsState](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/gathering/cache/SessionCache.java#L51)
