### ISSUE TITLE
Plan behind subdirectory reverse-proxy uses wrong relative links for data

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1210]
### Describe the issue

Using a reverse-proxy with Plan routed to from `/some/subdirectory/` causes relative links on `/server` page to route to `/some/` directory instead of `/some/subdirectory`

Original report https://github.com/plan-player-analytics/Plan/issues/1207#issuecomment-547364024

> ![image](https://user-images.githubusercontent.com/18757988/67760766-e0728100-fa7c-11e9-941f-ec14128b4301.png)
> ![image](https://user-images.githubusercontent.com/18757988/67760838-013ad680-fa7d-11e9-998b-a8a8677b413b.png)
> ![image](https://user-images.githubusercontent.com/18757988/67760906-29c2d080-fa7d-11e9-90d4-065631411c72.png)

**Comment by database64128** [comment]
It's only fixed for web users with a permission level of 0. Web users with lower permission levels still experience this bug.

**Comment by Rsl1122** [comment]
Web users with level below 0 are not allowed to view /server page

**Comment by database64128** [comment]
> Web users with level 1 are not allowed to view /server page

![image](https://user-images.githubusercontent.com/18757988/71588762-a3e70280-2b5d-11ea-85b4-6ef363393148.png)
The correct link to /players should be https://cn1.cube64128.xyz:666/mc-java/plan/v1/players . This only occurs to users with permission levels lower than 1.

**Comment by Rsl1122** [comment]
Sounds like /players page is using a wrong relative link. You can change the link with Html Customization (See the wiki) for a temporary fix.

**Comment by database64128** [comment]
Also, if you:

- Go to a player page (e.g. https://cn1.cube64128.xyz:666/mc-java/plan/player/Cube64128)
- Click the "Server page" button in the top right corner.
- It takes you to https://cn1.cube64128.xyz:666/mc-java/plan/server which has the bug:
![image](https://user-images.githubusercontent.com/18757988/71645172-2ebb2f00-2d0f-11ea-86bb-19b4213063bf.png)
