### ISSUE TITLE
Adding a “Median first session time” statistic 

### ISSUE THREAD

**Issue by CamronW** [plan-player-analytics/Plan#1211]
I’m really interested in having a median first session time statistic. It would be really useful to see how long new players are playing on my server for the first time they login.

Being able to see this information, especially in the last 7 days comparison chat would be really helpful 

I’m currently getting this information through a janky python script which isn’t the nicest way to view the data.

**Comment by CamronW** [comment]
Honestly I didn't even see the first session length previously. 

Which average is that using? I assume the mean?

**Comment by Rsl1122** [comment]
Yes

> Mean of first sessions

**Comment by CamronW** [comment]
Ah okay. Yeah a median would be a cool statistic as well. Shouldn't be too hard to implement surely?
