### ISSUE TITLE
Playerbase Development: Doubled Players

### ISSUE THREAD

**Issue by FrozenFireElias** [plan-player-analytics/Plan#1216]
### Describe the issue
Good day,
I noticed that in the "Player Base Overview" at "Player Base Development" a player is scored twice.
I tried to set up "Plan" again, but the error was there since the first one entered the server.

In the picture you can see what that looks like. (I reset the server and let 2 players join it.)
![BUG](https://user-images.githubusercontent.com/13907167/68483152-51632700-023b-11ea-98c6-66308a969be0.PNG)

### Server information
Bungee version: BungeeCord 1.14-Snapshot:9e76966:1421
Server version: Spigot-1.8.8-R0.1-Snapshot
Plan version: 5.0 build 260

Plan was used on a bungee server with SSL certificate and MySQL Database

### Exceptions & Other Logs
I would like to provide logs, but I have no more...
As far as I have seen in the console, no exceptions have been sent.

### Additional information
I currently use the cloud system CloudNet version v3.1.1

**Comment by Rsl1122** [comment]
I might need some more information to debug this further - I can send some SQL queries whne I get home, that will reveal where the issue is.

**Comment by Rsl1122** [comment]
Could you execute the following sql and send the results
```sql
SELECT * FROM plan_user_info u1
LEFT JOIN (SELECT COUNT(1), plan_sessions.uuid FROM plan_sessions GROUP BY plan_sessions.uuid) q2 on q2.uuid=u1.uuid;
```

**Comment by FrozenFireElias** [comment]
No problem, here is the output

![Unbenannt](https://user-images.githubusercontent.com/13907167/68500670-92b7fe80-025c-11ea-8e9e-d92ee7dfc551.PNG)

**Comment by Rsl1122** [comment]
Looks like the issue might be in one query that doesn't limit by server.
I'll get it fixed for next release.
