### ISSUE TITLE
Saving not connected player data

### ISSUE THREAD

**Issue by haeiven** [plan-player-analytics/Plan#1218]
### Describe the issue

Plan is saving data for players who never joined the network, like bots who was denied to join.

### Server information

Latest Waterfall version, with Plan Build 279

### Exceptions & Other Logs

/

### Additional information

Plan shouldn't save this data, it's registering useless players in the database.

**Comment by Rsl1122** [comment]
How to distinguish between a user and a bot?

**Comment by haeiven** [comment]
If the login event was cancelled, it should not add the player to the database ^^

**Comment by Rsl1122** [comment]
Duplicate of #758 - Follow the issue for resolution to this one.
