### ISSUE TITLE
Allow api access to player data including playtime

### ISSUE THREAD

**Issue by fireboyev** [plan-player-analytics/Plan#1219]
### Is your feature request related to a problem? Please describe.
I don't like how I need to calculate the play time of the player myself and would rather get the data from the Plan API instead.
### I would like to be able to..
I would like to be able to get the player data possible as an object or other means from the plan API. I don't want to have to copy over plan's code for calculating playtime by day, month, etc. My reason for wanting to do this is to create a table which will display play times and sessions separated by permission groups. I assume another use for this would be to create an in-game command for viewing playtime. 

Possibilities of ways to get player data / playtime

- PlayerData object:
`PlayerData pData = api.getPlayerData(UUID uuid);`
`long playTimeMonth = pData.getPlaytime(Playtimes.MONTH);`
`List<Session> sessions = pData.getSessions(Playtimes.MONTH);`
`Session session = sessions.get(0);`
`long sessionPlaytime = session.getPlaytime();`
`List<String> playedServers = session.getPlayedServers();`
`LocalDateTime playedAt = session.getDateTime();`

- Get playtime directly from API using method:
`api.getPlayerData(DataType.PLAYTIME).get(Playtimes.month);`

Obviously these ideas could be expanded on to great lengths.

**Comment by Rsl1122** [comment]
Try the playtime query in Query API's CommonQueries - it allows specifying timeframe with epoch ms
https://github.com/plan-player-analytics/Plan/wiki/APIv5-Query-API#available-pre-made-queries

There was a api like you describe but it was too cumbersome to maintain or document.
