### ISSUE TITLE
DiscordSRV IllegalArgumentException

### ISSUE THREAD

**Issue by haeiven** [plan-player-analytics/Plan#1221]
### Describe the issue

This error is happening when the server start, related to DiscordSRV.

### Server information

Server version: 1.14.4
Plan version: Build 279

### Exceptions & Other Logs

https://file.properties/paste/rerusifuxo.md

### Additional information

/

**Comment by Vankka** [comment]
DiscordSRV updated with some breaking changes because of JDA4, will look PR:ing

**Comment by Rsl1122** [comment]
Fixed in build 282
https://plan.djrapitops.com/job/Player%20Analytics/job/master/
