### ISSUE TITLE
global playerlist primary group

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Plan#1222]
### I would like to be able to..
Hi, i like to have the option on Primary playergroup on the global playerlist
Now it's only possible to view the primary group on a server page.

Can you please show this information aswel on the global list so we can search for a group globaly, instead of go to every server and search there for a specific group

Thanks

**Comment by Rsl1122** [comment]
I can probably add similar functionality

**Comment by thunderlight411** [comment]
That will be great thanks 👍

**Comment by Rsl1122** [comment]
Added a task to
https://github.com/plan-player-analytics/Plan/projects/13
