### ISSUE TITLE
DiscordSRV IllegalStateException

### ISSUE THREAD

**Issue by Sopher** [plan-player-analytics/Plan#1225]
### Describe the issue
This error is happening when the server start, related to DiscordSRV.

### Server information
Server version: paper 1.14.4
Plan version: 5.0 build 286

### Exceptions & Other Logs
https://file.properties/paste/luvomukuwo.cpp

### Additional information
_jdbc:mysql://HOST:PORT/DATABASE?useSSL=false&interactiveClient=true&autoReconnectForPools=true_

**Comment by Sopher** [comment]
I have the newest version of discord srv so why I have to disable the integration? :)

**Comment by Rsl1122** [comment]
Fixed in build 288
https://github.com/plan-player-analytics/Plan/releases/tag/5.0.288
