### ISSUE TITLE
AreaShop - Integration Request

### ISSUE THREAD

**Issue by redstonedesigner** [plan-player-analytics/Plan#1227]
### Data to display

Region totals, regions rented per player, region percentage rented, Rent duration, Money septn, region cost, rent limits, region group summary

### Plugin information

**API or Source Code:** [Link](https://github.com/NLThijs48/AreaShop)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/areashop.2991/)

**Comment by Rsl1122** [comment]
- This plugin stores its data in WorldGuard regions and it is difficult to access existing data.
- Listeners offer some view into the data when regions are changed.

Implementation assesment: **75**  
Implementing support for the wanted data requires data storage in Plan (Query API) and many different listeners.
- Storage of different regions + listeners
- Implementation of analysis queries
- Extension implementation (easiest part)

Could you expand on what you mean by region group summary?

**Comment by redstonedesigner** [comment]
Regions can be grouped (e.g. Market-East, Market-South) to allow for properties to be set etc.

By Region Group Summary, what I mean is stats by region group (e.g. % rented, rent cost, total spent on rent etc.)

**Comment by AuroraLS3** [comment]
After further consideration this integration is deemed out of scope due to lack of API that would easily allow extraction of the data.
