### ISSUE TITLE
QuickShop - Integration Request

### ISSUE THREAD

**Issue by redstonedesigner** [plan-player-analytics/Plan#1228]
### Data to display

Total shops, shops per palyer, common items, average prices

### Plugin information

**API or Source Code:** [Link](https://github.com/Ghost-chu/QuickShop-Reremake)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/quickshop-reremake-now-support-1-14.62575/)

**Comment by Rsl1122** [comment]
This plugin unfortunately does not provide any easy to use API for wanted features
