### ISSUE TITLE
MarriageMaster - Integration Request

### ISSUE THREAD

**Issue by redstonedesigner** [plan-player-analytics/Plan#1229]
### Data to display

Married status, bonuses status (e.g. shared XP)

### Plugin information

**API or Source Code:** [Link](https://github.com/GeorgH93/MarriageMaster)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/marriage-master-mc-1-7-1-14.19273/)

**Comment by AuroraLS3** [comment]
The API unfortunately did not support bonus information, but other data was added.
