### ISSUE TITLE
MyPet - Integration Request

### ISSUE THREAD

**Issue by redstonedesigner** [plan-player-analytics/Plan#1230]
### Data to display

Amount of pets, what pets (in dropdown/separate menu), skilltree stats for pets

### Plugin information

**API or Source Code:** [Link](https://github.com/xXKeyleXx/MyPet)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/mypet.12725/)

**Comment by Rsl1122** [comment]
Implementation assesment: **50**
Implementing support for the wanted data requires large amount of looking through the MyPet codebase

**Comment by AuroraLS3** [comment]
The API used callbacks for data access so it was not possible to integrate all pets' data, only the currently active pet
