### ISSUE TITLE
Savage Faction compatibility

### ISSUE THREAD

**Issue by Creat789** [plan-player-analytics/Plan#1231]
LINK : https://www.spigotmc.org/resources/savagefactions-the-ultimate-factions-experience.52891/

Thx and good plugin

**Comment by Rsl1122** [comment]
You need to list what data you want to be displayed about the plugin

**Comment by haeiven** [comment]
Hello, i'm from SavageFactions Staff.

The plugin is being reworked from scratch, it will take few weeks/months before it's done, I think you should wait for it before adding it to Plan.

Best regards,

**Comment by Rsl1122** [comment]
Thanks for letting us know @haeiven

**Comment by Rsl1122** [comment]
SavageFactions has been discontinued and replaced by FactionsX - FactionsX source or API does not seem to be anywhere yet so I'm closing this one.

Please open a new plugin request with necessary information once an API is available
https://github.com/plan-player-analytics/Plan/issues/new?labels=New+Feature%2C+DataExtensions%2C+Help+Wanted&template=plugin_request.md
