### ISSUE TITLE
Playtime should be non-afk time

### ISSUE THREAD

**Issue by skerit** [plan-player-analytics/Plan#1235]
### Is your feature request related to a problem? Please describe.

When I go to the player list, and I sort the players by playtime, the same players are always on the top, because they're the ones who AFK from time to time. A single night of AFK-ing would shoot you up the list. It's a totally skewed result, because this is not actually "played" time.

### I would like to be able to..

Basically:
* The current playtime value should be stored as "on-line time"
* The playtime should be this "on-line time" minus the AFK-time
* Session durations should possibly also subtract the AFK-time

Then, all those numbers would start making sense. Because now I have an "average playtime per player" of over a day, and it's just useless info.

Changing it would give me a much better understanding of who is actually playing the most.

**Comment by Rsl1122** [comment]
Activity index takes only active playtime into account (afk time is reduced) as well as all other active playtime statistics - what locations on the page would, in your opinion, benefit from active playtime statistic?

**Comment by skerit** [comment]
Ah, that's good that it's used in activity index.

I was thinking about using "Active Playtime" on the `/players` page (instead of regular "Playtime")

And also using "Active Playtime / Player" on the homepage instead of "Average Playtime / Player". ("Average Playtime" is currently at 23h, but that's just because of all the AFK'ers)

The same goes for "Total Playtime" on the home page.

**Comment by Rsl1122** [comment]
Added 3 tasks here https://github.com/plan-player-analytics/Plan/projects/13
