### ISSUE TITLE
Couldn't use with Cloudflare

### ISSUE THREAD

**Issue by viet** [plan-player-analytics/Plan#1243]
### Describe the issue
I setup exactly like instruction when setting up Plan with Cloudflare. I set Flexible SSL and automatic HTTPS rewrite correctly. However, when requesting the page via https, it shows error.

### Server information
PaperSpigot 1.14

### Exceptions & Other Logs
This site can’t provide a secure connectionstats.mc.lectron.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### Additional information
The page is at http://stats.mc.lectron.com

**Comment by Rsl1122** [comment]
Plan uses TLS 1.2 - make sure that Cloudflare uses that version when connecting to the Plan webserver

**Comment by viet** [comment]
Yes, I use TLS 1.2

**Comment by Rsl1122** [comment]
I found this which might solve the issue.
https://community.cloudflare.com/t/community-tip-fixing-err-ssl-version-or-cipher-mismatch-in-google-chrome/42162

Googling the error and cloudflare suggests that the cloudflare has not deployed its certificate

**Comment by viet** [comment]
Is there any way you can include a self-signed certificate in the plugin so Cloudflare users can use Full SSL right away?

**Comment by Rsl1122** [comment]
Plan includes one, see here https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up#if-youre-unable-to-obtain-a-certificate

**Comment by viet** [comment]
Somehow I couldn't set Flexible SSL with Cloudflare for Plan. My address is https://stats.mc.lectron.com

**Comment by Rsl1122** [comment]
Does Full SSL work?

**Comment by Rsl1122** [comment]
Can you access the page when *not* going through cloudflare?
