### ISSUE TITLE
Encountered NoClassDefFoundError with LuckPerms Extension

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#1248]
### Describe the issue
After updating to Plan-5.0-build-309.jar all our servers gave the error on boot but the rest of the plan loads just fine

### Server information
Spigot 1.12.2 server with LuckPerms-Bukkit-4.4.30.jar and Plan-5.0-build-309.jar 
Waterfall-295 server with LuckPerms-Bungee-4.4.26.jar and Plan-5.0-build-309.jar
SpongeForge-1.12.2-2825-7.1.6  server with LuckPerms-Sponge-4.3.83.jar and Plan-5.0-build-309.jar

### Exceptions & Other Logs
https://paste.ee/p/56dlW

**Comment by Aurelien30000** [comment]
@Kriiiiiiiz#0502 If you use this recent version of Plan, update LuckPerms to 5.0 ^^

(Or downgrade Plan to https://www.spigotmc.org/resources/plan-player-analytics.32536/download?version=301573)

**Comment by Rsl1122** [comment]
This is due to updating Pla. To use Luckperms api 5.
Situation will improve with #1245

**Comment by poqdavid** [comment]
Oh ok thanks well i will just disable the LuckPerms Extension until we update
