### ISSUE TITLE
Implement Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by TheRosdi** [plan-player-analytics/Plan#1251]
Very useful.
It is necessary to be able to control where the content of the web panel can be viewed.
The idea is that you can choose from where to allow viewing with 'Access-Control-Allow-Origin "https://example.com/"'.

**Comment by Rsl1122** [comment]
Here is a build with this implemented: [Plan-5.0-build-315.jar.zip](https://github.com/plan-player-analytics/Plan/files/3967495/Plan-5.0-build-315.jar.zip)

I couldn't test it right now, so if it doesn't work please open another issue
