### ISSUE TITLE
Top Playtime List

### ISSUE THREAD

**Issue by TheMattVid** [plan-player-analytics/Plan#1252]
I have aspects of my server that are contingent on a player's weekly playtime. The plugin I currently use, Ontime, is outdated and can be unreliable at times.

I would like to be able to select a certain calendar day or week or month and see a list of all the players who were on within that time and how long their total playtime was. This would not only greatly help me to replace the outdated plugin, but it would also allow me to better analyze player's playing habits as well as how the composition of the top list changes over time.

**Comment by Rsl1122** [comment]
This feature will be included in #963 - Please follow that issue.
