### ISSUE TITLE
Data from the database is not completely displayed on the page.

### ISSUE THREAD

**Issue by SemperEtAnte** [plan-player-analytics/Plan#1260]
I am outputting information through the API to the statistics page. Just a few separate plugins, each of which has 3 tabs with a table, in the style of "Current time", "Previous month", "All time". At the same time, normal data is entered into the plugin database, but not all of them are shown on the page in tables. Queris in my plugin are 100% correct

**Comment by Rsl1122** [comment]
Is this about Data Extension API?

If so please double check the sections about how the data in Plan is updated (two sections in this part of the documentation) https://github.com/plan-player-analytics/Plan/wiki/APIv5---DataExtension-API#-provider-annotations

**Comment by SemperEtAnte** [comment]
> Is this about Data Extension API?
> 
> If so please double check the sections about how the data in Plan is updated (two sections in this part of the documentation) https://github.com/plan-player-analytics/Plan/wiki/APIv5---DataExtension-API#-provider-annotations

Yes. About Data Extension API.
All correct. The plugin database contains correct data, but not all of data are displayed on pages

**Comment by Rsl1122** [comment]
Ok so Plan database contains the proper data but the queries in Plan are not displaying the data?

Could you screenshot some example data and the faulty output in order to start figuring out the part the problem is in?

**Comment by SemperEtAnte** [comment]
https://ibb.co/Lg2XNL8
https://ibb.co/0sYhB4T
https://ibb.co/HXn8Hwh
https://ibb.co/njD0Rc4

Icons also do not display correctly

**Comment by Rsl1122** [comment]
Alright. Seems like a bug indeed.

**Comment by Rsl1122** [comment]
Has the situation improved with newer versions?

**Comment by Rsl1122** [comment]
Assuming that this has been fixed.
