### ISSUE TITLE
Feature Idea: Ingame Chat / Console

### ISSUE THREAD

**Issue by Kollho** [plan-player-analytics/Plan#1261]
For authorized people / groups an access to the chat via the panel and a chat logging function.
Or you can only read the chat but not write via the web interface.  (Maybe a button to deactivate the chat? With a bypass perm you can still write)

Goes over the basic function "Analysis" but would be nice features if you have the time.
PS: Thanks for your work and the time for the project

**Comment by Rsl1122** [comment]
I'm probably not going to implement this, but I think it is a good idea for an add-on once those become relevant next year.
