### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by iLemon** [plan-player-analytics/Plan#1265]
### Describe the issue

There's a memory leak caused by Plan on one of my paper 1.12 servers.

### Server information

Proxy:
**Plan Version:** 5.0 build 335
**Server:** BungeeCord git:Travertine-Bootstrap:1.15-SNAPSHOT:61be17f:115 (git:Travertine-Bootstrap:1.15-SNAPSHOT:61be17f:115)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-70-generic
**Java Version:** 1.8.0_232, Private Build
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.232-b09, Private Build

Server with memory leak:
This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Here is the heap: https://i.imgur.com/yD0NmBN.png

**Comment by Rsl1122** [comment]
Please send a list of enabled extensions in Plan config under `Plugins`

**Comment by iLemon** [comment]
`Plugins:
    ASkyBlock:
        Enabled: true
    Buycraft:
        # http://help.buycraft.net/article/36-where-to-find-the-secret-key
        Secret: '-'
    Economy (Vault):
        Enabled: true
    Essentials:
        Enabled: true
    Factions:
        HideFactions:
          - ExampleFaction
    GriefPrevention:
        Enabled: true
    Jobs:
        Enabled: true
    ProtocolSupport:
        Enabled: true
    SuperbVote:
        Enabled: true
    Towny:
        HideTowns:
          - ExampleTown
    ViaVersion:
        Enabled: true
    mcMMO:
        Enabled: true
    nuVotifier:
        Enabled: true
`

**Comment by iLemon** [comment]
Just noticed that since I copied the config to all servers (10), those plugins are for our Skyblock server but the issue is happening on a Prison server.

**Comment by Rsl1122** [comment]
Alright, I don't see any memory-leak suspect data on that extension list.

----

Are there any differences between the prison server and other servers? (eg are the other servers closer to the MySQL server, or are there a vast amount more players on this server for example)

I think the ThreadPool in question is the Transaction execution thread pool, which is a single thread that processes all database transactions. If more transactions are added than what it can process then that could lead to it getting overwhelmed (increasing amount of waiting transactions uncontrollably).

**Comment by Rsl1122** [comment]
One memory leak was discovered in Html Export - was export enabled on the Prison server?

**Comment by iLemon** [comment]
> One memory leak was discovered in Html Export - was export enabled on the Prison server?

Is it enabled by default? If so, yes. If not, no.

**Comment by Rsl1122** [comment]
Not enabled by default

**Comment by Rsl1122** [comment]
I just got an idea on how to try reproducing this. I'll report results after I've done so (Just writing this down here as a note for myself so that I don't forget it).

- Add a `Transaction` that sleeps a long time (simulates mysql being very busy)
- See what happens
  - Add some debug stuff to see how many items are in the transaction queue
- Figure out if it is possible to swap to "Skip unnecessary transactions"-mode while running

**Comment by Rsl1122** [comment]
The situation might have improved, but I don't know since this issue was never reproduced.
Added a task for this here though just in case https://github.com/plan-player-analytics/Plan/projects/13
