### ISSUE TITLE
Error after Updating

### ISSUE THREAD

**Issue by TUBEOF** [plan-player-analytics/Plan#1268]
I get the following error after updating BungeeCord to the latest version: https://pastebin.com/npdNQZUL

**Comment by Rsl1122** [comment]
Looks like 2 extensions failing to register.

- Luckperms extension - see #1266 for solution
- ProtocolSupport - I was not aware of this plugin supporting bungee so it has an error when trying to register a bukkit listener. You can disable the integration in the Plan config.

**Comment by Rsl1122** [comment]
Looks like some plugin likely included ProtocolSupport code inside them and ProtocolSupport doesn't support Bungee.
I'll close this issue as the Bungee support for ProtocolSupport was the thing keeping this one open.
