### ISSUE TITLE
View Player Page Button Doesn't Work In Sessions List When Exporting To External Webserver.

### ISSUE THREAD

**Issue by R416alex** [plan-player-analytics/Plan#1269]
**Describe the bug**
I have the webserver disabled and have Plan set to export to an apache site. When accessing a player page through the link provided in the player list tab seen [here](https://imgur.com/a/PxwJsZb), it brings me to .www.website.com/stats/player/(Name of payer) and everything shows up and works. When trying to access a player page through the sessions tab seen [here](https://imgur.com/a/Sty53m0), it directs me to .www.website.com/stats/player/(UUID of player) and I get a 404 not found error.

**Server information**
Plan Version: 5.0 Build 335
Server: PaperMc 1.15.1 Version 31
Operating System: Ubuntu 18.04 LTS

**Additional Information**
I have tried editing the file /var/www/html/stats/js/sessionAccordion.js and changing the value session.server_uuid to sessions.name in the createAccordionBody function. This works temporarily and allows the sessions page to link to the player page but as soon as it exports a player page it resets it back to session.server_uuid. After that I tried denying write permissions to that file so it couldn't change it back, but then Plan could no longer export any sessions and I was receiving errors in the console saying it was denied. My next step was to decompile the jar and edit the code that creates the sessionAccordion.js file but I though if I was going to do that I should post here so it can be included in future updates.

**Comment by Rsl1122** [comment]
You can modify sessionAccordion.js using Htmö Customization (See the wiki article about it) to have the changed file be exported
