### ISSUE TITLE
New Installs: "Plan Requires internet access on first run to download GeoLite2 Geolocation database."

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1273]
### Describe the issue

Plan gives the following error for new installs as of December 30th 2019.
```
[ERROR]: [Plan] Plan Requires internet access on first run to download GeoLite2 Geolocation database.
```

This causes the geolocation of the plugin to not function.

### Additional information

MaxMind have changed their distribution model on a very short notice by [posting a blog post on December 18](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) - stating the change is due to having to comply with The California Consumer Privacy Act (CCPA)

The changes mentioned in the blog post include disabling public distribution of the GeoIP2 database and change of license.

----

An account must be created to get a distribution key for the database. (By the developer)

To solve the issue on client side, MaxMind eula acceptance policy setting needs to be introduced. - The EULA can be found here: https://www.maxmind.com/en/geolite2/eula

To comply with the eula, the GeoIP database needs to be updated on a regular basis (point 3 under Additional Restrictions).

----

Unfortunately this will take a while to fix, sorry for any inconvenience. Temporary solution is to obtain a copy of GeoIP2 database from MaxMind and placing `GeoIP.dat` in the Plan plugin folder.

**Comment by Rsl1122** [comment]
A fallback option could also be implemented to prevent situation like this from disrupting functionality of geolocation in the future: https://about.ip2c.org/

**Comment by SlimeDog** [comment]
GeoIP.dat on my servers is dated 2017-12-02 (ie., very out-of-date). If I remove it and plan reload, I get
```
[14:43:05] [Plan Reload Thread/ERROR]: [Plan] Error: Something went wrong saving the downloaded GeoLite2 Geolocation database
```
I can create a MaxMind account. Is GeoLiteIP.dat sufficient or do we need GeoIP.dat?

**Comment by Rsl1122** [comment]
- Download GeoLite2-Country
- Rename the file to GeoIP.dat
- Place the file to /plugins/Plan/
- Reload Plan

**Comment by SlimeDog** [comment]
Downloads as _GeoLite2-Country_20191231.tar.gz_
which contains _GeoLite2-Country.mmdb_

So
> mv GeoLite2-Country.mmdb GeoIP.dat

will result in the correct content?

**Comment by Rsl1122** [comment]
Yes, that should do it

**Comment by SlimeDog** [comment]
I accepted the EULA in _config.yml_ and executed **plan reload**. The downloaded file is _plugins/Plan/GeoLite2-Country.mmdb_. It looks like it works. Do I need to rename it?

**Comment by Rsl1122** [comment]
The new version uses that new filename and removes the one with the old filename if necessary. Cache is cleared on reload

**Comment by SlimeDog** [comment]
Great! Thanks.
