### ISSUE TITLE
Litebans issue

### ISSUE THREAD

**Issue by Geeeeri** [plan-player-analytics/Plan#1276]
Hey there! 
I am really fond of this plugin but it seems to have an issue right now. Since I've installed LiteBans, I always wanted to have an online interface to see punishments but I couldn't be bothered to properly set it up. When I got this plugin I was very surprised to see that this has something like that. Sadly it seems to me as though the addon for Litebans is bugged out. 

If I open it up, it only shows a little window with the punishments and I'm not sure how I could modify that.
![image](https://user-images.githubusercontent.com/35484305/71663832-048d5f80-2d57-11ea-8469-631ec41b8878.png)

**Comment by Rsl1122** [comment]
For the fix I'll try to make it as wide as the page - there is likely some css class missing and this affects all other plugins with tables as well.
