### ISSUE TITLE
Sub-Server startup error

### ISSUE THREAD

**Issue by FrozenFireElias** [plan-player-analytics/Plan#1277]
### Describe the issue
Hello everyone
Today when I started my server I noticed that it is giving an error (https://pastebin.com/nRWPBrDp) according to the log files, this has been going on for a long time.

### Server information
Bungee version: BungeeCord 1.15
Server version: Spigot-1.8.8-R0.1-Snapshot
Plan version: 5.0 build 335

Plan was used on a bungee server with SSL certificate and MySQL Database
The server that deals with the error is a sub-server, the others do not send this error.
Essentials: EssentialsX-2.0.1

### Exceptions & Other Logs
[Errors-2020_01_02.txt](https://github.com/plan-player-analytics/Plan/files/4015895/Errors-2020_01_02.txt)

**Comment by Rsl1122** [comment]
Try updating EssentialsX to a newer version (latest is 2.17.0)

If that is not possible disable the interaction in the Plan config

**Comment by FrozenFireElias** [comment]
Updating the plugin solved the problem, thanks for the help
