### ISSUE TITLE
Spacing in folder name referenced multiple ways

### ISSUE THREAD

**Issue by TripleNothing** [plan-player-analytics/Plan#1278]
### Describe the issue
(Exported for external web server)
Basically, the links (assuming all) that reference a server name that has a space in it defines server%20name while the folder of such has been created as server+name

### Server information
Ubuntu 18.04
Player Analytics 5.0 build 335
Waterfall build 309 (Exports all for external web server)
PaperMC 1.15.1 build 33 (Just DB info)
(Waterfall/Paper are BungeeCord/Spigot-based)

**Comment by Rsl1122** [comment]
Could you send some example screenshot so that I can see which exporter is doing it - I've fixed this for some, but looks like I've missed this somewhere

**Comment by TripleNothing** [comment]
[Examples](http://minecraft.hellzoneinc.com/plan/DupName.jpg)
I think the sites intends every space to be referenced as %20 which I would as well, but the directory creation is the catch.
The image is at a root Plan web directory, so feel free to peek around. Just installed, so not much to example.

**Comment by TripleNothing** [comment]
[Updated Reference](http://minecraft.hellzoneinc.com/plan/successDirName.png)
It appears to have built clean. Great job! ;-)
Just curious... Is the Server list intended to be the displayed size forcing the scroll with the 3 1/2 servers currently displayed?

**Comment by Rsl1122** [comment]
Yes the server list limits itself by the height of the browser window.
