### ISSUE TITLE
Exported Server Analysis link on /network page is broken when using Plan from a subdirectory [export path as /plugins/Plan/web/]

### ISSUE THREAD

**Issue by c0wg0d** [plan-player-analytics/Plan#1279]
I am using my own webserver and have Plan running off mydomain.com/plan.

The Server analysis link points to mydomain.com/server/ServerName instead of mydomain.com/plan/server/ServerName.

I have no idea how you are generating these links, but the actual href in the HTML source is:

href="../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../server/Creative"

If we disable the internal web server, perhaps you could create links based on the "External_Webserver_address" setting?  I have that set to mydomain.com/plan but it doesn't seem like that gets used.

**Comment by Rsl1122** [comment]
Hmm seems familiar - Are you exporting to `/plugins/Plan/web`? (Don't do that, Plan takes the template files from there) #1195

**Comment by Rsl1122** [comment]
I'll have to prevent this in the future by making `/plugins/Plan/web` an invalid export path

**Comment by c0wg0d** [comment]
Yes.  I'll try renaming the export folder to something else.

**Comment by Rsl1122** [comment]
Make sure to delete network-values.js in the folder too

**Comment by c0wg0d** [comment]
I changed the export to /plugins/Plan/html and I deleted the entire export folder so it would regenerate. 
 It works great now!  Thanks!
