### ISSUE TITLE
[Improvements] Make the World Playtime pie chart scale better with multiple dimensions

### ISSUE THREAD

**Issue by database64128** [plan-player-analytics/Plan#1280]
### Is your feature request related to a problem? Please describe.
Currently the World Playtime pie chart only has 10 colors to be allocated to items. However, the number of dimensions on a server can easily exceed 10 with Galacticraft or Advanced Rocketry installed.
![image](https://user-images.githubusercontent.com/18757988/71767472-9eb3fa00-2f47-11ea-8ac6-41e4413cdda8.png)
![image](https://user-images.githubusercontent.com/18757988/71767480-a83d6200-2f47-11ea-8968-4d074d74051d.png)

### I would like to be able to..
Make the World Playtime pie chart scale better with multiple dimensions. Automatically assign colors based on the number of dimensions, so that each item has a distinguishable color.

**Comment by Rsl1122** [comment]
You can add more colors in theme.yml
