### ISSUE TITLE
[Suggestion] Staff View

### ISSUE THREAD

**Issue by SkyLicks** [plan-player-analytics/Plan#1282]
### Is your feature request related to a problem? Please describe.

Its not a plan-related problem. However, if the word problem more general, then yes.

At this time, I am unable to wasily keep track of all my staff playtime and activity. If I want to, then I have to spend several minutes waiting for the data on a specific player tk load, hence checking each of my staff members one by one.

### I would like to be able to..
I would like to be able to view certain group(s) of players seperately based on their permission. For example, in the player list, I want to be able to view a list of all players with the permission plan.player.staff easily and right there instead of having to search each player seperately. Or maybe just view only moderators who have the permission plan.player.moderator. Basically, I am requesting the ability to organize the plan player data in a way where one can easily track a specified group of player.

In the future, this feature (or maybe even just now) could perhaps even be expanded to view player statistics on only a certain group and track information like, how has the player retention of my donators changed? How has the over playtime of only my staff members changed. Etc. I hope I make sense.

**Comment by Rsl1122** [comment]
Sounds very similar to #963 

This sort of "search players by group" feature seems to be a highly requested one, so I'll move the original issue to a higher priority.
