### ISSUE TITLE
Be able to view geolocation data in time range + percentage in pie chart

### ISSUE THREAD

**Issue by YellowZaki** [plan-player-analytics/Plan#1283]
### I would like to be able to..

1. (PINK IN THE IMAGE) View the geolocation data in a time frame, like the one in Online Activity.
It would help to identify the evolution of the playerbase. For example if I see I'm loosing Japanese players, take a look to language files to see if there is a problem or something like that.
2. (GREEN IN THE IMAGE) At the same time, a pie chart showing the percentage of each country, since right now, the numbers of players of a country is not very useful.

The time frame feature would update the 3 graphs at the same time.

![Anotación 2020-01-07 030530](https://user-images.githubusercontent.com/13599841/71862935-a9af8b80-30fb-11ea-95c1-541e684b99f9.png)

**Comment by Rsl1122** [comment]
Hello! Thank you for the suggestion.

I think the first suggestion could be accomplished with a search feature (#963) - Follow that issue for that.

I'm a bit puzzled on what the use for the piechart would be - Is it to find the countries where you have small number of players from? (I'd estimate that the bar chart in the image covers at least ~90% of your playerbase)

**Comment by YellowZaki** [comment]
A search feature would not be that visual as a time range selector.

The piechart, I said pie as I could have said bar char, the important thing is that it shows the percentage. The raw amount of users on a country is not useful without a context (in proportion to other countries).

**Comment by Rsl1122** [comment]
Why?

**Comment by YellowZaki** [comment]
What thing?

**Comment by Rsl1122** [comment]
In what way is the percentage useful?
