### ISSUE TITLE
Dynmap integration

### ISSUE THREAD

**Issue by LoneDev6** [plan-player-analytics/Plan#1284]
Would be cool to have a Dynmap widget inside the Plan website

**Comment by Rsl1122** [comment]
How does the dynmap thing usually work?

**Comment by LoneDev6** [comment]
dynmap creates a webserver on your Spigot running intance and listens to a port (different from 80).
Would be cool to have this web page in a iframe or something, inside Plan directly

**Comment by Rsl1122** [comment]
I guess it would be handly to view it on the same site, but at the moment it doesn't really fit the scope of analytics (Location clustering is pretty complicated)

I'll keep it in mind when adding more APIs to Plan (for adding more content easily) so that this would then be doable after that.

**Comment by LoneDev6** [comment]
Would be cool to be able to add a special menu in Plan where we can add our links inside, so I can for example add Buycraft (Tebex) admin panel link, dynmap link, something like that.

But probably we'll get problems with CORS if we add them in iframe.

Thanks for the time! I hope to see a dynmap integration in the future

**Comment by Rsl1122** [comment]
You might be interested in [Html Customization](https://github.com/plan-player-analytics/Plan/wiki/Html-Customization)

**Comment by ChristianDobbie** [comment]
Adding to this, if player location tracking was added it might be possible to display paths/heatmaps on a dynmap installation.

**Comment by Rsl1122** [comment]
> Adding to this, if player location tracking was added it might be possible to display paths/heatmaps on a dynmap installation.

Yep, I did my Bachelor's thesis on detecting bases of players from location traces with clustering so it would definitely be interesting to implement such algorithms to Plan.
Clustering is a very computationally expensive process though (and complicated algorithmically), so I'm not sure if it's worth it.

I think that raw position data is too noisy to get any good information out of it.
Here is an example picture from [_S. Müller, M. Kapadia, S. Frey, S. Klingler, R. P. Mann, B. Solenthaler, R. W. Sumner, ja M. H. Gross, “Statistical analysis of player behavior in minecraft,”  Zagal et al. 2015_](http://eprints.whiterose.ac.uk/88990/)
![image2](https://user-images.githubusercontent.com/24460436/73611102-162c8600-45e7-11ea-9f32-781ea8e5d471.png)
![image1](https://user-images.githubusercontent.com/24460436/73611099-13ca2c00-45e7-11ea-9aa5-ec5dba33b78c.png)
