### ISSUE TITLE
DKPerms

### ISSUE THREAD

**Issue by RaidLands** [plan-player-analytics/Plan#1294]
### Data to display

The Group you are in
### Plugin information

**API or Source Code:** [Link]()  
it is in the Download of Plugin

**Project page or Downloads:** [Link]()
https://www.spigotmc.org/resources/dkperms-permissionsystem-mysql-yaml-bukkit-bungeecord-german-english.58810/

**Comment by Rsl1122** [comment]
Vault permissions are now supported so explicit support for DKPerms is not required as the group should be visible there.
