### ISSUE TITLE
Message 90030 not found [H2 is corrupted]

### ISSUE THREAD

**Issue by mercadanteus** [plan-player-analytics/Plan#1295]
I ran the plugien for some days without problem, but now i have this issue, can you give me some insight on its causes?

16.01 18:05:20 [Server] INFO  Enabling Plan v5.0 build 335
16.01 18:05:20 [Server] INFO  ██▌
16.01 18:05:20 [Server] INFO  ██▌   ██▌
16.01 18:05:20 [Server] INFO  ██▌██▌██▌██▌  Player Analytics
16.01 18:05:20 [Server] INFO  ██▌██▌██▌██▌  v5.0 build 335
16.01 18:05:20 [Server] INFO  [Plan] Locale: 'English' by Rsl1122
16.01 18:05:20 [Server] INFO  [Plan] You're using the latest version.
16.01 18:05:20 [Server] ERROR [Plan] ----------------------------------------
16.01 18:05:20 [Server] ERROR [Plan] Error: H2 init failure: (Message 90030 not found) [90030-199]
16.01 18:05:20 [Server] ERROR [Plan] ----------------------------------------
16.01 18:05:20 [Server] ERROR [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
16.01 18:05:20 [Server] INFO  [Plan] Processing critical unprocessed tasks. (0)
16.01 18:05:20 [Server] INFO  [Plan] Processing complete.
16.01 18:05:20 [Server] INFO  [Plan] Player Analytics Disabled.

**Comment by Rsl1122** [comment]
> FILE_CORRUPTED_1 = 90030
> ~ http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html

H2 is prone to this for some reason.
Try restoring `database.mv.db` & `database.trace.db` from a backup, or use `plan m restore` to restore from a backup (if you have used Plan to back up)

If you don't have a backup, you can try using the h2 recovery tool

- Download h2 here first https://h2database.com/h2-2019-03-13.zip
- Recovery tool instructions https://h2database.com/html/advanced.html#using_recover_too

I recommend migrating to MySQL or SQLIte if possible.

**Comment by mercadanteus** [comment]
Tried to use Mysql and obtained this error message: 

17.01 20:43:53 [Server] INFO  Enabling Plan v5.0 build 335
17.01 20:43:54 [Server] INFO  ██▌
17.01 20:43:54 [Server] INFO  ██▌   ██▌
17.01 20:43:54 [Server] INFO  ██▌██▌██▌██▌  Player Analytics
17.01 20:43:54 [Server] INFO  ██▌██▌██▌██▌  v5.0 build 335
17.01 20:43:54 [Server] INFO  [Plan] Locale: 'English' by Rsl1122
17.01 20:43:54 [Server] INFO  ----------------------------------------
17.01 20:43:54 [Server] INFO  New Release (5.0 build 367) is available https://github.com/plan-player-analytics/Plan/releases/tag/5.0.367
17.01 20:43:54 [Server] INFO  ----------------------------------------
17.01 20:43:54 [Server] ERROR [Plan] ----------------------------------------
17.01 20:43:54 [Server] ERROR [Plan] Error: MySQL init failure: Failed to initialize pool: CLIENT_PLUGIN_AUTH is required
17.01 20:43:54 [Server] ERROR [Plan] ----------------------------------------
17.01 20:43:54 [Server] ERROR [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload

**Comment by Rsl1122** [comment]
CLIENT_PLUGIN_AUTH thing apparently comes up when the mysql and client use different login protocols - I'm not sure if this is a Mysql or Hikaricp problem. 
https://dev.mysql.com/doc/internals/en/non-client-plugin-auth-clients.html

What mysql version are you using?

**Comment by mercadanteus** [comment]
Iwrited to beastnode, they updated their mysql and that worked
thanks
