### ISSUE TITLE
5.0-build-367 can not support the hammercore mod.

### ISSUE THREAD

**Issue by zsn741656478** [plan-player-analytics/Plan#1296]
https://paste.ubuntu.com/p/GJTyv6bghH/
This is crash report.

When I updated to 5.0-build-367, I found that the server failed to start and retried several times. So I rolled back to 5.0-build-335 and the server was ready to start.

**Comment by Rsl1122** [comment]
Hmm, third report about a sponge forge crash with
> signer information does not match signer information of other classes in the package

I think it is mixin related - did you update anything else than Plan? 

See #1291 & #1292 for more dicussion

**Comment by zsn741656478** [comment]
> Hmm, third report about a sponge forge crash with
> 
> > signer information does not match signer information of other classes in the package
> 
> I think it is mixin related - did you update anything else than Plan?
> 
> See #1291 & #1292 for more dicussion

No. Only update the Plan.

**Comment by Rsl1122** [comment]
Try accepting GeoLite2 EULA in the Plan config under `Data_gathering.Accept_GeoLite2_EULA` or disabling geolocation. People have reported that that helps

**Comment by Rsl1122** [comment]
Another option is to try the dev build https://github.com/plan-player-analytics/Plan/releases/tag/5.0.368 that might the root cause fixed

**Comment by zsn741656478** [comment]
> Another option is to try the dev build https://github.com/plan-player-analytics/Plan/releases/tag/5.0.368 that might have the root cause fixed

Solved the problem. Thank you
