### ISSUE TITLE
Fals Online time date on other Language

### ISSUE THREAD

**Issue by RaidLands** [plan-player-analytics/Plan#1299]
### Describe the issue

Ob the player overwiew is last seen. In german "Zuletzt gesehen" thats right. But the information is only partially right. The Time (16:14 is right) but the when is false. There stands: "Gestern" that means in english Yesterday. But he was last online on Wednsday last week. in the Tab sessions on last sessions stands also yesterday. But in the Calender it stands right. 
https://imgur.com/a/oFdSGYX

Same Problem with "Today" that means heute. But i wasn´t online today. I was last online yesterday.

### Server information

5.0 367

**Comment by Rsl1122** [comment]
If you disable recent days under Formatting.Dates in the Plan config, do the dates have a wrong date, or is this just when the Today and Yesterday are in use?

Please also send what timezone you are using to make reproducing the issue easier.
