### ISSUE TITLE
Option to hide inactive players from playerbase graph

### ISSUE THREAD

**Issue by lerokko** [plan-player-analytics/Plan#1303]
I have a very small but public server. No whitelist. The "playerbase development" graph has become unusable to me, meaning i get little to no useful information out of it. Because of the nature of this server (and many minecraft servers in general) many players only log in for a few seconds or minutes and immediately leave forever. Never to be seen again.
Now after a few weeks of running plan the "inactive player" portion grew to a enormous chunk occupying over 95% of the graph. The interesting part of the graph is barely visible because we are talking about a handful of players here.

I'd like to see an option were you could disable the inactive players from being accounted for in the graph. Or only showing players that have passed a threshold of some king (eg they need to have been active at some point, at least once, so only players that descended to inactive are shown. Or they need to have a total playtime of x hours, or had to have a session in the recent past.)
I'd suggest either fixed config options which activity groups to display or just check boxes on the website to toggle the data live.
This way I could see more details in the development I am interested in. To me the dozens of on time players are just noise in the data I'm trying to read.

With the way the data is presented right now I can not get any useful information out of this graph in my use-case.

Thank you in advance and kind regards
-lerokko

**Comment by Rsl1122** [comment]
You can hide them by clicking on the label (See v5 trailer for an example)

**Comment by lerokko** [comment]
Oh thats exactly what I was looking for thank you so much!
I did not watch the trailer, will do now
