### ISSUE TITLE
TPS error in console

### ISSUE THREAD

**Issue by tajemniktv** [plan-player-analytics/Plan#1304]
### Issue description
I'm getting error in console. Performance tab doesn't show any info

### Server Information
**Plan Version:** 5.0 build 367
**Server:** CraftBukkit 1.8.8-R0.2-SNAPSHOT (git-TacoSpigot-04511af6 (MC: 1.8.8))
**Database:** SQLite

**Operating SubSystem:** Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
**Java Version:** 1.8.0_40, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.40-b25, Oracle Corporation
### Benchmarks
```
906 ms     -107 MB Enable
28 ms      -3 MB   subsystem-enable
```

### Exceptions & Other Logs
Console log: https://hasteb.in/icinetaj.pl

**Comment by Rsl1122** [comment]
Why this issue happens:
- Plan checks if the server is using Paper (by checking if a certain class exists)
- TacoSpigot is a fork of Paper, so it includes that class
- Paper has an additional method called `getTPS()`
- TacoSpigot for some reason doesn't have this method

**Comment by tajemniktv** [comment]
When I was using PaperSpigot, the same issue was happening

**Comment by Rsl1122** [comment]
Hmm, perhaps the method doesn't exist in version 1.8.8 of Paper

**Comment by Rsl1122** [comment]
[The method was added on Mon, 29 Feb 2016](https://github.com/PaperMC/Paper/blob/19de9af63c98137a8bbfe9b0550bb30c3d6da7df/Spigot-API-Patches/0006-Add-getTPS-method.patch#L3), which is [the release date of 1.9](https://minecraft.gamepedia.com/Java_Edition_1.9) - I'll write some code to go around the method not existing.
