### ISSUE TITLE
Buycraft Date Newest -> Oldest not working properly

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1305]
### Describe the issue
If you click on the "Date" tab in Buycraft section to do so it shows newest -> oldest it doesn't work correctly and shows dates from 2018 & 2019 on the first 7 entries, and then goes to january 8th 2020 to january 2nd 2020, before jumping to january 19th 2020 which then goes to 12th january 2020 and then jumps to 1st january 2020. Its also showing purchases from 31st of december 2019 as 31st of december 2020. After that it works as it should.

https://imgur.com/a/iSNzWt0

### Server information
1.15.2 Paper (71) || Plan v5.0 build 382

**Comment by Rsl1122** [comment]
The current data extension table api in Plan doesn't support sort order values, so it's probably sorting the dates alphabetically.

**Comment by DrakePork** [comment]
Ah okay
