### ISSUE TITLE
Placeholder Suggestions

### ISSUE THREAD

**Issue by DrakePork** [plan-player-analytics/Plan#1312]
Some suggestions to placeholders:
- A placeholder to show Player Caused Deaths
- A placeholder to show Mob K/D
- A placeholder to show Mob Caused Deaths
- A placeholder to show recent player kills (ex: player_recent_kill_<1-10>)
- A placeholder to show recent deaths (ex: player_recent_death_<1-10>)

A list of all available placeholders on the github wiki.

**Comment by Rsl1122** [comment]
Nice that you clarified the recent player kill and death thing - These seem doable.

**Comment by Rsl1122** [comment]
List is now available at https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

**Comment by lks1248** [comment]
also, placeholders for bungee networks where you can pull individual server stats across the network would be a nice touch

**Comment by Rsl1122** [comment]
@lks1248 see issue #1323
