### ISSUE TITLE
Failed to load Players table data for an Export

### ISSUE THREAD

**Issue by TripleNothing** [plan-player-analytics/Plan#1313]
### Describe the issue
Basically this is all that is now displayed for the details of the universal players page:
**Failed to load Players table data: HTTP 404 (See ./v1/players)**
No errors seem to be printing back-end.
Works fine for each server's player list.
Since it's got nothing to lose, I cleared all and set for a fresh build, yet error still arrives.

### Server information
Ubuntu
Paper/Waterfall
Exported Web files

### Additional information
http://minecraft.hellzoneinc.com/plan/players/

**Comment by Rsl1122** [comment]
Looks like it is not replacing the address with the appropriate location because the address was changed in <https://github.com/plan-player-analytics/Plan/commit/304d8da86bc7a84e32bd8cb72e6c71c80b0f5b78#diff-d9b770c937e4d048ea2569aed582c548L286> to fix #1210
