### ISSUE TITLE
no PVP info

### ISSUE THREAD

**Issue by mercadanteus** [plan-player-analytics/Plan#1314]
PVP info, number of deaths, weapons used, etc is no displayed in the info site.

### Server information
Plugin Nukkitx Beta 1.14 (#592)

### Exceptions & Other Logs
31.01 19:24:19 [Server] INFO  Enabling Plan v5.0 build 382
31.01 19:24:19 [Server] INFO  ██▌
31.01 19:24:19 [Server] INFO  ██▌   ██▌
31.01 19:24:19 [Server] INFO  ██▌██▌██▌██▌  Player Analytics
31.01 19:24:19 [Server] INFO  ██▌██▌██▌██▌  v5.0 build 382
31.01 19:24:19 [Server] INFO  [Plan] Locale: 'English' by Rsl1122
31.01 19:24:19 [Server] INFO  [Plan] You're using the latest version.
31.01 19:24:19 [Server] INFO  [Plan] MySQL-database connection established.
31.01 19:24:19 [Server] INFO  WebServer: Certificate KeyStore File not Found: /plugins/Plan/Cert.jks
31.01 19:24:19 [Server] INFO  [Plan] WebServer: No Certificate -> Using HTTP-server for Visualization.
31.01 19:24:19 [Server] INFO  WebServer: User Authorization Disabled! (Not secure over HTTP)
31.01 19:24:19 [Server] INFO  [Plan] Webserver running on PORT 8804 (http://xxxxxxxxxxx)
31.01 19:24:20 [Server] INFO  [Plan] Player Analytics Enabled. (1017 ms)

### Additional information
All other info is adequately displayed, using Mysql, database
![yy](https://user-images.githubusercontent.com/24380156/73584047-5bbc4800-445b-11ea-83f7-0eff96ab67be.png)

**Comment by Rsl1122** [comment]
Could you check if `plan_kills` table has any entries?

Please also check /plugins/Plan/logs for any error logs

**Comment by mercadanteus** [comment]
Thank your for your answer, there´s no error logs, but where can I find the plan_kills table?

**Comment by Rsl1122** [comment]
In your MySQL

**Comment by mercadanteus** [comment]
Thanks, that table is empty

**Comment by Rsl1122** [comment]
I've narrowed down the issue, to confirm - Is the total death count 0 on your server page?

**Comment by mercadanteus** [comment]
Yes, it shows zero deaths for all players

**Comment by mercadanteus** [comment]
I realized no new players are neither displayed, I opened new issue,
