### ISSUE TITLE
Import data from logs

### ISSUE THREAD

**Issue by ChristianDobbie** [plan-player-analytics/Plan#1319]
Add the ability to import data into Plan from the Minecraft server log files from before plan was installed.

**Comment by Vankka** [comment]
Statistics [Player Data, Bukkit/Sponge] `world/stats/<uuid>.json`
(https://minecraft.gamepedia.com/Statistics however seems like the id's are bunk or are different for specific Minecraft versions)
- Available data: 
  + Player kills
  + Mob kills & deaths `stat.mobKills`
    - These are also available per entity (is player included?) eg. `stat.killEntity.Enderman`
  + Number of deaths `stat.deaths`
  + Leave Game (amount of sessions) `stat.leaveGame`
  + Time played (in minutes) `stat.playOneMinute`
  + Uses for specific items (including weapons, potentially useful for Insights/Weapons) `stat.useItem.minecraft.diamond_sword`

**Comment by AuroraLS3** [comment]
Statistics have been placed in #872, but processing log files may be out of scope due to all differences between formats, locales, platforms and messages in different versions.
It would be rather difficult to deal with all that complexity so it is deemed out of scope.
