### ISSUE TITLE
No new users register

### ISSUE THREAD

**Issue by mercadanteus** [plan-player-analytics/Plan#1320]
### Describe the issue
"new players" is always in zero in info site

### Server information
Nukkitx redstone branch

### Exceptions & Other Logs
05.02 18:11:22 [Server] INFO  Enabling Plan v5.0 build 382
05.02 18:11:23 [Server] INFO  ██▌
05.02 18:11:23 [Server] INFO  ██▌   ██▌
05.02 18:11:23 [Server] INFO  ██▌██▌██▌██▌  Player Analytics
05.02 18:11:23 [Server] INFO  ██▌██▌██▌██▌  v5.0 build 382
05.02 18:11:23 [Server] INFO  [Plan] Locale: 'English' by Rsl1122
05.02 18:11:23 [Server] INFO  [Plan] You're using the latest version.
05.02 18:11:23 [Server] INFO  [Plan] MySQL-database connection established.
05.02 18:11:23 [Server] INFO  WebServer: Certificate KeyStore File not Found: /plugins/Plan/Cert.jks
05.02 18:11:23 [Server] INFO  [Plan] WebServer: No Certificate -> Using HTTP-server for Visualization.
05.02 18:11:23 [Server] INFO  WebServer: User Authorization Disabled! (Not secure over HTTP)
05.02 18:11:23 [Server] INFO  [Plan] Webserver running on PORT 8804 (http://)
05.02 18:11:23 [Server] INFO  [Plan] Player Analytics Enabled. (962 ms)
![Sin título](https://user-images.githubusercontent.com/24380156/73891818-b6c6b400-483a-11ea-980d-1938226b98ad.png)

**Comment by Rsl1122** [comment]
Could you send the "Registered" column of Playerbase > Playerlist so that I can see what Nukkit is recording as the register dates.
Please sort it by the most recent register date by clicking on the Registered title

**Comment by mercadanteus** [comment]
![uno](https://user-images.githubusercontent.com/24380156/73961056-83833400-48d1-11ea-9190-900cdd8998c9.png)
![dos](https://user-images.githubusercontent.com/24380156/73961061-854cf780-48d1-11ea-8a1a-70c4d70038d2.png)

Thanks, I´m attaching the sort by recent and by older,

**Comment by mercadanteus** [comment]
![uno](https://user-images.githubusercontent.com/24380156/73962178-8d0d9b80-48d3-11ea-867c-b0a79dede00d.png)
![dos](https://user-images.githubusercontent.com/24380156/73962181-8e3ec880-48d3-11ea-8a6e-48358196e088.png)

Thanks, I´m attaching the sort by older and by newer, date looks wrong

**Comment by Rsl1122** [comment]
Looks like Nukkit returns 0 for register date after login.

**Comment by mercadanteus** [comment]
I ask and the Nukkit developer answered this 
![Screenshot_2020-02-06-13-36-41](https://user-images.githubusercontent.com/24380156/73972196-f9919600-48e5-11ea-9074-5d2b7d11fccb.png)

**Comment by Rsl1122** [comment]
Disclaimer: This is not directed at you or the developer, I am just getting tired of the state of the nukkit project. 

I mean yeah he's probably correct, but the nukkit project is full of corner cases like this and none of it is documented anywhere - best case there are comments in Chinese in the source code.

**Comment by mercadanteus** [comment]
I understand and agree with you, I've been moving between branches of the plugin

**Comment by mercadanteus** [comment]
I agree in general with you, I've bee moving between different branches of the plugin, everyone solving different problems.
