### ISSUE TITLE
Large Stack trace 5.0 build 382

### ISSUE THREAD

**Issue by divadnebnahtan** [plan-player-analytics/Plan#1321]
not sure what happened. just installed it a few hours ago and now this is happening.
https://hastebin.com/ohozepoqaj.sql
any help is appreciated thanks

**Comment by Rsl1122** [comment]
Looks like CPU usage is returning null for some reason.
What OS are you using?

**Comment by Rsl1122** [comment]
Ok so this is super bizarre error, because CPU usage is not stored in a field that can be null

**Comment by divadnebnahtan** [comment]
> Looks like CPU usage is returning null for some reason.
> What OS are you using?

It's a spare MacBook that i use for a test server. i wanted to test the plugin before adding it to my actual server which is linux but i was just experimenting and then that happened.

I really don't mind too much if the only solution is uninstalling, i just thought it would be good to let someone know

**Comment by Rsl1122** [comment]
I can't unfortunately find the cause for this exception - I think the error message has something wrong with it.

One possible remedy is changing to use MySQL instead.
