### ISSUE TITLE
Server placeholders to query other server's data

### ISSUE THREAD

**Issue by stw222** [plan-player-analytics/Plan#1323]
My request isn't really part of a problem, nor is it really necessary but it could provide more customize-ability for server networks that use PLAN

My suggestion involves the placeholders like ones similar to the following:

- player_server_time_active
- any of the ones on the in the server category here: [PLAN PAPI link](https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI#server)

I would like to be able to query the data of another server.
for example:
i have a hologram on my hub server that lists playtime for the player (total, afk, day, week, month) but that is across the whole network.
I would also like to be able to show the playtime of a player for a specific server without them having to visit a different hologram on each server

so the placeholders could look something like this:
plan_player_server_<server name set at the top of that server's PLAN config>_time_total
or
plan_sessions__<server name set at the top of that server's PLAN config>_average_session_length_total

----

*by AuroraLS3:*

### TODO

- Add placeholder resolution for https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI#server where server name is parsed from the end of the placeholder eg `%{server specific_placeholder}_server:{name or UUID of the server}%`
  - Identification code can be used
  - server UUID is already used for the queries and can be replaced with the one from Identifiers if a server can be parsed from the placeholder.

**Comment by ChrisWard316** [comment]
Hello, i like for my players to be able to see their ACTIVE time globally on the network (you currently allow this for all_time) but i would also like it daily, weekly and monthly. I'm trying to switch away from onTime which had this features and i feel it's something that is needed for this plugin.

**Comment by stw222** [comment]
any updates on when this feature might come?

**Comment by Rsl1122** [comment]
There is no ETA for this feature due to the large feature backlog.
I'd estimate it to arrive within 6 months to 3 years.

If this feature is critical consider implementing it and posting a Pull Request.

Here is some stuff to get started:
- https://github.com/plan-player-analytics/Plan/wiki/Project-Setup
- Starting point, the placeholder package https://github.com/plan-player-analytics/Plan/tree/master/Plan/common/src/main/java/com/djrapitops/plan/placeholder

**Comment by BrainStone** [comment]
per player per server placeholders would be super cool as well!

**Comment by stw222** [comment]
Nice. Cant wait to test this in the next beta release
