### ISSUE TITLE
Some Placeholders have many numbers past the decimal point

### ISSUE THREAD

**Issue by stw222** [plan-player-analytics/Plan#1324]
### Describe the issue

I think i might go through and test all the placeholders to see if they have the same case as these, but i just tried to use the following placeholders:

- player_ping_average_day
- player_ping_average_week
- player_ping_average_month

and they seem to display many more decimal places than they probably should

### Server information

[https://hastebin.com/adamoxohuj.css](https://hastebin.com/adamoxohuj.css)
all of our servers use the same PLAN version
The problem was encountered on our Paper-1618 for 1.12.2 hub server

### Exceptions & Other Logs

[https://hastebin.com/ipezoseguy.md](https://hastebin.com/ipezoseguy.md)

### Additional information

Screenshot:
[https://i.imgur.com/w7xznwz.png](https://i.imgur.com/w7xznwz.png)

**Comment by stw222** [comment]
These have the same problem:

- ping_total
- ping_day
- ping_week
- ping_month

**Comment by Rsl1122** [comment]
Looks like they're not formatted, easy fix.

**Comment by stw222** [comment]
I thought it would be. i didn't find any other un-formatted placeholders
