### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mcqwy** [plan-player-analytics/Plan#1326]
This is the breakdown question I asked at sponge.
I like your plug-in very much
Unfortunately, it may have problems
But I didn't see its error in the log
[url](https://forums.spongepowered.org/t/server-crashes-it-shows-a-timeout-of-60-s/34900)
You may not believe it
Yes, I didn't believe it at first
However, after I removed plan-5.0-build-382.jar, the effect was obviously improved.
On February 8, there was a constant breakdown
It's all because the timeout is 60s
On February 9, after I uninstalled, there was no crash
If the crash doesn't happen again on February 10, it's definitely plan's problem
I'll keep testing tomorrow.
Plan Version: plan-5.0-build-382

**Comment by Rsl1122** [comment]
Try accepting GeoLite2 EULA - see 'Data_gathering.Accept_GeoLite2_EULA' in the config.
```
[10:10:52] [pool-3-thread-3/WARN] [plan]: Fallback: using IP2C for Geolocation (doesn't support IPv6).
```
IP2C has been causing issues on SpongeForge in previous versions - perhaps it is still the issue

**Comment by mcqwy** [comment]
Now the service provider is maintaining, I will continue to test tomorrow
Please wait for the good news tomorrow

**Comment by Rsl1122** [comment]
How did it go?

Previously the crashes have not been caused by the fact that IP2C doesn't support IPv6, but the fact that it uses HTTP to call an API.

**Comment by mcqwy** [comment]
I'm sorry to have replied to you so long.
My server hard disk is broken in the middle.
I'm testing it now.

**Comment by mcqwy** [comment]
Now it works very well!
There is no problem.
Thank you
