### ISSUE TITLE
Configurable Table Prefixes

### ISSUE THREAD

**Issue by metalshark** [plan-player-analytics/Plan#1328]
Being able to use the same database server for multiple instances of plan, or being able to use a plan__ (double underscore) to enable neat nesting of tables in MySQLAdmin would make life much easier.

I would like to be able to configure a prefix for table names used by plan.

**Comment by Rsl1122** [comment]
Plan supports connecting multiple servers to the same MySQL database

**Comment by Rsl1122** [comment]
What would the nesting be used for?

----

There are some difficulties with this setting due to the backup databases and normal databases using same code. Configurable prefixes might break backups, or at least increase code complexity quite a lot.

The current table names are assumed constant and the code uses these as constants, so the implementation would be a lot of work considering the amount of queries in the plugin.

**Comment by metalshark** [comment]
Nesting would be used for removing visual clutter. https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeTableSeparator

**Comment by metalshark** [comment]
Database nesting is a single underscore, whereas table nesting is a double underscore. The plan database tables have a single underscore in their prefix, so allowing a configurable prefix would let me use a double underscore instead.

**Comment by Rsl1122** [comment]
It sounds like a pretty specific thing that would take a bit too much effort to change & maintain as a config option, so I'll have to close this issue as out of scope (I'd estimate the config option at around 12 hours of work)

----

If you still want to change the table names you can *fork* the project and change the `TABLE_NAME ` variables in [`com.djrapitops.plan.storage.database.sql.tables`](https://github.com/plan-player-analytics/Plan/tree/master/Plan/common/src/main/java/com/djrapitops/plan/storage/database/sql/tables)

You can build the project after the change with `./gradlew build` in `/Plan/` directory (More here https://github.com/plan-player-analytics/Plan/wiki/Project-Setup#building-and-testing)
