### ISSUE TITLE
Failed to load graph data: Timed out after 45 seconds. (../v1/graph?type=activity&server=...)

### ISSUE THREAD

**Issue by FrozenBeard** [plan-player-analytics/Plan#1329]
Using 5.0 build 382

![Screenshot 2020-02-11 at 14 19 52](https://user-images.githubusercontent.com/144046/74244614-9fc01000-4cd9-11ea-8130-2bfc2c97ce76.png)

**Comment by Rsl1122** [comment]
Hmm, the query is probably taking a long time.

You can use Html Customization for a temporary "fix" for the timeout by changing this line in [`/web/js/xmlhttprequests.js`](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/js/xmlhttprequests.js#L29)

**Comment by FrozenBeard** [comment]
I've got a lot of data... Can you link me to the SQL query for it? Might be pulling too much

**Comment by Rsl1122** [comment]
[This](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/storage/database/queries/analysis/ActivityIndexQueries.java#L142) called x8 (for 8 weeks)

It says a lot that the query has 81 parameters..

Basically this:
```
                - Select active_playtime for each player [selectActivityIndexSQL()]
            - Select activity index (calculated in sql) for each player  [selectActivityIndexSQL()]
        - Select activity_index, uuid, activity group (based on activity index limit) [selectIndexes]
    - Group by activity group & count players in the group [selectCount]
- union this 5 times for each activity group [selectMultipleCounts]
```

So 5 nested queries with some joins in-between.

I already got some ideas for some optimizations looking at it.

**Comment by FrozenBeard** [comment]
Holy SQL, Yeah i'm not going to be any help haha

`LIMIT`? haha

**Comment by Rsl1122** [comment]
In the above commit I applied some optimizations to the query, it will arrive with next release.
I tested with ~900k sessions and the execution time went from a couple of minutes to ~25 seconds.

**Comment by FrozenBeard** [comment]
Good news!

**Comment by LoneDev6** [comment]
Any way to fix this?
I'm using v.5.1 build 615 and I still have this problem

**Comment by Rsl1122** [comment]
@LoneDev6 
a 3 minute timeout (temporary fix) https://discord.com/channels/364107873267089409/635887328770129922/714046032669048842 in `xmlhttprequest.js` via Html Customization

Needs  #1459 to fix completely. (The issue is that some queries just take too long on some setups)
