### ISSUE TITLE
Errors since update [Data truncation: Data too long for column 'string_value', StringProvider values are not truncated]

### ISSUE THREAD

**Issue by KlayaR** [plan-player-analytics/Plan#1333]
Since I updated the server with the new update, I have a lot of console errors (see joined file). One of the server actually crashed because of this.
[Error_after_facs_reboot.txt](https://github.com/plan-player-analytics/Plan/files/4208279/Error_after_facs_reboot.txt)

**Comment by Rsl1122** [comment]
Disable the plugin integrations one by one until the exceptions stop (Temporary solution)

**Comment by Rsl1122** [comment]
Another person having this issue on Discord said disabling essentials integration stopped their issue.
