### ISSUE TITLE
server time zone value 'CDT' is unrecognized

### ISSUE THREAD

**Issue by mercadanteus** [plan-player-analytics/Plan#1339]
### Describe the issue
Server was flawlessly running, then migrated to a nearest servers location with same host (Beastnode). Now plugin fails to initialize.  Asked to beastnode support, and told me "This is an issue with the plugin not recognising the timezone the system is set to use".

### Server information
Nukkitx

### Exceptions & Other Logs
20.02 08:30:03 [Server] INFO  Enabling Plan v5.0 build 410
20.02 08:30:03 [Server] INFO  ██▌
20.02 08:30:03 [Server] INFO  ██▌   ██▌
20.02 08:30:03 [Server] INFO  ██▌██▌██▌██▌  Player Analytics
20.02 08:30:03 [Server] INFO  ██▌██▌██▌██▌  v5.0 build 410
20.02 08:30:03 [Server] INFO  [Plan] Locale: 'English' by Rsl1122
20.02 08:30:04 [Server] INFO  [Plan] You're using the latest version.
20.02 08:30:05 [Server] ERROR [Plan] ----------------------------------------
20.02 08:30:05 [Server] ERROR [Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'CDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.
20.02 08:30:05 [Server] ERROR [Plan] ----------------------------------------
20.02 08:30:05 [Server] ERROR [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload

### Additional information
Last update´s error corrections for nukkitx worked fine. Now plugin works perfectly and records everything. Until migration to new server.

**Comment by Rsl1122** [comment]
See <https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up>

**Comment by mercadanteus** [comment]
Hello, this is a hosted server, and Mysql is also a hosted database created by Beastnode for me, so theres no way I can modify the time settings.

**Comment by Rsl1122** [comment]
See the second bullet point
