### ISSUE TITLE
Servername from Bungeecord & Auto Delete server db on stop

### ISSUE THREAD

**Issue by Esmaay** [plan-player-analytics/Plan#1353]
### Is your feature request related to a problem? Please describe.
No

### I would like to be able to..
I use a Cloud System, which dynamically starts and stops servers from a template. It would be nice if PLAN is able to get the server name from the bungeecord, because I'm not able to put the exact server name in the config. Also maybe its nice to auto delete the server database on stop, otherwise i'll have 3000 servers.

**Comment by AuroraLS3** [comment]
I looked into this and unfortunately it is rather difficult to get server name from the bungeecord configuration from another server instance, as it needs using plugin messaging channel and that needs a player to join the server

https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#getserver

**Comment by Esmaay** [comment]
Looking through my old issues, would it be possible to use the API for this? Most large servers have devs anyway.

**Comment by AuroraLS3** [comment]
What API?

**Comment by AuroraLS3** [comment]
I think the way to solve this will be to add environment variable support for configuring the plugin.

**Comment by Esmaay** [comment]
> I think the way to solve this will be to add environment variable support for configuring the plugin.

Yes, that would work too.

**Comment by AuroraLS3** [comment]
The commit above adds support for configuring the server ID, UUID and name using environment variables (As well as other settings)

You can use `PLAN_SERVER_ID`, `PLAN_SERVER_UUID` and `PLAN_PLUGIN_SERVERNAME` variables. The commit message describes the general pattern for converting config paths to environment variables (Basically uppercase and then replace . with _).
