### ISSUE TITLE
litebans support bug [Table column names are not updated properly]

### ISSUE THREAD

**Issue by RimuruChan** [plan-player-analytics/Plan#1355]
### Describe the issue

the column is not aligned
![image](https://user-images.githubusercontent.com/42002296/76111258-eaa01f80-601a-11ea-8ee6-0bea190f654a.png)

### 服务器 Information
**Plan 版本:** 5.0 build 415
**服务器:** BungeeCord git:Travertine-Bootstrap:1.15-SNAPSHOT:8e3fe77:128 (git:Travertine-Bootstrap:1.15-SNAPSHOT:8e3fe77:128)
**Database:** MySQL

**Operating SubSystem:** Windows 服务器 2019 (amd64) version 10.0
**Java 版本:** 1.8.0_241, Oracle Corporation
**Java VM 版本:** Java HotSpot(TM) 64-Bit 服务器 VM version 25.241-b07, Oracle Corporation
### Benchmarks
```
35 ms      -1 MB   subsystem-enable
```

**Comment by Sprite233** [comment]
Title and content do not correspond

**Comment by Rsl1122** [comment]
Looks like the issue happens because two methods are the same name with different parameters and Plan doesn't distinguish between the two. Because a player's table is updated more frequently the player table's columns are shown on the server page.
