### ISSUE TITLE
Max pool connection

### ISSUE THREAD

**Issue by MrMorganCz** [plan-player-analytics/Plan#1358]
Please add the maximum number of connections to the db. (pool limit)

**Comment by Rsl1122** [comment]
What do you mean?

**Comment by Vankka** [comment]
With HikariCP, limits the maximum amount of connections to the database, https://github.com/openbouquet/HikariCP/blob/d9f6eddadac19eb12cf08660fe20d0294ba3ca3e/src/main/java/com/zaxxer/hikari/HikariConfig.java#L608

**Comment by Rsl1122** [comment]
Yes, it is set to 8.
https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/storage/database/MySQLDB.java#L116
