### ISSUE TITLE
ReferenceError: loadNetzwerkÜbersichtValues is not defined

### ISSUE THREAD

**Issue by Prifabu** [plan-player-analytics/Plan#1372]
### Describe the issue

On Loading Network site "ReferenceError: loadNetzwerkÜbersichtValues is not defined" appears

### Server Information
**Plan Version:** 5.1 build 474
**Server:** BungeeCord git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326 (git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.18-21-pve
**Java Version:** 1.8.0_201, Oracle Corporation
**Java VM Version:** Java HotSpot(TM) 64-Bit Server VM version 25.201-b09, Oracle Corporation

**Comment by Rsl1122** [comment]
This is a regression bug related to how locale works in Plan.

You can fix the issue by changing following lines in the Locale
https://github.com/plan-player-analytics/Plan/blob/287eaf9b1283eaae7f02f16966155a0a3d3bd3e5/Plan/common/src/main/resources/assets/plan/locale/locale_DE.txt#L195
to `Overview`

and
https://github.com/plan-player-analytics/Plan/blob/287eaf9b1283eaae7f02f16966155a0a3d3bd3e5/Plan/common/src/main/resources/assets/plan/locale/locale_DE.txt#L247
to `Network`

If you don't have a custom locale.txt here is how to generate it:
https://github.com/plan-player-analytics/Plan/wiki/Localization#generating-a-locale-file
