### ISSUE TITLE
Unable to reach plan's website pages (~infinite loading)

### ISSUE THREAD

**Issue by Aurelien30000** [plan-player-analytics/Plan#1373]
### Describe the issue

Hey, frozen on this screen when I try to access Plan's website with an error in Chrome console and another in server's logs. (Bungee) I think it's related with config, but I need some help, thanks in advance ^^

![image](https://user-images.githubusercontent.com/43724816/77585227-6ee01700-6ee4-11ea-9e9a-d0b7fc8891bd.png)

### Server information

**Plan Version:** 5.1 build 474
**Server:** BungeeCord git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326 (git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.19.0-8-amd64
**Java Version:** 1.8.0_212, Azul Systems, Inc.
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.212-b04, Azul Systems, Inc.
### Benchmarks
```
13 ms      -2 MB   subsystem-enable
```

### Exceptions & Other Logs

> [19:23:38 ERROR] [Plan]: Error was caught by com.djrapitops.plan.delivery.webserver.ResponseResolver
java.util.ConcurrentModificationException: null
at java.util.ArrayList.sort(ArrayList.java:1464) ~[?:1.8.0_212]
at java.util.Collections.sort(Collections.java:141) ~[?:1.8.0_212]
at com.djrapitops.plan.settings.config.ConfigNode.sort(ConfigNode.java:196) ~[?:?]
at com.djrapitops.plan.settings.config.ResourceSettings.shouldBeCustomized(ResourceSettings.java:47) ~[?:?]

**Comment by Aurelien30000** [comment]
For information, I only had the following rows in my configuration file (before you temporary fix that doesn't work for me after a /planbungee reload, do I need to put it in all my servers ?) ^^

> 
![image](https://user-images.githubusercontent.com/43724816/77585725-40af0700-6ee5-11ea-8180-9f472d72bee4.png)

**Comment by Rsl1122** [comment]
Looks like I was mistaken about the cause - This is a regression bug from something similar to #1334

Likely same root cause as #1372, but with different locale

**Comment by Aurelien30000** [comment]
Confirmed fixed, thanks ! :)
