### ISSUE TITLE
 [some] 404 page lacks CSS

### ISSUE THREAD

**Issue by untuned** [plan-player-analytics/Plan#1378]
### Describe the issue

The 404 page does not appear to contain any CSS at all.

### Server Information
**Plan Version:** 5.1 build 486
**Server:** Tuinity 1.15.2-R0.1-SNAPSHOT (git-Tuinity-"8f8b451" (MC: 1.15.2))
**Database:** SQLite

**Operating SubSystem:** Windows 10 (amd64) version 10.0
**Java Version:** 11.0.6, Oracle Corporation
**Java VM Version:** Java HotSpot(TM) 64-Bit Server VM version 11.0.6+8-LTS, Oracle Corporation
### Benchmarks
```
721 ms     -154 MB Enable
13 ms      -2 MB   subsystem-enable
```
### Exceptions & Other Logs

![](https://untnd.me/Kj5-LCpBW)

**Comment by Rsl1122** [comment]
Could you give the address to the page you were accessing (With all slashes in place, eg `/player/Some/`)

**Comment by untuned** [comment]
/player/Sanistra (has been on the server, but **not** after Plan was installed)
