### ISSUE TITLE
Plan bugs

### ISSUE THREAD

**Issue by viet** [plan-player-analytics/Plan#1389]
### Describe the issue

I got this exception log. There are many more exception log of these type but I couldn't copy it all here cause it goes by too fast.

### Server information

Latest Plan version on Spigot right now, using PaperSpigot #155

### Exceptions & Other Logs

https://pastebin.com/mE78212Q

**Comment by Rsl1122** [comment]
Duplicate of #1377
Fixed in 5.1 build 497 https://github.com/plan-player-analytics/Plan/releases/tag/5.1.497
