### ISSUE TITLE
401 Unauthorized after update.

### ISSUE THREAD

**Issue by FrozenBeard** [plan-player-analytics/Plan#1393]
5.1 build 486
Paper 1.12.2

I have my own Ningx server that I use as a proxy for Plan using .htpasswd, it was working fine until I updated and suddenly the user/pass is not recognized, I assume this has something to do with your in-game auth?

Thanks

**Comment by Rsl1122** [comment]
You can disable Plan authentication with `Webserver.Security.Disable_authentication` set to `true` in the Plan config

**Comment by FrozenBeard** [comment]
I tried and /plan reload, didn't work, I will wait until next reboot to test again.

**Comment by FrozenBeard** [comment]
Yup, not working ☹️

**Comment by Rsl1122** [comment]
Hmm, have you tested a previous version of Plan to see if this is a regression bug?

Could you send a screenshot/gif/video of what happens when the user/pass are not recognized? (to rule out nginx being the issue)

**Comment by FrozenBeard** [comment]
I can't even remember the last version of Plan I had on now, as I cleaned up my plugin directory locally and I had like 10 plan versions haha, All I know was that it was working fine.
See #1215 for our previous conversation.

What it does, it it Asks for my Credentials using the password that I setup with Nginx, then it pops up again but this time with your version, I can tell because I have a different message set.
From memory I couldn't get your version to work with Plan setup in Nginx Proxy, so I had to just use my own.

So all it does is give me a 403, You have too many failed login attempts. Please wait 2 minutes until attempting again, with broken CSS/JS.

![Screenshot 2020-04-09 13 16 26](https://user-images.githubusercontent.com/144046/78894091-60f1d080-7a64-11ea-96ce-5d45e385d51f.png)

**Comment by Rsl1122** [comment]
Very weird that it still attempts to authenticate with it disabled - I'll probably have to investigate.
Could you send the Plan enable console log of the main server with the Plan webserver (`/plan(bungee/velocity) reload`)

**Comment by Rsl1122** [comment]
Ok, I managed to find a very easy to miss regression bug where the authentication header is still processed even when authentication is disabled.

Basically this:
- Old version of Request code is being used to create a new kind of Request object
  - The code is throwing an exception on an incorrect Plan web user if the authentication is present
- The exception is caught before the if check for authentication
- The exception returns a 401 unauthorized
  - If 5 attempts fail it trips the password brute-force checker, returning 403 afterwards.

I'll get this fixed for next update.

**Comment by FrozenBeard** [comment]
Awesome, thanks man.

**Comment by Rsl1122** [comment]
You can test this build to see if it works - The setting now prevents the authentication attempts, however if the auth is not disabled Plan will still try to use the the given authentication header.
[Plan-5.1-dev-build-502.jar.zip](https://github.com/plan-player-analytics/Plan/files/4469997/Plan-5.1-dev-build-502.jar.zip)
