### ISSUE TITLE
Different Playtime between Playerlist and Player Page

### ISSUE THREAD

**Issue by Exophobias** [plan-player-analytics/Plan#1396]
### Describe the issue
 When I go to the player list, it shows their playtime in the list. However, when I click a player or any player. It says their active playtime is LESS than what I saw on the player list.

### Server information

Plan Version: 5.1 build 497
Server Ver: Paper 1.12.2 Build 1618

### Exceptions & Other Logs

This was in the log and was spammed for some hours. No idea what happened. Did not update, just left the server for the night and all was fine.

![image](https://user-images.githubusercontent.com/26949488/78800042-d334b900-796f-11ea-998b-b23ec22beb0b.png)

### Additional information

![image](https://user-images.githubusercontent.com/26949488/78799717-5efa1580-796f-11ea-96a7-f499837fd7a5.png)
![image](https://user-images.githubusercontent.com/26949488/78799749-6a4d4100-796f-11ea-95f5-2b1902c557c7.png)

**Comment by Rsl1122** [comment]
Seems like 2 bugs in one report.
The exception is related to DiscorSRV extension - I guess it somehow disabled. If the exception continues you can disable the extension in the Plan config.

The playtime seems to look like similar issue as #1388 - there is probably something wrong with the server table query.. 🤔

**Comment by Rsl1122** [comment]
Are you using H2 as database?

**Comment by Exophobias** [comment]
Yes I believe so. The default database
________________________________

**Comment by Rsl1122** [comment]
I think this issue has been fixed but was left open by accident. (At least the tests that reproduced the issue have not failed for a long time). Please let me know if this still happens
