### ISSUE TITLE
AvancedBan add-on don't count ban, mute and warn

### ISSUE THREAD

**Issue by Ilovemyhous** [plan-player-analytics/Plan#1400]
**Hello!**

I banned, muted and warned some players who broke the rules with AdvancedBan, but the numbers' don't synchronize with the panel. I already banned one person, muted one person, and muted two persons. There is nothing in the plugins overview. On the player profile; I just say that he's banned, but on the plugin tab, (still in the player's profile) the is nothing that tells about a ban.
![image](https://user-images.githubusercontent.com/50217071/79099997-a57fb380-7d65-11ea-94e2-e97e8aba5d60.png)

I waited for the server to reboot, but there is still nothing.

Global plugin overview
![image](https://user-images.githubusercontent.com/50217071/79099029-86802200-7d63-11ea-865c-e24d0ce4968f.png)

This player was banned (Player profile)
![image](https://user-images.githubusercontent.com/50217071/79099138-c6dfa000-7d63-11ea-8ef3-56517948729e.png)

This player had a warning (Player profile)
![image](https://user-images.githubusercontent.com/50217071/79099185-e70f5f00-7d63-11ea-9f18-9475645c8ceb.png)

/history on the warned player
![image](https://user-images.githubusercontent.com/50217071/79099285-17ef9400-7d64-11ea-864c-b49a39ead94c.png)

/history on the banned player
![image](https://user-images.githubusercontent.com/50217071/79099349-35246280-7d64-11ea-9241-b4ed1ba4dbd1.png)

By the time were is was writing this, I have the latest Plan version. _(5.1 Build 497)_
![image](https://user-images.githubusercontent.com/50217071/79099393-4ec5aa00-7d64-11ea-86c2-917d26362719.png)
I also have the latest AdvancedBan version _(2.1.8)_
![image](https://user-images.githubusercontent.com/50217071/79099676-f8a53680-7d64-11ea-855b-cc94c0add1b2.png)

_**Thanks for time and support!**_

**Comment by Vankka** [comment]
I wasn't able to reproduce this, the `banned` tag (on the player's page) appears to only show on the player when they are banned via the vanilla ban system, are you perhaps banning them through the vanilla system by accident?

**Comment by IloveB747** [comment]
Hello again!

I have EssentialsX which uses /ban and /mute ass well. I might be that the problem. In essentials; when you do /seen [player] it shows is the player is banned or muted. I mute and banned my second account to test it.

**AdvancedBan**
TempMute (with AdvancedBan)
![image](https://user-images.githubusercontent.com/50217071/79206560-ca485980-7e3f-11ea-9ae9-f86a5403cc8f.png)


PermaMute (with AdvancedBan)
![image](https://user-images.githubusercontent.com/50217071/79204238-86078a00-7e3c-11ea-8d63-7834060d998d.png)

TempBan (with AdvancedBan)
![image](https://user-images.githubusercontent.com/50217071/79204427-d41c8d80-7e3c-11ea-8f7a-0416ca9014e5.png)

PermaBan (with AdvancedBan)
![image](https://user-images.githubusercontent.com/50217071/79205220-ec40dc80-7e3d-11ea-9c82-7b27cf9c8b2f.png)

**EssentialsX**
TempMute (with EssentialsX)
![image](https://user-images.githubusercontent.com/50217071/79206602-dcc29300-7e3f-11ea-8b9c-eb8eab5b82f8.png)

PermaMute (with EssentialsX)
![image](https://user-images.githubusercontent.com/50217071/79205359-1abeb780-7e3e-11ea-8290-e36ad83fb8fb.png)

TempBan (with EssentialsX)
![image](https://user-images.githubusercontent.com/50217071/79206227-5017d500-7e3f-11ea-963b-baa71e073248.png)

PermaBan (with EssentialsX)
![image](https://user-images.githubusercontent.com/50217071/79206356-7fc6dd00-7e3f-11ea-81f8-6b7560e3f2cb.png)


My thought here; is that Essentials and AdvancedBan have some problem to synchronize between the ban and mutes.

**Comment by Vankka** [comment]
When you ban/mute with AdvancedBan does it show on plan?

**Comment by IloveB747** [comment]
No, that's why I opened this issue.

**Comment by Vankka** [comment]
Would need more details, I wasn't able to reproduce this with default settings, on the same versions on both of the plugins

**Comment by IloveB747** [comment]
It's little bit complicated to explain that here. It think it would be better on Discord with Voice.

**Comment by Rsl1122** [comment]
Thanks for attempts to reproduce the issue @Vankka.
I won't be able to assist until I've dealt with some other bugs.

@IloveB747 
Could you list steps and their order to reproduce the issue eg:
- Used command `/ban someone`
- Went to Plan to view `/player/someone`

```
- Used command `/ban someone`
- Went to Plan to view `/player/someone`
```

**Comment by IloveB747** [comment]
Ok

1. /tempban [player] [time] [reason]
2. Go to the Plan site xxx.xxx.xxx.xxx:8804 (not InGame Command)
3. Went to plugins overwiev.
4. Went to player profile by typing the address in the address bar in Browser (not In Game command)
5. Reloaded both plugins.
6. Reload the webpage.
7. Restart the server.
8. Open issue on GitHub.

And here is a list of my plugins if that can help:
![image](https://user-images.githubusercontent.com/50217071/79232975-8158cb00-7e68-11ea-9277-dccc235c4f17.png)

And I'm running Paper 1.12.2. I completely forgot to put these info in the first post.
