### ISSUE TITLE
Allow few IP to login on the web only using htaccess [IP whitelist]

### ISSUE THREAD

**Issue by maxlehot1234** [plan-player-analytics/Plan#1405]
Hi,

I just want to know if you can implement something that allow only few IP to login on the web for people that doesn't are able to setup a certificate like me.

Having a restriction fo r IP allow the server owner to allow only his staff to access the website and prevent us to setup a password (which is not secure over http)

Maybe use a htaccess or anything else that list IP.

Thanks again.

**Comment by paz** [comment]
very good feature

**Comment by maxlehot1234** [comment]
Ethos thing need to be implemented to add a better security and a better control of access tonit

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
