### ISSUE TITLE
Failed to load graph data: Unexpected end of JSON input [Ad blocker interference]

### ISSUE THREAD

**Issue by aldun** [plan-player-analytics/Plan#1406]
### Describe the issue
After updating to v5.1 Build 505 all of the graphs in the Performance section are displaying "Failed to load graph data: Unexpected end of JSON input (See ../v1/graph?type=performance&server=fdf37897-3f15-459a-9711-96fcc38d5efc)" on all tabs except for the Ping tab.

### Server information
**Plan Version:** 5.1 build 505
**Server:** Paper 1.15.2-R0.1-SNAPSHOT (git-Paper-173 (MC: 1.15.2))
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-88-generic
**Java Version:** 1.8.0_232, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.232-b09, Oracle Corporation
### Benchmarks
```
430 ms     -179 MB Enable
12 ms      -3 MB   subsystem-enable


### Exceptions & Other Logs
None



### Additional information
None

**Comment by Rsl1122** [comment]
I haven't been able to reproduce this issue as it usually goes away after a site refresh.

**Comment by Rsl1122** [comment]
Another person with this issue was using Brave as the browser and the built in ad-blocking is blocking the json requests (or replacing their content)

Disable the ad-block to fix this issue.

**Comment by aldun** [comment]
Ah.. that's what it was, Thanks.
