### ISSUE TITLE
What does this MySQL timezone error mean?

### ISSUE THREAD

**Issue by skilastic** [plan-player-analytics/Plan#1407]
I didn't change anything on my MySQL server and for some reason I get this error.

04:12:22 [ERROR] [Plan] ----------------------------------------
04:12:22 [ERROR] [Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
04:12:22 [ERROR] [Plan] ----------------------------------------
04:12:22 [ERROR] [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
04:12:22 [INFO ] [Plan] Processing critical unprocessed tasks. (0)
04:12:22 [INFO ] [Plan] Processing complete.
04:12:22 [INFO ] [Plan] Player Analytics Disabled.

**Comment by skilastic** [comment]
Also this is not a bug, My apologies for picking the wrong category.

**Comment by Rsl1122** [comment]
No worries, bug label is automatically assigned to bug report templates

----

MySQL attempts to use OS timezone and sometimes the OS gives a timezone that is not recognized by MySQL (In this case Central European Summer Time)

Here is how to fix the issue:
https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up

**Comment by skilastic** [comment]
Thank you, I will try to see if I can fix it on my server.

**Comment by Rsl1122** [comment]
Assuming fixed.
