### ISSUE TITLE
Multiple servers in single Web UI

### ISSUE THREAD

**Issue by Pingger** [plan-player-analytics/Plan#1415]
Hi,

I'm running multiple modded Forge Servers (Amnesia, FTB Academy, FTB Revelation, FTB SkyFactory 3). 
My aim is to install plan on each of them and only have a single webserver running, that has the statistics for all Servers. By that I mean
- Worlds are per Server
- Players are tracked globally (if possible)

Additional specific Questions:
1. Is it as easy as just setting all Plan configs to the MySQL Server and Database?
2. Can I even put all servers into the same Database? Or do I need to specify a different Database for each of them?

### Additional context

Running Minecraft/Forge/Sponge 1.12.2/14.23.5.2846/7.2.0
on a Debian

**Comment by Rsl1122** [comment]
You can run a separate Bungeecord instance and have Plan on it.
You won't need to connect the bungee to any of the servers.
https://github.com/plan-player-analytics/Plan/issues/1198#issuecomment-565755862

**Comment by Pingger** [comment]
nice thanks
