### ISSUE TITLE
Multiple servers as one or group?

### ISSUE THREAD

**Issue by Spacelord09** [plan-player-analytics/Plan#1420]
Is it possible to name 2 or more servers the same to act as one server in the plugin?

### Additional context
I have 3 bedwars server. I want to include them in plan, but not as individual servers, but as a group, that I don't have 3 individual servers in plan.

**Comment by Rsl1122** [comment]
Set the Server UUID to be the same in the `ServerInfoFile.yml`

Some data will be unreadable such as all time based graphs like players online or performance.

See #1340

**Comment by Spacelord09** [comment]
Since that is a dup. from #1430 im closing this now. Please implement the original Issue ;)
