### ISSUE TITLE
Feature Request: Ldap login support

### ISSUE THREAD

**Issue by Spacelord09** [plan-player-analytics/Plan#1421]
### Is your feature request related to a problem? Please describe.
Hey guys!
Firstly I must thank you for this realy nice stats system with a realy nice web gui!
So let's get back to my question: Is Ldap support planed? or/and can it be implementet in near future?

### I would like to be able to..
I have a global ldap server for my staff to login to our systems.
This makes the administration effort extremely easy for me and my admins.

**Comment by Rsl1122** [comment]
This is not going to be supported.

If you want to use Ldap export the html files https://github.com/plan-player-analytics/Plan/wiki/External-WebServer-Use and use an Ldap compatible webserver to serve those files.

**Comment by Spacelord09** [comment]
Why ldap export? I just want Ldap authentication ;D
@Rsl1122

**Comment by Rsl1122** [comment]
The missing comma in that sentence probably lead to some confusion.
