### ISSUE TITLE
Integration CMI (command management interface)

### ISSUE THREAD

**Issue by Nogapra** [plan-player-analytics/Plan#1430]
### Data to display

Home of player
Balance of player
The sanction system

### Plugin information

**API or Source Code:** [CMI API](https://github.com/Zrips/CMI-API)  

**Project page or Downloads:** [CMI](https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/)

**Comment by Vankka** [comment]
API Jar is available here: http://www.zrips.net/wp-content/uploads/2019/02/CMIAPI7.6.2.0.jar (same can be found on the plugin page), although both this version & the API repo are quite old 2+ years

**Comment by austin4195** [comment]
Here is an updated API: https://github.com/Zrips/CMI-API

Updated 2 days ago as of writing this

**Comment by AuroraLS3** [comment]
The API download is out of date and repository requires eclipse to build.

The old API differs too greatly from the new version, and so it's not possible to read the repository to get understanding.
I don't want to work like this so I won't add support for this plugin.

If a proper way to use the API is provided by the plugin author this might change.
