### ISSUE TITLE
[SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)

### ISSUE THREAD

**Issue by viet** [plan-player-analytics/Plan#1436]
### Describe the issue

I got this error after migrating my server files from one machine to another.

On the web page it shows "Failed to load values: HTTP 500 (See ../v1/player?player=vietyork)"
Player page: https://m.ly/vietyork

### Server information

server version 1.15.2

### Exceptions & Other Logs

https://pastebin.com/43g9Tgue

**Comment by Rsl1122** [comment]
Can occur if the write ahead log files were present and not copied over as well
![kuva](https://user-images.githubusercontent.com/24460436/81403439-14211880-913c-11ea-83a9-0e4ffc0898ed.png)

You might need to copy all 3 again or restore from a backup.

**Comment by viet** [comment]
Those files are copied over correctly

**Comment by Rsl1122** [comment]
If the error did not go away with another copy, you might need to shut down the server before copying them again to avoid plan writing to the wal when it is being copied.

**Comment by Rsl1122** [comment]
I don't unfortunately have any more tips on fixing the issue.
Here is the list of ways sqlite can get corrupted https://www.sqlite.org/howtocorrupt.html (I'm guessing it's 1.3 or 1.4)

----

> A manual approach to Repair SQLite Database 
>
>    - In your system open database browser for SQLite.
    - After this click on Execute tab of SQL to start to check in command.
    - In the command prompt, type PRAGMA integrity_check and click on PLAY button.
    - Click on File and move the cursor to export option and click on SQL file.
    - On Export Dialogue box, select objects which you want to export. You can select other ways to export the objects.
    - To import database, click on the file, then import option & click database file from SQL.
> ~ https://www.databasefilerecovery.com/blog/sqlite-database-corruption.html

SQLite browsers:
- https://linoxide.com/linux-how-to/install-use-sqlite-linux/
- https://sqlitebrowser.org/

----

Closing this issue as I can not do anything in the Plan code to fix this.
