### ISSUE TITLE
Passwords with Ampersands Invalid

### ISSUE THREAD

**Issue by kevinsal03** [plan-player-analytics/Plan#1444]
### Describe the issue

I use a password manager to generate all passwords I use for accounts, by default it uses symbols in the password. 
When a user account has symbols in their password, they are unable to login to the dashboard as the plugin always views the password as wrong.

For example, an account registered with the command: `/planbungee register this^has&symbols! Test 0` does not work, but one registered with `/planbungee register thisdoesnthavesymbols Test 0` does work.

### Server information

* Waterfall Proxy version `git:Waterfall-Bootstrap:1.15-SNAPSHOT:53695f0:343` (as reported by /bungee)
* Plan version 5.1 Build 545
* Using MariaDB  `Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

### Exceptions & Other Logs

No errors are displayed to Console and no `/plugins/Plan/logs/Error_{date}.txt` is generated.

### Additional information

Using a Let's Encrypt SSL Cert, not proxied behind CloudFlare or a load balancer.  
Was working on an older build, but I can not remember the exact version. Was before the login page.

**Comment by kevinsal03** [comment]
> For example, an account registered with the command: `/planbungee register this^has&symbols! Test 0` does not work, but one registered with `/planbungee register thisdoesnthavesymbols Test 0` does work.  

After some further testing it actually appears to not be all symbols, rather just specific ones. In my testing it looks to just be the ampersand but I haven't tested all possible symbols.

* `/planbungee register test&test Test 0` did not work.
* `/planbungee register thishasthe^symbol Test 0` and `/planbungee register password*with*symbol Test 0` both worked.

**Comment by itaquito** [comment]
Maybe it has to do something with colour codes?
Since when you use the symbol & you are referring to a colour code on Minecraft servers.

**Comment by kevinsal03** [comment]
> 
> 
> Maybe it has to do something with colour codes?
> Since when you use the symbol & you are referring to a colour code on Minecraft servers.

Interesting idea. It could be possible but highly unlikely imo unless Plan uses `ChatColor.translateAlternateColorCodes(...)` or an equivalent on command parameters for some reason.  

As a quick test I did try replacing the ampersand with `\u00a7` and `§` in the password field but it did not have an impact.

**Comment by kevinsal03** [comment]
I figured out the cause of the issue.  
Kind of disappointed in myself that I did not think of this earlier since I am working on an API project right now.  

When you login into Plan via the form on the page the system directly takes the information in the password box and appends it to the HTTP GET request being sent to the /auth/login endpoint.  

This request looks like this: `https://clubnetwork.us.to:8081/auth/login?user=Test&password=test&test`.  
Except that is problematic because in URLs the & symbol is used to represent a variable being passed to the page. 

This causes a 400 response:
```JSON
{
  "error": "User and Password did not match",
  "status": 400,
  "requestedTarget": "/auth/login"
}
```

This can be fixed by encoding the information being passed to the GET request using a JavaScript function to sanitize the data before it is appended to the request. An example of this would be:
```JavaScript
encodeURIComponent("test&test");
// Returns: "test%26test"
```

Which would make the new GET request look like this: `https://clubnetwork.us.to:8081/auth/login?user=Test&password=test%26test`

Except that still returns as a bad password. I assume that this is because in however Plan processes requests they need to account for "&" being escaped to "%26".

**Comment by Rsl1122** [comment]
Yep it's the `&` character, thank you for finding this out. Other likely candidates are `=` & `?` characters as these two are valid characters in an URI Query (`?this=part&another`) and thus encodeURI does not touch these characters.

The solution is to transmit the login data in the request body instead of URI. I'll try to sort that out for next update.

**Comment by kevinsal03** [comment]
I believe # also causes an issue, but I haven’t tested.

 Switching to a JSON POST or something similar makes more sense in my opinion, but correct me if I am wrong, as I frequently am, but if you wanted to keep the data in the GET request could you just encode with `encodeURIComponent()` on the client end and then wrap where you get the String from the URI in Java with `URLDecoder.decode()`?

I was going to try that myself but I didn’t have Gradle installed and didn’t want to start down that path.

**Comment by Rsl1122** [comment]
URI#getQuery does the decoding.
I guess use of [URI#getRawQuery](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html#getRawQuery()) and then decoding later would solve the issue.

https://github.com/plan-player-analytics/Plan/blob/73147b5f8a98fd39d4672dc4124c519994e75c68/Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/RequestHandler.java#L149
https://github.com/plan-player-analytics/Plan/blob/73147b5f8a98fd39d4672dc4124c519994e75c68/Plan/api/src/main/java/com/djrapitops/plan/delivery/web/resolver/request/URIQuery.java#L49
