### ISSUE TITLE
Can't run server from a subdirectory (nginx)

### ISSUE THREAD

**Issue by Rundik** [plan-player-analytics/Plan#1455]
### Describe the issue
I'm running plan behind a nginx proxy in /plan subdirectory. Scripts, styles etc have an absolute path and can't be accessed from a subdirectory

**Comment by Rsl1122** [comment]
If you're running nginx in subdirectory you need to add a rewrite rule that removes the subdirectory from the address of any requests before they reach Plan.

You also need to point Plan links to your nginx by setting `Webserver.Alternative_IP` to `domain.com/plan`

**Comment by Rundik** [comment]
@Rsl1122 I tryed both and nothing worked. I don't think rewrite rule can help here
Here is what I used:
```nginx
location /plan {
    rewrite /(.*) /plan/$1 break;
    proxy_pass http://localhost:8804;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by Rsl1122** [comment]
Have you managed to fix this issue? I've seen people on discord with subdirectory reverse-proxies but I don't unfortunately have their configurations to help here

**Comment by turikhay** [comment]
This should work:

```nginx
location /plan/ { 
  proxy_pass http://127.0.0.1:8804/;

  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

I just added trailing slashes to my location and proxy_pass urls.
