### ISSUE TITLE
Make better use of caching

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1459]
### Is your feature request related to a problem? Please describe.

Current data cache stores stuff for the site for a few minutes.
The cache time settings could be exposed to users so that they can be tweaked in case the site is taking a long time to load.

### I would like to be able to..

- Load cached data even if it is from previous day so that first load is fast.
- Display loading icon for everything that is not up to date
- Decouple loading of data and the data-loading requests to avoid webserver getting swamped. Poll server for updates if out of date.

In order to make the use of cache transparent to users a "Last refreshed" date should be displayed next to each item, and some endpoints could be used to update the data when newer version comes available.

To keep memory usage low with the cache, the json could be stored on disk after calculation.

The caching should be configurable by users so that users can optimize wether they want to keep things in memory or on disk or not use cache at all.

**Comment by Leonardo-Fiori** [comment]
Any news so far? My plan is still half broken 😃

**Comment by Rsl1122** [comment]
This issue is up next on the feature backlog
https://github.com/plan-player-analytics/Plan/projects/10
