### ISSUE TITLE
Questions about network#online-tab

### ISSUE THREAD

**Issue by 10935336** [plan-player-analytics/Plan#1461]
### Question

My web service runs on proxy's Plan.
Some servers are deployed on proxy, but some are not, they are all connected to the same database.

If a server connected to the same database is deployed outside of proxy, then in network overview network#online-tab will not show the players of that server, is this expected behavior?

### Additional context

network overview
![image](https://user-images.githubusercontent.com/32383605/82872082-1faa7700-9f65-11ea-8698-217bc8dffd21.png)

Servers that are deployed outside of proxy
![image](https://user-images.githubusercontent.com/32383605/82872209-48cb0780-9f65-11ea-8e84-92c8fbb14185.png)

**Comment by Rsl1122** [comment]
Yes, the network overview online count shows the players online given by the proxy server (Something along the lines of Bungee#getOnlinePlayerCount)
