### ISSUE TITLE
MySQL Database Init Failure (Timezone)

### ISSUE THREAD

**Issue by good777LUCKY** [plan-player-analytics/Plan#1464]
### Describe the issue

I want to connect with MySQL but it says `[Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'KST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`. What is wrong?

### Server information

Latest Build of Nukkit.

### Exceptions & Other Logs

`[Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'KST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`

**Comment by Rsl1122** [comment]
See https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up on how to fix
