### ISSUE TITLE
Chat logging

### ISSUE THREAD

**Issue by Flo122** [plan-player-analytics/Plan#1473]
### Is your feature request related to a problem? Please describe.
No problem 

### I would like to be able to..
U can see in the server Statistic what a player wrote to the chat and when 
Example 
Today at 15.34 the player Name here wrote blablabla

**Comment by Rsl1122** [comment]
Chat logs is something that has been requested in the past (#1261, #657, #344).

I do not think chat logs should be a part of Player Analytics. Here are my reasons:
- It appears invasive to the players
- It is difficult to incorporate to the context of other analytics, ie:
  - Impossible to keep context of conversations for player pages, so the chat logs would only appear on the server page
  - Same context issue with sessions, would each session have *all* chat that happened within that session
- A personal anecdote: Reading chat logs about someone going through a rough time while you've been asleep is not good.
- Chat logs can contain personal information and would place Plan data under GDPR and I don't want to deal with consent stuff.
