### ISSUE TITLE
TimeZone issues - MySQL 8 doesn't like EDT/UTC....etc

### ISSUE THREAD

**Issue by revpixel** [plan-player-analytics/Plan#1482]
TimeZone issues - MySQL 8 doesn't like EDT/UTC....etc 

`10:48:23 [ERROR] [Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.`

Do you have an option to change the flag like with Launch After Options? (That would allow manual setting of the TZ?

_Originally posted by @revpixel in https://github.com/plan-player-analytics/Plan/pull/1413#issuecomment-640073360_

**Comment by Rsl1122** [comment]
See https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up for the launch options setting

**Comment by revpixel** [comment]
Sometimes I've found the following flag works but launch after JDBC isn't resolving for me on this plugin

`useLegacyDatetimeCode=false`

**Comment by revpixel** [comment]
> See https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up for the launch options setting

You cannot set UTC as a TIMEZONE in MySQL 8 (I can set the session time to -4:00 for example and use the FALSE flag as referenced earlier and that works (also settings the GLOBAL Time to -4:00 

But that still is a work around....what I'd like to see is either a newer JDBC driver (or an option to configure it more finely? The proper code for MySQL in session for the new TZX support is: 
`SET  @@global.time_zone="-4:00"`

It defaults to SYSTEM (which is still -4:00 for me as an example but if I don't set the vaulue specifically and then set this on the the plugin (below) the plugin will fail to load

`useLegacyDatetimeCode=false`

**Comment by Rsl1122** [comment]
What exactly is the issue? - The `Database.MySQL.Launch_options` setting allows configuring the connector

**Comment by revpixel** [comment]
> What exactly is the issue? - The `Database.MySQL.Launch_options` setting allows configuring the connector

Because it's a deprecated workaround that will eventually stop working.

**Comment by Rsl1122** [comment]
So `&serverTimezone=UTC` is a deprecated launch option?

**Comment by Rsl1122** [comment]
As seen here, Plan sets timezone for the session as soon as connection is established. https://github.com/plan-player-analytics/Plan/blob/fe66c2dd6331400910daf793bb592e639497a438/Plan/common/src/main/java/com/djrapitops/plan/storage/database/MySQLDB.java#L148

But here the connection fails for some reason.

I will consider moving this execution to HikariCP `connectionInitSql` option to see if it sorts out any future issues

**Comment by revpixel** [comment]
yes....without the option for using legacy timezone support additonally at the server level for MySQL 8 take a look at the output when trying to set timezones using EDT vs -4

`11:11:50	SET  @@global.time_zone="EDT"	Error Code: 1298. Unknown or incorrect time zone: 'EDT'	0.000 sec
11:12:23	SET  @@global.time_zone="-4:00"	0 row(s) affected	0.000 sec
11:12:36	SELECT @@global.time_zone LIMIT 0, 1000	1 row(s) returned	0.000 sec / 0.000 sec`

And here is the value of the current field (once changed from SYSTEM) which is the default value which has to be done for this or any down-level JDBC driver to work with the legacy option. 

`# @@global.time_zone
-04:00`

**Comment by revpixel** [comment]
Thanks...even adding that as a configurable option in the config.yaml would help I think so it doesn't use UTC,EDT, etc.

**Comment by Rsl1122** [comment]
MySQL itself defaults to SYSTEM so if your system changes to daylight saving time (EDT - Eastern Daylight Saving Time) MySQL does not recognize it. MySQL does not recognize any DST timezone.

>.even adding that as a configurable option in the config.yaml would help I think so it doesn't use UTC,EDT, etc.
Your comments confuse me and I do not understand what config option you are referring to.

**Comment by revpixel** [comment]
correct...even as SYSTEM (and the server is EDT MySQL doesn't recognize that as an incoming connection option for timezone support. Based on the fact you're pushing +00:00 and not UTC tho should (I would think mean it wouldn't fail with an EDT value....

I'll push it back to SYSTEM and see if I can figure out if there is any other reason it's bugging.

**Comment by revpixel** [comment]
Confirmed... I removed the legacy option and with your new build (600)

I see no TZ issues.

**Comment by Aurelien30000** [comment]
Now causes issue with 'CEST' timezone, but nevermind, additional launch option fixed it :)
