### ISSUE TITLE
Server timezone configuration

### ISSUE THREAD

**Issue by Floffah** [plan-player-analytics/Plan#1489]
I just now updated from build 5.1 562 i think it was to build 5.1 600 and am getting the error:
```
SEVERE [Plan] ----------------------------------------
SEVERE [Plan] Error: MySQL init failure: Failed to initialize pool: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
SEVERE [Plan] ----------------------------------------
SEVERE [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /planbungee reload
```
on all servers (3 paper and 1 bungeecord)

I have tried changing Formatting.Dates.TimeZone to 'UTC' but that doesn't solve the issue. I can't find any other similar configuration property to 'serverTimezone' and i am wondering where i do this?

### Additional context
paper servers:
 - 1.15.2 plan 5.1 600
 - 1.13.2 plan 5.1 600
 - 1.8.8 plan 5.1 600

an 1 bungee server.

**Comment by Rsl1122** [comment]
See https://github.com/plan-player-analytics/Plan/wiki/Bungee-Set-Up#%EF%B8%8F-if-you-get-mysql-time-zone-error-on-start-up
