### ISSUE TITLE
Suggestion: USTATS support

### ISSUE THREAD

**Issue by Pwnzeye** [plan-player-analytics/Plan#1500]
It would be an awesome addition to the panel because USTATS collects tons of data about the player

Thank you!

**Comment by Rsl1122** [comment]
Please open a new suggestion that follows [the plugin suggestion template](
https://github.com/plan-player-analytics/Plan/issues/new?labels=New+Feature%2C+DataExtensions%2C+Help+Wanted&template=plugin_request.md)
