### ISSUE TITLE
Suggetsion: Add Tebex/Buycraft player verification end point.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#1501]
This is a long shot, but worth a suggestion.

Today I had an issue where someone used a VPN to buy 10x the cheapest thing on my store for 10 random people on my server, as Tebex does not verify usernames when they are typed in, any user can put in any username at the checkout, they then instantly charged back all 10, as they know that I have automated bans setup for Chargebacks those poor 10 random users were auto banned!, what a ball ache!

**How is this anything to do with Plan?**
Tebex actually has player verification but it requires an endpoint that has to be hosted by yourself with your own code. There is nothing that exists that anyone can just set this up themselves at all.

https://docs.tebex.io/store/preventing-fraud/player-verification

https://blog.tebex.io/feature-spotlight-enhanced-user-verification-and-user-actions/

1. Requires web server endpoint (Plan has a web server)
2. Requires a history of IP addresses from players (Plan has this!)
3. Country requested from and the country of the user (Plan has this!)

Plan already has everything needed to create an endpoint for verifying players using Tebex, all they would need to do is put in the URL/IP of their plan install into tebex.

This would instantly allow thousands of people that run plan to protect their stores with 1 simple copy and paste of a URL.

The only issue I can think of would be authentication checking the request is coming from buycraft/a way to test as an end user that its working for requests.
Maybe a whitelist of allowed requests based on IP/Domain?

I know this is out of the scope of Plan, but its a perfect fit for data you already collect and being a very useful tool to thousands of people with very basic setup once implemented.

**Comment by Rsl1122** [comment]
A worthy suggestion for a Plan add-on.

- Plan no longer stores IP addresses of players.
I dunno how big of an issue that is for this, as it could be ignored.
- As this feature is out of scope for Plan, it might make sense as a separate plugin that integrates into Plan. It is currently possible to make this using [PageExtension API](https://github.com/plan-player-analytics/Plan/wiki/APIv5-PageExtension-API) to add an endpoint to the Plan webserver that does this.

----

[The feature backlog](https://github.com/plan-player-analytics/Plan/projects/10) is crowded.
If you need this badly another developer might have more time than I currently have.

**Comment by FrozenBeard** [comment]
That is one hell of a feature list of todos.

Is there somewhere I can read why IPs are no longer kept? Quite important when it comes to moderation, or has the project goals moved to be more universal for players to see data as opposed to just an admin tool?

Not much point making it work with Plan if no IPs are kept any more, key bit of information required for it to work! I think Ban Manager keeps a full history of IP's but no webserver.

I guess I will just make a PHP script to do this, shame!

**Comment by Rsl1122** [comment]
The IPs are no longer kept because it would have been more work to ensure consent of users for gathering that data (for GDPR reasons) than removing them from the code. In addition the constant requests for changing them one way or the other was creating more work than that small thing on the website deserves.

**Comment by Rsl1122** [comment]
Closing this as out of scope. It looks like I don't have time to write another plugin to do this.

**Comment by TomLewis** [comment]
No sweat.
