### ISSUE TITLE
MythicMobs [Free Version] - Integration Request

### ISSUE THREAD

**Issue by apollogauss** [plan-player-analytics/Plan#1507]
### Data to display

Count the number of different Mobs killed
### Plugin information

**API or Source Code:** [Link](https://www.mythicmobs.net/javadocs/)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/history)

**Comment by AuroraLS3** [comment]
The data that is wanted is difficult to gather from the plugin.
