### ISSUE TITLE
Feature request: GB notation option

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1511]
### Is your feature request related to a problem? Please describe.
Quantities are displayed in MB on the main Performance page:
```
Average RAM Usage | 2873.72 MB | 2902.13 MB | 2959.06 MB
Max Free Disk     | 43456 MB   | 42440 MB   | 40895 MB
Min Free Disk     | 39236 MB   | 39236 MB   | 39525 MB
```

### I would like to be able to..
Option to display in GB:
```
Average RAM Usage | 2.87 GB  | 2.90 GB  | 2.96 GB
Max Free Disk     | 43.46 GB | 42.44 GB | 40.90 GB
Min Free Disk     | 39.24 GB | 39.24 GB | 39.53 GB
```
without custom processing.

**Comment by Rsl1122** [comment]
Would it be sufficient if it automatically formatted to GB when over 1000 MB? Configurable features always increase complexity more than automated ones

**Comment by SlimeDog** [comment]
That would work for me. One vote. :)

**Comment by Rsl1122** [comment]
Added a task here https://github.com/plan-player-analytics/Plan/projects/13
