### ISSUE TITLE
Import command for playtime from Minecraft Statistics

### ISSUE THREAD

**Issue by austin4195** [plan-player-analytics/Plan#1515]
### Is your feature request related to a problem? Please describe.
I consolidated my network to a single server and reset everything along with it. Took me a while to get everything up and running so players have been playing on the server while I got everything with Plan set up. Finally, Plan is set up only now the playtime metrics are off.

### I would like to be able to..
Run an import command to bring the playtime from the built-in Minecraft Statistics into Plan so that they would sync up.

Something like /plan import playtime

Prompts with a warning saying that this will overwrite existing playtimes stored, please confirm.

Command run.

**Comment by Rsl1122** [comment]
Sort of similar to #872 - follow that issue for resolution
