### ISSUE TITLE
Solution to Privacy without needing SSL [Permission based IP whitelist addition]

### ISSUE THREAD

**Issue by Konsider** [plan-player-analytics/Plan#1521]
Is it possible to make it so that the IP of the server OP is automatically written into the whitelist, each time they sign into the server? Obviously the IP can change, so if it was done automatically, the OP could easily check stats and the stats would effectively be security protected? If an IP change is detected, the plugin could write it into the whitelist and then auto restart the plugin?

**Comment by vacoup95** [comment]
I really don't understand why you would need so many different ways to sign in, there's already accounts. But, it doesn't matter anyways, you can only read data in this panel and nothing that would violate a user's privacy. This is not a good replacement for SSL if you're going to privacy though, as SSL prevents man in the middle attacks. Meaning, if someone is listening in on, let's say your entire WiFi network at MacDonalds. SSL encrypts the traffic in between requests. So, this solution doesn't help for privacy. 
You're better off setting a username and password imho.

**Comment by AuroraLS3** [comment]
After consideration automated whitelist implementations have been deemed out of scope.
