### ISSUE TITLE
Safari: logo height is stretched

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1527]
### Describe the issue

![example](https://media.discordapp.net/attachments/466241867797889054/734493577115074560/unknown.png?width=1362&height=677)

Reported on discord

### Additional information

Safari probably does not apply `height: auto` by default so setting a width to an image might cause this behavior.
Will add that css property to `img` even though I can't test it

**Comment by yashendra2797** [comment]
You didn't need to make this an issue. I appreciate it, but the Safari user base is so small that you shouldn't be spending your time figuring out WebKit fuckery. :)

**Comment by Rsl1122** [comment]
It is an issue even if it doesn't get fixed until 2 years later 😉
