### ISSUE TITLE
Completely hide a tab when a feature is disabled

### ISSUE THREAD

**Issue by lifehome** [plan-player-analytics/Plan#1539]
### Is your feature request related to a problem? Please describe.
Currently, by disabling a feature in configuration does not hide certain figures/area/tables on the web panel.
![image](https://user-images.githubusercontent.com/1886237/88878212-015d4200-d25a-11ea-990e-ece4efb8c6a1.png)
![image](https://user-images.githubusercontent.com/1886237/88878228-08845000-d25a-11ea-9ded-06d1241069e6.png)

### I would like to be able to..
For example, if I disabled the Geolocation gathering, the Geolocation tab button and page should be disabled as well.

**Comment by Rsl1122** [comment]
This is probably possible to do.

While waiting you can do this manually with [Html customization](https://github.com/plan-player-analytics/Plan/wiki/Html-Customization)

**Comment by AuroraLS3** [comment]
### TODO

- Implement this after #1623 by removing tab.geolocations permission from web user if geolocation is disabled

**Comment by AuroraLS3** [comment]
Latest dev release has options if user authentication is enabled to hide geolocations by removing page.server.geolocations permission from the group user is in.
