### ISSUE TITLE
Enable Webserver by default on Sponge

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1548]
### Is your feature request related to a problem? Please describe.

Ore guidelines state that if the main purpose of the plugin is related to external connections then it is allowed to be enabled by default.
> If your project’s sole purpose involves utilizing an external system (such as a Sponge plugin that translates chat between languages), a configuration option to toggle making connections to that service is not required.
https://docs.spongepowered.org/stable/en/ore/guidelines.html

### I would like to be able to..

Have Plan enable the webserver by default on Sponge servers when installed for the first time.

**Comment by Vankka** [comment]
Wiki will need updating here: https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#step-2-change-webserver-port and here: https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#sponge
