### ISSUE TITLE
Login when Enter is pressed

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1557]
### Is your feature request related to a problem? Please describe.

Currently enter does nothing in the login form

### I would like to be able to..

Log in by pressing enter in the login screen

**Comment by lerokko** [comment]
I'd like to add that I am unable to press tab to select the next field. And that Firefox is no longer able to recognize this as a login window. I can not store passwords. This did not happen on the old login page.

**Comment by Rsl1122** [comment]
Yep it is missing proper role attributes. I'll fix it for next update.
