### ISSUE TITLE
Plugin Suggestion - Hellconomy

### ISSUE THREAD

**Issue by johnyuki** [plan-player-analytics/Plan#1560]
### Data to display
It'd be real nice if a graph could show a players balance over time. Just a nice little linegraph that goes up or down as a player has money withdrawn/deposited from/to their accounts.

### Plugin information

https://github.com/TheNewEconomy/HellConomy

https://github.com/TheNewEconomy/HellConomy/releases

**Comment by AuroraLS3** [comment]
Looked into this, HellConomy only stores balances, and does not provide events for money transactions - because of that it is not practical to obtain history or record transaction history to create a graph of the balance over time (A timed task could cause too much load on the economy).
