### ISSUE TITLE
NukkitPetteriM1Edition Support

### ISSUE THREAD

**Issue by good777LUCKY** [plan-player-analytics/Plan#1561]
### Is your feature request related to a problem? Please describe.

When I try to load Plan in NukkitPetteriM1Edition, it will load Bukkit source, so it will fail to load plugin.

### I would like to be able to..

Can you support NukkitPetteriM1Edition? (https://github.com/PetteriM1/NukkitPetteriM1Edition)

**Comment by Rsl1122** [comment]
Could you send an enable log snippet to see what the error is

**Comment by good777LUCKY** [comment]
> Could you send an enable log snippet to see what the error is

Error log was 
![Screenshot_2020](https://user-images.githubusercontent.com/43497313/91130778-27ee8b80-e6e7-11ea-8aa0-5fa44a65a9ec.jpg)

**Comment by Rsl1122** [comment]
Looks like their class loader is reading plugin.yml instead of nukkit.yml

I can't unfortunately change plugin.yml because that is used by Bukkit. Try suggesting their edition to prefer nukkit.yml over plugin.yml like the upstream version of nukkit, should sort out the issues.

**Comment by Rsl1122** [comment]
While waiting for them to implement that change you can open the Plan jar up with an archive manager and rename nukkit.yml to plugin.yml

**Comment by good777LUCKY** [comment]
> While waiting for them to implement that change you can open the Plan jar up with an archive manager and rename nukkit.yml to plugin.yml

thank you, i will try it
