### ISSUE TITLE
Loading animation on certain pages are visually bugged.

### ISSUE THREAD

**Issue by HeavenCrafter** [plan-player-analytics/Plan#1566]
This is mostly a visual issue related to the HTML side of the plugin. On certain web pages, the loading page is bugged while on others, it's completely fine.

Not sure how exactly I can fix this even after going through the HTML codes so hopefully, I could get some help with this.

Normal page loader.
![image](https://user-images.githubusercontent.com/22242534/91620218-e4836e00-e9c1-11ea-8fad-86dc02289df8.png)

Weird visually bugged loader.
![image](https://user-images.githubusercontent.com/22242534/91620147-adad5800-e9c1-11ea-8ca9-da2ba7c8fca7.png)

**Comment by HeavenCrafter** [comment]
The weird animation bug only occurs when clicking on a player page. On everything else, so far from what I can see, looks completely fine.

![image](https://user-images.githubusercontent.com/22242534/91620306-27dddc80-e9c2-11ea-93ca-0c88a38e1a56.png)

**Comment by Rsl1122** [comment]
Looks like `player.html` has wrong kind of loader structure so that causes the text to go off center

Correct structure
```html
<div class="page-loader">
    <span class="loader"></span>
    <p class="loader-text">Please wait..</p>
</div>
```

[Incorrect structure on player.html](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/player.html#L31-L34)
```html
<div class="page-loader">
    <span class="loader"></span>
    <span class="loader-text">Please wait..</span>
</div>
```

**Comment by HeavenCrafter** [comment]
Will check on the fix, thank you for the quick response.

**Comment by HeavenCrafter** [comment]
Issue has been resolved. And no longer occurs. Thank you for the quick fix and response.

**Comment by Rsl1122** [comment]
Would you like to PR the changes to player.html to get it fixed for everybody? :)
(You can click the pen icon on top of this page and edit the file, then open a PR https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/player.html#L31-L34)

**Comment by Rsl1122** [comment]
Added task here https://github.com/plan-player-analytics/Plan/projects/13
