### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by Equity7** [plan-player-analytics/Plan#1567]
I have used Plan Analytics for at least 8 months and am well-acquainted with it. I am running Paper 1.16.2 and have the latest version of the plugin. I am using an bungee network and everything is fine in all the config files. It was working fine one day and the next I get the following error when I try to load the webserver. (I looked first to see if anyone else reported this issue and couldn't find any reports.) I checked with my webhost and they said there is nothing wrong with my MySQL database. Not sure how to proceed.

 500 Internal Error occurred
Please report this issue here: Issues

```
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed. | /network
    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:146)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:61)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:51)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$0(NetworkPage.java:102)
    com.djrapitops.plan.delivery.domain.container.CachingSupplier.get(CachingSupplier.java:50)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$1(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCacheString(JSONCache.java:68)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.toHtml(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.forPage(ResponseFactory.java:95)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.networkPageResponse(ResponseFactory.java:148)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerPage(ServerPageResolver.java:86)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$resolve$0(ServerPageResolver.java:71)
    java.util.Optional.map(Optional.java:215)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:71)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:186)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:137)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:133)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
    plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
    com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:128)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:50)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:61)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:51)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$0(NetworkPage.java:102)
    com.djrapitops.plan.delivery.domain.container.CachingSupplier.get(CachingSupplier.java:50)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$1(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCacheString(JSONCache.java:68)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.toHtml(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.forPage(ResponseFactory.java:95)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.networkPageResponse(ResponseFactory.java:148)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerPage(ServerPageResolver.java:86)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$resolve$0(ServerPageResolver.java:71)
    java.util.Optional.map(Optional.java:215)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:71)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:186)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:137)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:133)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
```

**Comment by Equity7** [comment]
I should add the Plan error logs from my bungeecord server:

---- Context 5 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Transaction: class com.djrapitops.plan.extension.implementation.storage.transactions.providers.StoreProviderTransaction
DB State: OPEN

---- Context 4 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Transaction: class com.djrapitops.plan.extension.implementation.storage.transactions.providers.StoreProviderTransaction
DB State: OPEN

---- Context 3 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Transaction: class com.djrapitops.plan.extension.implementation.storage.transactions.providers.StoreProviderTransaction
DB State: OPEN

---- Context 2 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Transaction: class com.djrapitops.plan.extension.implementation.storage.transactions.providers.StoreProviderTransaction
DB State: OPEN

---- Context 1 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Transaction: class com.djrapitops.plan.extension.implementation.storage.transactions.providers.StoreProviderTransaction
DB State: OPEN

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: StoreProviderTransaction initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
   java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: StoreProviderTransaction initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   com.djrapitops.plan.storage.database.transactions.Transaction.initializeTransaction(Transaction.java:174)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:84)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:249)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:128)
   com.djrapitops.plan.storage.database.transactions.Transaction.initializeTransaction(Transaction.java:171)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:84)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:249)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:242)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:201)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer$Gatherer.gather(ProviderValueGatherer.java:184)
   com.djrapitops.plan.extension.implementation.providers.gathering.ProviderValueGatherer.updateValues(ProviderValueGatherer.java:153)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:169)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:158)
   com.djrapitops.plan.gathering.listeners.bungee.PlayerOnlineListener.lambda$beforeLogout$3(PlayerOnlineListener.java:138)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:79)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
--------------------------------------------------------------------------------------------------------

--- Context 1 ----
Plan v5.1 build 657
BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532
Server vgit:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:e93c762:1532

Error code: 0
SELECT uuid, last_seen FROM (SELECT MAX(session_end) as last_seen, uuid FROM plan_sessions GROUP BY uuid) as q1 WHERE last_seen < ?
Unknown SQL Error code

---- Stacktrace ----
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Plan Connection Pool-1 - Connection is not available, request timed out after 30000ms.
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:146)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
   com.djrapitops.plan.storage.upkeep.DBCleanTask.cleanOldPlayers(DBCleanTask.java:128)
   com.djrapitops.plan.storage.upkeep.DBCleanTask.run(DBCleanTask.java:108)
   com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:55)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.SQLTransientConnectionException: Plan Connection Pool-1 - Connection is not available, request timed out after 30000ms.
   plan.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:128)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:50)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
   com.djrapitops.plan.storage.upkeep.DBCleanTask.cleanOldPlayers(DBCleanTask.java:128)
   com.djrapitops.plan.storage.upkeep.DBCleanTask.run(DBCleanTask.java:108)
   com.djrapitops.plugin.task.bungee.BungeeRunnableFactory$1.run(BungeeRunnableFactory.java:55)
   net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
plan.com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   plan.com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
   plan.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
   plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
   plan.com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
   plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
   plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
   plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
   plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
   plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
   plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
   plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
plan.com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   sun.reflect.GeneratedConstructorAccessor105.newInstance(Unknown Source)
   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
   plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
   plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
   plan.com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
   plan.com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
   plan.com.mysql.cj.NativeSession.connect(NativeSession.java:144)
   plan.com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
   plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
   plan.com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
   plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
   plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
   plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
   plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
   plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
   plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
   plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.net.ConnectException: Connection refused (Connection refused)
   java.net.PlainSocketImpl.socketConnect(Native Method)
   java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
   java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
   java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
   java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
   java.net.Socket.connect(Socket.java:607)
   plan.com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
   plan.com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
   plan.com.mysql.cj.NativeSession.connect(NativeSession.java:144)
   plan.com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
   plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
   plan.com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
   plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
   plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
   plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
   plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
   plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
   plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
   plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
   plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
   java.util.concurrent.FutureTask.run(FutureTask.java:266)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)

**Comment by Rsl1122** [comment]
Looks like MySQL server stopped accepting connections for a bit and since Plan doesn't reconnect if the connection is lost (#1458) the error occurred.
I received some note about this in the feedback form recently, and reloading Plan should temporarily fix the issue.

Follow the linked issue in this comment for resolution to the problem.
