### ISSUE TITLE
500 internal error

### ISSUE THREAD

**Issue by Til-Weimann** [plan-player-analytics/Plan#1576]
### Describe the issue

Console is spamming this:

>.... [21:18:11 ERROR]: [Plan] Ran into DBOpException - logged to plugins/Plan/logs/DBOpException-1738821493.txt
>.... [21:18:11 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
>.... [21:18:11 ERROR]: [Plan] Error msg: "SQL Failure: HikariDataSource HikariDataSource (Plan Connection Pool-2) has been closed."

com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: HikariDataSource HikariDataSource (Plan Connection Pool-2) has been closed.
at com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:146) ~[?:?]
at com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55) ~[?:?]
at com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233) ~[?:?]
at com.djrapitops.plan.settings.network.ServerSettingsManager.checkDBForNewConfigSettings(ServerSettingsManager.java:145) ~[?:?]
at com.djrapitops.plan.settings.network.ServerSettingsManager.access$100(ServerSettingsManager.java:59) ~[?:?]
at com.djrapitops.plan.settings.network.ServerSettingsManager$1.run(ServerSettingsManager.java:131) ~[?:?]
at com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-184]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-184]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-184]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

>.... [21:20:04 WARN]: [Plan] Plugin Plan v5.1 build 657 generated an exception while executing task 77

### Server information

Paper 1.16.2, Plan v5.1 build 657
[DBOpException-7da3d0fb09.txt](https://github.com/plan-player-analytics/Plan/files/5227269/DBOpException-7da3d0fb09.txt)

### Exceptions & Other Logs

_com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: HikariDataSource HikariDataSource (Plan Connection Pool-2) has been closed. | /server/Server 1
    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:146)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$getServerUUID$1(ServerPageResolver.java:103)
    java.util.Optional.flatMap(Optional.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerUUID(ServerPageResolver.java:102)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:70)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:186)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:137)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:133)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-2) has been closed.
    plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
    com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:128)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:50)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:233)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$getServerUUID$1(ServerPageResolver.java:103)
    java.util.Optional.flatMap(Optional.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerUUID(ServerPageResolver.java:102)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:70)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:186)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:137)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:133)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)_

### Additional information

Server restart seems to have fixed it

**Comment by Rsl1122** [comment]
Caused by #1458 - follow that issue for resolution
