### ISSUE TITLE
Compatibility to geysermc

### ISSUE THREAD

**Issue by Elguerrero11** [plan-player-analytics/Plan#1590]
### I would like to be able to..

Compatibility to geysermc for see who player are from bedrock edition and who of java edition.

**Comment by Rsl1122** [comment]
I don't see a way to ask geyser code about who is java and who is not so this is unfortunately not possible. (I did a quick look so I might be wrong)

This ticket was also opened using the wrong template. You should have used this instead. https://github.com/plan-player-analytics/Plan/issues/new?labels=New+Feature%2C+DataExtensions%2C+Help+Wanted&template=plugin_request.md

**Comment by BenjiButton** [comment]
The integration would actually be through Floodgate, which has an API to get details about the java/bedrock player on geyser and the device they are using as well for bedrock players

### Data to display
Player type (java / bedrock)
bedrock version
Player device used
can also display other information listed in the floodgate placeholders

### Plugin information


**API or Source Code:** [Link](https://github.com/GeyserMC/Floodgate)  

**Project page or Downloads:**
- [Geyser download](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/)
- [Floodgate download](https://ci.nukkitx.com/job/GeyserMC/job/Floodgate/job/development/)

**Example API usage:** [FloodgatePlaceholders](https://github.com/rtm516/FloodgatePlaceholders)

**Comment by Elguerrero11** [comment]
Thanks and sorry, I'm not used to using github, I'll use the other template next time.
I will hope to see that feature in the future :D
