### ISSUE TITLE
World Analytics

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [plan-player-analytics/Plan#1604]
### Is your feature request related to a problem? 
No

I want to be able to get analytics of what world players spend time in. 

### I would like to be able to..

I want analytics to show of like what server people spend the most time in but for worlds, so it would show what the most popular worlds are and what world each player spends the most time in. 
Also has a World's section which shows how much player time is spent in each one.

**Comment by Rsl1122** [comment]
There is already a world playtime pie that also allows breakdown of gamemodes - Does this not fill the wanted purpose? In what ways?

**Comment by ElementalMinecraftGaming** [comment]
Ah, yes. Sorry, didn't see that. 😂

**Comment by Rsl1122** [comment]
Well good that this got cleared up :)
