### ISSUE TITLE
Failed to load Players table data: Timed out after 45 seconds. (../v1/players?server=ID)

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#1606]
### Describe the issue
Clicking Player List times out, with `Failed to load Players table data: Timed out after 45 seconds. (../v1/players?server=idhere)`
If I click overview I get `Failed to load values: Timed out after 45 seconds. ` & also `Failed to load values: Request did not reach the server. (Server offline / Adblocker?)`

I have had over 250,000 unique players join my server.

Geolocations seems to work.

### Server information
Paper 1.12.2
Plan Build 5.1 - 770

Im using the internal web server but through a Nginx Proxy with Auth.

**Comment by Rsl1122** [comment]
Hmm, you can try decreasing the player table size in the config to see if that helps 🤔 
Otherwise this needs #1459

**Comment by HexedHero** [comment]
I've always had this issue but recently it's been pretty much impossible to view and now just never loads.
