### ISSUE TITLE
Lands Plugin 

### ISSUE THREAD

**Issue by cooleepicminer** [plan-player-analytics/Plan#1616]
### Plugin information

**API or Source Code:** [Link](https://github.com/Angeschossen/LandsAPI)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/lands-minecraft-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-16-support.53313/)

**Comment by Rsl1122** [comment]
Please provide information about what data you would like to be displayed about the plugin

**Comment by Rsl1122** [comment]
Closing as the required information was not given. Please provide the information to reconsider this.
