### ISSUE TITLE
Quest Extension

### ISSUE THREAD

**Issue by Skyfighter1** [plan-player-analytics/Plan#1632]
### Data to display

Pls add stats for Quest. This is the famous quest plugin and I thinl many would like stats for it...

### Plugin information

**API or Source Code:** [Link](https://www.spigotmc.org/resources/quests.3711/)

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/quests.3711/)

**Comment by Rsl1122** [comment]
What kind of stats?

**Comment by Rsl1122** [comment]
Duplicate of #1608

**Comment by Skyfighter1** [comment]
Stats like how many players did which quests. So server owners can see what players like.

**Comment by AuroraLS3** [comment]
How to implement:
- Dependency from https://jitpack.io/#PikaMug/Quests
- Get player specific quests through `Bukkit.getPluginManager().getPlugin("Quests")`, cast, `cuests.getStorage().getQuester(UUID)` https://github.com/PikaMug/Quests/blob/master/main/src/main/java/me/blackvein/quests/Quester.java
- Store completed quests as a table I guess
- For server table, perform an aggregation query of the player table data for the quests
