### ISSUE TITLE
Placeholder for lastseen not working when player is offline

### ISSUE THREAD

**Issue by MrTorchic** [plan-player-analytics/Plan#1634]
Title says it all when we try to see how long someones been online when running it on the server all it does it post the variable in plain text is this intentional? 

### Additional context

![image](https://user-images.githubusercontent.com/67416737/97995436-59e13580-1d9b-11eb-817b-3e9ade67c8a2.png)
First is when the player is offline
Second is when the player is online

**Comment by Rsl1122** [comment]
It kinda makes sense considering that the placeholder is about the player who is online seeing the text 🤔

**Comment by MrTorchic** [comment]
I'm very sorry I meant offline apologies

**Comment by Rsl1122** [comment]
Yes, I understood.

The implementation in Plan only shows placeholders about `player_` for a player who is seeing the placeholder, so when the player is offline (I'm guessing you're using commandline or something else), Plan doesn't know who this player is so it doesn't give a placeholder value

**Comment by Aitnys** [comment]
/papi parse SirTorchic %plan_player_lastseen% 

half the player placeholders dont make sense to only be seen by the player themselves though which is why i figured there was a way to show them for offline players.

**Comment by Rsl1122** [comment]
Ah I see.. It is probably easier to use `plan ingame <username>` for that

**Comment by Aitnys** [comment]
Ok lets start at the beginning :) I want to show more information then whats available in the essentialsx /seen.. I was hoping I would be able to use plans last seen placeholder to do that part of it.
