### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by ItzPeto** [plan-player-analytics/Plan#1648]
I recommend adding push notifications. When someone joins or leaves, gets banned or kicked or when theres a low tps spike. Its always good to stay updated with things like this.
(I would be really happy if the notifications for bans and kicks would work with Litebans)

**Comment by Rsl1122** [comment]
On one hand, yeah it might be useful. On the other hand, I think there is enough noise in the world already.

I think something like push notifications should be a completely separate plugin from Plan.
Besides nothing in Plan has real-time support implemented for it (I think someone was asking for Plan events at some point, but they don't exist).
