### ISSUE TITLE
Other BentoBox Addons

### ISSUE THREAD

**Issue by fredthedoggy** [plan-player-analytics/Plan#1649]
### Is your feature request related to a problem? Please describe.

Nope, Just a missing GameMode
### I would like to be able to..

I would like to be able to access bentoboxes newest gamemode AOneBlock from the bentobox addon, as well as what MagicCobblestoneGenerator They have selected.
(Preferably also able to show the AOneBlock phase and blocks broken aswell :)

https://github.com/plan-player-analytics/Extension-BentoBox/tree/master/src/main/java/com/djrapitops/extension

**Comment by AuroraLS3** [comment]
Unfortunately MagicCobblestoneGenerator does not provide add on request for getting the generator, same with AOneBlock related data - the add on request part has been largely ignored it seems.
