### ISSUE TITLE
DBOpException: PingStoreTransaction initialization failed

### ISSUE THREAD

**Issue by Til-Weimann** [plan-player-analytics/Plan#1650]
### Describe the issue
Got this error on the plan panel + console and it said I should report it here.
Dont know why this happened, restarting the server removed it (I will post an update if it comes back).

### Server information
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

### Exceptions & Other Logs
Paper 1.16.4 (271), Plan 5.1 791

com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: HikariDataSource HikariDataSource (Plan Connection Pool-3) has been closed. | /server/Server 1
    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:150)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$getServerUUID$1(ServerPageResolver.java:103)
    java.util.Optional.flatMap(Optional.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerUUID(ServerPageResolver.java:102)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:70)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:187)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-3) has been closed.
    plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
    com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:127)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:50)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$getServerUUID$1(ServerPageResolver.java:103)
    java.util.Optional.flatMap(Optional.java:241)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerUUID(ServerPageResolver.java:102)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:70)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:187)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)

--------
--------

aa06d02371 - Last occurred: 2020-11-21 Occurrences: 1134
---- Context 5 ----
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.events.PingStoreTransaction
DB State: OPEN

---- Context 4 ----
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.events.PingStoreTransaction
DB State: OPEN

---- Context 3 ----
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.events.PingStoreTransaction
DB State: OPEN

---- Context 2 ----
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.events.PingStoreTransaction
DB State: OPEN

---- Context 1 ----
Plan v5.1 build 791
Paper git-Paper-271 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Transaction: class com.djrapitops.plan.storage.database.transactions.events.PingStoreTransaction
DB State: OPEN

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: PingStoreTransaction initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
   java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: PingStoreTransaction initialization failed: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   com.djrapitops.plan.storage.database.transactions.Transaction.initializeTransaction(Transaction.java:174)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:84)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:257)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.SQLException: HikariDataSource HikariDataSource (Plan Connection Pool-1) has been closed.
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:127)
   com.djrapitops.plan.storage.database.transactions.Transaction.initializeTransaction(Transaction.java:171)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:84)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:257)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:250)
   com.djrapitops.plan.gathering.timed.BukkitPingCounter.run(BukkitPingCounter.java:156)
   com.djrapitops.plugin.task.bukkit.BukkitRunnableFactory$1.run(BukkitRunnableFactory.java:55)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
   net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297)
   net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
   net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212)
   net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
   net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
   java.lang.Thread.run(Thread.java:748)

**Comment by Rsl1122** [comment]
Because it says "data source was closed" it is likely that the mysql suffered from a momentary connection loss. Follow this issue for resolution https://github.com/plan-player-analytics/Plan/issues/1458

**Comment by Rsl1122** [comment]
Possibly fixed by 8423e392bb5630a2561b5c27563d14b75e4b907b
