### ISSUE TITLE
Parts of webpage being falsely detected as phishing attempts on Firefox 83

### ISSUE THREAD

**Issue by bitrot-alpha** [plan-player-analytics/Plan#1651]
### Describe the issue

My primary browser is Firefox, and until I updated from Plan `build 657`, I could load the webpage and login just fine.
Now, when I load up the webpage, it looks like this:
![image](https://user-images.githubusercontent.com/55378293/99899834-0c047280-2c61-11eb-8270-4653113c4fb9.png)
On Edge or Chrome, the webpage will load just fine.
Since for whatever reason the Javascript running the webpage doesn't work, I can't login on Firefox.

### Server information

[config.yml](https://hastebin.com/ijipodedas.yaml)
```
>plan info
Version: 5.1 build 813
Update Available: No
Current Database: SQLite (OPEN)
Connected to Proxy: No
```

### Exceptions & Other Logs

I don't know what to include here at the moment. There doesn't seem to be any relevant logs that I can provide.

### Additional information

The server has hopped a few operating systems and machines, so I may have missed something in one of the migrations.
Also, my SSL certificate is about to expire, but hasn't yet, and I don't get this issue using another browser.

<h5>This is my first issue..</h5>

**Comment by Rsl1122** [comment]
Looks like the login page css is missing - have you modified css via html customization?

If not

- Please open a new browser tab and open developer tools (ctrl+shift+I or F12) 
- then go to *Network* and then open the Plan page. 
- Try to enlarge the view and take a screenshot so that the issue can be further debugged (to see if it is a missing resource or something else blocking the css)

**Comment by Rsl1122** [comment]
Please also include any errors on the dev tools *Console*

**Comment by bitrot-alpha** [comment]
Here's the dev tools screenshots.

**Comment by bitrot-alpha** [comment]
> Here's the dev tools screenshots.

![Network Tab](https://user-images.githubusercontent.com/55378293/99916268-fe310a80-2cbd-11eb-94c2-f28c7c8321ab.png)
![Console](https://user-images.githubusercontent.com/55378293/99916270-ff623780-2cbd-11eb-9201-819dba7dc56d.png)

It looks like Firefox with Safe Browsing enabled falsely detects the JS and CSS as Phishing attempts..

**Comment by bitrot-alpha** [comment]
This issue also happens regardless of whether I'm on my own network (LAN) or accessing the page remotely.

**Comment by bitrot-alpha** [comment]
![Firefox security preferences](https://user-images.githubusercontent.com/55378293/99916526-7f3cd180-2cbf-11eb-9f29-38aeee90ac35.png)

The webpage works normally when I disable "Block dangerous and deceptive content" in Firefox Preferences.

**Comment by bitrot-alpha** [comment]
Aside from updating the plugin, the only other change (since it stopped working on Firefox) is that I registered my DNS record as both an A (IPv4) and AAAA (IPv6).

**Comment by Rsl1122** [comment]
Are you using a valid https certificate? (A self signed cert apparently can cause this issue, so checking if this is the cause)

**Comment by bitrot-alpha** [comment]
HTTPS cert is from CertBot (Let's Encrypt), so it should be fine.. For now.
I'll try a totally new certificate when the existing one expires in a few
days.

**Comment by Rsl1122** [comment]
Very weird. I'm not sure what to do in this situation because googling firefox safe browsing issues comes up with nothing - I also can't reproduce the issue on my own panel with firefox 83.

**Comment by bitrot-alpha** [comment]
Cert expires this Friday. I’ll register an all new one soon after that, and
try again.

**Comment by Rsl1122** [comment]
Was this issue resolved after registering a new certificate?
(I was reminded of it when reading https://gomox.medium.com/google-safe-browsing-can-kill-your-startup-7d73c474b98d)

**Comment by bitrot-alpha** [comment]
New certificate fixed it. You can close the issue.
