### ISSUE TITLE
30 minute offset for Timezone not being applied to graphs

### ISSUE THREAD

**Issue by brofin** [plan-player-analytics/Plan#1652]
### Describe the issue

Graphs are displaying the time 30+ minutes of what it should be. The timezone the server is in is called ["Newfoundland Time"](https://en.wikipedia.org/wiki/Newfoundland_Time_Zone).

### Server information

Paper-288.
5.1 build 813

**Comment by Rsl1122** [comment]
Bugfix for this was rather clean, "Stop rounding the hours and give minutes a chance"
