### ISSUE TITLE
Logblock data

### ISSUE THREAD

**Issue by arriej** [plan-player-analytics/Plan#1653]
### Data to display
Information about amount of certain blocks mined. 
Can be used/calculated in a way to also expose players with higher count for diamonds or other valuable resources. 
Back in the day i used this [this ](https://github.com/redpoptarts/X-Ray-Detective) Xray detective website to catch people.

### Plugin information

**API or Source Code:** [Link](https://github.com/LogBlock/LogBlock/wiki/API)  
Or can just read from the mysql database. 

**Project page or Downloads:** [Link](https://github.com/LogBlock/LogBlock)

I feel like this would be a nice Addon if you're already logging blockdata in a mysql database.

**Comment by Rsl1122** [comment]
Please expand what are the "certain blocks mined" - this would make it a lot easier to make something that fits needs instead of something generic

**Comment by arriej** [comment]
Sorry, Noticed I included the wrong link to the piece of software I was referring to. Changed that link. 
For the data I would like to see: 

on the user stats pages an over view if the mined blocks,
Stone, Granite, Diorite, Andersite, Gold Ore, Iron Ore, Coal Ore, Diamond Ore, Redstone Ore, and Lapis Lazuli Ore. 

Based on the Ratio of ores to stone mined you can make a strong suggestion of someone is using x-ray. 
> Ratio of ores to stone - The average user may find a diamond once out of every 300 blocks mined. A very lucky user may find a diamond once out of every 200 blocks. However, a user with X-Ray may consistently find diamonds in 1 out of every 30 blocks mined. Some X-Rayers even discover diamonds in 1 in 10 blocks! This is 10 to 30 times the average rate!

With that data you can then display the users ranked from high to low chance of using x-ray for a general server page. 
(this does make it more an admin feature that you might want to put behind a login screen )

**Comment by wysohn** [comment]
This issue possibly can be merged with #1642
