### ISSUE TITLE
Unhandled corner case of worlds

### ISSUE THREAD

**Issue by bobhenl** [plan-player-analytics/Plan#1656]
### Is your feature request related to a problem? Please describe.

Hi, i'm frustrated from the full config of my worlds. I have player worlds plugin and there are too many worlds there, even if they aren't already exist.
### I would like to be able to..

Hi, I would be able to stop generate new worlds there, if it's possible, or automatically detect and delete non existing worlds, if they aren¨t loaded in main folder or by multiverse, or somehow by plan. SO, there are 2 ways how it could be solved:
1. Way to stop generate new worlds and add them only manually.
2. Way to detect which worlds are really existing etc. by Plan automatically

----

*by AuroraLS3:*

### TODO

- Move world aliases setting to world aliases list config point
- Add world aliases regex config point
  - Alias: "regex"
- Comment both properly to avoid confusion
- Change logic that checks if world has an alias by matching regex
- Use regex check when alias matches a regex instead of the list of world names.

**Comment by Rsl1122** [comment]
The issue with removing worlds when they no longer exist is that Plan still stores data about that world - It might make more sense to keep the existing worlds. I don't know if there is some event for world unloading.

I think an alternative would be to add a regex based world alias scheme - Is it possible to detect that the world is player made from its name this way (do they share a common prefix perhaps)?
This way there would be one alias for all of the player made worlds and I wouldn't have to code a ton of new code for a corner case

**Comment by bobhenl** [comment]
Yes sorry that I forget to reply. They have prefix PW_ like https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-the-nether-and-the-end-support-expiration-1-8-1-16-4.72113/updates. Would be glad if you could try to solve it with your suggested method.

**Comment by AuroraLS3** [comment]
Sorry that this took so long to implement.

Next update will have `World_aliases.Regex` that allows using regex for the described use-case:
```yml
World_aliases
    Regex:
        - "Player world:PW_.*"
```
