### ISSUE TITLE
Add Lands support

### ISSUE THREAD

**Issue by AZFire1** [plan-player-analytics/Plan#1664]
### Data to display

Lands is like Towny. So, probably the amount of lands.
### Plugin information

**API or Source Code:** [Link]() https://github.com/Angeschossen/LandsAPI 

**Project page or Downloads:** [Link]() (Paid Plugin) https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-wars-1-16-support.53313/

**Comment by Rsl1122** [comment]
Duplicate of #1429 - follow that issue for resolution
