### ISSUE TITLE
Dark theme on external URL

### ISSUE THREAD

**Issue by mechcalvin** [plan-player-analytics/Plan#1666]
i export external URL https://mc.mechcalvin.com/wom_stats/network/ but the dark theme is messed up also the network hour by hour tab do not load, also it seems it is much slower than using port: http://mc.mechcalvin.com:8804, however I would like to use https with external link

**Comment by Rsl1122** [comment]
The `${defaultTheme}` variable is not replaced in /js/color-selector.js file.
You can use https://github.com/plan-player-analytics/Plan/wiki/Html-Customization to fix it while waiting for a fixed version.
Change this line https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/js/color-selector.js#L13 to say `'night'` or `'plan'` instead

**Comment by mechcalvin** [comment]
doesn't seems to work, i will wait for the fix
