### ISSUE TITLE
SB Admin2 css

### ISSUE THREAD

**Issue by TOWUK** [plan-player-analytics/Plan#1670]
### Describe the issue
I don't understand your code, but I sort of aligned the text a little through the browser, maybe there will be somewhere else, I will add it
![image](https://user-images.githubusercontent.com/28830162/101613984-6f422300-3a1d-11eb-89c3-0c64e2ef5ad3.png)
in General, it's not clear what I did, I'm not a web developer, but I want it to be beautiful, maybe you will find a better solution to this problem

!!!!! https://startbootstrap.com/previews/sb-admin-2 (demo sbadmin2)
![image](https://user-images.githubusercontent.com/28830162/101615983-d9f45e00-3a1f-11eb-8c41-f73ddd72e67e.png)

maybe update core sb admin2?

### Server information
paper latest, plan latest now

### Exceptions & Other Logs
none

### Additional information

```
<div class="dataTables_length" id="DataTables_Table_0_length" style="
    margin-left: 11.400px;
"><label>Show <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div>
```

```
<div class="row" style="
    padding-top: 11.400px;
"><div class="col-sm-12 col-md-5" style="
    left: 11.400px;
"><div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 0 to 0 of 0 entries</div></div>
```

**Comment by AuroraLS3** [comment]
Forgot to close this after fixing this in 5.2 build 1063
