### ISSUE TITLE
AAC broken integration

### ISSUE THREAD

**Issue by untuned** [plan-player-analytics/Plan#1673]
### Describe the issue

The recent AAC 5.0.0 release broke integration with Plan.

### Server information

1.16.4, Plan 5.1 build 813

### Exceptions & Other Logs

```
[08:05:34 ERROR]: [Plan] Plugin Plan v5.1 build 813 has failed to register events for class com.djrapitops.extension.AACHackKickListener because me/konsolas/aac/api/PlayerViolationCommandEvent does not exist.
```

**Comment by Rsl1122** [comment]
Disable the AAC integration in the Plan config.

This is an expected breakage since they have upped their Major version to 5 from 4.

**Comment by untuned** [comment]
I do not believe it is possible to get the status of a player at the current time with the API, does this mean the AAC extension will be removed?

**Comment by Rsl1122** [comment]
I don't know - the current use of the API listens for kick events and stores data about those, I doubt the events were removed, just moved to another location or renamed.
If there are no events to listen to or that data is not stored by AAC then there is no use for the extension as there would be no data. I'll see when I get to updating it

**Comment by Rsl1122** [comment]
It appears that the kick event was removed as an API, and the new API does not provide a method to listen for this event.

Because of this there is **no way to obtain any data from AAC** and the extension will disable in the future versions if AAC v5+ is in use.
