### ISSUE TITLE
Ran into CompletionException and IllegalArgumentException on Geyser player join

### ISSUE THREAD

**Issue by Technoguyfication** [plan-player-analytics/Plan#1674]
### Describe the issue

When a player from Geyser joins the server, Plan throws a CompletionException or IllegalArgumentException. This only seems to happen with Bedrock players connecting through Geyser. Players who connect through Geyser are given a prefix of "*", which I believe may be illegal in one of the columns in the database. The logs mention GriefPrevention too, so I'm really not sure where to start here.

### Server information

Server: Paper 1.16.4 b291
Plan: 5.1 build 791, Database: SQLite
Geyser: 1.2.0-SNAPSHOT
GriefPrevention: 16.16.0

### Exceptions & Other Logs

Here is a compilation of all the console errors, obtained by grepping the console output for Plan errors:
https://paste.ubuntu.com/p/m7RQt2R8BD/

These are all the files in the `plugins/Plan/logs` folder:
https://paste.ubuntu.com/p/njcXjNBbmy/
https://paste.ubuntu.com/p/wP2xPwhcC9/
https://paste.ubuntu.com/p/kn6wfkkXhR/
https://paste.ubuntu.com/p/8VZ446B79K/
https://paste.ubuntu.com/p/4gZnYWmxhR/

### Additional information

Unfortunately I can't change my prefix for Geyser players, and I know this probably isn't a supported use scenario, but I'd appreciate any guidance I can get with this issue!

**Comment by Technoguyfication** [comment]
As an added note, I'm planning on migrating to MySQL anyways, so I'm open to trying that out and seeing if it fixes the issue!

**Comment by Rsl1122** [comment]
Already fixed in build 813 https://github.com/plan-player-analytics/Plan/releases/tag/5.1.813 (Under Extensions)
