### ISSUE TITLE
PlaceholderAPI not working

### ISSUE THREAD

**Issue by alfdef1** [plan-player-analytics/Plan#1676]
### Describe the issue
I am trying to access the Plan PlaceholderAPI as documented but's not working.
I've tried %player_server_time_active% and %player_time_active%
https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

### Server information
Plan: 5.1 build 813
Server: 1.16.4

**Comment by Rsl1122** [comment]
Try `%plan_player_server_time_active%` instead.

![image](https://user-images.githubusercontent.com/24460436/102761236-558acf00-437f-11eb-99e8-b0583ad45701.png)

**Comment by alfdef1** [comment]
Thanks, Sorry I somehow misread that.
