### ISSUE TITLE
Network Overview Page shows only statistics of the server the main Plan instance is running at

### ISSUE THREAD

**Issue by alfdef1** [plan-player-analytics/Plan#1677]
### Describe the issue
The network Overview on my side is not an Overview of all Servers in the network (connected to the main Plan instance) it is just an overview of players of the Server Plan is running at.

The Graph and some of the Numbers you can see in this image are only representing the server Plan is running on not the whole "Network"
![plan_network_overview](https://user-images.githubusercontent.com/10639428/102994937-59a22280-4520-11eb-82c7-4e9d9b532a38.PNG)

### Server information
I am running the main Instance of Plan with the website enabled on a separate BungeeCord instance. My main BungeeCord hasn't installed Plan to avoid overload or possible attacks. Every spigot other Server in my Network has Plan installed and reports to the Main instance, which works fine.

It would be great to have this fixed because then we can use the Network page to see an overview of the whole network and not only the main instance plan is running.

**Comment by Rsl1122** [comment]
Sorry, I am having a hard time understanding the issue.

As I understand it you have 2 bungeecord instances with Plan on a secondary, not so important bungeecord, that still gets players on it from somewhere.
You can install RedisBungee and Plan will take the online count from that instead.

If this is incorrect interpretation, could you draw a diagram that explains your network's servers and where Plan is installed or not

**Comment by alfdef1** [comment]
Sorry for my late response.
My current setup is a Sub Bungee where the Main Bungee is connecting to and on this Sub Bungee Plan is running.
I just was thinking if there would be a possibility to calculate the network overview using data from all the servers and not only the main Plan instance. This is already done for the weekly comparison below the graph but not for the data in the graph.

Using RedisBungee would solve this when I am running Plan on another bungee instance synced to the main bungee, which I will do in the future.

This is minor and was just about why the network page is showing different data for the graph and the statistic boxes below if someone uses a weird setup.

**Comment by Rsl1122** [comment]
The statistics below should remain accurate if the game servers have Plan installed, as most of them are calculated from other data.

The online player graph however is gathered by a task on bungeecord which is why it either shows only the traffic of that bungee or the information from RedisBungee.

Issues with combining data from all servers is that it would take more resources to do so - especially if calculating the graph from session entries.

I'll close this as solved since you're going to use redisbungee
