### ISSUE TITLE
Copying server config to bungee before bungeecord installation causes server name to be wrong in the database

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#1678]
### Describe the issue

If the following line is in the config (ServerName), the server identification will pick up the name from the config instead of using "BungeeCord", making Plan not detect it as a proxy server.
```yml
Server:
    ServerName: Plan
```

### Additional information

Due to technical debt Plan detects bungeecord instances from name "BungeeCord" in the database. Due to recent changes to server identification the config name can be used instead, as it was assumed the field is not present in the proxy config.

That field can however be added if the original config is from a server and bungeecord config defaults are copied on top of it.

**Comment by ItTakesTwo** [comment]
FYI: this also breaks the multi server functionality in combination with a proxy.
As long as `Server.ServerName` is present in the config file, the `Network.Name` value will not be picked up and `/plan network` only returns `Server is not connected to a network. The link redirects to server page.`
Additionally the web interface always redirects to the server page from the server running the Plan webserver and does not show any network information.

**Comment by AuroraLS3** [comment]
This has been fixed in the latest version by replacing the proxy detection with platform based instead of name based check
