### ISSUE TITLE
Crash on startup - Sponge

### ISSUE THREAD

**Issue by Druwan-ctrl** [plan-player-analytics/Plan#1680]
### Describe the issue
The server crashes on startups as per crash log

### Server information
spongeforge-1.12.2-2838-7.3.0.jar
Plan-5.1-build-813.jar 
hell lot of other mods, but everything stable

### Exceptions & Other Logs
https://pastebin.com/NHZfbGi2

### Additional information
Was trying to make it work on the game server after setting up correctly on velocity

**Comment by Rsl1122** [comment]
I dunno, seems like bStats metrics class is missing from sponge forge jar

**Comment by Druwan-ctrl** [comment]
Ok, what can I try to fix this?

**Comment by Rsl1122** [comment]
Try a newer version of spongeforge

**Comment by Druwan-ctrl** [comment]
Sadly i can't, newer versions of sponge require a non-recommended version of sponge and i have the FutureMc mod (https://www.curseforge.com/minecraft/mc-mods/future-mc) that requires a newer one. Shouldn't Plan work with the recommended version of sponge? Maybe my jar got corrupted or some core mods are conflicting?

**Comment by Rsl1122** [comment]
I don't know - it's a bit weird.
Error says
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Plan (plan)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
 
1) No implementation for org.bstats.sponge.Metrics2 (with no qualifier annotation) was bound, and could not find an injectable constructor. Injectable classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at org.bstats.sponge.Metrics2.class(Metrics2.java:41)
  while locating org.bstats.sponge.Metrics2
    for field at com.djrapitops.plan.PlanSponge.metrics(PlanSponge.java:62)
```
Sponge tends to crash if you touch it wrong so I dunno where the issue is, could be load order, something modifying the class, change of implementation, bug in sponge, corrupted sponge jar, corrupted Plan jar. Unfortunately there isn't enough information to say which or if it is even one of these

**Comment by Druwan-ctrl** [comment]
I will try to upload everything again so i'm sure that nothing is corrupted, then place sponge and plan 1° and 2° in load order and see if that solves the problem, will need some time though

**Comment by Druwan-ctrl** [comment]
Ok, renamed spong with a prefix "a-" and plan with "aa-" and it seems to work now. If you want to be sure i will close this myself if it's stable for a few days

**Comment by Rsl1122** [comment]
Interesting workaround
