### ISSUE TITLE
Use CDN instead of local file url

### ISSUE THREAD

**Issue by mrjesen** [plan-player-analytics/Plan#1686]
### Is your feature request related to a problem? Please describe.
load file from local filesystem is not the fast,I think.
I prefer to use CDN link.
### I would like to be able to..
change the static file url into "https://cdn.jsdelivr.net/gh/plan-player-analytics/Plan@html/Plan/src/main/resources/assets/plan/web/*****"
or I can change the url through editing the config.yml file.

**Comment by Rsl1122** [comment]
You can change the addresses with html customization https://github.com/plan-player-analytics/Plan/wiki/Html-Customization - CDN is not used for assets to allow customization of the library files as well if necessary.
