### ISSUE TITLE
java.lang.IllegalStateException: ExtensionService has not been initialised yet.

### ISSUE THREAD

**Issue by carbotaniuman** [plan-player-analytics/Plan#1710]
### Describe the issue

I followed the tutorial for loading plan, but I get an error 
```
java.lang.IllegalStateException: ExtensionService has not been initialised yet.
```
in the logs. I followed the tutorial and copy pasted `PlanHook`, so I assume I'm using the wrong listener.

```
public class It {
    @Inject
    private Logger logger;

    @Listener
    public void onServerStart(GamePostInitializationEvent event) {
        logger.info("Loading It!");
        try {
            new PlanHook(logger).hookIntoPlan();
        } catch (NoClassDefFoundError planIsNotInstalled) {
            logger.warn("Data extension not loaded", planIsNotInstalled);
            // Plan is not installed
        }
    }
}
```

**Comment by Rsl1122** [comment]
Have you added Plan as a dependency so that Plan is enabled before your plugin?

**Comment by Rsl1122** [comment]
Plan starts on `GameStartedServerEvent` https://github.com/plan-player-analytics/Plan/blob/master/Plan/sponge/src/main/java/com/djrapitops/plan/PlanSponge.java#L81

**Comment by carbotaniuman** [comment]
```
@Plugin(
        id = "it",
        name = "It",
        version = "1.0-SNAPSHOT",
        dependencies = {
                @Dependency(id = "plan")
        }
)
```
it appears this still loads before Plan which is probably causing the issue. Versions are SpongeForge `1.12.2-2838-7.3.0` and Plan `5.1 build 813`.

**Comment by Rsl1122** [comment]
Odd, I guess you could try moving to `GameStartedServerEvent` as the listener

**Comment by carbotaniuman** [comment]
I completely misread the `GameStartedServerEvent` part. Thanks!
