### ISSUE TITLE
500 Internal Error occurred [MySQL is down]

### ISSUE THREAD

**Issue by Frodwo** [plan-player-analytics/Plan#1718]
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Plan Connection Pool-8 - Connection is not available, request timed out after 30000ms. | /network
    com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:151)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:55)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:61)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:51)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$0(NetworkPage.java:102)
    com.djrapitops.plan.delivery.domain.container.CachingSupplier.get(CachingSupplier.java:50)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$1(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCacheString(JSONCache.java:68)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.toHtml(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.forPage(ResponseFactory.java:95)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.networkPageResponse(ResponseFactory.java:148)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerPage(ServerPageResolver.java:86)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$resolve$0(ServerPageResolver.java:71)
    java.util.Optional.map(Optional.java:215)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:71)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:187)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: Plan Connection Pool-8 - Connection is not available, request timed out after 30000ms.
    plan.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
    plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
    plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
    plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
    com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:127)
    com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:50)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:61)
    com.djrapitops.plan.extension.implementation.storage.queries.ExtensionServerDataQuery.executeQuery(ExtensionServerDataQuery.java:51)
    com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$0(NetworkPage.java:102)
    com.djrapitops.plan.delivery.domain.container.CachingSupplier.get(CachingSupplier.java:50)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.lambda$toHtml$1(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCacheString(JSONCache.java:68)
    com.djrapitops.plan.delivery.rendering.pages.NetworkPage.toHtml(NetworkPage.java:106)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.forPage(ResponseFactory.java:95)
    com.djrapitops.plan.delivery.webserver.ResponseFactory.networkPageResponse(ResponseFactory.java:148)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.getServerPage(ServerPageResolver.java:86)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.lambda$resolve$0(ServerPageResolver.java:71)
    java.util.Optional.map(Optional.java:215)
    com.djrapitops.plan.delivery.webserver.resolver.ServerPageResolver.resolve(ServerPageResolver.java:71)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:187)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: plan.com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    plan.com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
    plan.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
    plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
    plan.com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:456)
    plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
    plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
    plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
    plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: plan.com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    sun.reflect.GeneratedConstructorAccessor221.newInstance(Unknown Source)
    sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
    plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
    plan.com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
    plan.com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
    plan.com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
    plan.com.mysql.cj.NativeSession.connect(NativeSession.java:144)
    plan.com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
    plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
    plan.com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:456)
    plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
    plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
    plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
    plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
    java.net.PlainSocketImpl.socketConnect(Native Method)
    java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    java.net.Socket.connect(Socket.java:589)
    plan.com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
    plan.com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
    plan.com.mysql.cj.NativeSession.connect(NativeSession.java:144)
    plan.com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
    plan.com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
    plan.com.mysql.cj.jdbc.ConnectionImpl.(ConnectionImpl.java:456)
    plan.com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
    plan.com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
    plan.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
    plan.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
    plan.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
    plan.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
    plan.com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
    plan.com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
    java.util.concurrent.FutureTask.run(FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)

**Comment by Rsl1122** [comment]
Your MySQL seems to be down
