### ISSUE TITLE
Add a warning on network page stats when no game servers are in the database

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1730]
### Describe the issue

Week comparison is mostly zeros when network has no game servers installed.

This might confuse users, so it would be beneficial to add a notice on there

**Comment by Rsl1122** [comment]
While at it, it might be beneficial to add warnings for Geolite EULA, Geolocation gathering, Ping gathering, Disk space gathering & chunk gathering on sponge warnings.
