### ISSUE TITLE
DBOpException when loading /network

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1731]
### Describe the issue
Upgraded from `Plan 5.1 build 813` to `5.2 build 970` and started getting DBOpExceptions whenever the /network page (front page) gets loaded.

### Server Information
**Plan Version:** 5.2 build 970
**Server:** BungeeCord git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395 (git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395)
**Database:** MySQL _(DB server is MariaDB)_

**Operating SubSystem:** Linux (amd64) version 5.4.0-56-generic
**Java Version:** 1.8.0_275, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.275-b01, Oracle Corporation
### Benchmarks
```
18 ms      +2 MB   subsystem-enable
```
### Exceptions & Other Logs
https://gist.github.com/Kopo942/770c6f07223310e25a24dbff988c12a6

**Comment by Rsl1122** [comment]
I see what is causing it, will fix it for next dev release.
Feel free to downgrade to 904 or 813 in the meantime if this is critical
