### ISSUE TITLE
Broken JS because of translations

### ISSUE THREAD

**Issue by QuakyCZ** [plan-player-analytics/Plan#1734]
### Description
This bug report refers to my pull request #1732.

After I translated all possible keys, I found several problems with JS. These translations has overwritten the code (names of functions, comments).

For example this [row](https://github.com/plan-player-analytics/Plan/blob/3f118a5ea8ffb6badb9f1ee6901e0812b407ac4f/Plan/common/src/main/resources/assets/plan/locale/locale_CS.txt#L217) was originally `/ Player`. But this is in our language little bit weird. So I translated it as `na hráče (per player)`. However, by removing the `/` character, many parts of website features have broken up (`/player/nick` and `/query`). There is a comment in js files `/js/player-values.js:12` and `query.js:343` which was rewritten by my translation. Because there is no `/` at the beginning of the translation, the comment has only 1 `/`. This is causing wrong syntax and whole js file is broken.

This also causes problem when I try to perform a query. Website calls translated function instead of original (`performNewQuery`). The problem is in the word `New` which was translated too.

### Server information

v5.2 build 970

### Exceptions & Other Logs

`Uncaught SyntaxError: unterminated regular expression literal player-values.js:12:30`
`Uncaught ReferenceError: performNovýQuery is not defined (onclick https://plan.example.com/query:1)`

**Comment by Rsl1122** [comment]
I have opened the ticket #1733 for fixing the technical debt causing this issue, but this one probably needs to be fixed by renaming the broken javascript to something else
