### ISSUE TITLE
Make HTTP session timeout configurable

### ISSUE THREAD

**Issue by BrainStone** [plan-player-analytics/Plan#1740]
### Is your feature request related to a problem? Please describe.

My problem is that I very often have to reauthenticate on the page which has become a major nuisance to the point where checking stats has turned from a joy to a chore.

### I would like to be able to..

To combat this I would like to have a couple options:
- Configurable session lengths.  
  While I can see an argument being made for the current 2 hour limit as a default it definately needs to be configurable
- Option to allow session refreshing. Meaning that the session ends X amount after the last successful request of the user.  
  That allows continuous usage of the panel but still logs out the user fairly quickly on inactivity. I personally think this should default to true for convenience.
- Option to persist sessions across restarts.  
  As Discussed on Discord currently the sessions get lost on restarts. There at least should be an option to persist them across restarts so sessions can stay active for an extended period of time even if there are regular server restarts.

Source code: https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/delivery/webserver/auth/ActiveCookieStore.java#L32

**Comment by AuroraLS3** [comment]
I implemented configurable session lengths and persistence for sessions.

The session refreshing part was a bit complex to implement because of multiple expiry mechanisms (one on the browser and one on the server). If the two above features turn out to not be enough for reducing the annoyances, please open a new ticket for session refreshing
