### ISSUE TITLE
Plan logs reached 6.3 Gb on disk and consumed all free space on disk

### ISSUE THREAD

**Issue by NDruce** [plan-player-analytics/Plan#1744]
### Describe the issue
See screenshots below.

### Server information
Paper 1.12.2
Plan v5.1-b563

### Additional information

![image](https://user-images.githubusercontent.com/33526036/107224706-d6ce1c00-6a28-11eb-8d53-81abc9a83803.png)

![image](https://user-images.githubusercontent.com/33526036/107224455-7fc84700-6a28-11eb-9653-df19b3391299.png)

![image](https://user-images.githubusercontent.com/33526036/107224513-953d7100-6a28-11eb-97eb-927701e519a4.png)

**Comment by Rsl1122** [comment]
This issue has been fixed in build 586. Consider updating to build 813

**Comment by Rsl1122** [comment]
https://github.com/plan-player-analytics/Plan/wiki/Migration-guide-to-Version-5.1-build-768
