### ISSUE TITLE
Error on calling the Servertab in Network-Overview

### ISSUE THREAD

**Issue by Pretoreaner** [plan-player-analytics/Plan#1749]
### Describe the issue
I had an issue when i called the Servertab in the webinterface, to solve the issue i reseted the complete database. afte restarting the intire network i get the saaame issue

### Server information
**Plan Version:** 5.1 build 813
**Server:** BungeeCord Aegis fork (Aegis fork)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.15.0-122-generic
**Java Version:** 11.0.9.1, Ubuntu
**Java VM Version:** OpenJDK 64-Bit Server VM version 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, Ubuntu
### Benchmarks
```
402 ms     -725 KB subsystem-enable
```

### Exceptions & Other Logs
db7857fb3a - Last occurred: 2021-02-09 Occurrences: 2
---- Context 2 ----
Plan v5.1 build 813
BungeeCord Aegis fork
Server vAegis fork

Request{method='GET', path=URIPath{path='/v1/network/servers'}, query=URIQuery{byKey={}}, user=WebUser{playerName='console', username='Iron_Beagle_', permissions=[page.server, page.players, page.player.self, page.debug, page.player.other, page.network]}, headers={}}

---- Context 1 ----
Plan v5.1 build 813
BungeeCord Aegis fork
Server vAegis fork

Request{method='GET', path=URIPath{path='/v1/network/servers'}, query=URIQuery{byKey={}}, user=WebUser{playerName='console', username='Iron_Beagle_', permissions=[page.server, page.players, page.player.self, page.debug, page.player.other, page.network]}, headers={}}

---- Stacktrace ----
java.lang.NullPointerException
   com.djrapitops.plan.storage.database.queries.objects.TPSQueries$4.prepare(TPSQueries.java:150)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:64)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:52)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:241)
   com.djrapitops.plan.delivery.rendering.json.JSONFactory.serversAsJSONMaps(JSONFactory.java:174)
   com.djrapitops.plan.delivery.rendering.json.network.NetworkTabJSONCreator.get(NetworkTabJSONCreator.java:32)
   com.djrapitops.plan.delivery.webserver.cache.JSONCache.lambda$getOrCache$0(JSONCache.java:78)
   com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCache(JSONCache.java:54)
   com.djrapitops.plan.delivery.webserver.cache.JSONCache.getOrCache(JSONCache.java:76)
   com.djrapitops.plan.delivery.webserver.resolver.json.NetworkTabJSONResolver.getResponse(NetworkTabJSONResolver.java:56)
   com.djrapitops.plan.delivery.webserver.resolver.json.NetworkTabJSONResolver.resolve(NetworkTabJSONResolver.java:52)
   com.djrapitops.plan.delivery.web.resolver.CompositeResolver.lambda$resolve$2(CompositeResolver.java:110)
   java.base/java.util.Optional.flatMap(Optional.java:294)
   com.djrapitops.plan.delivery.web.resolver.CompositeResolver.resolve(CompositeResolver.java:110)
   com.djrapitops.plan.delivery.web.resolver.CompositeResolver.lambda$resolve$2(CompositeResolver.java:110)
   java.base/java.util.Optional.flatMap(Optional.java:294)
   com.djrapitops.plan.delivery.web.resolver.CompositeResolver.resolve(CompositeResolver.java:110)
   com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:181)
   com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:138)
   com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:134)
   com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:97)
   jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
   jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
   jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
   jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
   jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
   jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:662)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:834)

### Additional information
Server is now runing on Aegis but i already get this issue on paper 1.16.4 we used bevor

**Comment by Rsl1122** [comment]
It appears that Plan is not detecting the proxy server properly. 

This could be caused by https://github.com/plan-player-analytics/Plan/issues/1678 - Check that your proxy server config does not have `Plugin.ServerName` in it (If it does, remove it and the problem should go away with a couple of reloads)

**Comment by Pretoreaner** [comment]
Thx it woked
