### ISSUE TITLE
No data on Chunks at all

### ISSUE THREAD

**Issue by 456and7strings** [plan-player-analytics/Plan#1752]
### Describe the issue
I have no data on the Average Chunks in 'Performance as Numbers' (marked a 'Unavailable') or Chunks data point in the Performance graph (marked as '-6' all the way through). I have tried both using the local database and setting up MySQL to see if that would solve the issue. I was running the server on the local database for around a 2 weeks and saw no change.

### Server information
**Plan Version:** 
5.1 build 813
**Server:** 
Forge: 14.23.5.2847
Sponge 1.12.2-7.1.4 (API 7.1.0-70763aa8)
**Database:** 
MySQL 

### Exceptions & Other Logs
/config/plan/logs is empty

**Comment by AuroraLS3** [comment]
Chunks are not gathered on sponge because it affected the performance even with single player online - A note will be added about this in the future <https://github.com/plan-player-analytics/Plan/issues/1730#issuecomment-773393189>
