### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by MrFreasy** [plan-player-analytics/Plan#1753]
### Server information
This server is running Tuinity version git-Tuinity-"f8c0db4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plan version: 5.1 build 813

### Exceptions & Other Logs
https://pastebin.com/tFAU5xG3

**Comment by AuroraLS3** [comment]
Duplicate of #1673 - disable AAC integration on the Plan config.
AAC integration will be disabled in the next version (AAC 5 has no api for data)
