### ISSUE TITLE
Is there any way to limit the number of connections plan makes to a MySQL database

### ISSUE THREAD

**Issue by sebbyd05** [plan-player-analytics/Plan#1754]
Is there I way to limit the number of times each plan instance connects to my database?

### Additional context

I'm working on setting up Plan with a MySQL database for my Bungeecord network. I'm having an issue with it saying that the database has reached it's maximum number of connections (10 because I am using a free MySQL hosting site). Is there a way for me to limit how many connections it has to the database per client? 

Thanks!

**Comment by AuroraLS3** [comment]
I can add a setting for next version

**Comment by sebbyd05** [comment]
Awesome, thanks!!
