### ISSUE TITLE
Plan placeholders unsupported

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1756]
### Describe the issue

Due to
- Placeholders no longer replaced on the server thread to avoid unintentional server crashes

placeholders are no longer accessible.

### Server information

Spigot 1.16.5-3007
Plan 5.2-b1056

### Exceptions & Other Logs

Both in-game and at the console:
```
/papi parse SlimeDog %plan_player_death_count%
[placeholder replacement on server thread is not supported by Plan because it can crash the server!]
```
This was true for all the placeholders I attempted.

**Comment by AuroraLS3** [comment]
Commands are always run on the server thread, including papi parse

**Comment by AuroraLS3** [comment]
I will consider doing a similar async refresh thing as the json for the web pages is now.

**Comment by SlimeDog** [comment]
> Commands are usually run on the server thread, including papi parse

Understood, but placeholders also don't expand in my scoreboard (QuickBoard). Is that a Plan issue, or a board issue?

**Comment by AuroraLS3** [comment]
It's unfortunately likely that most plugins run the placeholder replacement on the server thread since all the examples do so.

**Comment by SlimeDog** [comment]
Given AuroraLS3 comment, is Plan going to address this issue, or should QuickBoard (and other scoreboard)?

**Comment by AuroraLS3** [comment]
> Given AuroraLS3 comment, is Plan going to address this issue, or should QuickBoard (and other scoreboard)?

It needs to be addressed in Plan since it's pretty much impossible to demand every other plugin suddenly starts doing their placeholder replacement differently because I want to access the database during a placeholder request.

Doing it off the server thread is of course advisable for every single plugin because there is no telling if someone else is going to do what Plan build 813 is currently doing, risking crashing the server in the process (#1694)

On the providing side it is possible to store stuff in memory and update that memory value off server thread, on the replacing side it is possible to perform the request off server thread.

**Comment by SlimeDog** [comment]
Thanks. I will leave the QuickBoard issue open, just to see what is the response.

**Comment by SlimeDog** [comment]
Apologies. I missed that AuroraLS3 is your new nick.

**Comment by AuroraLS3** [comment]
No worries, easy thing to miss :)

**Comment by AuroraLS3** [comment]
I added a cache when using the server thread, but there was a small issue of what to return when waiting for the result - it was either "loading.." would show up for invalid placeholders or nothing would show up so I decided to have it show nothing on the first attempt.

Now if running papi parse (or another placeholder replacing), it needs to be attempted 2 times for the placeholder to show up, and similarly with everything else - the placeholder needs to be updated periodically for it to show up (if using server thread that is) - I don't know if this is problematic (Does the placeholder stay visible or something) but at least it won't crash servers.

**Comment by SlimeDog** [comment]
Spigot 1.16.5-3009
Placeholder 2.10.10-DEV-122
Plan 5.2 build 1062

On server start-up
```
[09:06:18] [Server thread/INFO]: [Plan] Loading Plan v5.2 build 1062
[09:07:35] [Server thread/INFO]: [Plan] Enabling Plan v5.2 build 1062
[09:07:37] [Server thread/INFO]: [Plan] Locale: 'English' by AuroraLS3
[09:07:37] [Server thread/INFO]: [Plan] SQLite-database connection established.
[09:07:37] [Server thread/INFO]: [Plan] WebServer: Certificate KeyStore File not Found: plugins/Plan/Cert.keystore
[09:07:37] [Server thread/INFO]: [Plan] WebServer: No Certificate -> Using HTTP-server for Visualization.
[09:07:37] [Server thread/INFO]: [Plan] Webserver running on PORT 8804 (http://blackdog.straight8.com:8804)
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: BSkyBlock
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: Essentials
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: LuckPerms
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: Economy (Vault)
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: Permission Groups (Vault)
[09:07:37] [Server thread/INFO]: [Plan] Registered extension: ViaVersion
[09:07:37] [Server thread/INFO]: [Plan] Player Analytics Enabled. (1332 ms)
[09:07:51] [Server thread/WARN]: [Plan] Failed to register PlaceholderAPI placeholders: java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/Caffeine
```

**Comment by AuroraLS3** [comment]
ohh that's fun

**Comment by SlimeDog** [comment]
> I don't know if this is problematic (Does the placeholder stay visible or something) but at least it won't crash servers.

It might be problematic for some uses. For scoreboards and tablists, it should not be an issue.

**Comment by AuroraLS3** [comment]
Hotfix out https://github.com/plan-player-analytics/Plan/releases

**Comment by SlimeDog** [comment]
Thank. Build 5.2-b1063 works fine with QuickBoard.

**Comment by SlimeDog** [comment]
However, if player is not connected (or doesn't exist), at console:
```
>papi parse SlimeDog %plan_player_death_count%
[11:48:51] [Server thread/INFO]: %plan_player_death_count%
[11:48:51] [Plan Non critical-pool-2/WARN]: [Plan] Ran into NullPointerException - logged to plugins/Plan/logs/NullPointerException-073b290297.txt
[11:48:51] [Plan Non critical-pool-2/WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[11:48:51] [Plan Non critical-pool-2/WARN]: [Plan] Error msg: "null"
>papi parse SlimeDog %plan_player_death_count%
[11:49:00] [Server thread/INFO]: %plan_player_death_count%
```
```
073b290297 - Last occurred: 2021-02-14 Occurrences: 1
---- Context 1 ----
Plan v5.2 build 1063
CraftBukkit 3011-Spigot-73fb609-d5c5d99 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT


---- Stacktrace ----
java.lang.NullPointerException
   java.base/java.util.Objects.requireNonNull(Objects.java:221)
   com.djrapitops.plan.addons.placeholderapi.PlanPlaceholderExtension.lambda$getCached$0(PlanPlaceholderExtension.java:127)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:79)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by AuroraLS3** [comment]
Ah I didn't realize it would throw an exception when the result is null (The player based placeholders will return null if the player is not online). Easy fix I suppose, but not as dire as complete breakage.

**Comment by SlimeDog** [comment]
Agreed. Not dire. No exception is thrown if executed in-game; just at the console.
