### ISSUE TITLE
Feature to search on player name under the LiteBan plugin Tab

### ISSUE THREAD

**Issue by FMS25** [plan-player-analytics/Plan#1762]
Would be fantastic for server owners to be able to go in and see-through plan who has been banned on Lite Bans. Currently, it is ok to check players manually but for bigger servers, a player search function would really improve the functionality.

This can allow staff to easily go in and see if someone has already been banned.

Love the plugin, fantastic support in discord, and works wonders on the server. Please keep up the good work!

**Comment by AuroraLS3** [comment]
Requested feature: Reduce Extension table dynamic style swap to 25 rows from current 100 rows (To show search on the table)

**Comment by FMS25** [comment]
Got another idea for you, with this, could you add a comment box so we can write in a comment to further explain why a player was banned eg for video evidence?

**Comment by AuroraLS3** [comment]
That sounds a bit out of scope feature for Plan - is the reason field not sufficient?

**Comment by FMS25** [comment]
yeah I mean, we can always train staff to add a link into the reason if links work there, cant say I've tried
