### ISSUE TITLE
Add React Plugin Addon

### ISSUE THREAD

**Issue by hellot1m** [plan-player-analytics/Plan#1765]
**Wiki page to modify**: 

### Suggested modifications
Add react support :)
[React Plugin](https://www.spigotmc.org/resources/react-smart-server-performance.21057/) on Spigot

### Additional context
react is a plugin that monitors everything that plan already monitors but it gives the ability to address the issues and be alerted in game when it detects an issue and how to fix it. also has a auto react feature which can just attempt to fix the issues causes the lag in real time. Having this ass a addon to plan would amazing. especially if you can manage to integrate it in a way to other areas of the plan GUI to manage react within areas of plan. like on the TPS screen, you can add a button to trigger react to well... react lol.

**Comment by AuroraLS3** [comment]
Please reopen the issue with the correct template - you're using Wiki edit template instead of plugin suggestion template: https://github.com/plan-player-analytics/Plan/issues/new?assignees=&labels=New+Feature%2C+DataExtensions%2C+Help+Wanted&template=plugin_request.md
