### ISSUE TITLE
IllegalArgumentException with Nucleus V1

### ISSUE THREAD

**Issue by austin4195** [plan-player-analytics/Plan#1766]
### Describe the issue

Ran into IllegalArgumentException

### Server Information
**Plan Version:** 5.2 build 1062
**Server:** Sponge 1.12.2 (1.12.2)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.19.0-6-amd64
**Java Version:** 1.8.0_275, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.275-b01, Oracle Corporation
### Benchmarks
```
2584 ms    -21 MB  subsystem-enable
```

### Exceptions & Other Logs

`java.lang.IllegalArgumentException: class com.djrapitops.extension.NucleusExtension method homeCount could not be called: null`

### Additional information

See log file attached from /config/plan/logs/
[IllegalArgumentException-8e74253795.txt](https://github.com/plan-player-analytics/Plan/files/6006604/IllegalArgumentException-8e74253795.txt)

**Comment by austin4195** [comment]
Pastebin of attached txt log file: https://pastebin.com/LttR92c0

**Comment by AuroraLS3** [comment]
Plan supports Nucleus API 2.3 onwards and version 1 is incompatible.

Disable nucleus integration in Plan config or update nucleus
