### ISSUE TITLE
"This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies."

### ISSUE THREAD

**Issue by cloakfox** [plan-player-analytics/Plan#1770]
https://pastebin.com/085CxpZp

This is preventing the shutdown of our server (during auto reboots)
[02:01:35] [JDA Shutdown Hook/INFO]: [net.dv8tion.jda.internal.requests.RateLimiter] Waiting for 1 bucket(s) to finish. Average queue size of 0 requests

Paper 1.16.5
Plan version: 1068

**Comment by cloakfox** [comment]
[CompletionException-4588d7109c.txt](https://github.com/plan-player-analytics/Plan/files/6025487/CompletionException-4588d7109c.txt)
[CompletionException-5abc1ed89e.txt](https://github.com/plan-player-analytics/Plan/files/6025488/CompletionException-5abc1ed89e.txt)
[CompletionException-198b3447ec.txt](https://github.com/plan-player-analytics/Plan/files/6025489/CompletionException-198b3447ec.txt)
[CompletionException-fc23c2d6e3.txt](https://github.com/plan-player-analytics/Plan/files/6025490/CompletionException-fc23c2d6e3.txt)
[CompletionException-a63ff063b9.txt](https://github.com/plan-player-analytics/Plan/files/6025492/CompletionException-a63ff063b9.txt)
[CompletionException-ed16cc9100.txt](https://github.com/plan-player-analytics/Plan/files/6025493/CompletionException-ed16cc9100.txt)
[CompletionException-f861b78097.txt](https://github.com/plan-player-analytics/Plan/files/6025494/CompletionException-f861b78097.txt)

Plan logs ^ during 8 AM (when auto reboots occur)

**Comment by AuroraLS3** [comment]
The shutdown hook attempts to store sessions that were not saved on server shutdown (because players are disconnected *after* plugins have been shut down). It appears that the database is not executing the session storage transactions (possibly busy) and as a result the server keeps waiting.

Are all your servers rebooted at the same time? This could lead to a large spike in MySQL usage during reboot causing this issue.

**Comment by cloakfox** [comment]
Yes all servers reboot around 8 AM CET, this is not an issue with other plugins that use SQL.

**Comment by AuroraLS3** [comment]
Please monitor the CPU usage of MySQL around reboot time and see if restarting the hanging servers with small time-step from others improves the situation.

**Comment by cloakfox** [comment]
> Please monitor the CPU usage of MySQL around reboot time and see if restarting the hanging servers with small time-step from others improves the situation.

Also happened on EU server,
https://pastebin.com/myd3XBWb

Plan is preventing shutdown of my servers. Not an issue with other SQL plugins.

**Comment by AuroraLS3** [comment]
> > Please monitor the CPU usage of MySQL around reboot time and see if restarting the hanging servers with small time-step from others improves the situation.
> 
> Also happened on EU server,
> https://pastebin.com/myd3XBWb
> 
> Plan is preventing shutdown of my servers. Not an issue with other SQL plugins.

That server appears to be running an older version.

**Comment by cloakfox** [comment]
That server runs on Plan-5.2-build-1063.jar

**Comment by AuroraLS3** [comment]
If no changes to reboot times or MySQL have not been done, this issue will still persist tomorrow. It is caused by slow response times of MySQL during a reboot, possibly due to a spike of load.

Note that other SQL plugins likely don't need to save data on shutdown - why Plan needs to do that is because servers kick players _after_ plugins have been shut down, and not saving active sessions on shutdown would lead to loss of that data.

**Comment by cloakfox** [comment]
> If no changes to reboot times or MySQL have not been done, this issue will still persist tomorrow. It is caused by slow response times of MySQL during a reboot, possibly due to a spike of load.
> 
> Note that other SQL plugins likely don't need to save data on shutdown - why Plan needs to do that is because servers kick players _after_ plugins have been shut down, and not saving active sessions on shutdown would lead to loss of that data.

Regardless it should not be hanging the server shutdown like that. I've delayed the auto reboot by an hour (rebooting 1 hour later). But hope this get's fixed still. I dont want to be rebooting gamemodes at random times to prevent this.

**Comment by cloakfox** [comment]
> > If no changes to reboot times or MySQL have not been done, this issue will still persist tomorrow. It is caused by slow response times of MySQL during a reboot, possibly due to a spike of load.
> > Note that other SQL plugins likely don't need to save data on shutdown - why Plan needs to do that is because servers kick players _after_ plugins have been shut down, and not saving active sessions on shutdown would lead to loss of that data.
> 
> Regardless it should not be hanging the server shutdown like that. I've delayed the auto reboot by an hour (rebooting 1 hour later). But hope this get's fixed still. I dont want to be rebooting gamemodes at random times to prevent this.
> 
> Edit: Other plugins like logblock also process data on shutdown, I believe they use some sort of queue system to process the data in bits.

So I tried what I mentioned above, rebooted the server 1 hour later and same thing happened. For now i've removed plan from the servers that suffer from this issue (servers located in NA) (and database is hosted in EU)
