### ISSUE TITLE
Impossible to register new users to plan (without ALL permissions)

### ISSUE THREAD

**Issue by cloakfox** [plan-player-analytics/Plan#1774]
Hello,

It's practically impossible to register new users, after figuring out the correct permissions setup, it will say that the registration failed, hinting that the code has expired. When the link/code is just new.

![Capture](https://user-images.githubusercontent.com/3696645/109071467-0c932600-76f4-11eb-8f86-824560ad354e.PNG)
 
It's kind of disappointing to see this has become so tedious now, and also not working at all.

Currently using latest version 1068

**Comment by AuroraLS3** [comment]
Could not reproduce the issue with the following steps

- Installed Plan and https on a bungee server with one paper server
- Installed Luckperms on bungeecord
- using Luckperms web editor, applied plan.player.other to specific player
- Created an account on the plan website with register page
- Ran `/planproxy --code <code>` as the player
- logged in and was redirected to /players page correctly.

If it doesn't work still you can try the legacy way

> There is also a legacy way to register users via /plan register <password> <user> <permission level> that requires plan.register.other permission to use
