### ISSUE TITLE
"Regular -> Inactive" metric calcualted the wrong way round

### ISSUE THREAD

**Issue by BrainStone** [plan-player-analytics/Plan#1775]
### Describe the issue

The metric "Regular -> Inactive" seems to be calculated the wrong way round. Before it passed the 30 day mark it was always exactly the "regular" count, So my guess is that it calculates how many inactive players because regulars and not the other way round.

Page: /network#tab-playerbase-overview

P.S.: This was discussed on Discord before but I forgot to make the bug report.

### Server Information
**Plan Version:** 5.2 build 1068
**Server:** BungeeCord git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395 (git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395)
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.19.0-13-amd64
**Java Version:** 11.0.9.1, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 11.0.9.1+1, Oracle Corporation

**Comment by AuroraLS3** [comment]
Looks like this was a mistake in the SQL and the dates were wrong way around, calculating regulars at the end of the timespan and inactive at the start, which is indeed reversed.
