### ISSUE TITLE
Centered Loading Icon on Phone

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#1783]
### Describe the issue
The loading icon, while trying to load player analytics on a mobile phone, is not centered to the page.

### Exceptions & Other Logs
Nothing to show here

```
Place log contents here
```

### Additional information
Running latest version of plan ( at the time of writing ), phone specs oneplus nord 8gb/256gb
6 inch display.

**Comment by AuroraLS3** [comment]
![image](https://user-images.githubusercontent.com/24460436/110235056-a8afff00-7f36-11eb-9036-662c0763ffbd.png)
