### ISSUE TITLE
IllegalStateException when loading player list

### ISSUE THREAD

**Issue by HexedHero** [plan-player-analytics/Plan#1784]
### Describe the issue

Error when I loaded the webpage and went to the player list, hard disk is not full. Still have 200gb+ of free space.

https://paste.gg/p/anonymous/aadfc7c083b14adfaecd773e4976a66d/files/23253544dbee43ea9a7b0a2ab2b4cab9/raw

**Comment by AuroraLS3** [comment]
Disk is full error can occur when temporary directory (`/tmp` on linux, `%APPDATA%/Temp` on windows) has reached capacity

**Comment by AuroraLS3** [comment]
Since I can't fix this, I have added "What to do" when this error occurs in the future.
More information about the error: https://sqlite.org/rescode.html#full
