### ISSUE TITLE
Network Plan, the servers menu navigation should list your servers.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#1790]
I recently migrated to a network/proxy based setup for Plan, which is amazing how simple it was! I was so happy I could just use the same database and add more servers.

My suggestion is on the sidebar navigation when you click Servers, list the servers you have added under that dropdown, when clicking goes to their server page. 

Keep overview & Sessions, maybe have a Horizontal rule between those and then list the servers, otherwise its Click Servers, Click Overview, Click the server page you want!

**Comment by AuroraLS3** [comment]
Good and simple addition. I'll consider it
