### ISSUE TITLE
Further mcMMO Optimization

### ISSUE THREAD

**Issue by nossr50** [plan-player-analytics/Plan#1792]
Thanks for fixing the previous issue I reported, however upon compiling the latest changes in Plan locally and testing I found another potential performance issue. When a player joins a server Plan seeks to gather data from this player, however that player is not yet loaded by mcMMO (mcMMO purposely waits 3 seconds to load player data, this is done to give some lag time to "sync" up data on bungee servers using a shared SQL database). It should be noted Classic mcMMO does not do this, but many things have changed from Classic.

mcMMO actually throws an exception for these API calls when player data is not yet loaded, however Plan ignores these exceptions and instead opts to invoke offline player data API calls, which would be fine but Plan invokes about 10-20 API calls per player join, each one loads the entire DB up and creates a bunch of resources unnecessarily, this is undoubtedly inefficient.

If Plan were to wait for this players data to be loaded it would be cached and there would be no concern, but Plan does not do this as it chooses to ignore the exception and opt for Offline API calls, I suggest that Plan does not opt for the Offline API calls unless the player is truly offline and any such offline API calls should be limited. It is better to grab the PlayerProfile (our offline data wrapper) object and cache it then to invoke 20 different offline API calls from mcMMO as that would be one invocation of loading up the database versus 10-20 something.

Choose to solve this how you will, you know your plugin better than I ever will. 
I hope you have a good day! ☺️

**Comment by AuroraLS3** [comment]
Is there an event for when mcMMO loads the data? I could hook into that and invoke the api calls manually on that event

**Comment by nossr50** [comment]
McMMOPlayerProfileLoadEvent is the event you are looking for, which should exist in Classic as well

**Comment by AuroraLS3** [comment]
Great that sorts this out.

**Comment by nossr50** [comment]
Thanks for being responsive to the feedback, I hope you have a good day! 😄
