### ISSUE TITLE
Average Player Count

### ISSUE THREAD

**Issue by RemainingToast** [plan-player-analytics/Plan#1796]
### Is your feature request related to a problem? Please describe.
Add an average player count value

### I would like to be able to..
See my average amount of online players over 12h/24h/7d/30d/All periods

----

*by AuroraLS3:*

### TODO

- Add a javascript function that averages the playercount in the current graph view and displays it as a separate line under the players online line chart.
  - Store performance data in a variable in the browser when it is fetched
  - See query page implementation on how to get the two dates from Hichcharts range selector
  - Write a function that averages the player count for the view
  - Update the player online graph with the average as 20 points across the timespan (One point every `end - start / 20`) as one series
    - Select a new color that is a bit lighter than the main color

**Comment by AuroraLS3** [comment]
I'll have to push this feature back since I couldn't get it to be on-par with the other features in the plugin.
