### ISSUE TITLE
MySQL Connector issue - ResultSet.TYPE_FORWARD_ONLY 

### ISSUE THREAD

**Issue by Bloodlex** [plan-player-analytics/Plan#1804]
### Describe the issue
The newest version breaks **all of logblock-like plugins connecting to database**, because it replaces mySQL connector. I am unable to use these plugins with Plan enabled. Could you please help and fix that? I wouldn't like to leave my server without protection... 😢 

**Database connection error: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY**

More details in pastebins below.

Plan version: 5.2 build 1124

It's a great plugin and I would really like to continue to use it. Thank you very much for your help!

**Steps to reproduce:**
1. Use the newest version of Plan: 5.2 build 1124
2. Configure database connection of [LogBlock](https://www.spigotmc.org/resources/logblock.67333/), [Prism ](https://www.spigotmc.org/resources/prism.75166/) or other player logging plugin connecting to mysql database (in my case it is MariaDB)
3. Multiple exceptions when starting those plugins and cannot do any kind of checking data from database.

### Exceptions & Other Logs
[https://pastebin.com/Cb3xnLGH](https://pastebin.com/Cb3xnLGH)
[https://pastebin.com/adcyWDUV](https://pastebin.com/adcyWDUV)

### Additional information
Related issues on GitHub of aforementioned plugins:
[https://github.com/LogBlock/LogBlock/issues/821](https://github.com/LogBlock/LogBlock/issues/821)
[https://github.com/AddstarMC/Prism-Bukkit/issues/257](https://github.com/AddstarMC/Prism-Bukkit/issues/257)

**Comment by AuroraLS3** [comment]
This is a difficult issue to understand and will take some time to fix.

**Comment by Brokkonaut** [comment]
You can have a look how luckperms handles this, they also use a bundled driver, but deregister it, so other plugins won't be affected
https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/storage/implementation/sql/connection/hikari/MySqlConnectionFactory.java#L54-L80

**Comment by AuroraLS3** [comment]
You are probably a life-saver :D

**Comment by AuroraLS3** [comment]
@Bloodlex Could you test if this build has the issue resolved 
[Plan-5.2-dev-build-1133.jar.zip](https://github.com/plan-player-analytics/Plan/files/6170540/Plan-5.2-dev-build-1133.jar.zip)

**Comment by Bloodlex** [comment]
> @Bloodlex Could you test if this build has the issue resolved
> [Plan-5.2-dev-build-1133.jar.zip](https://github.com/plan-player-analytics/Plan/files/6170540/Plan-5.2-dev-build-1133.jar.zip)

@AuroraLS3 Yeah, now it works! Thank you so much!!

**Comment by AuroraLS3** [comment]
Thanks for the confirmation
