### ISSUE TITLE
Adding new dashboard and changing layout of dashboards.

### ISSUE THREAD

**Issue by portlek** [plan-player-analytics/Plan#1808]
### I would like to be able to.
- change the layout of the panels.
- add new custom dashboards with a simple `+` button.
- add panels with a simple `+` button in the dashboard somewhere.
- change the titles of all panels.
- change the name of all dashboards.

these features would be useful to customize our website.
(_like grafana_)
![image](https://user-images.githubusercontent.com/12835420/111903805-ffe4c200-8a54-11eb-91f9-53b7ad602b11.png)

**Comment by AuroraLS3** [comment]
Please look at <https://github.com/plan-player-analytics/Plan/wiki/Html-Customization>

Rearrangement at runtime is out of scope.
