### ISSUE TITLE
HTTP 500 Error when trying to make a query

### ISSUE THREAD

**Issue by adenosine1** [plan-player-analytics/Plan#1812]
### Describe the issue
After updating to build 1147, I get an HTTP 500 error when navigating to the Query page. "HTTP 500 (See ./v1/filters)" is displayed on the query page. Running on a waterfall network with plan installed on the proxy and all backend servers. Same version is on all servers and proxy. 

### Exceptions & Other Logs

Console error: https://pastebin.com/0HZ9RZ8g

Log: https://pastebin.com/RX6CGhdP

![plan](https://user-images.githubusercontent.com/23322409/112080742-816d4a80-8b50-11eb-94c9-cc96565489b7.png)

### Additional information

Plan: Version: 5.2 build 1147
Waterfall build 403

**Comment by AuroraLS3** [comment]
Has been fixed in 624ed5005414f2f9777d2f669c38ac6b7e66623e but not released yet.

This seems to only occur with MySQL and MariaDB does not have this issue.

Here is a bash script to build the newest commit and delete the build files, feel free to edit before executing.
```bash
git clone https://github.com/plan-player-analytics/Plan.git
cd Plan/Plan
./gradlew shadowJar
cd ../..
cp Plan/Plan/builds/Plan-5.2-SNAPSHOT.jar Plan-5.2-SNAPSHOT.jar
rm -rf Plan
```
