### ISSUE TITLE
JVM fatal Crash on shutdown [SQLite SIGSEGV [libpthread.so.0+0xa6c0]  __pthread_mutex_lock+0x0]

### ISSUE THREAD

**Issue by HexedHero** [plan-player-analytics/Plan#1814]
### Describe the issue

I recently updated to v5.2 build 1147 and now everytime PLAN shuts down the Jvm crashes, pointing to PLAN.

### Exceptions & Other Logs

https://paste.gg/p/anonymous/c1bd983e25544e71afe7f5415323bda5/files/8f030fe6b1d94d23b568b881a64b5523/raw

### Additional information

Edit: It only happens when you open the web page and its gathering new data and the server shuts down during it.
Edit2: It also did it on the older version I was on (v5.2 build 1068)

**Comment by AuroraLS3** [comment]
This looks to be an SQLite SIGSEGV (Segmentation fault) in their native code. Looks like the database is being queried at the same time as the server is shutting down (by a processing thread)

I can't unfortunately stop this kind of error from happening so I've been recommending to switch to MySQL if it happens

**Comment by AuroraLS3** [comment]
I found another issue https://github.com/xerial/sqlite-jdbc/issues/509 with a similar crash where they explain that the crash occurs because SQLite connection is closed by a different thread than the one currently using the connection. I can try to see if I can do something about that.

**Comment by AuroraLS3** [comment]
Could you test if the crashes occur with this build & SQLite
[Plan-5.2-dev-build-1161.jar.zip](https://github.com/plan-player-analytics/Plan/files/6196905/Plan-5.2-dev-build-1161.jar.zip)

**Comment by HexedHero** [comment]
> Could you test if the crashes occur with this build & SQLite
> [Plan-5.2-dev-build-1161.jar.zip](https://github.com/plan-player-analytics/Plan/files/6196905/Plan-5.2-dev-build-1161.jar.zip)

Great news, I booted up a new droplet and copied my live database onto it with a fresh server and plan, tested it and the Spigot version crashed like normal but using that version/build it has never crashed and always says 
[Plan] Waiting queries to finish to avoid SQLite crashing JVM..
It takes a good 20~ seconds to complete but doesn't crash.
No extra time added when I'm not refreshing the web page.

However, that being said while testing plan said this a few times during shutdown:
[04:02:42 WARN]: [Plan] Ran into IllegalStateException - logged to plugins/Plan/logs/IllegalStateException-85932994e9.txt
[04:02:42 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[04:02:42 WARN]: [Plan] Error msg: "com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: database connection closed"
https://paste.gg/p/anonymous/3159882e26784ebc940a9228c8973840/files/aca8498275ae461fa4f2856fb39a9324/raw

then after the above error happened I got this on the next startup:
[04:07:32 ERROR]: [Plan] Ran into NullPointerException - logged to plugins/Plan/logs/NullPointerException-9babd9d943.txt
[04:07:32 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[04:07:32 ERROR]: [Plan] Error msg: "null"
https://paste.gg/p/anonymous/df7e79798677424692692491618ac1c7/files/086106e8d87042839935bbfb50b0985a/raw

**Comment by AuroraLS3** [comment]
Hmm, I'll try to be more aggressive shutting down the processing threads to see if that speeds up the queries finishing earlier.

Seems like the 2nd error is related to the 1st and invalid json was stored. I'll try to sort that out too.
