### ISSUE TITLE
/plan db remove <name/uuid><specific_value>

### ISSUE THREAD

**Issue by bobhenl** [plan-player-analytics/Plan#1820]
### Is your feature request related to a problem? Please describe.

Hi, I want to ask for improving command /plan db remove, where we could specify exact things like primary lp group or another db entry. Cause when players don't join when we set them another rank, it's not updated here in plan. So the player is still listed in query filter under rank "helper" even if he doesn't have a rank helper and just didn't join the server.
### I would like to be able to..

I would like to specify db entry there somehow, so lp group or something like this.

**Comment by AuroraLS3** [comment]
Closing this ticket in favor of #2269 which is about solving the underlying issue of luckperms group data not updating
