### ISSUE TITLE
Join address is displayed for multiple server_uuids

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#1827]
### Describe the issue

Plan SQLite database contains data for two servers. Both are displayed in join address pie chart. Only data for the current server should be displayed.

Data available if needed.

**Comment by AuroraLS3** [comment]
I tried to look at the code and server page should already limit to the join addresses of that server - Is this issue happening in build 1174 on the server page?

**Comment by SlimeDog** [comment]
Spigot 1.16.5-3042 (blackdog)
Paper 1.16.5-592 (whitedog)
Plan 5.2-b1174 (both)

There seem to be multiple issues here
- incorrect _opped_ data
- missing _join_address_ data on Paper
- display of multiple server data

If that proves to be the case, I will create separate tickets.

Perhaps I have misconfigured, but I'm not seeing the error. The database on whitedog begins life as a copy of the database from blackdog, so that it contains data for both servers, but the ids are distinct (this may be a contributing factor to the problems). I then connect an OP'd player to whitedog. Note that _join_address_ is `Unknown` rather than `whitedog.[elided].com`. Note that _max_players_ is actually 25 on both servers, and the player is actually OP'd on both servers, although the Plan data show otherwise.

If I run whitedog on Spigot instead of Paper, the _join_address_ data are captured and displayed.

```
sql> select * from plan_user_info ;
id          uuid                                  server_uuid                           join_address            registered     opped       banned    
----------  ------------------------------------  ------------------------------------  ----------------------  -------------  ----------  ----------
1           3cf9b867-2577-49d1-affb-7ba8196a0d39  6af88d11-64d3-3a61-b49d-d327d5932d73  blackdog.[elided].com   1504585288058  1           0         
2           3cf9b867-2577-49d1-affb-7ba8196a0d39  adc7e80a-9e51-3adf-ac41-1ca978fd9c57  Unknown                 1537588764582  0           0 
sql> select * from plan_servers ;
id          uuid                                  name        web_address                         is_installed  max_players  is_proxy  
----------  ------------------------------------  ----------  ----------------------------------  ------------  -----------  ----------
1           6af88d11-64d3-3a61-b49d-d327d5932d73  BlackDog    http://blackdog.[elided].com:8804   1             25           0         
2           adc7e80a-9e51-3adf-ac41-1ca978fd9c57  WhiteDog    http://whitedog.[elided].com:8804   1             -1           0 
```
Here is the screenshot for the Player Overview on whitedog.[elided].com
![Screen Shot 2021-04-15 at 2 11 54 AM](https://user-images.githubusercontent.com/17748923/114845241-7644bd80-9d90-11eb-9b73-196a0d2975f2.png)

**Comment by AuroraLS3** [comment]
Great detailed report, should help figuring this out.

**Comment by SlimeDog** [comment]
> I dunno if the other two things are related - if the user has not joined whitedog for a while the data might be out of date

The connection to whitedog was very fresh. No players connect to whitedog until these sorts of test runs.

**Comment by AuroraLS3** [comment]
Paper was returning something different than Spigot for the join addresses, so use of its method has been removed in 5f4ee93f5f1545c86ffff207efe20a06d30839ba - this should take care of the unknown address.

**Comment by AuroraLS3** [comment]
Looks like the issue was that the server page was missing server parameter from the request.

**Comment by AuroraLS3** [comment]
Alright the opped saying 'false' appears to be because this status is updated during LoginEvent, but the player is registered in JoinEvent, which comes after Login. Because of this the op status of the player is incorrect if the player is opped when the player is registered. Easy fix I suppose.

**Comment by SlimeDog** [comment]
Excellent.

**Comment by SlimeDog** [comment]
Confirmed fixed in build 1234. Thank you.
