### ISSUE TITLE
More detailed record of votes daily, monthly....

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#1828]
### Is your feature request related to a problem? Please describe.
Not a problem really its just not fully supported vote records

### I would like to be able to..
Would be really nice if we could search vote data in more detail way
like I could check if one of my servers votes for a specific timeline or even to show a graph of that view 
and also to be able to make queries for it

**Comment by AuroraLS3** [comment]
Integrated to #1574, follow that issue for resolution.
