### ISSUE TITLE
playtime as command

### ISSUE THREAD

**Issue by yogi7777** [plan-player-analytics/Plan#1849]
### I would like to be able to..

my players wish a personality /playtime command for view total playtime over all servers.
(without webgui)

Thanks :)

**Comment by AuroraLS3** [comment]
Consider using PlaceholderAPI to create a custom command with `%plan_player_time_total%`. Note that the command needs to run the placeholder replacement off the server thread for it to work.

`/plan ingame` provides playtime with a few other data points as well.

**Comment by PetyXbron** [comment]
> Consider using PlaceholderAPI to create a custom command with `%plan_player_time_total%`. Note that the command needs to run the placeholder replacement off the server thread for it to work.
> 
> `/plan ingame` provides playtime with a few other data points as well.

Hello AuroraLS3, can you explain to me in detail, how can I use this placeholder and how can I create custom command? I have PlceholderAPI installed and I tried Skript, but I think you don't mean making custom command in Skript.
I just want something like command `/playtime` for the default group that will just show your playtime (3h 22m 21s).

**Comment by PetyXbron** [comment]
@AuroraLS3 where can I find Plan extension for PlaceHolderAPI? I think it should work with Skript.

**Comment by AuroraLS3** [comment]
@PetyXbron 


> Hello AuroraLS3, can you explain to me in detail, how can I use this placeholder and how can I create custom command? I have PlceholderAPI installed and I tried Skript, but I think you don't mean making custom command in Skript.
I just want something like command /playtime for the default group that will just show your playtime (3h 22m 21s).

Add `%plan_player_time_total%` to whatever you use PlaceholderAPI with. If you want a custom command I got no idea since I don't use placeholder api. If you use skript for this make sure the skript is run off the server thread.

> where can I find Plan extension for PlaceHolderAPI? I think it should work with Skript.

PlaceholderAPI extension is registered by the Plan plugin when it enables. There is no separate jar for it.

https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

**Comment by PetyXbron** [comment]
So, @AuroraLS3 I made this simple Skript:
```Skript
command /playtime:
	description: "Shows player playtime from Plan Analytics plugin."
	trigger:
		send "&3Playtime: &a%plan_player_time_total%"
		send "&3Playtime: &a%plan_player_time_total%"
```
And the console shows me this error:
```
[17:09:43 ERROR]: indentation error: expected 2 tabs, but found 8 spaces (SC3.sk, line 22: send "&3Playtime: &a%plan_player_time_total%"')
[17:09:43 ERROR]: Can't understand this expression: plan_player_time_total (SC3.sk, line 21: send "&3Playtime: &a%plan_player_time_total%"')
```
That's why I asked you if I need to install Plan extension for placeholderAPI plugin.
Do you know what am I doing wrong?

**Comment by AuroraLS3** [comment]
Ask the author of the skript you're using for placeholders
