### ISSUE TITLE
Is there a way to disable non-anonymous statistics?

### ISSUE THREAD

**Issue by GuyInGrey** [plan-player-analytics/Plan#1858]
Is there a way to disable non-anonymous statistics?
We'd like to have an overview of how active the server is, and it's performance, but not the playtime/info on specific users. Is this possible?

We'd like the Server Overview and Performance tabs, but not the Player List or any player-specific data, for the sake of player privacy.

Thank you

**Comment by AuroraLS3** [comment]
Remove the relevant portions of the website <https://github.com/plan-player-analytics/Plan/wiki/Html-Customization>
