### ISSUE TITLE
Alice Plan Integration - idea

### ISSUE THREAD

**Issue by Banexplain** [plan-player-analytics/Plan#1867]
### Data to display
(I want to see from this Plugin called Alice: the Playerinformation about how many times a Player hacked or tried to hack and with what data, a Performance feedback of the Plugin, General information about what Checks are enabled/disabled, List of Player the Plugin detected in the last (24 hours, 48 hours, 7 days) who might hack. I am not the Developer of this Plugin, just a User and I hope that this  could be integrated. If something important is missing I think you could add this as well.)

### Plugin information

**API or Source Code:** [Link](https://github.com/NikV2/AliceAPI/wiki)  

**Project page or Downloads:** [Link](https://www.spigotmc.org/resources/under-small-recode-♕-alice-♕-an-advanced-next-generation-anti-cheat-⋙-1-8-1-16-5-⋘.89139/)

**Comment by AuroraLS3** [comment]
This plugin appears to have a rather small userbase compared to other plugins that Plan supports. It might make more sense to request support for Plan from the plugin author.
