### ISSUE TITLE
Use Fetch API & async requests instead of XHRs

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1869]
### Is your feature request related to a problem? Please describe.
Plan's current XHR implementation is a synchronous callback hell. The Fetch API would provide us with a much more modern & flexible way to do requests to the backend and allow us to process the responses more easily with promises instead of awful callbacks. 

Plan does a ton of stuff with JavaScript, so asynchronizing large web requests would probably increase browser performance and free up burden on the thread for other tasks, such as i18n or browser-based page rendering in the future. _(The Fetch API also has great support for the Cache API (if we ever need it), though the API can only be used in secure contexts hence the requirement for additional code for compatibility with non-HTTPS endpoints.)_

**Comment by AuroraLS3** [comment]
> callback hell

> only one level of callbacks instead of nested callbacks

🙄

----

Joking aside, the XHRs have async flag set to true so the requests are already performed asynchronously - what is performed there is the rendering of the results once the requests complete, and so [promises are used in some places where performance impact was apparent](https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/js/graphs.js#L194-L219). Changing to use fetch api or wrapping the xhr to a promise will only move when the code is executed by the js thread to a moment when call stack is empty.

I guess fetch api has easier request parameters setting though.

**Comment by Kopo942** [comment]
> Joking aside, the XHRs have async flag set to true so the requests are already performed asynchronously
3am got me again, and now that I think of it, the async flag for XHRs is set to true by default, so my mistake there.

I was also kinda misusing the term "callback hell", the thing I was referring to is the way functions are fired from inline script tags instead of separate files (which I prefer personally). The current implementation does work just fine and I get why it's done the way it is, but to my eyes there could be room for refactoring some stuff.

**Comment by AuroraLS3** [comment]
I don't think this is a super necessary change seeing how things work with the xhr just fine. Maybe in the future if the json requests get rewritten I'll consider using fetch api instead - but changing this for the sake of changing api seems like unnecessary extra work.
