### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by TheSirCororo** [plan-player-analytics/Plan#1877]
### Is your feature request related to a problem? Please describe.
I use PostgreSQL because (by me) it better than MySQL. But this plugin haven't support for this database and I can't use plugin

### I would like to be able to..
I would like to PostgreSQL support will add.

**Comment by AuroraLS3** [comment]
Duplicate of https://github.com/plan-player-analytics/Plan/issues/1197 - Out of scope
