### ISSUE TITLE
SQL Constraint Violation

### ISSUE THREAD

**Issue by Matejvvo** [plan-player-analytics/Plan#1881]
Hi, I am getting some kind of error with my external sql database

[10:57:58 ERROR]: [Plan] Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-5b7aa49fb4.txt
[10:57:58 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:57:58 ERROR]: [Plan] What to do: Report this, there is an SQL Constraint Violation.

Here is the log file:

289ae4bcfa - Last occurred: 2021-04-21 Occurrences: 41
---- Context 5 ----
Plan v5.2 build 1124
Paper git-Paper-414 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Report this, there is an SQL Constraint Violation.
Transaction: class com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction
DB State: OPEN
Error code: 1364
INSERT INTO plan_worlds (world_name,server_uuid) VALUES (?, ?)
Constraint Violation

---- Context 4 ----
Plan v5.2 build 1124
Paper git-Paper-414 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Report this, there is an SQL Constraint Violation.
Transaction: class com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction
DB State: OPEN
Error code: 1364
INSERT INTO plan_worlds (world_name,server_uuid) VALUES (?, ?)
Constraint Violation

---- Context 3 ----
Plan v5.2 build 1124
Paper git-Paper-414 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Report this, there is an SQL Constraint Violation.
Transaction: class com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction
DB State: OPEN
Error code: 1364
INSERT INTO plan_worlds (world_name,server_uuid) VALUES (?, ?)
Constraint Violation

---- Context 2 ----
Plan v5.2 build 1124
Paper git-Paper-414 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Report this, there is an SQL Constraint Violation.
Transaction: class com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction
DB State: OPEN
Error code: 1364
INSERT INTO plan_worlds (world_name,server_uuid) VALUES (?, ?)
Constraint Violation

---- Context 1 ----
Plan v5.2 build 1124
Paper git-Paper-414 (MC: 1.16.4)
Server v1.16.4-R0.1-SNAPSHOT

Report this, there is an SQL Constraint Violation.
Transaction: class com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction
DB State: OPEN
Error code: 1364
INSERT INTO plan_worlds (world_name,server_uuid) VALUES (?, ?)
Constraint Violation

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Field 'id' doesn't have a default value
   java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
   java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Field 'id' doesn't have a default value
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:155)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:45)
   com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:201)
   com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction.performOperations(WorldNameStoreTransaction.java:67)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:80)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:255)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
Caused by:
java.sql.SQLException: Field 'id' doesn't have a default value
   plan.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
   plan.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
   plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
   plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.callExecute(ExecStatement.java:60)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:52)
   com.djrapitops.plan.storage.database.transactions.ExecStatement.execute(ExecStatement.java:42)
   com.djrapitops.plan.storage.database.transactions.Transaction.execute(Transaction.java:201)
   com.djrapitops.plan.storage.database.transactions.events.WorldNameStoreTransaction.performOperations(WorldNameStoreTransaction.java:67)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:80)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$2(SQLDB.java:255)
   java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   java.lang.Thread.run(Thread.java:748)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:251)
   com.djrapitops.plan.gathering.listeners.bukkit.GameModeChangeListener.actOnEvent(GameModeChangeListener.java:81)
   com.djrapitops.plan.gathering.listeners.bukkit.GameModeChangeListener.onGameModeChange(GameModeChangeListener.java:68)
   com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor432.execute(Unknown Source)
   org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
   co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
   org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
   org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
   net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1636)
   net.minecraft.server.v1_16_R3.CommandGamemode.a(CommandGamemode.java:57)
   net.minecraft.server.v1_16_R3.CommandGamemode.lambda$a$2(CommandGamemode.java:26)
   com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
   com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
   net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:183)
   net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:164)
   net.minecraft.server.v1_16_R3.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:160)
   net.minecraft.server.v1_16_R3.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:121)
   net.minecraft.server.v1_16_R3.BlockCommand.a(BlockCommand.java:96)
   net.minecraft.server.v1_16_R3.BlockCommand.tickAlways(BlockCommand.java:73)
   net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:565)
   net.minecraft.server.v1_16_R3.WorldServer.b(WorldServer.java:807)
   com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306)
   net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:47)
   net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:465)
   net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355)
   net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
   net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208)
   net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996)
   net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
   java.lang.Thread.run(Thread.java:748)

**Comment by AuroraLS3** [comment]
>  Field 'id' doesn't have a default value

MySQL is supposed to have auto-increment on for this field. Try recreating the database. Check the Plan enable log on the console for any table creation errors afterwards

**Comment by Matejvvo** [comment]
Thanks for the quick reply.

I have recreated the database as instructed and everything works. Thanks very much.
