### ISSUE TITLE
Tracking issue: Add Java 16 support

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1886]
### Is your feature request related to a problem? Please describe.
Starting from Minecraft snapshot 21w19a, the required Java version for Minecraft is Java 16. All server platforms will have to follow this change if they want to update to 1.17, so proper Java 16 support is a must for Plan.

![image](https://user-images.githubusercontent.com/13612979/118017930-d7e05380-b35f-11eb-9ab0-9aaf33c37662.png)

# ⚠WORKAROUND AVAILABLE BELOW ⬇
### Spigot, Bungee and their respective forks:

[Try this experimental build](https://cdn.discordapp.com/attachments/635887328770129922/851618833235443722/Plan-5.3-DEV-Java16.jar) on **newest** Spigot/Bungee/fork builds
### Other platforms (and if above doesn't work):
Add `--illegal-access=permit` to the startup parameters of your server, and Plan should work for the time being. Thanks to Benji for pointing this out!
**Example: `java --illegal-access=permit --other-flags-here... -jar yourServerJarFile.jar`**

##### Tags
java.lang.reflect.InaccessibleObjectException, URLClassLoader, ExceptionInInitializerError, class loader

**Comment by AuroraLS3** [comment]
Will have to see how this pans out. 40% of servers is still running Java 8.
Only 0.7% of Spigot/Paper Plan installations is running Java 16

**Comment by SlimeDog** [comment]
On server start-up under Java 16
```
[06:22:41] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing Plan v5.3 build 1284 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.playeranalytics.plugin.dependencies.DependencyLoader.load(DependencyLoader.java:48) ~[?:?]
        at com.djrapitops.plan.DependencyStartup.loadDependencies(DependencyStartup.java:67) ~[?:?]
        at com.djrapitops.plan.Plan.onLoad(Plan.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-670]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-670]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7ab0d6cd
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at net.playeranalytics.plugin.ninja.egg82.mvn.classloaders.TransparentInjectableClassLoader.<clinit>(TransparentInjectableClassLoader.java:28) ~[?:?]
        ... 8 more
```

**Comment by SlimeDog** [comment]
> We will have to wait and see how this pans out. 40% of servers are still running Java 8.
> Only 0.7% of Spigot/Paper Plan installations is running Java 16

In addition to all the other reasons: Several important plugin developers have ignored the deprecation-with-intent-to-delete warnings for years. That has made it nearly impossible to run on Java 15 or 16, even for those of us who like to get on the leading edge. That chicken is about to come home to roost.

**Comment by Kopo942** [comment]
@SlimeDog Java 16 blocks illegal reflection with `URLClassLoader#addURL`, so that's the error that's being thrown for you and at the same time one of the main issues getting Plan to work with Java 16+. (for the record, this issue doesn't only affect Plan; for example, LuckPerms is probably one of the biggest plugins suffering from this change)

In addition to the above comment, the fact that many servers are still running Java 8 is probably because 
1. server hosts hesitate to update to not break compatibility with older apps, many hosts also don't have a way to select the JVM version you're using
2. many servers are running very old & unsupported versions of Minecraft (1.8.8, 1.12.2) for older combat and gameplay mechanics. Old, unmaintained plugins for these versions might not support newer versions of Java (heck, even Java 11).

I've rephrased my issue a bit to be a general Java 16 support issue, not about bumping the version Plan uses.

**Comment by AuroraLS3** [comment]
I have opened a ticket to MVNLoader. If I have time I'll try to PR a fix there, but no promises since I started at my new job this week.

**Comment by SlimeDog** [comment]
Thanks for the info. Good fortune at the new job.

**Comment by AuroraLS3** [comment]
I have been informed of a workaround that allows use of Plan on Java 16 until this issue is fixed. Thanks to Benji for pointing this out.

- Add `--illegal-access=permit` to the startup command for java

**Comment by SlimeDog** [comment]
Well, yes, if you need it in production. For testing Java 16 compatibility, that sort of defeats the purpose. :)

**Comment by AuroraLS3** [comment]
I attempted to patch MVNLoader with PrivilegedAction, but it did not work. I misunderstood where the issue is coming from.

Java now has *strong encapsulation* which means that anything that is not public is enforced to not be public. Because of this any reflective access using `setAccessible` can break. 

URLClassLoader (The class loader used by Spigot and most other servers to load plugin classes from jars) has methods to add classes at runtime, but these are all `protected`. Because of the change above **there is currently no way to add more classes to the plugin class loader at runtime in Java 16.** (Without replacing the plugin class loader used by spigot)

This makes it very difficult to work around this change, since in order to add dependencies at runtime, all Plan classes would need to be loaded by a separate loader from the plugin class loader.

I don't unfortunately understand how any of this class loading works.

Another workaround would be to include all the database drivers in Plan.jar - but that puts the jar over 25MB limit enforced by Ore and Cloudburst so it's not really viable. I guess one way would be to include the drivers in a separate plugin-jar, or building different artifacts for different platforms

**No good solutions so far!**

----

Optimal solution would be for platforms to extend their class loaders to allow runtime dependency downloading, but that is super unlikely to happen.

**Comment by AlessioDP** [comment]
This is the related issue in Spigot JIRA: https://hub.spigotmc.org/jira/browse/SPIGOT-5352

Take a look at Bjarne Koll comment, I completely agree with him :)

**Comment by Wild1145** [comment]
We've been looking to get plan up and running on a Java 16 environment ahead of the formal changes in the new MC Version (Coming June 8th). The following error is what we got on a fresh install - https://gist.github.com/Wild1145/14cb6b2540e71766c6400654300b6d5d

**Comment by AuroraLS3** [comment]
Use the workaround higher up in this thread @Wild1145

**Comment by AuroraLS3** [comment]
This build should work with Java 16 https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1317

**Comment by SlimeDog** [comment]
Plan 5.4-b1317 looks good on first inspection
- CentOS 7.9.2009 (Core)
- Java 16.0.1
- Spigot 1.17-3124

Thanks.
