### ISSUE TITLE
Overlay graphs

### ISSUE THREAD

**Issue by alexstore06** [plan-player-analytics/Plan#1891]
### I would like to be able to..
compare various statistics (player number, RAM, etc) over time by overlaying graphs on top of each other, similarly to Google Analytics. For example, I would like to take the player number over the last 24 hours and compare it to the player number throughout the previous day, to find when my players are active.

**Comment by AuroraLS3** [comment]
Have you tried to use the Punchcard (Online activity overview > Punchcard) for determining when your players are active?

**Comment by AuroraLS3** [comment]
I think Hour by Hour graph might also provide insights into this.
