### ISSUE TITLE
Geolocations Error

### ISSUE THREAD

**Issue by 0xBit-MC** [plan-player-analytics/Plan#1899]
### Describe the issue
South Korea does not display on the map, but displays fine on the bar graph.

Image: [https://i.imgur.com/ZPR8SsS.png](https://i.imgur.com/ZPR8SsS.png)

### Additional information

5.3 build 1284

**Comment by AuroraLS3** [comment]
The ISO code for south korea is probably incorrect 🤔 Should be an easy fix
