### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by SpecifiedNull** [plan-player-analytics/Plan#1901]
### Describe the issue

An error shows in console upon server startup after switched to ProtocolSupport.jar instead of previously using (ViaVersion.jar+ViaBackwards.jar+ViaRewind.jar)

### Exceptions & Other Logs

2109cedf14 - Last occurred: 2021-05-18 Occurrences: 9
---- Context 5 ----
Plan v5.3 build 1284
Paper git-Paper-675 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT

Report and/or disable ProtocolSupport extension in the Plan config.
ProtocolSupport
Method:protocolTable
Error code: 1267
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
Incorrect character encoding in MySQL

---- Context 4 ----
Plan v5.3 build 1284
Paper git-Paper-675 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT

Report and/or disable ProtocolSupport extension in the Plan config.
ProtocolSupport
Method:protocolTable
Error code: 1267
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
Incorrect character encoding in MySQL

---- Context 3 ----
Plan v5.3 build 1284
Paper git-Paper-675 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT

Report and/or disable ProtocolSupport extension in the Plan config.
ProtocolSupport
Method:protocolTable
Error code: 1267
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
Incorrect character encoding in MySQL

---- Context 2 ----
Plan v5.3 build 1284
Paper git-Paper-675 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT

Report and/or disable ProtocolSupport extension in the Plan config.
ProtocolSupport
Method:protocolTable
Error code: 1267
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
Incorrect character encoding in MySQL

---- Context 1 ----
Plan v5.3 build 1284
Paper git-Paper-675 (MC: 1.16.5)
Server v1.16.5-R0.1-SNAPSHOT

Report and/or disable ProtocolSupport extension in the Plan config.
ProtocolSupport
Method:protocolTable
Error code: 1267
SELECT protocol_version, COUNT(1) as count FROM plan_version_protocol INNER JOIN plan_user_info on plan_version_protocol.uuid=plan_user_info.uuid WHERE plan_user_info.server_uuid=? GROUP BY protocol_version
Incorrect character encoding in MySQL

---- Stacktrace ----
com.djrapitops.plan.exceptions.DataExtensionMethodCallException: ProtocolSupport.protocolTable errored: com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:56)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:181)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:174)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
Caused by:
java.lang.reflect.InvocationTargetException
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:567)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:181)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:174)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
Caused by:
com.djrapitops.plan.exceptions.database.DBOpException: SQL Failure: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
   com.djrapitops.plan.exceptions.database.DBOpException.forCause(DBOpException.java:155)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:57)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeQuery(QueryAPIQuery.java:45)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:251)
   com.djrapitops.plan.query.QuerySvc.query(QuerySvc.java:81)
   com.djrapitops.extension.ProtocolSupportStorage.getProtocolVersionCounts(ProtocolSupportStorage.java:122)
   com.djrapitops.extension.ProtocolSupportExtension.protocolTable(ProtocolSupportExtension.java:108)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:567)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:181)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:174)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
Caused by:
java.sql.SQLException: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
   plan.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
   plan.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
   plan.com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
   plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
   plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
   com.djrapitops.extension.ProtocolSupportStorage.lambda$getProtocolVersionCounts$4(ProtocolSupportStorage.java:124)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeWithConnection(QueryAPIQuery.java:55)
   com.djrapitops.plan.storage.database.queries.QueryAPIQuery.executeQuery(QueryAPIQuery.java:45)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:251)
   com.djrapitops.plan.query.QuerySvc.query(QuerySvc.java:81)
   com.djrapitops.extension.ProtocolSupportStorage.getProtocolVersionCounts(ProtocolSupportStorage.java:122)
   com.djrapitops.extension.ProtocolSupportExtension.protocolTable(ProtocolSupportExtension.java:108)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:567)
   com.djrapitops.plan.extension.implementation.providers.Parameters$ServerParameters.usingOn(Parameters.java:64)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$tryToBuildTable$0(DataValueGatherer.java:159)
   com.djrapitops.plan.extension.implementation.builder.BuiltDataValue.getValue(BuiltDataValue.java:48)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.getValue(DataValueGatherer.java:391)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.storeTable(DataValueGatherer.java:446)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.lambda$gather$28(DataValueGatherer.java:354)
   java.base/java.util.Optional.ifPresent(Optional.java:178)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.gather(DataValueGatherer.java:354)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:313)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:181)
   com.djrapitops.plan.extension.ExtensionSvc.updateServerValues(ExtensionSvc.java:174)
   com.djrapitops.plan.extension.ExtensionServerDataUpdater.run(ExtensionServerDataUpdater.java:51)
   net.playeranalytics.plugin.scheduling.UnscheduledBukkitTask.run(UnscheduledBukkitTask.java:22)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
   org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)

```
Place log contents here
```[Tue, 18. May 2021 09:05:41 UTC WARN] Ran into DataExtensionMethodCallException - logged to plugins/Plan/logs/DataExtensionMethodCallException-2109cedf14.txt
[Tue, 18. May 2021 09:05:41 UTC WARN] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[Tue, 18. May 2021 09:05:41 UTC WARN] What to do: Report and/or disable ProtocolSupport extension in the Plan config.

### Additional information
<!-- Any additional information, plugin versions, context, what was attempted, etc -->

**Comment by AuroraLS3** [comment]
>  Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT)

The database has been created with invalid charset collation, and the table (and it's varchar columns) `plan_version_protocol` will need to be converted manually:
https://confluence.atlassian.com/kb/how-to-fix-the-collation-and-character-set-of-a-mysql-database-744326173.html
