### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Produktecheck** [plan-player-analytics/Plan#1911]
I installed plan correctly on bungee cord. The only problem is when I want to go to the website there is no response. Apache2 runs without problems just like the dns entries.
### Additional context
Image Link: https://ibb.co/smBS2XL

**Comment by AuroraLS3** [comment]
There is not enough information to say what is causing the timeout. It could be any link in the connection chain.

Following questions help debugging the situation:

- How long does it take for Cloudflare to reach Apache?
- Does the timeout occur if you bypass Cloudflare and access Apache directly?
- Does the timeout occur if you bypass both and access Plan directly?
- Is Apache located on the same machine as Plan webserver?
- Is MySQL located on the same machine as Plan webserver?
- Is the server running Apache or Plan under heavy CPU load?
- Is the server running Apache or Plan running out of memory?

**Comment by Produktecheck** [comment]
1. not very long
2. yes
3. yes
4. yes
5. yes
6. no
7. no
