### ISSUE TITLE
NPE when getting response

### ISSUE THREAD

**Issue by HexedHero** [plan-player-analytics/Plan#1916]
### Describe the issue

NPE when on the webpage.

### Exceptions & Other Logs

https://paste.gg/p/anonymous/de07a3ff0aad4c60a3b33b7694be37ae/files/664643a2db83473c9bdcd5be5aff7316/raw

### Additional information

Saw it after I went onto the web panel to check server info. Using Plan 5.3 build 1284

**Comment by AuroraLS3** [comment]
JSON stored in the json_cache is null for some reason. If this keeps happening try clearing that cache folder in the Plan folder
