### ISSUE TITLE
GriefPrevention can't list specific claims

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#1925]
### Describe the issue
Using the plugin GriefPrevention, trying to list the claims in the plugin section at the webserver shows no results, even after a new claim is created, it's not showing up

### Exceptions & Other Logs
NA

```
Place log contents here
```

### Additional information
Paper version git-Paper-670 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 102 version(s) behind

Plan version 5.2 build 1174

GriefPrevention version 16.16.0

**Comment by AuroraLS3** [comment]
Update to 5.3 - this bug is caused by https://github.com/plan-player-analytics/Plan/issues/1722
