### ISSUE TITLE
Cannot visit subsections on mobile

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#1942]
### Describe the issue
Cannot visit subsections on a mobile interface on the webserver, unless you switch to viewing the site in desktop mode of course.

### Exceptions & Other Logs

```
Place log contents here
```

### Additional information
![Screenshot_20210617-095535.jpg](https://user-images.githubusercontent.com/70318494/122331285-2fbb3d00-cf52-11eb-824a-02d11bfb8b86.jpg)

![Screenshot_20210617-095559.jpg](https://user-images.githubusercontent.com/70318494/122331308-3cd82c00-cf52-11eb-9f16-c4e0231bc135.jpg)

**Comment by AuroraLS3** [comment]
Great bug to open, this would have been forgotten again otherwise 😅
