### ISSUE TITLE
Mobile sidebar makes stuff go flying

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1946]
### Describe the issue
When the sidebar is opened on mobile (or on a very narrow screen), due to the way the sidebar is implemented, stuff goes flying. A floating & collapsible sidebar (that doesn't change the position of elements on the page) for smaller displays would be a better experience.

(watch the right edge of the viewport ⬇)

https://user-images.githubusercontent.com/13612979/122624648-eda50f00-d0a9-11eb-9371-35dab3d640ae.mp4

### Additional information
Bootstrap 5 has some nifty ways to make a sidebar float & be collapsible. I'll try to fiddle with this and submit a PR if I come up with a good solution.

**Comment by AuroraLS3** [comment]
Just make sure to send the stuff flying on those devices where the black area doesn't appear to close the sidebar.

**Comment by AuroraLS3** [comment]
I don't consider this to be an issue so I'll close this. I'll accept a PR if this is done though, but I don't want to fiddle with this myself
