### ISSUE TITLE
Prometheus Exporter

### ISSUE THREAD

**Issue by sfxworks** [plan-player-analytics/Plan#1951]
### Is your feature request related to a problem? Please describe.

No

### I would like to be able to..

Hello,
I'd like plan to have a Plan Prometheus explorer available for scraping. This would allow nice customization of grafana dashboard in addition to aggregating data into one location from multiple servers.

**Comment by AuroraLS3** [comment]
Please provide a link to prometheus explorer documentation - I was unable to find what you are referring to

**Comment by sfxworks** [comment]
Sure, here are a list of exporters https://prometheus.io/docs/instrumenting/exporters/
As well as developer documentation with naming conventions here https://prometheus.io/docs/instrumenting/writing_exporters/

**Comment by AuroraLS3** [comment]
This seems waaay out of scope for implementation in Plan (Seems more like a separate plugin). On the list there is a lot of exporters for databases and different web services. It is likely possible to use existing exporters to get data out of Plan into grafana.

Here is some information about Plan data
https://github.com/plan-player-analytics/Plan/wiki/Database-Schema
Outdated list of endpoints:
https://github.com/plan-player-analytics/Plan/blob/master/Plan/json-endpoints.md

----

Seems like there is also existing prometheus exporters for few server platforms
- Spigot https://www.spigotmc.org/resources/prometheus-exporter.36618/
- Bungee https://www.spigotmc.org/resources/bungeecord-prometheus-exporter-redisbungee-support.91924/
- Sponge https://ore.spongepowered.org/phit/PrometheusExporter

**Comment by sfxworks** [comment]
Gotcha, ill see if I can't write a separate service that uses those endpoints. Thanks!
