### ISSUE TITLE
deadlocks

### ISSUE THREAD

**Issue by cloakfox** [plan-player-analytics/Plan#1952]
### Describe the issue

https://gist.github.com/cloakfox/ea4ca982ca1cd0de25c031c14db05706

### Exceptions & Other Logs
https://gist.github.com/cloakfox/ea4ca982ca1cd0de25c031c14db05706
```
Place log contents here
https://gist.github.com/cloakfox/ea4ca982ca1cd0de25c031c14db05706

### Additional information
Plan shits itself when you use it on a network type server (server with multiple gamemodes like survival, skyblock, kitpvp, etc)
Plan works fine when it doesnt have to do much. Past few days it has not been able to keep up it feels like.

Using MariaDB for storage
Plan Build 1330

**Comment by AuroraLS3** [comment]
The error appears to be related to extensions. It might be possible to reduce the load by disabling plugin data in all Plan configs under Plugins

**Comment by cloakfox** [comment]
> The error appears to be related to extensions. It might be possible to reduce the load by disabling plugin data in all Plan configs under Plugins

Disabled the plugin integrations on all our gamemodes but still get the same issue ;(

[CompletionException-4b99eac5d5.txt](https://github.com/plan-player-analytics/Plan/files/6703010/CompletionException-4b99eac5d5.txt)

**Comment by AuroraLS3** [comment]
Hmm, still seems to try store some kind of extension data - dunno which plugin though since it's not in the error log though 🤔

**Comment by AuroraLS3** [comment]
The situation may have improved as the icon selection was removed from this particular `UPDATE` SQL - It could have caused the deadlocks.

I'll close this as resolved. If it still occurs please reopen.
