### ISSUE TITLE
Placeholders unloading

### ISSUE THREAD

**Issue by Pirito10** [plan-player-analytics/Plan#1953]
### Describe the issue

I have added a bunch of placeholders to `Plugins.PlaceholderAPI.Load_these_placeholders_on_join`, then I created a hologram to use them. When the server starts up, they are not loaded, I have to reload the hologram for them to show up. But also, if I disconnect from the server for a few minutes, when I rejoin they have unloaded, and I need to reload the hologram again. Although this does not happen if I disconnect and rejoin instantly.

### Additional information

Plan version: 5.4 build 1330
Paper version: 1.16.5 Paper-768
For the holograms I was using PAPI, Holographic Displays and Holographic Placeholders

I am not sure if this issue is from Plan, but I had to start somewhere

**Comment by AuroraLS3** [comment]
The placeholders are loaded when player joins. If the hologram attempts to load the placeholder before Plan has loaded it then yeah it will not display.

Best solution is to suggest the other plugin to replace the placeholders on a non-server thread. I can't do anything more on Plan end without crashing the server.
