### ISSUE TITLE
"loadServerPie is not defined" Error caused by "CN" locale

### ISSUE THREAD

**Issue by BredyAK** [plan-player-analytics/Plan#1954]
### Describe the issue
If you set `Plugin.Logging.Locale` to `CN` in `config.yml`, then go to any page, it will show `Error occurred, see Developer Console (Ctrl+Shift+I) - Please report this: ReferenceError: load服务器Pie is not defined`. The word `服务器` means `Server`, so I think the origin error is: `Error occurred, see Developer Console (Ctrl+Shift+I) - Please report this: ReferenceError: loadServerPie is not defined`.

### Exceptions & Other Logs
No logs.

### Additional information
No other info.

----

### TODO

(written by plugin author)

- Rename loadServerPie function to loadserverPie to avoid `Server` being replaced.
- Look for any other functions javascript with `Server` in the name and replace them too

**Comment by Valyrox** [comment]
Same with French (FR) locale (and other locales I think)
