### ISSUE TITLE
Add a new API endpoint for internal usage

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1965]
### Is your feature request related to a problem? Please describe.
There's currently no way to inform the frontend about internal variables (such as logged-in username, primary language, available languages, version info, registration being enabled etc.). Currently version information and languages are rendered in Java using the backend. 

### I would like to be able to..
Query the backend about the aforementioned things and render stuff (hide the registration button for example) using only the frontend, making code easier to maintain.

**Comment by AuroraLS3** [comment]
Would partially solve #1895

**Comment by AuroraLS3** [comment]
### TODO

- Add /v1/whoami endpoint that returns information about the current logged in user, such as username, linked user and access permissions as json - This endpoint should return 404 if login is disabled.
- Add /v1/version endpoint that returns infromation about the current version and possible updated version. For update links to change log and download.
- Add /v1/language endpoint that returns currently active language code and list of available language codes

**Comment by Kopo942** [comment]
> Add /v1/whoami endpoint that returns information about the current logged in user, such as username, linked user and access permissions as json

I'd suggest we scrap the idea about adding a separate endpoint to handle this. Instead, I think we should use the auth endpoint to send us the details on login and store them in LocalStorage.

**Comment by rymiel** [comment]
> store them in LocalStorage

Please also consider non-browser use of the API, in this case it's probably fine though

**Comment by Kopo942** [comment]
> Please also consider non-browser use of the API, in this case it's probably fine though

Non-browser access will probably use auth tokens (see #2040) that won't have any user data associated with them, so I don't see this as an issue.

**Comment by AuroraLS3** [comment]
It is better to have a separate endpoint to have the server be in charge of logging out. That way it is not necessary to clear the user data from local storage.
