### ISSUE TITLE
Change how to obtain Certificate through windows on OpenSSL

### ISSUE THREAD

**Issue by vijaypondini** [plan-player-analytics/Plan#1973]
**Wiki page to modify**: 
https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-(HTTPS)-Set-Up
### Suggested modifications
Step 4 recreated for windows. 

### Step 4: Creating PKCS12 from Certificate files
Windows Users:
First, make sure you have OpenSSL downloaded. Link to download here - https://slproweb.com/products/Win32OpenSSL.html
Once installed, Open up libraries, and navigate to `/Users/Program Files/OpenSSL-Win64` . It would be OpenSSL-Win32 if you installed the 32 bit. 
Then, open up the `start.bat` file in that directory. That will open the OpenSSL terminal to perform our next set of actions. 
Install your certificate into the empty pkcs12 file by running the command

> openssl pkcs12 -export -in C:/Users/Your/SSL/Directory/domain.cert.pem -inkey C:/Users/Your/SSL/Directory/private.key.pem -out C:/Users/Your/SSL/Directory/pkcs.p12 -name <alias> -passout pass:your<keypass> -passin pass:<storepass>

And then,

**Comment by AuroraLS3** [comment]
### TODO

- Add a section for windows at the bottom with part about each step
- Link to the steps similar to how set-up tutorials do it.

**Comment by vijaypondini** [comment]
openssl pkcs12 -export -in C:/Users/Your/SSL/Directory/domain.cert.pem -inkey C:/Users/Your/SSL/Directory/private.key.pem -out C:/Users/Your/SSL/Directory/pkcs.p12 -name <your_cert_namw> -passout pass:<your_pass> -passin pass:<your_pass>

Just updated it cuz I realised I didn't show some things for the command like passwords and setting cert name lol

**Comment by AuroraLS3** [comment]
Now included,

This openssl installation was a lot better https://www.osradar.com/install-openssl-windows/ so I kept it in place like before.
