### ISSUE TITLE
Duplicate key when attempting insert to plan_ping

### ISSUE THREAD

**Issue by abhisantos** [plan-player-analytics/Plan#1974]
:52:11 ERROR]: [Plan] Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-420c0ed0c4.txt
[12:52:11 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[12:52:11 ERROR]: [Plan] What to do: Report this, duplicate key exists in SQL.

This error keeps spamming console all the time, in all spigot and paper versions.

**Comment by abhisantos** [comment]
[CompletionException-420c0ed0c4.txt](https://github.com/plan-player-analytics/Plan/files/6755958/CompletionException-420c0ed0c4.txt)

**Comment by AuroraLS3** [comment]
Are you using MySQL or SQLite?

**Comment by AuroraLS3** [comment]
Try updating to https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1330 to see if it goes away
