### ISSUE TITLE
Look into Crowdin for localizaition

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#1977]
This ticket is a reminder to look into crowdin for localization management

**Comment by comradekingu** [comment]
Look no further than its terms and services to understand why one would do well to avoid it.
Weblate is to the contrary copylefted libre software, and has no egregious terms.
It can be self-hosted too.

**Comment by AuroraLS3** [comment]
The terms are rather large, which part of them are you referring to?

**Comment by comradekingu** [comment]
I never doubted the amount of text and the internal spaghetti-relationship of sections and documents.
To start somewhere:

>The use of the Crowdin Services is subject to acceptance of these Terms. To accept these Terms for itself or on behalf of a Client, a person must have the legal capacity to do so. In the case of an individual, the individual must be at least 18 years of age or have valid authorization from his/her legal representative or custodian.

> Your continued use of the Crowdin Services after such changes have been posted as provided above constitutes your binding acceptance of such changes. Such amended Terms will automatically be effective upon the earlier of (i) your continued use of the Crowdin Services, or (ii) 30 days from posting of such modified Terms on or through the Platform.

https://support.crowdin.com/sub-processors/
Note that not everything used is even listed.

It is non-free software, and only available without payment for non-commercial libre software.

https://hosted.weblate.org/legal/terms/ and https://hosted.weblate.org/hosting/ in stark contrast as a service, and GPLv3+ as a project.

**Comment by AuroraLS3** [comment]
Yeah the spaghetti is real. It would take a lawyer to figure out what you're actually agreeing to when using this service.

My prior hesitation to use crowdin comes from "free" 3rd party services that I've used in the past like Travis CI and Bintray that suddenly pivoted and left the integrations broken.

Since these terms say they may at any moment change the terms, this leaves that open (They might even say no more free tier for open source in the future)

Pretty safe to say I'll probably avoid it.

**Comment by comradekingu** [comment]
@AuroraLS3 They never said so in the first place. It actually says
> If you're building awesome **non-profit projects** that could use the power of Crowdin, we're happy to help with this free option.

Emphasis mine. Insofar as "gratis" goes, it doesn't qualify, and it would be illegal to call it "free" in my jurisdiction.
However of things that qualify as libre software projects, non-commercial ones are those without a source of revenue.
