### ISSUE TITLE
ProtectionStones extension uses expensive method synchronously

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#1980]
### Describe the issue
It seems that our ProtectionStones extension is using the expensive `PSPlayer#getPSRegions()` method synchronously each time data is updated for a player. The method has to loop through all WorldGuard regions in the specified world each time it is run, so this is probably the cause of the lag @rymiel talked about on Discord.

The javadocs for ProtectionStones suggest running the method asynchronously, so I think that's what we should do also.

**Comment by AuroraLS3** [comment]
All Plan extension calls are supposed to be performed async already 🤔

**Comment by rymiel** [comment]
While asking for help on Paper's discord I was told the synchronous chunk loads were performed from an asynchronous source (I think?). Asynchrony is something I do not understand fully but apparently this is why it could not be traced in a timings report or spark profiler?

**Comment by AuroraLS3** [comment]
That would explain it then. Thanks for the input @rymiel 

Probably going to have to figure out some other way to get the data or disable the extension altogether
