### ISSUE TITLE
CraftingStore Plugin Integration

### ISSUE THREAD

**Issue by Tactryl3** [plan-player-analytics/Plan#1981]
### Data to display

Ranks Purchased, Total $ donated, etc. 
I'm not sure what you have for Buycraft/Tebex, but I would assume the information they provide is similar. 

### Plugin information

**API or Source Code:** https://github.com/CraftingStore/MinecraftPlugin

**Project page or Downloads:** https://craftingstore.net/

**Comment by AuroraLS3** [comment]
Duplicate of  #1917
