### ISSUE TITLE
Plugin cards with multiple tabs don't switch tabs correctly accross multiple servers

### ISSUE THREAD

**Issue by rymiel** [plan-player-analytics/Plan#1982]
### Describe the issue
(I'm basing this entirely off of [the luckperms extension](https://github.com/plan-player-analytics/Extension-LuckPerms)) When switching between tabs such as "Permission Groups" and "Metadata" in the luckperms card, the tabs only switch for the first server in the sidebar list of servers.

https://user-images.githubusercontent.com/53803019/124517727-610a8880-dded-11eb-9d87-dfb90482c4ae.mp4

### Additional information
I'm pretty sure this is because the tabs themselves have an ID (such as `#tab_metadata` as seen in `<div role="tabpanel" class="tab-pane fade in active show" id="tab_metadata">...`) but all of the "same" tabs across all the server options share the same ID so only one is changed as it probably expects IDs to be unique but I do not know enough about the jquery/bootstrap/sb2 stuff the frontend is built on to help fix it

**Comment by Kopo942** [comment]
https://github.com/plan-player-analytics/Plan/blob/f83cbad2b93233c262ea67b123a5e373b81ea608/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/structure/TabsElement.java#L53
TODO: `.append(id)` needs to have both server name and plugin name as unique identifiers, for example `tab_minigames_luckperms_general`

**Comment by rymiel** [comment]
Are server names unique identifiers?

**Comment by Kopo942** [comment]
![image](https://user-images.githubusercontent.com/13612979/124587621-7c62ab80-de60-11eb-9b71-97c550a26222.png)
Server name itself isn't enough since a single server might have multiple plugins with `General` tab, so there might be two `tab_minigames_general` which still causes an issue

**Comment by rymiel** [comment]
Right, but can two servers have the same name or is that something that breaks other stuff anyway?

**Comment by KairuByte** [comment]
Plan (at least should) uses a UUID for the server, so you can technically have the same name on two different servers. 

This isn't a great idea for other reasons, of course, such as simply telling the servers apart.

**Comment by Kopo942** [comment]
> Right, but can two servers have the same name or is that something that breaks other stuff anyway?

True, it _is possible_ to have more than one server with the same name (but with a different UUID) but in that case it'd be next to impossible to distinguish two servers apart without knowing their UUID/specific stats about them. I'd almost blame the user for having duplicate names 😂

I wonder if the `pluginID` in `ExtensionData.java` is unique to whole network or a single server only 🤔 if it is, we could overload the constructor in `TabsElement.java` to accept a `int pluginID` and pass it as a constructor parameter here using `datum.getPluginID()`:
https://github.com/plan-player-analytics/Plan/blob/f83cbad2b93233c262ea67b123a5e373b81ea608/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/pages/PlayerPluginTab.java#L114-L116

**Comment by AuroraLS3** [comment]
> I wonder if the `pluginID` in `ExtensionData.java` is unique to the whole network or a single server only 🤔 if it is, we could overload the constructor in `TabsElement.java` to accept a `int pluginID` and pass it as a constructor parameter here using `datum.getPluginID()`:
> e: @KairuByte sniped me again </3

Plugin id is unique across the whole network
