### ISSUE TITLE
Extension 'LogBlock' still not working properly with Plan

### ISSUE THREAD

**Issue by Luki2410** [plan-player-analytics/Plan#1989]
The problem described in Ticket #1880 is not fixed. The same error message is spit by Plan.

**Comment by Luki2410** [comment]
2109cedf14 - Last occurred: 2021-07-07 Occurrences: 2
---- Context 2 ----
Plan v5.4 build 1354
Paper git-Paper-79 (MC: 1.17)
Server v1.17-R0.1-SNAPSHOT

Report and/or disable LogBlock extension in the Plan config.
LogBlock
Method:playerData

---- Context 1 ----
Plan v5.4 build 1354
Paper git-Paper-79 (MC: 1.17)
Server v1.17-R0.1-SNAPSHOT

Report and/or disable LogBlock extension in the Plan config.
LogBlock
Method:playerData

---- Stacktrace ----
com.djrapitops.plan.exceptions.DataExtensionMethodCallException: LogBlock.playerData errored: java.lang.IllegalArgumentException: World is not logged: null
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:56)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:276)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:148)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:299)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:171)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:156)
   com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$beforePlayerQuit$6(PlayerOnlineListener.java:216)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
Caused by:
java.lang.reflect.InvocationTargetException
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:567)
   com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:99)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:276)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:148)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:299)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:171)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:156)
   com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$beforePlayerQuit$6(PlayerOnlineListener.java:216)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)
Caused by:
java.lang.IllegalArgumentException: World is not logged: null
   de.diddiz.LogBlock.LogBlock.getCount(LogBlock.java:317)
   com.djrapitops.extension.LogBlockExtension.getBrokenStoneCount(LogBlockExtension.java:149)
   com.djrapitops.extension.LogBlockExtension.playerData(LogBlockExtension.java:79)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
   java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   java.base/java.lang.reflect.Method.invoke(Method.java:567)
   com.djrapitops.plan.extension.implementation.providers.Parameters$PlayerParameters.usingOn(Parameters.java:99)
   com.djrapitops.plan.extension.implementation.providers.MethodWrapper.callMethod(MethodWrapper.java:50)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.callMethod(DataValueGatherer.java:288)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addDataFromAnotherBuilder(DataValueGatherer.java:276)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.addValuesToBuilder(DataValueGatherer.java:148)
   com.djrapitops.plan.extension.implementation.providers.gathering.DataValueGatherer.updateValues(DataValueGatherer.java:299)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:171)
   com.djrapitops.plan.extension.ExtensionSvc.updatePlayerValues(ExtensionSvc.java:156)
   com.djrapitops.plan.gathering.listeners.bukkit.PlayerOnlineListener.lambda$beforePlayerQuit$6(PlayerOnlineListener.java:216)
   com.djrapitops.plan.processing.Processing.lambda$submitNonCritical$1(Processing.java:78)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   java.base/java.lang.Thread.run(Thread.java:831)

**Comment by AuroraLS3** [comment]
Looks like there were two places where world parameter was not set and I only fixed one
