### ISSUE TITLE
Incorrect time displaying

### ISSUE THREAD

**Issue by GizliBaskan** [plan-player-analytics/Plan#1992]
I think the data is displayed incorrectly. 
im doing > make a query > selecting 7d and searching user
this is a 1 week query. This user seems to be active for 29 minutes in 1 week. But I'm sure it's more than that.
btw 29d = 29 dakika(minute) in my language
![unknown](https://user-images.githubusercontent.com/55203750/125068497-36a31e80-e0be-11eb-8cef-0d38af3c41d2.png)

**Comment by AuroraLS3** [comment]
Have you changed the time formatting settings to use d for minutes?
