### ISSUE TITLE
how to fix this issue

### ISSUE THREAD

**Issue by ARR4NN** [plan-player-analytics/Plan#1993]
java.lang.NullPointerException: Cannot invoke "com.djrapitops.plan.identification.Server.isProxy()" because "server" is null | Failed to get a response
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.getResponse(RootPageResolver.java:63)
    com.djrapitops.plan.delivery.webserver.resolver.RootPageResolver.resolve(RootPageResolver.java:57)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:191)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:142)
    com.djrapitops.plan.delivery.webserver.RequestHandler.getResponse(RequestHandler.java:135)
    com.djrapitops.plan.delivery.webserver.RequestHandler.handle(RequestHandler.java:98)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
    jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:96)
    jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
    jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:93)
    jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    java.base/java.lang.Thread.run(Thread.java:831)

**Comment by AuroraLS3** [comment]
Make sure Plan has enabled properly before accessing the webserver (`Player Analytics Enabled` shows up on the console)

**Comment by ARR4NN** [comment]
is it possible to limit who can see the panel ?

**Comment by ARR4NN** [comment]
like a login screen

**Comment by AuroraLS3** [comment]
https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up or IP whitelist
