### ISSUE TITLE
Hide unnecessary pages when Plan on proxy is not connectedto back-end server

### ISSUE THREAD

**Issue by MAX-XiaoKui** [plan-player-analytics/Plan#1997]
### I would like to be able to..

Hide unnecessary pages when Plan on proxy is not connectedto back-end server

### Is your feature request related to a problem? Please describe.

When Plan is not connect to back-end servers, many pages show invalid data.
I have fabric back-end servers and cannot load the plugin : )

**Comment by AuroraLS3** [comment]
Duplicate of #1539
