### ISSUE TITLE
Export is not updating /players page

### ISSUE THREAD

**Issue by stepech** [plan-player-analytics/Plan#1999]
### Describe the issue

After updating to latest release yesterday, I later noticed that my webserver (using external webserver from Apache) doesn't have up to date information on player list page. What is strange is that plan still managed to log some data which happened after update, but at the moment, the time at the top of plan page shows 17:56. It's 0:40 right now. That's more than 7 hours late.

### Exceptions & other logs

```text
My export config:
Export:
    HTML_Export_path: 'G:\WebServer\htdocs\Plan'
    JSON_Export_path: 'Raw JSON'
    Parts:
        # Player pages/JSON are only written on join/leave.
        Player_pages: true
        Player_JSON: false
        Players_page: true
        Server_page: true
        Server_JSON: false
    # All player pages/JSON can be exported by using /plan m export players
    Export_player_on_login_and_logout: true
    # If there are multiple servers the period is divided evenly to avoid export of all servers at once
    # Also affects Players page export
    Server_refresh_period: 15
        Unit: MINUTES
```

### Plugin versions

Plan 5.4 build 1366

### Additional information

The only connected thing I can imagine is short internet instability around 18:02, but I have plan's Internal webserver disabled.

**Comment by stepech** [comment]
I'm sorry, gonna edit it a little bit. I have been entering the command wrongly... Still strange that plan doesn't update itself.

**Comment by AuroraLS3** [comment]
Are there any errors in `/plugins/Plan/logs`?

**Comment by stepech** [comment]
No

**Comment by stepech** [comment]
It seems that the only page that is not being updated is the player list page, which is still stuck on yesterday's 17:56. (Update: After restarting the server, it updated. I'll see if it updates later itself too) Although I see some weird behaviour in session's tab too, like this: 
![image](https://user-images.githubusercontent.com/29132060/125191459-d8ec0f00-e242-11eb-9b2a-07e9c760905b.png)

Why is this weird? At the moment it's 12:24 - so this is impossible. Sessions shows at the top that it's up to date.

**Comment by AuroraLS3** [comment]
Player list page is updated only on Plan reload or manually with `plan export players`.

There could be any number of bugs with the exported pages since export has zero testing between updates at the moment.

**Comment by AuroraLS3** [comment]
### TODO

- Add players page export to the periodic server page export if players page export is enabled
