### ISSUE TITLE
Graphs not updating after in-panel refresh [on exported pages]

### ISSUE THREAD

**Issue by EsserGaming** [plan-player-analytics/Plan#2042]
### Describe the issue

When I click refresh button it updates the time on when it was last updated but nothing else seems to update.

### Exceptions & other logs

```text
I am using the dev version but this also happened before the dev version.
```

### Plugin versions

None

**Comment by AuroraLS3** [comment]
Are you using export?
Does this happen if the previous time is over 5 minutes old (eg. Is there actually new data to show)?

**Comment by EsserGaming** [comment]
Yes.

**Comment by AuroraLS3** [comment]
Exported pages don't update the data on the spot so the refresh icon doesn't work the same way there. (I think it doesn't actually do anything) - They should probably be removed from the exported pages

**Comment by EsserGaming** [comment]
Yep!

**Comment by AuroraLS3** [comment]
### TODO

- Add javascript file that is exported and is loaded by any exported html files
- Write code in the javascript to remove any refresh icons from the page (No need to remove the time since that is nice to have)
