### ISSUE TITLE
VotingPlugin support. 

### ISSUE THREAD

**Issue by Pikaronga** [plan-player-analytics/Plan#2044]
### I would like to be able to..

Use VotingPlugin to count votes on the Player Analytics page. Due to when using votingplugin on a network the best way to sync votes is to use votingplugin on the proxy and backend servers and sync with MySQL. Due to this the Nuvotifier plugin is not using pluginmessaging which means it doesn't tell plan it received a vote and that is why this would be a really good feature for the plugin. 

### Is your feature request related to a problem? Please describe.

^^

**Comment by AuroraLS3** [comment]
<https://github.com/plan-player-analytics/Plan/issues/new?assignees=&labels=New+Data%2CDataExtensions%2CHelp+Wanted&template=plugin_request.yml>

**Comment by AuroraLS3** [comment]
#2046
