### ISSUE TITLE
IllegalArgumentException not handled with Fabric commands

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#2045]
### Describe the issue

Fabric commands don't currently handle any IllegalArgumentExceptions, they're improperly logged to a file instead. For example, using `/plan yes` without a pending confirmation throws an exception. 

(this is just a reminder to get this fixed before the next release)

**Comment by AuroraLS3** [comment]
I guess the slimjar thing needs to be added to Fabric too
