### ISSUE TITLE
Fabric: update checker links to non-Fabric JAR

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#2093]
### Describe the issue

![image](https://user-images.githubusercontent.com/13612979/133908679-1e6da98a-62cb-4861-90d6-02c2c531abb8.png)
This should probably point to a Fabric JAR, or alternatively point to the release instead of the artifact (same thing in the console I assume).

**Comment by AuroraLS3** [comment]
Might as well do #936 while at it.
