### ISSUE TITLE
Add a web root folder to make resource customization & accessibility easier

### ISSUE THREAD

**Issue by AnttiMK** [plan-player-analytics/Plan#2098]
### I would like to be able to..

Have a folder in `/plugins/Plan/` (for example `/web/` or `/public_html/`) where the HTML files for Plan would be served from. This way, the HTML files for Plan could be customized directly, without having to first edit the config to enable custom files, then reload Plan and only after that, edit the files. 

This implementation would make it possible (and especially easy) for 
- end users to customize existing files or add custom files (be it HTML, Java, CSS or other static content) to the website without having to clone the project, add the files to the resources folder and build the JAR themselves.
- developers to live-edit (or live preview) the whole website (possibly importing the whole directory into an IDE) and make changes/corrections as needed.

### Is your feature request related to a problem? Please describe.

As discussed on Discord earlier, the current system _is_ usable in its current state. The actual problem comes with the setup required: the config has to be tweaked separately for each file you want to edit, and that takes time and effort.

As a side note, many users aren't aware of the current system since it's "hidden" in the config.
<img src="https://user-images.githubusercontent.com/13612979/134582331-22188668-bac2-4413-a3f2-0b2d141c8ec1.png" width="75%" height="75%">
<details>
<summary style="font-weight: 100;">⚠ A big can of worms: how to handle updates? (open me)</summary>

How the system currently works:
```
1. Update changes a file
2. The customized file on disk stays as it is, it might break things
3. The file is notified about on the console
4. The user has to look on GitHub to see how their file changed
5. The user goes and updates that file
```

How it might work:
```
1. Update changes a file
2. The customized files are dumped to a backup folder and new ones written to the web root
3. There is no way to tell which files were modified beforehand
4. The user has to look at all changes to the files to figure out what changed
5. The user has to look at all their files to find what they changed previously (possibly/hopefully using a VCS)
6. The user goes and updates that file
```
</details>

### Requirements & considerations
- Possibly #1987 
- Update handling

**Comment by AuroraLS3** [comment]
I figure easiest way to handle the React customization would be to have some extra scripts to build it and have git handle the versioning. 🤔
