### ISSUE TITLE
Get rid of server-side HTML rendering 

### ISSUE THREAD

**Issue by AnttiMK** [plan-player-analytics/Plan#2099]
### I would like to be able to..

Have Plan serve static HTML files that wouldn't have any server-side rendering/placeholder replacement done to them. I'd also like to develop the frontend independently without having to rely on/modify the code for the backend to make changes in the frontend.

The implementation would require (at least)
- a handful of new JSON API endpoints that would serve data about different things like extensions, plugin versions etc.
- JavaScript code on the frontend that would render the JSON data into actual HTML
- code on the backend that would render all gathered data to JSON

### Is your feature request related to a problem? Please describe.

The current frontend implementation relies on the backend for rendering many HTML elements, including many placeholder strings, the version check button & modal and most notably, all HTML for the plugin data extensions. The system is rather intertwined, making changing/developing the frontend rather hard due to many components relying on the backend to be displayed.

A new system that served 100% of the data via a JSON API would allow the frontend to be developed separately from the data gathering backend, making it easier to edit & render HTML on the client side. Additionally, Plan could be used as a REST API by other software, providing data to other programs/plugins if needed.

**Comment by AuroraLS3** [comment]
Merged to todo-list of #2260
