### ISSUE TITLE
Latest dev build errors.

### ISSUE THREAD

**Issue by Pikaronga** [plan-player-analytics/Plan#2107]
### Describe the issue

Errors on velocity. 

### Exceptions & other logs

```text
https://pastebin.com/QVakPp6W
```

### Plugin versions

5.4 1445

**Comment by AuroraLS3** [comment]
> Failed to read 'assets/plan/web/vendor/bootstrap/js/bootstrap.bundle.min.js'

Looks like the new html customization write task implemented in #1745 doesn't ignore errors about files that are no longer included in Plan.

Should be simple fix.

> java.net.SocketException: Broken pipe

This exception doesn't seem to be from Plan
