### ISSUE TITLE
Placeholder for the player pages

### ISSUE THREAD

**Issue by sphings79** [plan-player-analytics/Plan#2129]
### I would like to be able to..

Would be really nice to have also player based placeholders.
So you can see the bank balance or other placeholders from other plugins wich are player based.

### Is your feature request related to a problem? Please describe.

No

**Comment by AuroraLS3** [comment]
I stumbled upon this ticket while looking at other placeholder related tickets and I find it ambiguous.

Do you mean:
- you want to see placeholders from other plugins on the player page (This is currently supported)
- you want to see placeholders for the data on player page gathered from other plugins

**Comment by sphings79** [comment]
First one. I think we can close this.
I think I was to stupid.
Works like charm ...
Sorry.

**Comment by AuroraLS3** [comment]
No worries! It's a sort of hidden feature :)
