### ISSUE TITLE
Placeholder - playtime of other player 

### ISSUE THREAD

**Issue by ScrollDP** [plan-player-analytics/Plan#2130]
### I would like to be able to..

Hi, I need a specific placeholder.
When I look at the player I want to see below name his playtime, but I could not find the correct placeholder.

### Is your feature request related to a problem? Please describe.

For example, when a player wants to know how long is playing, its easier to see if the player need to ask him :)

**Comment by AuroraLS3** [comment]
### TODO

- Add :player to the end of the placeholder and implement similar functionality as the :server placeholder, but for player related placeholders.
