### ISSUE TITLE
[root]/players links to ..\player\[uuid] instead of .\player\[uuid]

### ISSUE THREAD

**Issue by KairuByte** [plan-player-analytics/Plan#2155]
### Describe the issue

`[root]/players` links to `..\player\[uuid]` instead of `.\player\[uuid]`

### Plugin versions

5.4 build 1494

**Comment by AuroraLS3** [comment]
### TODO

- Make the /v1/players endpoint return the proper links when server uuid is not given to it

**Comment by AuroraLS3** [comment]
I couldn't reproduce the issue
