### ISSUE TITLE
Show player death count

### ISSUE THREAD

**Issue by Shinigami92** [plan-player-analytics/Plan#2177]
### I would like to be able to..

...see the death count of each player.
If possible it would also be nice to see when and why a player died.

### Is your feature request related to a problem? Please describe.

I already see a total death counter, so I hope it already tracks deaths and aggregate them.

**Comment by AuroraLS3** [comment]
Could you elaborate on why you want to see how many times players have died? (I'm assuming you'd like the stat to appear on the player list since it is available on the player's pages)

**Comment by Shinigami92** [comment]
Yes, I mean on the player list. I found it now on player's page.
Many members on my server ask me who did died the most. We maybe want to show this also ingame sometime. But I just thought it would be easy to add a column due to data already are there and so I can see it in the analytics.

Yeah, don't put to much effort into it if it is complex. Keep it simple as e.g. add a (option?) column to the table :slightly_smiling_face: 

I would like to compare it (visually scan lines), so I don't want to go into each player's page and then find out who died most, and second most and so on.

**Comment by AuroraLS3** [comment]
I guess the easiest option would be to expand the placeholder api leaderboard placeholders to also include pve and pvp statistics
<https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI>

I was kinda worried players wanted to know who dies the most. Note that showcasing who dies the most can lead to the unintended consequence of players jumping off buildings at record numbers in order to get to the top spot. (I saw an article or a video about how someone put the death leaderboard on scoreboard and their players went nuts, but unfortunately I could not find it right now)

**Comment by Shinigami92** [comment]
Uhm... I died this https://gaming.stackexchange.com/a/169738 yesterday ... and one of my friends instantly killed himself 12 times in a row :rofl: 
So you were right with that point LOL

But I now don't see all these deaths in `Plan` :thinking: Only 1 death was counted for him.

![image](https://user-images.githubusercontent.com/7195563/144386666-b3f69dd4-1614-40d7-b40e-8ebb7a345d05.png)

Is something broken with the death counter in your project? Maybe a bug?

**Comment by AuroraLS3** [comment]
Unsure, I'll have to run tests - what server are you running?

**Comment by Shinigami92** [comment]
fabric 0.10.0, mc 1.18

**Comment by AuroraLS3** [comment]
Yeah there might be some issues on fabric since it's pretty new

**Comment by AuroraLS3** [comment]
I opened another ticket to track the bug.

**Comment by AuroraLS3** [comment]
I realized that since you're running fabric placeholders are not a feature there - The death bug has been fixed, do you think this needs any more additions to the website?

**Comment by Shinigami92** [comment]
Currently not :+1: 
I'm very happy with this tool :heart: 
Will reopen or open new issues if I found something
