### ISSUE TITLE
Fabric commands issue tracker

### ISSUE THREAD

**Issue by Kopo942** [plan-player-analytics/Plan#2183]
### Describe the issue

Plan's commands on fabric are a bit borked, see below:

1. Confirmations expire instantly (probably doesn't set up the confirmation at all)
2. `supportsChatEvents()` is always `true`, leads to console getting event-rich messages
![image](https://user-images.githubusercontent.com/13612979/144502392-3dd43215-b5ea-472e-858f-92a685db707c.png)
3. Can't enable Plan with `/plan reload` after `/plan disable` (threadpool killed -> can't submit runnable)
![image](https://user-images.githubusercontent.com/13612979/144503298-d72bd5c4-0ce7-4d7c-bf3b-f0319a678b94.png)
4. Because of 3., reloading is broken 
![image](https://user-images.githubusercontent.com/13612979/144507168-110992fe-6983-453e-b1a4-35ecfefbd612.png)

### Plugin versions

5.4 build 1516

**Comment by AuroraLS3** [comment]
The disable -> reload issue may also be present on other platforms.

**Comment by SulpherStaer** [comment]
I didn't get any console errors, but this error is halting me from going from SQLite to MySQL
![image](https://user-images.githubusercontent.com/5037244/147638323-45b43f48-d52f-4cc1-8499-a99639032ab1.png)

This is on 5.4 build 1526

**Comment by AuroraLS3** [comment]
Yeep that's point 1
