### ISSUE TITLE
LibertyBans Extension Issue

### ISSUE THREAD

**Issue by IceWaffles** [plan-player-analytics/Plan#2190]
### Describe the issue

Error Message shows in console. I've simply banned a user from console with the following error:

### Exceptions & other logs

```text
[10:05:32 WARN]: [Plan] Ran into DataExtensionMethodCallException - logged to plugins/Plan/logs/DataExtensionMethodCallException-f8e724ab1f.txt
[10:05:32 WARN]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[10:05:32 WARN]: [Plan] What to do: Report and/or disable LibertyBans extension in the Plan config.
```

### Plugin versions

Latest version of Plan (before 1.18 update) and latest official release of LibertyBans.

### Additional information

Plan config has not been changed, other than to set up the website.

**Comment by AuroraLS3** [comment]
Please include the mentioned log file

**Comment by IceWaffles** [comment]
[DataExtensionMethodCallException-4a132b4ef8.txt](https://github.com/plan-player-analytics/Plan/files/7703132/DataExtensionMethodCallException-4a132b4ef8.txt)
[DataExtensionMethodCallException-f8e724ab1f.txt](https://github.com/plan-player-analytics/Plan/files/7703133/DataExtensionMethodCallException-f8e724ab1f.txt)
[DataExtensionMethodCallException-7ab223ffe8.txt](https://github.com/plan-player-analytics/Plan/files/7703134/DataExtensionMethodCallException-7ab223ffe8.txt)

**Comment by IceWaffles** [comment]
I've received more errors since then; so I've attached all the log files...

**Comment by AuroraLS3** [comment]
Ok this seems to occur because the end date for ban is set as maximum Instant which is above the 64bit number Plan tries to convert the date to, which causes the ArithmeticException.
