### ISSUE TITLE
LogBlock Wrong Count

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [plan-player-analytics/Plan#2197]
### Describe the issue

It seems like it picks the Netherrack Broken count from the Stone Broken count.
I have on neither account ever broken a Netherrack on the server yet, but both show Netherrack Broken counts, weirdly the same as Stone.

User Account:
https://prnt.sc/22auas3
Admin Account:
https://prnt.sc/22ay2rc

I also wanted to note, that the user accounts blocks broken bottom part with the ores etc. often does not load, but only the part of the image provided, while this is not a big deal, I wanted to mention it too. It seemed to fix itself after several minutes most of the time and several reloads of the plan user page. As said, just a note, not too much of a deal, the main issue is the netherrack count.

Best regards

### Exceptions & other logs

```text
That Netherrack Broken does not display the Stone Broken and in stead displays its own stats
```

### Plugin versions

Latest version of Logblock and Plan

### Additional information

Tried resetting the db of Logblock even, still same result.

**Comment by AuroraLS3** [comment]
Nicely spotted, looks like there is a bug (on this line <https://github.com/plan-player-analytics/Extension-LogBlock/blob/master/src/main/java/com/djrapitops/extension/LogBlockExtension.java#L140>)
