### ISSUE TITLE
Add CraftingStore support

### ISSUE THREAD

**Issue by Fer-Jgu** [plan-player-analytics/Plan#2199]
### I would like to be able to..

Use CraftingStore stuff just as Buycraft is showcased in the [Supported plugins](https://github.com/plan-player-analytics/Plan/wiki/Supported-Plugins) section.

### Is your feature request related to a problem? Please describe.

Nope, just would be cool :)

**Comment by AuroraLS3** [comment]
Duplicate of #1917 - Follow that ticket instead
