### ISSUE TITLE
Player comparison

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2210]
### I would like to be able to..

Compare two or more players and increase the amount of interactive analysis tools available to users

### Is your feature request related to a problem? Please describe.

The manual analysis tools of the plugin are currently limited to the query page.

Players and their activity can be compared to one another. My idea:
- Have a button next to any player name that adds the player to comparison, and have that button on player page too
- Have the comparison float on top of the page
- Allow typing in player names to the floating comparison widget
- the comparison list follows user on the website so that they can go to comparison results once they have chosen players
- the comparison shows a horizontal stacked bar chart of online-offline player sessions for the chosen players
- the comparison shows a table of statistics with players as columns, and the highest or lowest value is highlighted per row
- the comparison has three comparison tabs: all time, 30d and 7d.
- Optional: The comparison window can be moved backwards or forwards

## What does this solve? 

- Allows viewing if two players have been online at the same time
- Another way to see who has bigger numbers (more interesting to players) 
- Lays in the groundwork for comparing groups of players.

**Comment by ILikeOrangeJuice** [comment]
That sounds so nice, could there be eventually (unless I miss this) a sort of top 5/top 10 function with given things like vault, external points (like the playerpoints integration I requested), the playtime (sorted by total, active, afk?) etc.? Either way, a 2 person comparison also opens up a lot of new possibilities aswell!

**Comment by AuroraLS3** [comment]
You can use the server playertable for sorting by plugin data to get a top 10

**Comment by AuroraLS3** [comment]
So https://github.com/plan-player-analytics/Plan/issues/2299 revealed that comparing sessions on a bar chart is almost useless. I think this feature is a bit too extensive to implement right now.
