### ISSUE TITLE
LiteBans Names Issue

### ISSUE THREAD

**Issue by NyhmsQuest** [plan-player-analytics/Plan#2220]
### Describe the issue

![image](https://user-images.githubusercontent.com/3873370/147451098-15a89794-05bc-419e-a314-7f29e62120c7.png)

The "by" section on Litebans doesn't seem to like nicknames with hex colors or something.
It's impossible to read who served the punishment and only happens on the "by" section and not the "Affects" part.

![image](https://user-images.githubusercontent.com/3873370/147451243-ecab69a6-ebe9-4390-972c-dd4c3a5472c4.png)

This last screenshot shows john13210 muting himself, but the "by" part doesn't translate his name properly.

### Plugin versions

5.4 build 1516

**Comment by AuroraLS3** [comment]
Looks like litebans stores the display name and Plan doesn't do color translation for the web.
Probably a semi easy fix by introducing some formatting APIs to Plan

**Comment by HexedHero** [comment]
Similar issue with the "Seen Nicknames" on the player's page
show nicknames like **xHexxexdxHx** when it's "HexedHero" with random colors presumably the nearest MC color.

**Comment by AuroraLS3** [comment]
There is also a likely issue with the new hex-color support since the translation for that is not coded into Plan
