### ISSUE TITLE
ReferenceError: Can't find variable: refreshingJsonRequest

### ISSUE THREAD

**Issue by ipozow** [plan-player-analytics/Plan#2221]
### Describe the issue

I have been using Plan for some years now, and after upgrading to some version it stopped loading the data. Now I am using 5.4 build 1516, and before the page loads I get this error: 
`Error occurred, see Developer Console (Ctrl+Shift+I) - Please report this: ReferenceError: Can't find variable: refreshingJsonRequest`

No matter how much time I wait it won't load the data.
<img width="1728" alt="Captura de Pantalla 2021-12-29 a la(s) 11 22 58" src="https://user-images.githubusercontent.com/10505413/147671863-4657c77e-ba54-4eae-940e-0c4b15a6366c.png">
 

### Exceptions & other logs

```text
<img width="1728" alt="Captura de Pantalla 2021-12-29 a la(s) 11 20 02" src="https://user-images.githubusercontent.com/10505413/147671607-b4cb911c-d79e-467b-b015-4598e478dc41.png">
```

### Additional information

<img width="1728" alt="Captura de Pantalla 2021-12-29 a la(s) 11 20 02" src="https://user-images.githubusercontent.com/10505413/147671607-b4cb911c-d79e-467b-b015-4598e478dc41.png">

**Comment by AuroraLS3** [comment]
Update your xmlhttprequest.js file - you have likely customized it

**Comment by ipozow** [comment]
Thanks! I remember that some time ago I downloaded that file to fix a problem
It's working fine now
