### ISSUE TITLE
Lag With placeholder (in warmup) and error

### ISSUE THREAD

**Issue by nivcoo** [plan-player-analytics/Plan#2225]
### Describe the issue

Hello, i've issue with plan_player_time_total placeholder
The retrieve is very long and sometimes he return this value https://pics.revolis.fr/2022/01/03/21-52_bXBJ.png

### Plugin versions

Plan-5.4-build-1516 in 1.12.2

**Comment by AuroraLS3** [comment]
### TODO

- Write a periodic task that refreshes placeholders set in the config in the cache for players who are online instead of doing it once
- Move the login warmup earlier in the event priority so that other plugins have better chance of asking for the placeholder *after* it has been warmed up
