### ISSUE TITLE
Player time other formats

### ISSUE THREAD

**Issue by Laro5444** [plan-player-analytics/Plan#2227]
### I would like to be able to..

I would like to make a suggestion. You can use placeholders to display the playing time in the scoreboard. My suggestion would be that you can choose the time display yourself. At the moment it is displayed like this: HH: MM: SS and this format cannot be changed. I would like that you can decide for yourself whether you only want to display the hours or hours and minutes or everything.

### Is your feature request related to a problem? Please describe.

No it´s a suggestion :D

**Comment by AuroraLS3** [comment]
Currently this format is formatted the same as the numbers on the webserver (under the Formatting settings)

**Comment by Laro5444** [comment]
Ok so if I comment something out now, would the time in the game be displayed differently or do I get it wrong? Because I would like to have it in hours.

**Comment by Laro5444** [comment]
Ok so if I comment something out now, would the time in the game be displayed differently or do I get it wrong? Because I would like to have it in hours.

**Comment by AuroraLS3** [comment]
If you comment it out a new one will be generated. Set it as empty string instead `""` if you want something removed

**Comment by Laro5444** [comment]
![image](https://user-images.githubusercontent.com/83806525/148245793-e983e032-eca5-4efb-8477-b84315271028.png)
is that so right?

**Comment by AuroraLS3** [comment]
Yeah, note that it will now no longer show any time over 24h since the other time groups are still being formatted

**Comment by Laro5444** [comment]
So if I leave it like that, would he stop counting after 24 hours?

**Comment by AuroraLS3** [comment]
It'll roll back to 0 and continue counting since the 24h rolled over to days

**Comment by Laro5444** [comment]
Ah ok and if I leave it in day and hour it would then show 1d 0h or? Or is there a limit for days where it also starts at 0?

**Comment by AuroraLS3** [comment]
Yes that's correct, except zeros are not shown by default so it would show 1d, then 1d 1h etc

**Comment by Laro5444** [comment]
Kann ich auch Monat und Jahr thetisch weg lassen? Und er würde dann nach 31 tagen dann anzeigen 32d

**Comment by Laro5444** [comment]
Can I also omit the month and year thetically? And then after 31 days it would then show 32d

**Comment by AuroraLS3** [comment]
Similar thing happen with days it'll roll over to months

**Comment by Laro5444** [comment]
If I leave months and years off now, would it eventually start wider at 0 or would it continue counting and after I say 3 months of playing time would show 90d?

**Comment by Laro5444** [comment]
![image](https://user-images.githubusercontent.com/83806525/148248260-98752839-d65e-465e-8f02-67251c790111.png)
To better understand what I mean, I've now set it to what would happen if I did that and 1 month was over. would he then continue counting for days or start again at 0?

**Comment by AuroraLS3** [comment]
29d 23h -> 1 month -> 1 month 1h -> 1 month 1d -> 1 month 1d 1h -> 11 month 29d 23h -> 1 year -> 1 year 1h etc
