### ISSUE TITLE
Improve loading speed of the website

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2230]
### I would like to be able to..

Have data appear faster on the frontend. 

This is a complicated issue, but improving the schema, indexes and reducing the amount of data being queried (by calculating some stuff beforehand for example) could improve the performance.

### Is your feature request related to a problem? Please describe.

following survey answers:

- Web is pretty heavy (especially few graphs) and loading speed is quite long
- Slow loading of web panel sometimes
- the graphs on the website take a long time to load
- Speed with loading my data, I have over 350,000 users joined, and loading any data page takes a good 60+ seconds and sometimes just straight up fails.
- Loading data errors
- Loading times with lots of data (I like to keep all data from the past), however that is something I am willing to put up with because 2+ years of data is a lot to load lol
- Long loading times when dataset gets bigger
- some very minor performance issues

Related ticket #2196

**Comment by Jeffrey-H** [comment]
I think the biggest issues is interacting with de database. With these kinds of datasets it's getting very slow. Here are a couple of options:

- Improve the SQL queries
- Add indexes to the database
- Change the database table engines

I think these options are something to look at in this codebase. Also please prepare the SQL statements.

**Comment by cloakfox** [comment]
+1

**Comment by AuroraLS3** [comment]
Frontend BETA should have resolved this (can be enabled from the config)

Individual requests may still be slow - if that is the case please open individual tickets for specific page that is loading slowly (Known issues: Server page player list).
