### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by Exophobias** [plan-player-analytics/Plan#2241]
### I would like to be able to..

_Just some spitballing here, the first one is one I'd really like to see_

- See the player's ranking related to their active playtime on the admin's player list and on the player page. 

- Weekly comparison history. Configurable amount of time to keep history.

- Add more options to the query. My players like knowing who has the highest kills or deaths and I'd like to be able to query deaths within a certain range or a certain K/D, or query a player killing a specific person --> or a search bar?

- An option to view all sessions, all PvP kills

- FactionsUUID integration. Adding average players online per faction, average PvP kills and deaths, general mob kills and deaths, average balances, etc.

### Is your feature request related to a problem? Please describe.

- Players are competitive and mine would like to know what position they sit in regarding the top players for playtime.

- Having history for week comparisons would be nice to see previous time periods and if you are improving or not.

- As for the other suggestions, I was just spitballing on some data I'd like to see as I find it super interesting to look at the data and graphs.

**Comment by AuroraLS3** [comment]
I have split this ticket to new ticket based on feasible features. They can be seen above.

FactionsUUID is integrated already.
