### ISSUE TITLE
[Suggestion] add avatar URL as config option

### ISSUE THREAD

**Issue by Romvnly-Gaming** [plan-player-analytics/Plan#2243]
**Avatar URL**
As a Geyser user, I need to have the simple option of changing avatar urls and having them point to TydiumCraft's avatar API. Also, what if I don't like the avatar API you're using? 

**Alternatives I've concerned**
Using HTML customization, however that means I'll have to maintain the HTML myself, which isn't a option for me considering I'm extremely busy with school and working on my server.

**Comment by AuroraLS3** [comment]
### TODO

- Add a config option under Display_options
- Add a placeholder to player.html where the player head URL is
- Add the URL to a variable in internal JSON endpoint if one exists at the time this ticket is implemented
