### ISSUE TITLE
South Korea is displayed wrongly on the geo map

### ISSUE THREAD

**Issue by jungwuk-ryu** [plan-player-analytics/Plan#2259]
### Describe the issue

![image](https://user-images.githubusercontent.com/29895665/151689967-19dc0cf7-cba6-4722-aa50-95c8406b2639.png)
South Korea is displayed as North Korea on the geolocation map.

### Plugin versions

Plan version 5.4 build 1542

**Comment by AuroraLS3** [comment]
Oh no wtf

**Comment by AuroraLS3** [comment]
Should be fixed in the latest dev release https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1555
