### ISSUE TITLE
Rewrite the frontend with React

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2260]
### I would like to be able to..

Keep frontend development maintainable

### Is your feature request related to a problem? Please describe.

Current frontend is implemented with bare-bones javascript provided by the browser. While this is all functional, the burden is on the developer to maintain a clear state-DOM relation in the code.

A lot of the features on the backlog would drastically increase the amount of state in the frontend, and that will incur maintenance issues if not dealt with beforehand.

Features that will need a lot of frontend javascript glue-code:
- #2078 Links to query page (State is in the query page filter state)
- #1793 Query templates (State is in the query page filter state)
- #1733 Locale replacement (The framework for replacing the language in the scripts)
- #1623 Web user access control (Permission based visibility management)
- #1539 Hiding features when disabled (Backend state based visibility management)
- #2210 Player comparison (Keeping state of the selected players)
- #2234 Live view (Constant updating of the data)
- #2230 Improving loading speed of the webpage (View based visibility management to reduce amount of data being queried)

----

Current plan on how this is going to be done is to write each page one at a time in React (starting with the simplest, player page) and transferring the webserver responses to the new frontend implementation bit by bit. This way it is easier to continuously develop the plugin without having to maintain two copies of the website.

It is possible to include a yarn wrapper on the project and run yarn build with gradle before resources are copied.

**Comment by ILikeOrangeJuice** [comment]
I wonder if we could get, once you are at that point and done with the important stuff, an easy option to replace certain elements, as far as I understood you right now have to enable in the server/bungee (which ever webserver u use) the config to edit certain files in the config and then go through the file. Maybe we could in the config where the web server is enabled get options to edit certain choices such as those highlighted:
• Own Favicon (which I think is possible rn) and tab names, https://prnt.sc/26q2bl9.
• Replace that Icon (Same as above) https://prnt.sc/26q2bh2.
• True/False option to hide and/or option to modify the output of that string with possibility to add link to it, current version string located on the left side https://prnt.sc/26q2crb.

It is mostly simple things which r mostly possible but require a lot of work where it would be handy, quicker, easier and better for unexperienced/less experienced people to change those things which are branding tools. I personally would change the stuff to my networks stuff, but change the current version to a link and 'ad' to your plugin as I think that is a better option for me personally. 

Again, just some qol changes and IDEAS!:)

**Comment by AuroraLS3** [comment]
![image](https://user-images.githubusercontent.com/24460436/157922340-86849185-92c4-46b9-9670-eda99b081352.png)

Some relations to this ticket visualized

**Comment by AuroraLS3** [comment]
https://reactjs.org/docs/code-splitting.html#route-based-code-splitting

**Comment by AuroraLS3** [comment]
Bug tracker for the rewritten frontend:

- [ ] Nickname and plugin String colors are not set correctly (Move the parsing to frontend) #2329 
- [ ] When logged in on a user that was registered using console, the terminal icon doesn't show up (Move it inside src from public)
- [ ] When the address Plan has configured is wrong, the page doesn't load properly and user doesn't get a proper error message
  - [ ] This can be detected by comparing the address to the start of current address in use.
  - [ ] Fall back to relative address in hopes that the panel is not behind a reverse-proxy subfolder.
