### ISSUE TITLE
Configuration option(s) to zero-baseline charts

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#2270]
### Data to display

I would like charts to be presented with 0 baseline. For example, TPS would chart from 0 to max (20) rather than the current (in my case) 19.2 to 20. A configuration option to do that, without having to create customized JS, would be a nice addition. 

### Link to API or Source Code

n/a

### Link to Project page or Downloads

n/a

**Comment by AuroraLS3** [comment]
I think this could be implemented as a toggle-button on the frontend :)

**Comment by SlimeDog** [comment]
Great!

**Comment by SlimeDog** [comment]
Hopefully the toggle would be a flag on the URL, so that the graph could be called the the desired configuration.

**Comment by AuroraLS3** [comment]
I'll probably have to store it in localstorage (The same place where the user chosen theme is so it persists between reloads) - Thinking more about it, a default value will likely need to be defined in the config anyway.

**Comment by SlimeDog** [comment]
Works for me. :)

**Comment by SlimeDog** [comment]
I assume that this is included in Plan 5.5-b1923. How do I configure to get zero-based charts? I don't see a toggle on the page.

**Comment by AuroraLS3** [comment]
I decided to zero baseline all the charts on the rewritten server page (except the TPS graph, since the TPS is zero-baselined in the All graph so it allows more in depth look) - Enable `Plugin.Frontend_BETA` setting to see those.

If it's not enough I'll look more into it when I make it possible to configure user preferences on the frontend side some time after the rewrite is complete

**Comment by SlimeDog** [comment]
Looks good. It would still be nice to have the option to zero-baseline the TPS chart.

**Comment by AuroraLS3** [comment]
I figured the same stuff is available if you hide the other series from All chart 🤔

**Comment by SlimeDog** [comment]
I supposed, but if one wants All ...

Still, the beta looks good.
