### ISSUE TITLE
Added support for a Discord Bot integration?

### ISSUE THREAD

**Issue by mitchellcrazyeye** [plan-player-analytics/Plan#2272]
### I would like to be able to..

use commands on Discord and possible integration with DiscordSRV (already implemented) to allow users to lookup personal stats.

### Is your feature request related to a problem? Please describe.

Nope, just something I'd love to see happen.

**Comment by AuroraLS3** [comment]
It is possible to integrate custom discord bots to the json endpoints Plan has. https://github.com/plan-player-analytics/Plan/blob/master/Plan/json-endpoints.md

Direct discord bot support is unfortunately out of scope for this project as discord infamously keeps screwing over their bot/bot library developers with their API changes.

Another way you could integrate is have a discord bot run `plan ingame [player]` command and displaying the output. (I'm unsure if DiscordSRV allows this)
