### ISSUE TITLE
@DataBuilderProvider not work

### ISSUE THREAD

**Issue by EnTIv** [plan-player-analytics/Plan#2300]
### Describe the issue

![image](https://user-images.githubusercontent.com/38716516/159155198-73f3a921-eb40-45b6-a369-56fddc27668d.png)
![image](https://user-images.githubusercontent.com/38716516/159154985-3988a05e-604a-4624-8d0a-5b3038f3ab66.png)
No Extension Data
Test: Extension-AuthMe，Extension-MyPet，Extension-MyPlugin

### Plugin versions

Plan: 5.4 build 1583
Authme: 5.6.0 beta2

### Additional information
Purpur-1547 (MC: 1.18.1)
Java 17

**Comment by AuroraLS3** [comment]
You have created a `@DataBuilderProvider` for a player - if you want the data to show up on the Sever page remove the player name argument from your method or create another method annotated with  `@DataBuilderProvider` without any arguments

**Comment by AuroraLS3** [comment]
Player extension data is shown on the player's page

**Comment by AuroraLS3** [comment]
Also if you want the data to show on the server page playerlist you can add a `showInPlayerTable()` to the `ValueBuilder` call chain
