### ISSUE TITLE
Relatively high Database write load

### ISSUE THREAD

**Issue by Thin-Troll** [plan-player-analytics/Plan#2308]
### Describe the issue

PLAN updates, sends and writes data line by line, sending many requests, this phenomenon can occur for several minutes, ten minutes, and sometimes several hours, while the load on the database grows to 100-200%
with small online and data volumes, the load reaches only 80-120%

I uploaded the video with the problem to the discord `Thin_Troll#8809` I do not want to advertise it.

### Plugin versions

The plan is version 5.4 build 1583
database version is 10.7.3-MariaDB-1:10.7.3+maria~buster

**Comment by AuroraLS3** [comment]
In further discussions it was found that Essentials-Extension is updating its data way too frequently if EssentialsEco is also in use
