### ISSUE TITLE
Plan on Paper's logger doesn't show colors

### ISSUE THREAD

**Issue by HexedHero** [plan-player-analytics/Plan#2313]
### Describe the issue

When using Paper 1.18.2, Plan shows 
[Plan] Enabling Plan v5.4 build 1583
[16:39:28 INFO]: [Plan] 
[16:39:28 INFO]: [Plan] §2           ██▌
[16:39:28 INFO]: [Plan] §2     ██▌   ██▌
[16:39:28 INFO]: [Plan] §2  ██▌██▌██▌██▌  §2Player Analytics
[16:39:28 INFO]: [Plan] §2  ██▌██▌██▌██▌  §fv5.4 build 1583
[16:39:28 INFO]: [Plan] 

for its startup message without any colors, even with Paper's use named colors true or false in the paper.yml

### Plugin versions

Plan v5.4 build 1583

**Comment by Kopo942** [comment]
https://github.com/PaperMC/Paper/issues/7596#issuecomment-1073307545

**Comment by AuroraLS3** [comment]
Do the `plan` commands show colors?

**Comment by Kopo942** [comment]
Yes, colors are only lost when `Logger` is used. Uncommenting the below lines could fix it, but there's probably a reason why they were commented out
https://github.com/plan-player-analytics/Platform-abstraction-layer/blob/1f78cae20c68787249b34c08929ac91ad9b082cf/api/src/main/java/net/playeranalytics/plugin/server/JavaUtilPluginLogger.java#L22-L26

**Comment by AuroraLS3** [comment]
It seems that using legacy color formatting is getting more difficult every version - especially since that is pretty much abstracted away. I can't remember why that was commented out, but it may be because I removed the INFO_COLOR log level at some point - probably because colors seemed to work on Paper at the time

**Comment by AuroraLS3** [comment]
Oh yeah this is why I turned it off.. (Bungee)
![image](https://user-images.githubusercontent.com/24460436/167242489-13318d33-daf7-4895-9217-2e6fae4f7711.png)
