### ISSUE TITLE
[Suggestion] Add an option to add a login to see the stats,

### ISSUE THREAD

**Issue by CortezJEL** [plan-player-analytics/Plan#2322]
### I would like to be able to..

Add a login to prevent people to see stats unless they have permission

### Is your feature request related to a problem? Please describe.

it would prevent people from seeing the stats unless authorized

**Comment by Kopo942** [comment]
Plan already has login functionality, it requires HTTPS to be set up: https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up
