### ISSUE TITLE
AFK Time showing 0s for all users [on Fabric]

### ISSUE THREAD

**Issue by IonicEcko** [plan-player-analytics/Plan#2324]
### Describe the issue

After running for a couple of weeks all my users are showing with 0s AFK time. My account shows with 8 minutes but I have AFK'd for FAR longer than that so I'm assuming it was working very briefly at some point? But I've also been OP for a lot of my time which would include the exclude permission.

### Exceptions & other logs

```text
I don't have any (and none show in the console) but am more than happy to provide some where necessary :)
```

### Plugin versions

5.4 build 1583

### Additional information

We are running a Fabric server with the following mods:
 - Fabric API 0.48.0+1.18.2
 - Floodgate build 65 (Users I'm checking aren't floodgate users though)
 - Geyser build 131
 - Lithium 0.7.9
 - Starlight (latest)
 - Plan

We also have some Vanilla tweaks datapacks, namely:
- AFK Display
- Anti Enderman Griefing
- More Mob Heads
- Player Head Drops

**Comment by AuroraLS3** [comment]
Looks like the move event is getting constantly triggered even though the player is not moving.

**Comment by OlegAkimenko** [comment]
I have a server network on Bungeecord, and it shows the AFK time as 0 minutes for all players. What should I do about this? When I had only one server, everything was fine
