### ISSUE TITLE
Show UUID in Player Overview

### ISSUE THREAD

**Issue by pray4kevy** [plan-player-analytics/Plan#2326]
### I would like to be able to..

Is it possible to have a section in the player overview page that shows the UUID provided from the usercache.json?

### Is your feature request related to a problem? Please describe.

Not a problem with Plan; Geyser plugin creates a new UUID for bedrock players joining Java servers, some plugins wont accept the user's faux name but will accept the UUID that is cached with the server. Would be useful to grab the UUID from the overview page.

**Comment by AuroraLS3** [comment]
I'm changing the address to use UUIDs, is that adequate?

**Comment by pray4kevy** [comment]
If that shows up easily on the player page, sounds great to me!

**Comment by AuroraLS3** [comment]
All addresses on the frontend beta should now be using the uuid in the address
