### ISSUE TITLE
Frontend rewrite on playerpage showing Nickname wrong

### ISSUE THREAD

**Issue by jayyythewaffle** [plan-player-analytics/Plan#2329]
### Describe the issue

```Due to the new rewrite of the playerpage, there is an issue with showing the nickname on servers.```

![Issue](https://user-images.githubusercontent.com/77808206/163565271-15cde6a6-2c06-429e-8a86-19e558067e7a.png)

### Exceptions & other logs

```text
I don't believe log files to be needed.
```

### Plugin versions

```text
Plan | Player Analytics 5.4 build 1628
```

### Additional information

```text
Not needed.
```

**Comment by AuroraLS3** [comment]
Thanks! I totally forgot about this one

**Comment by jayyythewaffle** [comment]
No problem. Thank you for fixing :)

**Comment by Technofied** [comment]
Just to add onto this issue, it's also seen in the Plugins sub page of the Player's Page :)

<img width="485" alt="Screen Shot 2022-04-15 at 8 01 52 pm" src="https://user-images.githubusercontent.com/40795318/163568459-325d1de0-9cbf-4a84-b5c4-36e1ad00e57d.png"

**Comment by jayyythewaffle** [comment]
@AuroraLS3 Quick addition I found in the newest dev release -> It seems that someone used scissors to cut my Luckperms Integration
![image](https://user-images.githubusercontent.com/77808206/167827024-d433ac0c-bdc2-49b9-a8cd-085333103519.png)

**Comment by AuroraLS3** [comment]
I have fixed the original issue of the ticket and opened new ticket for @Technofied #2374

If the luckperms cutoff issue still persists in next release please open another ticket.
