### ISSUE TITLE
Disable Registering

### ISSUE THREAD

**Issue by KaspianDev** [plan-player-analytics/Plan#2332]
### I would like to be able to..

disable registration feature, so I can create staff accounts and don't let other's register (ip whitelist doesn't really help)

### Is your feature request related to a problem? Please describe.

it is not

**Comment by AuroraLS3** [comment]
You can nageate or not give plan.register.self and nobody will be able to register since registration links to an account using register command in game or on console.

**Comment by KaspianDev** [comment]
I would prefer to disable /auth/register endpoint tho
