### ISSUE TITLE
Something you did completely messed up viewing uuid 

### ISSUE THREAD

**Issue by TreeOfSelf** [plan-player-analytics/Plan#2337]
### Describe the issue
So, I have been able to use the node.js module sqlite3 to access the sqlite database to pull information. Whatever a later update did managed to completely mess up viewing the uuid at all through this module. 

### Exceptions & Other Logs
Running
db.all("SELECT * FROM 'plan_user_info'", [], (err, result) => {
Does not display uuid at all (breaking everything)

![image](https://user-images.githubusercontent.com/53889485/163727853-627eeade-c0ab-4d00-82de-1fac9d62d67a.png)

Pretty much displays everything except the uuid

### Plugin versions
Latest

### Additional information
Please fix, annoyingly I don't think I can just revert the plugin now because I am pretty sure it changed the DB and there is no going back now.

**Comment by TreeOfSelf** [comment]
Ok, I found a work around, basically have to query the entire plan_users, create a table that connects a user id to a uuid, THEN I can finally use the plan_sessions user_id to get their uuid, whatever, it works.

**Comment by Kopo942** [comment]
[The changelog for 1628](https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1628) very clearly states that the database schema has changed, the builds are backwards incompatible and changes have to be made to your queries if using the database directly. 

> basically have to query the entire plan_users, create a table that connects a user id to a uuid, THEN I can finally use the plan_sessions user_id to get their uuid, whatever, it works

This isn't really how you're supposed to use a relational database. If you would've read the changelog, **there's literally a line** that tells you how to get the player UUID in the result set for the SQL query (`If you need uuid in ResultSet...`). <- This is how you're supposed to use a relational database.

> Guess from now on before I update I am going to have to backup the database and make absolutely sure nothing is going to break.

As said earlier, if you would've read the changelog, there literally was a link to a "How to prepare for this update" guide, in which the first thing it tells you to do is backup your database. It's always a good thing to take backups with larger, schema-breaking updates in case anything goes wrong.

**Comment by AuroraLS3** [comment]
Joining tables in sql:
```sql
SELECT uuid, session_start FROM plan_sessions
JOIN plan_users on plan_users.id=plan_sessions.user_id;
```

**Comment by TreeOfSelf** [comment]
That query is actually more inneficient because it requires multiple look ups on the users table for each session (looping through every session). Next time something breaks on update I'll read the changlog.

**Comment by AuroraLS3** [comment]
It may be more inefficient for this lookup, but there are a lot of other queries in the plugin that require joining plan_sessions to other tables or query results - and joining by doing a String based join (uuid column, even if indexed) is a lot more inefficient than having a foreign key index with integers.

**Comment by TreeOfSelf** [comment]
Yeah for just a few lookups it is certainly faster to not make an entire table, but if you are going through all of the sessions as I am doing it would be slower to do joins for session uuid look up.

**Comment by AuroraLS3** [comment]
If you do a new select query for every single session then that is slower indeed. O(n^2)

But if you query them all at once with similar query as I put that is marginally slower than before because the database can get the data in O(n log n) time.

**Comment by TreeOfSelf** [comment]
Ok thanks for the information and sorry for being fussy.
