### ISSUE TITLE
Raw placeholder returns regular value

### ISSUE THREAD

**Issue by FinnChildress** [plan-player-analytics/Plan#2347]
### Describe the issue
%plan_player_time_month_raw% returns the same value as %plan_player_time_month%

### Exceptions & Other Logs
N/A

### Plugin versions
5.4 build 1633

### Additional information
%plan_player_time_week_raw% and the other raw placeholders seem to be working fine

**Comment by FinnChildress** [comment]
Any ETA on this fix would be very appreciated :)

**Comment by AuroraLS3** [comment]
ETA 1 week to 2 months
