### ISSUE TITLE
Bungee: SQL Errors after updating "What to do: Report this, there is an SQL grammar error."

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#2349]
### Describe the issue
I updated to Plan-5.4-build-1633 from an older version that was before your SQL upgrades, and bungee is reporting SQL errors every few seconds spamming & creating logs.
```
[14:56:19] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-8420195ab0.txt
[14:56:19] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[14:56:19] [Plan MySQLDB-transaction-thread-1/ERROR] [Plan]: What to do: Report this, there is an SQL grammar error.
```
Contents of [CompletionException-8420195ab0.txt](https://gist.github.com/TomLewis/1c971e9fbb98e30251a56c90a767f3ea)

**Comment by AuroraLS3** [comment]
That server is running an old build -  I tried to be clear in the change log that all servers should be updated
![image](https://user-images.githubusercontent.com/24460436/165105099-ae115bb1-7761-44b8-a531-5f72d5538684.png)
https://github.com/plan-player-analytics/Plan/wiki/Preparation-for-update-with-database-schema-changes

![image](https://user-images.githubusercontent.com/24460436/165105157-7957ea37-3426-42d5-b0e8-65c5b5383f61.png)

**Comment by AuroraLS3** [comment]
Soo make sure that all servers are running the new build 😅

**Comment by TomLewis** [comment]
> Soo make sure that all servers are running the new build 😅

My survival did go through this process.

**Comment by Kopo942** [comment]
```
Plan v5.4 build 1583
BungeeCord git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:ba3bbcc:483
```

According to the error log, your proxy is still running an old version ^^

**Comment by TomLewis** [comment]
Urgh such a noob mistake! thaks! Glad its simple! haha

**Comment by TomLewis** [comment]
Its just stuck booting my bungee now at;
``10:44:20 | [Plan]: Applying Patch: RemoveDanglingUserDataPatch..`` its now 10:58

**Comment by TomLewis** [comment]
Ive had to just remove Plan all together, its not progressing past that point after already converting, I cant have my production down for much longer.

**Comment by TomLewis** [comment]
So what now? is that now 5-6 years of data now lost because there wasnt an IF statement to check if the database was upgraded?

The database wasnt backed up first as its a seperate database to my main server(s) as its so large.

**Comment by AuroraLS3** [comment]
I can help recover the database to a working condition.

Please run this and send the results so that I get a better picture of what state the current schema is in (Change 'Plan' to whichever database name you're using)
```sql
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, COLUMN_DEFAULT FROM information_schema.columns WHERE table_schema = 'Plan';
```

**Comment by TomLewis** [comment]
https://gist.github.com/TomLewis/89865f15776f6f48af67fc4aea5547b9

**Comment by TomLewis** [comment]
Thanks for the raw SQL, I always prefer schema changes this way, After a very long time running some of those queries, 0 rows were effected from every single one.

```SQL
DELETE FROM plan_user_info WHERE uuid IN (SELECT * FROM (SELECT DISTINCT g.uuid FROM plan_user_info g 
LEFT JOIN plan_users s on s.uuid=g.uuid
WHERE s.uuid IS NULL) AS x);

283.859 s  Query 1 OK: 0 rows affected

DELETE FROM plan_user_info WHERE server_uuid IN (SELECT * FROM (SELECT DISTINCT g.server_uuid FROM plan_user_info g 
LEFT JOIN plan_servers s on s.uuid=g.server_uuid
WHERE s.uuid IS NULL) AS x);

264 ms Query 1 OK: 0 rows affected

DELETE FROM plan_ping WHERE uuid IN (SELECT * FROM (SELECT DISTINCT g.uuid FROM plan_ping g 
LEFT JOIN plan_users s on s.uuid=g.uuid
WHERE s.uuid IS NULL) AS x);

3488.911 s Query 1 OK: 0 rows affected

DELETE FROM plan_ping WHERE server_uuid IN (SELECT * FROM (SELECT DISTINCT g.server_uuid FROM plan_ping g 
LEFT JOIN plan_servers s on s.uuid=g.server_uuid
WHERE s.uuid IS NULL) AS x);

2.123 s Query 1 OK: 0 rows affected

DELETE FROM plan_sessions WHERE uuid IN (SELECT * FROM (SELECT DISTINCT g.uuid FROM plan_sessions g 
LEFT JOIN plan_users s on s.uuid=g.uuid
WHERE s.uuid IS NULL) AS x);

3979.148 s Query 1 OK: 0 rows affected

DELETE FROM plan_sessions WHERE server_uuid IN (SELECT * FROM (SELECT DISTINCT g.server_uuid FROM plan_sessions g 
LEFT JOIN plan_servers s on s.uuid=g.server_uuid
WHERE s.uuid IS NULL) AS x);

3.020 s Query 1 OK: 0 rows affected

DELETE FROM plan_world_times WHERE uuid IN (SELECT * FROM (SELECT DISTINCT g.uuid FROM plan_world_times g 
LEFT JOIN plan_users s on s.uuid=g.uuid
WHERE s.uuid IS NULL) AS x);

7686.269 s Query 1 OK: 0 rows affected

DELETE FROM plan_world_times WHERE server_uuid IN (SELECT * FROM (SELECT DISTINCT g.server_uuid FROM plan_world_times g 
LEFT JOIN plan_servers s on s.uuid=g.server_uuid
WHERE s.uuid IS NULL) AS x);

3.522 s Query 1 OK: 0 rows affected

DELETE FROM plan_worlds WHERE server_uuid IN (SELECT * FROM (SELECT DISTINCT g.server_uuid FROM plan_worlds g 
LEFT JOIN plan_servers s on s.uuid=g.server_uuid
WHERE s.uuid IS NULL) AS x);

31 ms Query 1 OK: 0 rows affected
```

**Comment by TomLewis** [comment]
What shall I do? I booted up Plan on my Creative and no other server and its been 2 hours and its not passed;
`Applying Patch: RemoveDanglingUserDataPatch..`

**Comment by TomLewis** [comment]
13:37 now, its dont nothing since 10:38, server still stuck at boot, Do I leave it to keep trying?

**Comment by TomLewis** [comment]
Its done something, only if I `cat` the latest.log tho, I can no longer access the server at all, It may have fully frozen up.
```
[13:41:54] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: RemoveDanglingServerDataPatch..
[13:41:59] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: PingOptimizationPatch..
```

**Comment by AuroraLS3** [comment]
Looks like it's going to take a while to update the database since you have so much data, leaving it overnight will probably help. If you're unable to keep Creative doing it I suggest booting up an extra server just to get the patches done.

Once all the patches complete they won't be run again.

**Comment by TomLewis** [comment]
I wonder why it patched it first time fine then, super odd, creative can just chug away overnight, I still cant access the console for it, I have to pull the logs from latest.log for some reason, which is very odd.

Update from the time now:

```
[13:41:54] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: RemoveDanglingServerDataPatch..
[13:41:59] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: PingOptimizationPatch..
[15:53:36] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: UserInfoOptimizationPatch..
[15:59:26] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: WorldTimesOptimizationPatch..
[19:25:52] [Plan MySQLDB-transaction-thread-1/INFO]: [Plan] Applying Patch: SessionsOptimizationPatch..
```

So I guess it seems to still be upgrading and hasn't crashed... Ill just leave it and hope for the best.
Shame there wasn't some raw SQL I could have just done myself.

**Comment by AuroraLS3** [comment]
Ah so awesome to hear that the optimizations have worked! :)

Kinda bummer that it took so long to patch - but my guess is that it took so long for the same reason the panel was unusable. Main optimization was swapping from UUIDs (stored as varchar) to Integers (foreign key) as the join column, so likely the amount of string lookups the database had to do was the main hinderance.

In order to get the integers the patches had to look up the id in plan_users for each uuid in each table that was patched. So if you have say 1 million users, and 15 million rows of sessions, that's 15 million million lookups to get all the data for the patch.

**Comment by AuroraLS3** [comment]
I'll close this since the original issue seems to be resolved.

**Comment by TomLewis** [comment]
> Main optimization was swapping from UUIDs (stored as varchar) to Integers (foreign key) 

Lot less information to store too instead of UUID every time and it can be indexed! Why is it always the joins that destroy performance haha

I have just shy of 350,000 users on plan out of the 500k unique Ive had join, I did get plan on early, maybe one day youll have a way to scan Essentails data folder or the world folder for player accounts, so that all users can be imported to one giant searchable UI!
