### ISSUE TITLE
Plan Ran into DataExtensionMethodCallException (GriefDefender.claimTable errored: java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by poqdavid** [plan-player-analytics/Plan#2354]
### Describe the issue
This issue was also reported here https://github.com/plan-player-analytics/Plan/issues/2051

[DataExtensionMethodCallException-ffa4d867bd.txt](https://github.com/plan-player-analytics/Plan/files/8599094/DataExtensionMethodCallException-ffa4d867bd.txt)

### Exceptions & Other Logs
None

### Plugin versions

**Forge**: 14.23.5.2860
**Sponge**: 2838-7.4.3
**GriefDefender**: 2.0.1

### Additional information
None

**Comment by AuroraLS3** [comment]
Seems like they have changed something again
Previously it was
`NoSuchMethodError: 'com.flowpowered.math.vector.Vector3i com.griefdefender.api.claim.Claim.getGreaterBoundaryCorner()`
Now it is
`NoSuchMethodError: com.griefdefender.api.claim.Claim.getGreaterBoundaryCorner()Lcom/griefdefender/lib/flowpowered/math/vector/Vector3i`

**Comment by AuroraLS3** [comment]
Looks like they had relocated the class
