### ISSUE TITLE
Design Suggestion: Move the "Servers" Dropdown from the network page to be on all pages top left.

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#2357]
### I would like to be able to..

For Network servers you implemetnted this server dropdown based on an old suggestion ages ago:
![Screenshot 2022-05-06 at 11 51 39](https://user-images.githubusercontent.com/144046/167118231-af76d09e-2301-4c2b-b33b-94e044f5e28d.png)

This is a very minor QOL improvemnet, to move this "Servers" dropdown to be on every server page top left as a global navigaton.

Currently If I click survival, to get back to another server, I have to click on the button on the right "Network page"
![Screenshot 2022-05-06 at 11 52 54](https://user-images.githubusercontent.com/144046/167118462-79515ad6-634d-4f65-9812-2a246ba8fa5f.png)

You could remove this entirely and just have it all under one "split button" where this is;

![Screenshot 2022-05-06 at 11 54 04](https://user-images.githubusercontent.com/144046/167118596-5efabd66-b890-4929-9569-d7730c30913c.png)

I see you are using Bootstrap 5, there is a spit button option:
https://getbootstrap.com/docs/5.1/components/dropdowns/#split-button

The left button would be Server Overview, but rename to "Survival Overview" so that we know what page we have selected, then the split button dropdown on the right of it would activate the server list dropdown! then we can navigate from one menu and not have 2 seperate menus split across the page to get around.

- [ ] So something like this, but with an icon etc, I just inspected element to get a dirty screenshot ha

![Screenshot 2022-05-06 at 11 59 23](https://user-images.githubusercontent.com/144046/167119276-89677b61-1983-4b27-b730-e9cf7d1a465d.png)

### Is your feature request related to a problem? Please describe.

Accessability and Quality of life for UI.

### Second Suggestion

- [ ] Use the server list icon from each server as the Logo.

### Third Suggestion

- [ ] CLICK the Logo to go back to Network page!

**Comment by AuroraLS3** [comment]
The back button is definitely getting moved to the left sidebar as part of #2260

I'll try to incorporate the idea of showing which server you're looking at during the rewrite of server page.

**Comment by AuroraLS3** [comment]
Ohh, I read this again with the edits and a server / page selector at the top of the navigation bar sounds brilliant - It would also allow managing multiple servers from one game server without a proxy if there isn't one. I'll have to see what I can do. It's going to be a lot smoother transition between pages once they're all rewritten in React too.

**Comment by TomLewis** [comment]
awesome
