### ISSUE TITLE
Network: Failed to load Players table data

### ISSUE THREAD

**Issue by TomLewis** [plan-player-analytics/Plan#2359]
### Describe the issue
Did the enhanceemnts to fix loading large player sets not get pushed to network based player list?
https://panel.fakedomain.com/players/
Times out with:
`Failed to load Players table data: Request did not reach the server. (Server offline / Adblocker?)`

When I load Network developer tools, the players.json Responce says "Response has been truncated"

![Screenshot 2022-05-06 at 12 27 55](https://user-images.githubusercontent.com/144046/167123028-d9419521-0306-4740-9e7d-cb5fd02778ca.png)

Edit: I realise this says cached, so I shift+reloaded to confirm, same result. 8.72mb json file being loaded LOL.

But my Survival now works (It never used to until this MySQL updte)
https://panel.fakedomain.com/server/Survival/#tab-playerlist

Edit edit: I checked, same things happening in Survival, but its displaying users still...

Quick google, could be a limit in FireFox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1223726

edit edit edit:
I tried in Chrome, same issue. It dousnt say truncated, but the responce isnt all there, Im wondering if the filesize is just to massive. Youll have to split it up into the pagenated results for the table and load the lists as the pages are changed in the playerlist.

**Comment by AuroraLS3** [comment]
Sidenote: Dev tools says `"Response has been truncated"`, but you can still get the full response by going to the requested address (this is just an optimization they had to make in dev tools) - The linked bug seems to be related to dev tools

8 MB is definitely not too much data - as I've run into the actual limit for how much you can load into browser memory when I was working on [Visualizing bike stand data](https://github.com/AuroraLS3/HSL-bike-data-visualization), and that's closer to 500MB (After that the browser just refuses to even try to load the javascript object and goes along as if it was `undefined` - no error no nothing, that was fun to debug)

What is happening is that the Plan code has limit on how new data it wants to show on /players page and the query is taking too long - and the cached value is too old for the limit.

I think I removed this cache limit from the server page at some point but that was not applied to the /players page.

I'll deal with this when rewriting the players page in React as part of #2260

**Comment by AuroraLS3** [comment]
New version has optimized request size (17k players /v1/players = 6MB -> /v1/playersTable = 4MB). I think other optimizations in the player list queries have fixed this bug. If this is still an issue please open another ticket.
