### ISSUE TITLE
Track join addresses per week

### ISSUE THREAD

**Issue by SiuanSong** [plan-player-analytics/Plan#2362]
### I would like to be able to..

**track join addresses on a per week basis just like the New/Total/Regular players function.**

### Is your feature request related to a problem? Please describe.

I have different IPs for each advertising platform I use and would love to be able to see which sites have the most impact, and most importantly, at which time they have an impact.  
If at all possible, tracking this with just new player joins would be amazing.
It would allow me (and other servers) to see if their adverts, paid or otherwise, have the desired effect.

**Comment by AuroraLS3** [comment]
I'll need to change how the join addresses are stored in the database for this.

**Comment by AuroraLS3** [comment]
Database schema is updated in commit above, but this will still need some new visualization. That visualization is postponed after React rewrite of the frontend.
