### ISSUE TITLE
Database table with latest activity index

### ISSUE THREAD

**Issue by Bloodlex** [plan-player-analytics/Plan#2368]
### I would like to be able to..

show top activity index list and also for specific players on own page, so my players could easily check their own activity or ranking without access to all of the information in Plan panel and to better integrate my server webpage. Is it possible to add a database table storing the latest activity index? It could be saved on a specific interval and easily accessed via database query to present it on a website or another place.

### Is your feature request related to a problem? Please describe.

This feature would be used to present current activity index list on my website and also my players would be able to check activity index for them. Thanks a lot for the help :)

**Comment by AuroraLS3** [comment]
Since activity index changes as sessions go in or out of the 3 week time window it is inefficient to keep it as a value in database table.

I can send you the query for it later.

Note that activity index is visible in `/plan ingame` which shows some information about the player who uses the command in game

**Comment by Bloodlex** [comment]
> Since activity index changes as sessions go in or out of the 3 week time window it is inefficient to keep it as a value in database table.
> 
> I can send you the query for it later.
> 
> Note that activity index is visible in `/plan ingame` which shows some information about the player who uses the command in game

Hey,

I would be grateful if you could send me such a query 🙂 And thanks for the tip with /plan ingame, I didn't know it shows activity too 🙂 But still I would like to show it on the website in player's profile 🙂 Thanks for your help.

Best regards

**Comment by AuroraLS3** [comment]
It's a bit complicated query and I don't want to write it out by hand so I'll have to run the plugin to print out the full SQL - I'll send the query as soon as I have time to do that.

**Comment by Bloodlex** [comment]
> It's a bit complicated query and I don't want to write it out by hand so I'll have to run the plugin to print out the full SQL - I'll send the query as soon as I have time to do that.

Thank you very much 🙂

**Comment by AuroraLS3** [comment]
Replace `{playtime_threshold_ms}` and you should be good to go. Here's the very "simple" sql 😅 

```sql
SELECT
  u.uuid,
  u.name,
  act.activity_index
FROM
  plan_users u
  LEFT JOIN (
    SELECT
      5.0 - 5.0 * AVG(1.0 / (PI() / 2.0 * (q1.active_playtime * 1.0 / {playtime_threshold_ms}) + 1.0)) as activity_index,
      u.id as user_id,
      u.uuid
    FROM
      (
        SELECT
          ux.id,
          ux.uuid,
          COALESCE(active_playtime, 0) AS active_playtime
        FROM
          plan_users ux
          LEFT JOIN (
            SELECT
              user_id,
              SUM(session_end - session_start - afk_time) as active_playtime
            FROM
              plan_sessions
            WHERE
              session_end >= UNIX_TIMESTAMP(NOW())*1000 - 604800000
              AND session_start <= UNIX_TIMESTAMP(NOW())*1000
            GROUP BY
              user_id
          ) sx on sx.user_id = ux.id
        UNION ALL
        SELECT
          ux.id,
          ux.uuid,
          COALESCE(active_playtime, 0) AS active_playtime
        FROM
          plan_users ux
          LEFT JOIN (
            SELECT
              user_id,
              SUM(session_end - session_start - afk_time) as active_playtime
            FROM
              plan_sessions
            WHERE
              session_end >= UNIX_TIMESTAMP(NOW())*1000 - 1209600000
              AND session_start <= UNIX_TIMESTAMP(NOW())*1000 - 604800000
            GROUP BY
              user_id
          ) sx on sx.user_id = ux.id
        UNION ALL
        SELECT
          ux.id,
          ux.uuid,
          COALESCE(active_playtime, 0) AS active_playtime
        FROM
          plan_users ux
          LEFT JOIN (
            SELECT
              user_id,
              SUM(session_end - session_start - afk_time) as active_playtime
            FROM
              plan_sessions
            WHERE
              session_end >= UNIX_TIMESTAMP(NOW())*1000 - 1814400000
              AND session_start <= UNIX_TIMESTAMP(NOW())*1000 - 1209600000
            GROUP BY
              user_id
          ) sx on sx.user_id = ux.id
      ) q1
      JOIN plan_users u on u.id = q1.id
    GROUP BY
      q1.id
  ) act on u.id = act.user_id
ORDER BY
  ses.activity_index DESC
LIMIT
  10;
```
