### ISSUE TITLE
Skins in offline mode (for players who have original mc)

### ISSUE THREAD

**Issue by LosBagros** [plan-player-analytics/Plan#2375]
### I would like to be able to..

You can take player name
![image](https://user-images.githubusercontent.com/45005533/170356501-63fe7646-5884-4097-b554-461dfd30f234.png)
get player id from minecraft api `https://api.mojang.com/users/profiles/minecraft/${username}`
![image](https://user-images.githubusercontent.com/45005533/170356858-124ecf2e-7a02-4629-a944-0163c9fc8fc4.png)
if the api answers player have original mc, then you can use the id to get skin image
![mc](https://user-images.githubusercontent.com/45005533/170358219-83c2cf47-66b1-401c-869e-14d3c814a8da.png)

Thanks Bagros
![skin](https://crafatar.com/avatars/dac6791243e64af8931d15c3a794ea19?size=120&default=MHF_Steve&overlay)

### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/45005533/170356580-f8c57c9b-9470-478e-b815-1a5f49369b39.png)

**Comment by AuroraLS3** [comment]
Change your player head image provider to one that supports player names and include `${playerName}` in the URL.

`Display_options.Player_head_image_url` in the config.
