### ISSUE TITLE
Players are shown to be joining using ''Unknown'' as the IP address on all servers

### ISSUE THREAD

**Issue by KayaLambrechts** [plan-player-analytics/Plan#2413]
### Describe the issue
Players are shown to be joining using ''Unknown'' as the IP address on all servers

### Plugin versions
Plan 5.4 build 1690

### Additional information
Both backend servers are using Purpur, build 1531, downloaded from https://purpurmc.org/downloads
Proxy - Velocity, 3.1.2-SNAPSHOT (git-3ae93875-b138) from https://papermc.io/downloads#Velocity

Plan configs;
Proxy https://bin.bloom.host/obuzelowit.yaml
SMP https://bin.bloom.host/ekezowaqam.yaml
Lobby https://bin.bloom.host/ikocikufiw.yaml

**Comment by AuroraLS3** [comment]
Sorry for not realizing to ask this sooner - Are are servers running Plan build 1690?

**Comment by AuroraLS3** [comment]
Ah I found the issue - The address is removed from cache before it's stored 🤦‍♀️
