### ISSUE TITLE
Problem with LibertyBans extension [Don't update data during server disable]

### ISSUE THREAD

**Issue by 1ntent1on** [plan-player-analytics/Plan#2432]
### Describe the issue

Having a problem with LibertyBans disabling before Plan.

### Exceptions & Other Logs

```
Warn - https://pastebin.com/WfCK3Z0f
Log 1 - https://pastebin.com/BuuHwEEy
Log 2 - https://pastebin.com/WifejTmj
```

### Plugin versions

Plan v5.4 build 1722
LibertyBans 1.0.1
### Additional information

Velocity 3.1.2-SNAPSHOT (git-74edac96-b153)
LibertyBans saves data into MariaDB, its completely fresh (there arent any ban data etc).

**Comment by AuroraLS3** [comment]
LibertyBans disabled before Plan so the correct way to deal with this is to prevent dataextension data updates from occuring during Plan shutdown.

**Comment by 1ntent1on** [comment]
Hello, so should i change "Wait_for_DB_Transactions_on_disable" value from default 20s to something else, or?

**Comment by AuroraLS3** [comment]
That probably doesn't help
