### ISSUE TITLE
[Feature Request]: Hiding tabcomplete commands if permission is set to false

### ISSUE THREAD

**Issue by 1ntent1on** [plan-player-analytics/Plan#2441]
### I would like to be able to..

Hello, i would like to ask if it was possible to hide tabcomplete commands. if main permission is set to false. 
Many other plugins are doing that, sadly Plan is not one of them yet.
Adding that makes chat more clear for players, as they dont see commands that are pointless for them, since they dont have perm for it anyway. 
Currently setting plan.* to false will let players still see commands such "/plan:p", "/planproxy" etc.

### Is your feature request related to a problem? Please describe.

Not related to any problem, just would make much cleaner chat for people without perms.

**Comment by AuroraLS3** [comment]
I'm unsure of the mechanism for doing this and it may differ for different platforms - what server(s) are you running?
