### ISSUE TITLE
Pterodactyl server and Plugins

### ISSUE THREAD

**Issue by Sterwim0ff** [plan-player-analytics/Plan#2460]
### Describe the issue
The problem is that if we have a pterodactyl server, we put the port of the server is well that tells us that it is already used when not. On the servers under the Pterodactyl panel it does this but server "diediated" everything works fine!

### Logs
![image](https://user-images.githubusercontent.com/108615437/177038690-f74e9b94-3a18-4eb0-a32a-6fe7d00c3fd2.png)

### Plugin versions
Lasted

**Comment by AuroraLS3** [comment]
Change `Webserver.Internal_IP` in Plan config back to `0.0.0.0` - It is causing "Cannot assign requested address" error
