### ISSUE TITLE
Function to Disable all unwanted in the WebUI

### ISSUE THREAD

**Issue by axiades** [plan-player-analytics/Plan#2466]
### I would like to be able to..

Hello,

i would Like to have a Function in the Config.yml to disable all Unwanted Sites from the WebUI

For Example i would like to Disable the Performance Site, GeoLocations, The Plugins Section and the Query Section on the Dashboard.

And the Function to Disable TPS Display in the Server Overview. 

And in the Player Overview i want to Disable PvP/PvE, Servers Overwiew and Plugins Section.

And The Function to Disable Average, best and Worst Ping display at the User Page

### Is your feature request related to a problem? Please describe.

No Its not Related to a Problem

**Comment by AuroraLS3** [comment]
Sort of the same thing as #1539 but with different features. I'll incorporate this to that one and close this as duplicate.
