### ISSUE TITLE
Suggestion: Show trendlines for each server in online activity

### ISSUE THREAD

**Issue by BrightSteel** [plan-player-analytics/Plan#2469]
### I would like to be able to..

So for bungeecorded networks, this is the current overview of player count totals
<img width="920" alt="Screen Shot 2022-07-07 at 11 55 39 PM" src="https://user-images.githubusercontent.com/11802079/177919839-9b1ce030-b2aa-4250-9178-50b87b381c45.png">

I would love to be able to see a trend line for each server individually in this view. It would make it much easier to compare the traffic between servers.

### Is your feature request related to a problem? Please describe.

Feature would be used to compare player traffic between servers in a network.

**Comment by AuroraLS3** [comment]
You can view this information by going to /network > Performance tab, selecting Players Online and selecting Proxy and servers you wish to view from the server selector

**Comment by BrightSteel** [comment]
I don't believe that the performance tab has players as an option?

**Comment by AuroraLS3** [comment]
Ah yep, I think that's good place to add it then. I assumed since it was the same table, but I guess it wasn't added

**Comment by AuroraLS3** [comment]
### TODO

- [ ] Add players online to Network Performance tab
  - [ ] Add query
  - [ ] Add endpoint
  - [ ] Add js code
