### ISSUE TITLE
[Suggestion] Floodgate (Geyser) support for Plan

### ISSUE THREAD

**Issue by ColdSight** [plan-player-analytics/Plan#2483]
### Data to display

Hello! Floodgate is a plugin for Geyser which allows Bedrock players to authenticate to Java servers without needing to purchase a Java Minecraft account. Currently, there is no Floodgate data in Plan, hence this suggestion.

Some good data that could be useful and helpful would be:
- Ratio of Java to Bedrock Players (Or do a pie system with %)
- Average playtime of Java & Bedrock players
- Possibly how many bedrock players have joined the server
- How many bedrock players have voted (if a votifier plugin is added and enabled)

This data would be helpful to server owners/managers to know more about bedrock players.

### Link to API or Source Code

https://wiki.geysermc.org/floodgate/api/

### Link to Project page or Downloads

https://geysermc.org/

**Comment by Kopo942** [comment]
https://github.com/plan-player-analytics/Extension-Floodgate ?

**Comment by ColdSight** [comment]
Oh didn't see that, thank you.

**Comment by Kopo942** [comment]
If the extension is not working for you (showing as enabled in the console after the Plan logo), please post the version of Plan, your server platform and Floodgate you're using so we can possibly troubleshoot this further.

**Comment by ColdSight** [comment]
It's currently not showing that the floodgate extension is enabled even though floodgate and plan are both installed on the proxy (Says nothing after Plan logo). (Even tried enabling it manually)

Plan Version: 5.4 build 1722
Proxy Platform: Velocity
Floodgate Version: 2.2.0-SNAPSHOT (b70-6e2c19f)

**Comment by Kopo942** [comment]
Ah, apparently the extension was never ported to Velocity 😅 I'll PR a fix, though since Aurora is taking a break from development, it might take a while for it to be merged.

**Comment by ColdSight** [comment]
Oh, I see... Yeah, no rush on that since I know Aurora is away. Is there any way to do it on a backend (paper) server?
