### ISSUE TITLE
Plan is trying to load a class from another plugin (Logger)

### ISSUE THREAD

**Issue by shimajima** [plan-player-analytics/Plan#2486]
### Describe the issue

Hello, we are trying to determine why Plan seems to be loading a class from the plugin Logger. Can you let us know why this is? Thank you so much!

### Exceptions & Other Logs

```
[15:57:18 WARN]: [Plan] Loaded class me.leoko.advancedban.Universal from Logger v1.8.0.2 which is not a depend or softdepend of this plugin.
```

### Plugin versions

Plan-5.4-build-1633
### Additional information

Paper 1.19

**Comment by Kopo942** [comment]
Plan's AdvancedBan extension is [looking for the class](https://github.com/plan-player-analytics/Extension-AdvancedBan/blob/35cbe6ca77bf18487d08d7a454090f992d610ae4/src/main/java/net/playeranalytics/extension/advancedban/AdvancedBanExtensionFactory.java#L47-L49) to determine if AdvancedBan is available.

However, in this case, the plugin "Logger" has incorrectly shaded the AdvancedBan API/plugin into its JAR without properly relocating it (eg. `abc.def.logger.libs.me.leoko.etc`). This not Plan's fault, but rather the aforementioned plugin's issue.

**Comment by Vankka** [comment]
> without properly relocating it

That plugin shouldn't be shading that API at all, the API is provided by AdvancedBan
