### ISSUE TITLE
CompletionException - SQL Grammar Error

### ISSUE THREAD

**Issue by KyGuy2002** [plan-player-analytics/Plan#2507]
### Describe the issue
[03:16:11 ERROR]: [Plan] Ran into CompletionException - logged to plugins/Plan/logs/CompletionException-9f9843c6f9.txt
[03:16:11 ERROR]: [Plan] (INCLUDE CONTENTS OF THE FILE IN ANY REPORTS)
[03:16:11 ERROR]: [Plan] What to do: Report this, there is an SQL grammar error.

### Exceptions & Other Logs
[CompletionException-9f9843c6f9.txt](https://github.com/plan-player-analytics/Plan/files/9186254/CompletionException-9f9843c6f9.txt)

### Plugin versions
Plan-5.4-build-1722

### Additional information
All my servers suddenly started spamming this.
Sorry if this is not the correct place to report this, I couldn't find any other means of contact.

**Comment by AuroraLS3** [comment]
Update all servers to the same version, one of the servers is using old version and reverted database schema changes

**Comment by KyGuy2002** [comment]
Makes sense, will try that asap.  Thx

**Comment by KyGuy2002** [comment]
Seems like that was it, thanks for the help!  Closing this issues
