### ISSUE TITLE
WebAuth login

### ISSUE THREAD

**Issue by LakyLuc** [plan-player-analytics/Plan#2512]
### I would like to be able to..

that users can connect a WebAuth device to their account and use WebAuth as login method so the users only need their username to login.

### Is your feature request related to a problem? Please describe.

This feature makes login faster and no longer requires a password for login.  Passwords do not have to be remembered for every single login.

**Comment by AuroraLS3** [comment]
The Jetty webserver used in Plan doesn't have support for WebAuth and the protocol seems complicated for me to implement.

Closing as out of scope.
