### ISSUE TITLE
Plan DEV 5.5 - Build 1793 using too much resources

### ISSUE THREAD

**Issue by iVillager** [plan-player-analytics/Plan#2521]
### Describe the issue
As we noticed after put the dev build 1793, Plan started to gain too much resources, causing lag to the entire network. 

### Exceptions & Other Logs
Spark profiler
https://spark.lucko.me/g86L75D24N

### Plugin versions
> Player Analytics
Version: 5.5 build 1793
Update Available: No
Current Database: MySQL (OPEN)
Connected to Proxy: Yes

**Comment by AuroraLS3** [comment]
What resources?

**Comment by iVillager** [comment]
CPU

**Comment by AuroraLS3** [comment]
I need a baseline to compare to to use this information
![image](https://user-images.githubusercontent.com/24460436/182894871-8dbce596-8553-49a5-87d4-9ffc7d2cb72b.png)

**Comment by AuroraLS3** [comment]
Please send some context for spark (I don't know how much is too much resources)

Closing until reply.
