### ISSUE TITLE
Kicks player when sending a message on the chat

### ISSUE THREAD

**Issue by Tresillo2017** [plan-player-analytics/Plan#2533]
### Describe the issue
Kicks player when types a messages on the chat (not commands)

### Exceptions & Other Logs
![image](https://user-images.githubusercontent.com/56476330/182895200-0189d238-39a1-4aca-a3ea-a04da8402998.png)

```
https://pastebin.com/raw/w48FwjQ5

```

### Plugin versions
5.4
Minercaft 1.19.1 fabric 0.14.8

### Additional information
Type on the chat

**Comment by AuroraLS3** [comment]
What build version

**Comment by AuroraLS3** [comment]
Try this build, it has 1.19.1 support https://github.com/plan-player-analytics/Plan/actions/runs/2794035358

**Comment by Tresillo2017** [comment]
Now works, thank you
