### ISSUE TITLE
A option to not-self-host the dashboard.

### ISSUE THREAD

**Issue by ANDREI12333** [plan-player-analytics/Plan#2545]
### I would like to be able to..

Enable a option, And you add a "secret-key" in the config, After this, you can go over to the dashboard, And you will see all of the analytics of the server.

### Is your feature request related to a problem? Please describe.

No, This feature is not related to a problem.

Thank you,
ANDREI12333_

**Comment by AuroraLS3** [comment]
It would need money to host somewhere. I don't have extra for this sort of thing.

To get payments I'd need to set up a subscription service that sets one up with accounts and all that - and I don't have time for that sort of thing.

Closing as out if scope.

**Comment by ANDREI12333** [comment]
Wow, It's not like i already got a better plugin, That doesn't close your issues without even replying.

**Comment by AuroraLS3** [comment]
This feature is out of scope of my resources. At least this way you know it won't get implemented.
