### ISSUE TITLE
The chart displayed on the homepage of Plan is incorrect

### ISSUE THREAD

**Issue by jiajiaxd** [plan-player-analytics/Plan#2552]
### Describe the issue
The chart displayed on the homepage of Plan is wrong
![image](https://user-images.githubusercontent.com/51043917/184862397-88dc534e-bd1b-41da-b01f-7d9caaef8b79.png)

What's more,the chart in the query page is correct
![image](https://user-images.githubusercontent.com/51043917/184862593-b4cd096d-2340-475d-bd7d-8fb3334ffd2e.png)

### Plugin versions
5.5 Build 1824

**Comment by AuroraLS3** [comment]
Double check that there are not two servers storing data for the same server uuid (You can check this by zooming in - If it oscillates between two values that means you have two servers set up to store data as one)

**Comment by AuroraLS3** [comment]
Note that Plan only supports one proxy server per database if this is on a network

**Comment by jiajiaxd** [comment]
My configuration is right,every server has a unique UUID
