### ISSUE TITLE
Plan is removing plan_user entries when new players join.

### ISSUE THREAD

**Issue by TreeOfSelf** [plan-player-analytics/Plan#2553]
### Describe the issue

The player count of my server is going down. The total amount of players is for whatever reason just going down when new people join.

### Plugin versions
Latest spigot release
5.4 build 1722

### Additional information
So I noticed on my website, I use PLAN to count the total unique players, and its way down
![image](https://user-images.githubusercontent.com/53889485/184914153-e4c907dc-391c-4c75-bc3b-a120ee5f6718.png)
1022? We celebrated 1000 players months ago. That can't be right.
![image](https://user-images.githubusercontent.com/53889485/184914221-d763e2c4-b40f-4fc8-9967-2af19525aca9.png)
same thing on the plan website.

I have an older screenshot from 7/25 showing a way higher player count
![image](https://user-images.githubusercontent.com/53889485/184914579-c490dca7-4716-408f-86da-99030ed68f5b.png)

So lovely, looks like PLAN managed to completely lose all of that data. I checked the database in an online db viewer and yep, its completely removing entries. Think this might just be the final nail in the coffin for me using PLAN, because this is pretty ridiculous. 
Yesterday it was at 1024, and 2 new players joined, so it looks like its just going down every time a player joins.

**Comment by TreeOfSelf** [comment]
Ok I see, you have it set to remove player data after 180 days by default. while I could see that being useful for huge servers, I think for 99% of servers that is just isn't needed. Please consider having it default to never removing data and having people manually set that limit themselves.

**Comment by AuroraLS3** [comment]
Increased default deletion threshold to 10 years

**Comment by AuroraLS3** [comment]
I get that finding out some data has been removed because of default configuration can be annoying, but saying it's a final nail in the coffin when I have not heard of any of other problems you have had is not very constructive.

**Comment by TreeOfSelf** [comment]
![GUD](https://user-images.githubusercontent.com/53889485/185005030-bbbc9677-8beb-49c6-a9f1-c489e8ffdd5f.gif)

**Comment by TreeOfSelf** [comment]
Nah you are right though I am being overly-dramatic. I honestly have no other way of recording player kills for my website. Thanks for the plugin.
