### ISSUE TITLE
Not usable on Velocity

### ISSUE THREAD

**Issue by SageSphinx63920** [plan-player-analytics/Plan#2557]
### Describe the issue

Yeah as the title says. I installed the latest version of the plugin and nothing really loaded. No graphs and the server pages just showed something like "Could not find row" idk exactly. Then i updated to the latest dev build because, i thought this issue may be fixed(The plugin was usable before the update), but now i can't even login. I even tried to delete the database. Nope doesn't change anything. There are no errors in the log. It also shows a ViaVersion error on every start, but that's just another issue.

### Exceptions & Other Logs

```
Nothing. Thats the problem
```

### Plugin versions

Plan is on the latest Dev build at the moment (1833). 
### Additional information

Plan is running on my proxy(latest velocity) and on my 2 backend server, both running latest version of purpur(fork of paper). I think it has to do something with the auth part so some more information about my setup: Im using nginx as reverse proxy and no ip-whitelist. The web interface worked (ok not really, because i couldn't view any data, but at least i managed to log in) in the latest release.

**Comment by SageSphinx63920** [comment]
I can provide any additional data, if needed :)

**Comment by AuroraLS3** [comment]
Reverse proxy was not passing query parameters to Plan
