### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [plan-player-analytics/Plan#2558]
### Data to display

Hello, i found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

Plan Plugin Version Plan-5.4-build-1722 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/Tl07oC3

Thanks :D

### Link to API or Source Code

https://github.com/games647/LagMonitor.git

### Link to Project page or Downloads

https://github.com/games647/LagMonitor

**Comment by AuroraLS3** [comment]
Unfortunately it is not possible to run this task asynchronously (I checked the code where this is done and there was a comment explaining why it's sync) Basically Spigot 1.14+ it will throw an error if this is tried to run async
```
        // Spigot 1.14 requires Sync events to be fired from a server thread.
        // Registering a service fires a sync event, and bStats registers a service,
        // so this has to be run on the server thread.
        runnableFactory.create(() -> new BStatsBukkit(plugin).registerMetrics()).runTask();
```
