### ISSUE TITLE
Cache/DNS issue

### ISSUE THREAD

**Issue by taylorhaight** [plan-player-analytics/Plan#2559]
## Describe the problem
It has been noted on a server I work on that we frequently run into an error where we have to change our DNS in order to get into plan and see the data. When the error occurs, nothing happens. So I will go to log in, and it just doesn't go any farther than that. It doesn't say my login was incorrect, or show an error message or anything. It just doesn't log me in.

### Plugin versions
Plan-5.5-dev-build-1833

### Additional information
I have personally only tried on Chrome and had tried clearing Cache/cookies before changing the DNS. While it is a minor inconvenience I just wanted to be sure you knew about it. No errors are thrown in game console when it occurs. I have also tried deregistering myself and reregistering for plan with no success.

**Comment by AuroraLS3** [comment]
This is rather confusing ticket - I think you may have left out some information.

Are you using Cloudflare? Is it caching something?
Is your server IP dynamic instead of static? (This could explain why you need to change DNS every now and then)

**Comment by SageSphinx63920** [comment]
I kinda have the same issue. I just used Firefox to connect and everything works fine.

**Comment by AuroraLS3** [comment]
Should be fixed in 5.5 build 1984 and above, there was an issue with cookie parsing when multiple cookies (such as cloudflare cookies) were present
