### ISSUE TITLE
Update Floodgate Extension

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2561]
### Describe the issue

Floodgate bukkit plugin was renamed to spigotplugin so it no longer registers the extension

https://github.com/plan-player-analytics/Extension-Floodgate

**Comment by SageSphinx63920** [comment]
Any updates on this?

**Comment by AuroraLS3** [comment]
No, it was opened 3 days ago and development is on hiatus until I get my thesis done
