### ISSUE TITLE
Plan shows too much user online time

### ISSUE THREAD

**Issue by Corvonn** [plan-player-analytics/Plan#2578]
### Describe the issue
Hi!
I have a small private network based on Waterfall, my servers run on Paper, the one in question on Paper 1.16.5. As the headline already shows, I have seen with one user that Plan shows him more online time than he really has. Specifically, we are talking about over 18 hours. But about the error:

I have a lobby, on which a user (as you know it) always logs in first. According to the schedule, the user in question was on the lobby last Saturday for a total of 18h and 34min. However, the logs speak against it. The time when he logs in according to the plan is correct, but this login process was apparently not finished properly, as the log shows: 
```
[18:25:04] [User Authenticator #240/INFO]: UUID of player ***** is *****
[18:25:04] [Server thread/INFO]: ***** lost connection: Disconnected
```
Apparently, however, Plan did not record this logout correctly and so, according to Plan, his session does not end until he logs back in and then logs out at 1pm the next day.
``` 
[13:00:02] [User Authenticator #241/INFO]: UUID of player ***** is *****
[13:00:02] [Server thread/INFO]: *****[/***.***.***.***:*****] logged in with entity id 7737 at ([world]0.2257904741113452, 157.61088005749346, -1.4466970923477491)
``` 

Greetings :D

### Plugin versions
5.4 build 1722

**Comment by AuroraLS3** [comment]
Thank you so much! You probably didn't know it when opening this ticket, but you have reported the source of a mystery bug that I haven't been able to wrap my head around for 3 years!

It looks like spigot may have either not fired the quit event, or the quit event was fired before the login event (since they occurred so close to each other)

**Comment by AuroraLS3** [comment]
Please try this dev release once it's available and let me know if it happens again https://github.com/plan-player-analytics/Plan/actions/runs/2961580965

**Comment by Corvonn** [comment]
Oh, I'm glad I could be of such help there :D
I have replaced the plugin on all my servers and keep an eye on it for the next few days, I'll get back to you as soon as the problem occurs again - or hopefully not xD

**Comment by AuroraLS3** [comment]
Last time this was reported was about 1.5 year ago or so, so might need to wait a while :D

**Comment by Corvonn** [comment]
Mhh, I dont think so. I looked at other players again and the problem did not seem to be an isolated case. In any case, I can not imagine what some players should do partly days on my lobby xD
