### ISSUE TITLE
Placeholders don't work

### ISSUE THREAD

**Issue by PanetiX** [plan-player-analytics/Plan#2579]
### Describe the issue
We use some placeholders like:

{#Cerulean} • {#Feijoa}Gesamte Spielzeit: {#Geyser}%plan_player_time_total%
{#Cerulean} • {#Feijoa}Lieblingsserver: {#Geyser}%plan_player_favorite_server%
{#Cerulean} • {#Feijoa}Registriert seit: %plan_player_registered%
{#Cerulean} • {#Feijoa}Getötete Spieler: %plan_player_kill_count%
{#Cerulean} • {#Feijoa}Gestorben: %plan_player_deaths%
{#Cerulean} • {#Feijoa}Getötete Mobs: %plan_player_mob_kill_count%
{#Cerulean} • {#Feijoa}Sitzungen: %plan_player_sessions_count%

But they don't work. For sure we use PlaceholderAPI. Other Placeholder works perfect.

### Plugin versions
5.4 build 1722

### Additional information
We use Plan Plugin on Bungee and all subservers. Works perfect since over 1 year.
Only Placeholders don't work (we just tried out at this time)

**Comment by AuroraLS3** [comment]
![image](https://user-images.githubusercontent.com/24460436/187690468-91c7deea-b6e1-44a3-85dc-820109cf613a.png)
https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI

**Comment by PanetiX** [comment]
I don't know what "Plugins.PlaceholderAPI.Load_these_placeholders_on_join" is :/
what exactly i need to do with that?

**Comment by AuroraLS3** [comment]
That setting should appear in the Plan config under Plugins

**Comment by PanetiX** [comment]
okay i'm in the config.yml from PLan Plugin. But where exactly i need to add "Plugins.PlaceholderAPI.Load_these_placeholders_on_join"?

**Comment by AuroraLS3** [comment]
If there already isn't a
```yml
Plugins:
    PlaceholderAPI:
        Load_these_placeholders_on_join:
            - %example_placeholder%
```
in your config then Plan has not detected PlaceholderAPI

**Comment by PanetiX** [comment]
Ahh okay. Yes i have this part. And there i need to add all Placeholders what i need?

**Comment by AuroraLS3** [comment]
In that list

**Comment by PanetiX** [comment]
Do i need to edit this on every Subserver?
Or can i install PlaceholderAPI Plugin on Proxy Server, too and place in the Plan cnofig from Proxy Server?

**Comment by AuroraLS3** [comment]
On the ones where you use specific placeholders (unfortunately PlaceholderAPI is only for game servers)

Note that you can also edit the server configs from /plugins/Plan/serverConfiguration on Bungeecord server

**Comment by PanetiX** [comment]
Okay so we have a Proxy Server there is Plan installed.
Then we have a Lobby Server without Plan Plugin installed.
On this Lobby Server we want to use the Placeholders from Plan Plugin.

So i need to install Plan Plugin on this Lobby Server, too to get the Placeholders to work?

**Comment by PanetiX** [comment]
Nice, i get this to work, thanks :)
Only the Placeholder %plan_player_kill_count% don't works.
But i set this like the other placeholders on config.yml

**Comment by PanetiX** [comment]
But Placeholders works only when i enter the command twice.
We have made a custom Alias like /account

It show this:

&2 Deine Account-Informationen:
{#Cerulean} •&l&m                                                &r{#Cerulean}•
{#Cerulean} • {#Feijoa}Spielername: {#Geyser}%cmi_user_name%
{#Cerulean} • {#Feijoa}Gesamte Spielzeit: {#Geyser}%plan_player_time_total%
{#Cerulean} • {#Feijoa}Lieblingsserver: {#Geyser}%plan_player_favorite_server%
{#Cerulean} • {#Feijoa}Registriert seit: {#Geyser}%plan_player_registered%
{#Cerulean} • {#Feijoa}Getötete Spieler: {#Geyser}%plan_player_player_kill_count%
{#Cerulean} • {#Feijoa}Gestorben: {#Geyser}%plan_player_deaths%
{#Cerulean} • {#Feijoa}Getötete Mobs: {#Geyser}%plan_player_mob_kill_count%
{#Cerulean} • {#Feijoa}Sitzungen: {#Geyser}%plan_player_sessions_count%
&r

But the informations would only be showed when a user enter thic command twice, why? :/

**Comment by Dreeam-qwq** [comment]
check https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI carefully, I think it can solve your problem.
