### ISSUE TITLE
In bungee mode, the sub-server port reports an error

### ISSUE THREAD

**Issue by FZDNSZYT** [plan-player-analytics/Plan#2629]
Here is the error log from the console
[error_log_1.txt](https://github.com/plan-player-analytics/Plan/files/9638238/error_log_1.txt)

**Comment by AuroraLS3** [comment]
Step 7, part 3 <https://github.com/plan-player-analytics/Plan/wiki/Bungee-Set-Up#step-7-set-up-plan-on-game-servers>

> Disable Plan webserver on this server by setting Webserver.Disable_Webserver to true
