### ISSUE TITLE
[Question] Migrating server to network

### ISSUE THREAD

**Issue by InoryS** [plan-player-analytics/Plan#2631]
I have an existing network and a standalone server.
Both have been running for a while each producing some data and I don't want to lose them.
The standalone server uses a sqlite database, and the network uses a mysql database.
Is there a way to merge the standalone server to the network? 
I tried /plan db move SQLite MySQL and watch the table, the data like player id is not consistent so I don't think it can be merged directly, thanks a lot.

**Comment by AuroraLS3** [comment]
There is no merge functionality at the moment, just moving from one to the other, overriding in the process - indeed because of the complexity of the ID differences.

If you move to Mysql from sqlite reload Plan on all servers afterwards.
