### ISSUE TITLE
Masonry layout doesn't update when plugin card size changes

### ISSUE THREAD

**Issue by AnttiMK** [plan-player-analytics/Plan#2637]
### Describe the issue
https://user-images.githubusercontent.com/13612979/193048667-3f629dde-0fde-4a20-9987-b6f34df6af30.mp4

### Plugin versions
5.5 build 1969

**Comment by Kopo942** [comment]
![image](https://user-images.githubusercontent.com/13612979/193067406-351cc24f-f338-44e8-9844-be4172cfd47b.png)
Additionally, the page selector sometimes overflows if the card isn't wide enough
