### ISSUE TITLE
ResolverSvc startsWith() causes funky behaviour

### ISSUE THREAD

**Issue by AnttiMK** [plan-player-analytics/Plan#2648]
### Describe the issue
https://github.com/plan-player-analytics/Plan/blob/8e170252785ba9d08a2653fc5d8e781965726c5e/Plan/common/src/main/java/com/djrapitops/plan/delivery/web/ResolverSvc.java#L50
Since Plan's resolver service uses `Predicate#startsWith()` to resolve requests, browsing pages like `/loginnnn`, `/networkkkk` etc. causes odd results. For example, if not logged in, `/loginnn` returns HTTP 200 with a blank page; if logged in, `/networkkkk` returns a 403.

### Plugin versions
5.5 build 1969

**Comment by AuroraLS3** [comment]
Ah I see it's likely an issue with the react router doing literal matching while the backend does more lenient one

**Comment by AuroraLS3** [comment]
This seems to no longer be an issue, react-router does a main page redirect to /network from /networkkkkk
