### ISSUE TITLE
404 page exposes "logged in" navbar when logged out

### ISSUE THREAD

**Issue by AnttiMK** [plan-player-analytics/Plan#2649]
### Describe the issue
![image](https://user-images.githubusercontent.com/13612979/193475420-533ba66e-478e-40a2-979a-b650455fbdc8.png)
title + image above. `<- to main page`, `logout` and `plugin version` should probably be hidden.

### Plugin versions
5.5 build 1969

**Comment by AuroraLS3** [comment]
Error page is still handled by old front-end code which doesn't know login status at the time of rendering.

This will be easy to sort out once it's moved to react side

**Comment by AuroraLS3** [comment]
Error page uses React version if frontend beta is enabled so I'll close this as completed even though it still happens with the old frontend.
