### ISSUE TITLE
Show the increase/decrease of players in geolocations tab

### ISSUE THREAD

**Issue by qbasty** [plan-player-analytics/Plan#2660]
### I would like to be able to..

Show the increase/decrease of players in geolocations tab. For example how many % you had from this country 30 days ago and how many now.

### Is your feature request related to a problem? Please describe.

This would be really useful to track from what countries your player-base is growing and where are the trends for your type of server

**Comment by AuroraLS3** [comment]
This is a bit complicated to visualize on a map. I'm pruning some good ideas that I just don't have time to implement so this ticket is closed.

It's currently possible to get this information using the Query page by using Played Between filter and making two different queries - and then comparing the map on the results page
