### ISSUE TITLE
The ability for returning player data to be readded to the dashboard

### ISSUE THREAD

**Issue by TypicalTropic** [plan-player-analytics/Plan#2682]
### I would like to be able to..

If a player was removed by plan and rejoins the analytics, it could be nice to have their history there. I am uncertain if this is good, but could it be done by adding a field to the user tab to not show the data on the frontend?

### Is your feature request related to a problem? Please describe.

Sometimes a user doesn't play for a while or leaves and comes back and it could be nice to still have their data be available on the panel

**Comment by AuroraLS3** [comment]
This can be achieved by changing `Remove_inactive_players_after` threshold to a high number - the default was changed to 10 years recently.
