### ISSUE TITLE
Pie chart for Server Activity in Network

### ISSUE THREAD

**Issue by AlexanderMoebius** [plan-player-analytics/Plan#2683]
### I would like to be able to..

It would be great to see how the online time divides to different servers in a network.
This way you can optimize bad servers or focus on the servers the player use the most.

### Is your feature request related to a problem? Please describe.

Currently you have to compare everything manually.

**Comment by AuroraLS3** [comment]
I think this is already on the sessions page but I might remember incorrectly, could you check? :)

**Comment by AlexanderMoebius** [comment]
Yes, sorry.
Totally missed this
