### ISSUE TITLE
A group is not updated instantly

### ISSUE THREAD

**Issue by sakulmore** [plan-player-analytics/Plan#2684]
### I would like to be able to..

Add a thing, if a player updates a group to a player (LuckPerms), the player does not have to connect to the server to update the group, but it is updated immediately after changing the group (without the need to connect to the server).

### Is your feature request related to a problem? Please describe.

When I set a player's group (https://i.imgur.com/9yFPlwQ.png), it doesn't update right away (https://i.imgur.com/OMFZ1Mh.png). It must connect to the server to keep it up to date.

**Comment by AuroraLS3** [comment]
Closing as duplicate #2269
