### ISSUE TITLE
Create monthly Top killers in game mode 

### ISSUE THREAD

**Issue by Testingit1265** [plan-player-analytics/Plan#2697]
### I would like to be able to..

Is there a way to show on the server the players with the most kills? I can find by individual user profile and total kills for the server, but I was looking for a top 10 players with most amount of kills.

***********Support response ********
I think a placeholder would be pretty simple to implement since top_playtime_month_{n} already existS

### Is your feature request related to a problem? Please describe.

Feature request only

**Comment by AuroraLS3** [comment]
Will be supported in build https://github.com/plan-player-analytics/Plan/actions/runs/3455360034
