### ISSUE TITLE
Discard join address data after \u0000 character

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#2710]
### Describe the issue

Something is sending IP in join address handshake packet separated by \u0000 character. Discard anything after that. character

### Plugin versions

5.5 build 1984

**Comment by AnttiMK** [comment]
https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java#L132-L135
