### ISSUE TITLE
[11:41:04 WARN]: [Plan] Database can't keep up with transactions (Queue size: 500), dropping some unimportant transactions from execution.

### ISSUE THREAD

**Issue by DimaSergeew** [plan-player-analytics/Plan#2718]
### Describe the issue

[11:41:04 WARN]: [Plan] Database can't keep up with transactions (Queue size: 500), dropping some unimportant transactions from execution.
keeps writing it in the console

```
https://mclo.gs/J5hLZqQ
```

### Plugin versions

Plan-5.5-build-1984

**Comment by AuroraLS3** [comment]
This can happen if there's a lot of write activity on the database - The queue starts dropping extension data updates to keep up with the data and things should normalize after that - so not a bug but intended behavior to keep things rolling, the warning is to notify server owners that it's happening so they can make a decision if they need to increase database capacity or disable some extensions in the Plan config

**Comment by DimaSergeew** [comment]
> This can happen if there's a lot of write activity on the database - The queue starts dropping extension data updates to keep up with the data and things should normalize after that - so not a bug but intended behavior to keep things rolling, the warning is to notify server owners that it's happening so they can make a decision if they need to increase database capacity or disable some extensions in the Plan config

Thanks, Can you make the plugin be able to take information from CMI?

**Comment by AuroraLS3** [comment]
No CMI doesn't have a proper API to do that
