### ISSUE TITLE
Add %plan_player_time_active_month%

### ISSUE THREAD

**Issue by jurohn** [plan-player-analytics/Plan#2721]
### I would like to be able to..

So, in my Holograms at my spawn, i display a 'top active playtime per month', to see the top players per month, ofcourse.
But on my scoreboard in the right of my screen, i display: 'plan_player_time_month'

This last value includes AFK time while i want to display the active time, for that player, for 30d.
Can you make it so there will be a placeholder for that? There is a placeholder for it per month for a top rank number (1-10) but not for the individual player currently.

### Is your feature request related to a problem? Please describe.

No, just an update.

**Comment by AuroraLS3** [comment]
`%plan_top_active_playtime_month_{n}_value%` (where `n` is 1-10) is already supported, so I guess you want `%plan_player_time_active_month%` to be added? :)

**Comment by AuroraLS3** [comment]
There will be a new build with following placeholders in 12 minutes here: https://github.com/plan-player-analytics/Plan/actions/runs/3455320055

- %plan_time_active_day%
- %plan_time_active_day_raw%
- %plan_time_active_week%
- %plan_time_active_week_raw%
- %plan_time_active_month%
- %plan_time_active_month_raw%

**Comment by jurohn** [comment]
Are you an ambulance or something? This was way to fast for any developer to respond and implement it. Thank you, great person!

**Comment by jurohn** [comment]
I see the build failed. Can i still test it or use it?

**Comment by AuroraLS3** [comment]
Yeah, it was just code style check that failed :)
