### ISSUE TITLE
Why can I access my Intranet address but not my public address

### ISSUE THREAD

**Issue by wodeshijei666** [plan-player-analytics/Plan#2722]
Why can I access my Intranet address but not my public address

**Comment by AuroraLS3** [comment]
Make sure you have routed your port correctly

- [Open port](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#step-3-open-port-from-firewall)
- [Allocating port if using Pterodactyl Panel](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#pterodactyl-panel)
- Also if you use Pterodactyl remember to restart the server after allocating the port

**Comment by wodeshijei666** [comment]
> 确保您已正确路由端口
> 
> * [开放端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#step-3-open-port-from-firewall)
> * [如果使用翼手龙面板，则分配端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#pterodactyl-panel)
> * 此外，如果您使用Pterodactyl，请记住在分配端口后重新启动服务器

I've got all the ports open

**Comment by wodeshijei666** [comment]
I've got all the ports open

**Comment by wodeshijei666** [comment]
Out of effect

**Comment by wodeshijei666** [comment]
> 确保您已正确路由端口
> 
> * [开放端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#step-3-open-port-from-firewall)
> * [如果使用翼手龙面板，则分配端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#pterodactyl-panel)
> * 此外，如果您使用翼手龙，请记住重新启动服务器后分配端

> > 确保您已正确路由端口
> > 
> > * [开放端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#step-3-open-port-from-firewall)
> > * [如果使用翼手龙面板，则分配端口](https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#pterodactyl-panel)
> > * 此外，如果您使用翼手龙，请记住重新启动服务器后分配端口
> 
> 我打开了所有端口
口
