### ISSUE TITLE
MultiLib#getLocalServerName Support in config.yml

### ISSUE THREAD

**Issue by Euphillya** [plan-player-analytics/Plan#2753]
### I would like to be able to..

For people using MultiPaper, we can afford to regularly delete the Plugin folder from the slave servers as everything reloads at startup, so there is no duplication. Unfortunately, we can't do this with Plan because we have to change the Name Server config in Plan every time. 

Would it be possible to put the possibility to integrate it directly like : 
```java
MultiLib.getLocalServerName().equalsIgnoreCase("bukkit")? <Server.ServerName> : MultiLib.getLocalServerName()
```

https://github.com/MultiPaper/MultiLib

### Is your feature request related to a problem? Please describe.

Not Really.

**Comment by AuroraLS3** [comment]
Does the new feature of being able to configure servername using environment variables solve this?

**Comment by Euphillya** [comment]
> Does the new feature of being able to configure servername using environment variables solve this?

I don't know, because we are using Folia now.

**Comment by AuroraLS3** [comment]
How is that related? 🤔

**Comment by Euphillya** [comment]
> How is that related? 🤔

I didn't know if work now on Mpp

**Comment by AuroraLS3** [comment]
Alright I'll close this and if someone has the same problem they can open a new ticket
