### ISSUE TITLE
Why could not support PowerNukkitX?

### ISSUE THREAD

**Issue by commandalan** [plan-player-analytics/Plan#2765]
### I would like to be able to..

Please support PowerNukkitX. Plan plugin has some error on PowerNukkitX.

### Is your feature request related to a problem? Please describe.

Emm,listener register failed.
And please add Cbinese .

**Comment by AnttiMK** [comment]
Please provide any error logs as a paste (eg. https://paste.gg), it's impossible to know why Plan isn't working without any available logs.

**Comment by commandalan** [comment]
oh,sorry,I reboot server to slove this problem
Emm,this plugin support Chinese?

**Comment by AuroraLS3** [comment]
https://github.com/plan-player-analytics/Plan/wiki/Localization
