### ISSUE TITLE
Playerbase Development data seams switched

### ISSUE THREAD

**Issue by Hutch79** [plan-player-analytics/Plan#2772]
### Describe the issue
It seams like the Data from the last 30 days and this week are switched.
![image](https://user-images.githubusercontent.com/42042811/206461613-fb0211ef-426a-4d79-9802-d60f0fe81700.png)

### Plugin versions
Newest version: 5.5 build 2100

### Additional information
I'm using the Frontent Beta

**Comment by AuroraLS3** [comment]
Thanks I'll check if that's the case :)

**Comment by AuroraLS3** [comment]
Fixed in the new release https://github.com/plan-player-analytics/Plan/releases/tag/5.5.2121

**Comment by Hutch79** [comment]
And i just updated plan an hour ago to 5.5 2100 XD
