### ISSUE TITLE
 NOT NULL constraint violation occurred.

### ISSUE THREAD

**Issue by jacklollz2** [plan-player-analytics/Plan#2785]
### Describe the issue
Occurred when launching the server.

### Exceptions & Other Logs
[CompletionException-a17737b791.txt](https://github.com/plan-player-analytics/Plan/files/10232155/CompletionException-a17737b791.txt)

### Plugin versions
Version: 5.5 build 2121

**Comment by AuroraLS3** [comment]
Does this happen every time?

**Comment by jacklollz2** [comment]
Yes, every server start

**Comment by AuroraLS3** [comment]
Could you send the ServerInfoFile.yml from the Plan folder?

**Comment by jacklollz2** [comment]
Latest build solved this problem.
