### ISSUE TITLE
500 Internal Error occurred

### ISSUE THREAD

**Issue by dwdsty** [plan-player-analytics/Plan#2798]
Playerbase -> Join Addresses

java.lang.NullPointerException: Cannot read field "json" because the return value of "com.djrapitops.plan.delivery.webserver.resolver.json.GraphsJSONResolver.getGraphJSON(com.djrapitops.plan.delivery.web.resolver.request.Request, com.djrapitops.plan.delivery.webserver.cache.DataID)" is null | Failed to get a response
    com.djrapitops.plan.delivery.webserver.resolver.json.GraphsJSONResolver.getResponse(GraphsJSONResolver.java:131)
    com.djrapitops.plan.delivery.webserver.resolver.json.GraphsJSONResolver.resolve(GraphsJSONResolver.java:120)
    com.djrapitops.plan.delivery.web.resolver.CompositeResolver.lambda$resolve$2(CompositeResolver.java:94)
    java.base/java.util.Optional.flatMap(Optional.java:289)
    com.djrapitops.plan.delivery.web.resolver.CompositeResolver.resolve(CompositeResolver.java:94)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.tryToGetResponse(ResponseResolver.java:221)
    com.djrapitops.plan.delivery.webserver.ResponseResolver.getResponse(ResponseResolver.java:172)
    com.djrapitops.plan.delivery.webserver.http.RequestHandler.lambda$attemptToResolve$0(RequestHandler.java:86)
    java.base/java.util.Optional.orElseGet(Optional.java:364)
    com.djrapitops.plan.delivery.webserver.http.RequestHandler.attemptToResolve(RequestHandler.java:86)
    com.djrapitops.plan.delivery.webserver.http.RequestHandler.getResponse(RequestHandler.java:68)
    com.djrapitops.plan.delivery.webserver.http.JettyRequestHandler.handle(JettyRequestHandler.java:64)
    plan.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
    plan.org.eclipse.jetty.server.Server.handle(Server.java:563)
    plan.org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
    plan.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
    plan.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
    plan.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
    plan.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
    plan.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
    plan.org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
    plan.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
    plan.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
    plan.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
    plan.org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
    plan.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
    plan.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
    plan.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
    java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AuroraLS3** [comment]
Is there another error prior to this? It sounds like another error occurred first and caused this one

**Comment by dwdsty** [comment]
After clicking on the blue link an error occurs which I have already discounted https://imgur.com/a/j78SKPu

**Comment by AuroraLS3** [comment]
Could you zip up /plugins/Plan/logs and attach it here

**Comment by dwdsty** [comment]
[logs.zip](https://github.com/plan-player-analytics/Plan/files/10288476/logs.zip)

**Comment by AuroraLS3** [comment]
This is what the error log say

> SQLite database is corrupt, restore database.db, .db-shm & .db-wal files from a backup, or repair the database: See https://wordpress.semnaitik.com/repair-sqlite-database/.

This can sometimes happen if Plan is updated using PlugMan or if the server running the older version is not shut down with `stop` before starting with the new version

**Comment by AuroraLS3** [comment]
Closing this ticket since there are no actions that I can take to fix the SQLite corruption.
