### ISSUE TITLE
Players' activity placeholder changed

### ISSUE THREAD

**Issue by Bloodlex** [plan-player-analytics/Plan#2802]
### Describe the issue
After updating to the newest Plan version, a placeholder responsible for players' activity (%plan_player_activity_index%) returns much different values than before. Players who had quite high activity now have even below 1 for instance 0.9. I don't know why this has been changed and what could be the issue.

### Plugin versions
5.5 build 2144

**Comment by AuroraLS3** [comment]
Does the index match what they have on their player pages? The activity index queries have not changed, so some of the playtime data for those players may have gone outside the 'last 3 weeks' window

**Comment by Bloodlex** [comment]
> Does the index match what they have on their player pages? The activity index queries have not changed, so some of the playtime data for those players may have gone outside the 'last 3 weeks' window

Hey, here you have some examples, where you can notice this difference:

Player list:
![image](https://user-images.githubusercontent.com/1086720/209430160-3ed3f608-25b9-4e7f-a9cd-f14cbc60fe75.png)

Player profile:
![image](https://user-images.githubusercontent.com/1086720/209430174-0291c55c-223e-45c8-8f0c-32155ccab900.png)

Placeholder:
![image](https://user-images.githubusercontent.com/1086720/209430514-a9f9c278-d97b-4099-85db-82132c76c4db.png)

I asked you some time ago about query which would return me the activity and I use it on my page and I get the same result as in player list (the higher one).

I hadn't noticed this discrepancy ever before. Do you have some idea for that?

**Comment by AuroraLS3** [comment]
The player page and placeholder use Java code to calculate the index while the player list uses the query - Is this on a network or single game server?

**Comment by Bloodlex** [comment]
> The player page and placeholder use Java code to calculate the index while the player list uses the query - Is this on a network or single game server?

It's a single game server and Plan is connected to external database on another machine. It was all right before, and suddenly it changed and now seems like it's reversed or something like that.

**Comment by AuroraLS3** [comment]
I'll have to write more tests before I know what's going on

**Comment by Bloodlex** [comment]
> I'll have to write more tests before I know what's going on

I'd be very grateful for that 🙂. My players are very interested in checking their activity index 🤣.

**Comment by AuroraLS3** [comment]
Fixed in build 2150

**Comment by Bloodlex** [comment]
> Fixed in build 2150

Yes, it works, thank you very much 🙂.
