### ISSUE TITLE
Error 404 in Google Chrome

### ISSUE THREAD

**Issue by SGirl-Zockt** [plan-player-analytics/Plan#2821]
### Describe the issue
I have install a SSL Cert insite Plan, and then i get a 404 Not Found in Google Chrome but whit order Brwoser it work normal

### Exceptions & Other Logs

```
Logs Folder is Empty
```

### Plugin versions
Plan-5.5-build-2163.jar

### Additional information
I use a Cert from GoDaddy

**Comment by SGirl-Zockt** [comment]
[https://www.directupload.net/file/d/6790/mopbl8cg_jpg.htm](Screenshot)

**Comment by AuroraLS3** [comment]
Try clearing the chrome browser cache, I could not reproduce the issue

**Comment by SGirl-Zockt** [comment]
I have and now it works, tank you
