### ISSUE TITLE
Create a Security Advisory

### ISSUE THREAD

**Issue by KaspianDev** [plan-player-analytics/Plan#2831]
### I would like to be able to..

You can use [this github feature](https://github.com/plan-player-analytics/Plan/security/advisories/new) to keep track of vulnerabilities. Even tho I never used it thankfully, it should be pretty straight forward.

### Is your feature request related to a problem? Please describe.

.

**Comment by AuroraLS3** [comment]
https://github.com/plan-player-analytics/Plan/security/advisories/GHSA-mcq3-5hhm-75rx
