### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by dwdsty** [plan-player-analytics/Plan#2833]
[placeholder-errors.log](https://github.com/plan-player-analytics/Plan/files/10420574/placeholder-errors.log)

What's the problem?

**Comment by AuroraLS3** [comment]
Sounds like Plan was updated without restarting the server with something like PlugMan (This is not supported) or the .jar file deleted while the server was running

**Comment by AuroraLS3** [comment]
A restart should fix it

**Comment by dwdsty** [comment]
Before I loaded the plugin, I turned off all the servers. Then I turned on the servers, then restarted the server and the error appears. I did not use Plugman.
[placeholder-errors.log](https://github.com/plan-player-analytics/Plan/files/10421128/placeholder-errors.log)

**Comment by AuroraLS3** [comment]
The issue is that spigot has unloaded the plugin jar partially (and closed the file read access to the jar file)

There may be errors early in the startup log that indicate why that happened

**Comment by dwdsty** [comment]
No errors, I wonder what the problem is

**Comment by AuroraLS3** [comment]
I would try re-downloading the jar

**Comment by dwdsty** [comment]
I already tried it, it didn't work

**Comment by AuroraLS3** [comment]
Are you using old Java version? 🤔 5.5 requires Java 11 or higher - Here's the last build of 5.4 https://github.com/plan-player-analytics/Plan/releases/tag/5.4.1722.1 if you can't update from Java 8 for some reason

**Comment by dwdsty** [comment]
I use Java 17

**Comment by AuroraLS3** [comment]
I'm very confused - Could you send logs that shows where Plan enables

**Comment by AuroraLS3** [comment]
Alright, it might be useful to take solving this issue on Discord https://discordapp.com/invite/yXKmjzT

**Comment by dwdsty** [comment]
[logs.zip](https://github.com/plan-player-analytics/Plan/files/10427782/logs.zip)

**Comment by AuroraLS3** [comment]
The errors in the zip suggest database could not be connected to

**Comment by AuroraLS3** [comment]
New build with the fix will appear here in 12 minutes https://github.com/plan-player-analytics/Plan/actions/runs/3940945944
