### ISSUE TITLE
Autocreate Plan Accounts once Discord account linked (DiscordSRV)

### ISSUE THREAD

**Issue by Exophobias** [plan-player-analytics/Plan#2852]
### I would like to be able to..

Add further integration with DiscordSRV so that on user-link, it creates a Plan user account with a randomly generated password and the bot DMs the user. If the DM fails, it messages an admin, sends an MSG ingame, or creates a private ticket with the user.

### Is your feature request related to a problem? Please describe.

No

**Comment by AuroraLS3** [comment]
I'll have to check if the user linking has access to player permissions at the time of linking

**Comment by Vankka** [comment]
> I'll have to check if the user linking has access to player permissions at the time of linking

The player is not guaranteed to be online at the time of linking

**Comment by Exophobias** [comment]
> > I'll have to check if the user linking has access to player permissions at the time of linking
> 
> The player is not guaranteed to be online at the time of linking

Well, they have to at least join the server as they have to do /discord link

**Comment by AuroraLS3** [comment]
I guess there could be a default group to assign users created through this so that permission check is not mandatory.

This'll need #1623 first

**Comment by Vankka** [comment]
> Well, they have to at least join the server as they have to do /discord link

Not when required linking is enabled (linking.yml), they just get kicked with the linking code when that's enabled
