### ISSUE TITLE
Discord Growth Charts

### ISSUE THREAD

**Issue by Exophobias** [plan-player-analytics/Plan#2853]
### I would like to be able to..

I have been using https://statbot.net/ recently but I think it would be nice to have an all-in-one solution which tracks the growth of a Discord server, or even Discord servers (if multiple).

And possibly do some similar stuff where it also tracks usage of chats, engagement, etc.

### Is your feature request related to a problem? Please describe.

N/A

**Comment by AuroraLS3** [comment]
Tracking discord usage is out of scope for this plugin
