### ISSUE TITLE
Database failed

### ISSUE THREAD

**Issue by Arturo0359** [plan-player-analytics/Plan#2863]
https://sourceb.in/PKYN4X1iO6
1.19.2 
The data is correctly entered

**Comment by AuroraLS3** [comment]
If you have a lot of servers starting at the same time, the MySQL could have gotten overwhelmed by the server startup
A ladder startup where each server starts one after another might help if this is the case.

The error says that MySQL didn't give a new connection in 30 seconds. You can try increasing max connections setting in mysql https://stackoverflow.com/a/22297829/20825073
