### ISSUE TITLE
Player name got auto-translated

### ISSUE THREAD

**Issue by Glucy-2** [plan-player-analytics/Plan#2885]
### Describe the issue

Player name got auto-translated
![image](https://user-images.githubusercontent.com/53287753/220411143-d1f611d1-9595-4c9d-9528-5c07baf49298.png)
![image](https://user-images.githubusercontent.com/53287753/220411566-c0de5d34-b125-4f4c-91a3-039e288750b1.png)

In the player page, some parts in the player name are auto-translated.
As the images showed, player name `AllenXH` was translated to `全部enXH`, replacing `All` with `全部`(meaning all in Chinese), player name `0qxServer` was translated to `0qx服务器`, replacing `Server` with `服务器`(meaning server in Chinese)

### Exceptions & Other Logs

```
(No logs related.)
```

### Plugin versions

5.5 build 2172

**Comment by AuroraLS3** [comment]
Try enabling Frontend_BETA in the config - should sort it out

**Comment by Glucy-2** [comment]
OK it works, thank you.
