### ISSUE TITLE
Sql connection timed out

### ISSUE THREAD

**Issue by waiching514** [plan-player-analytics/Plan#2895]
### Describe the issue
cannot connecting the sql servers
### Exceptions & Other Logs
e0d97d8c8d - Last occurred: 2023-03-01 Occurrences: 1
---- Context 1 ----
Plan v5.5 build 2172
BungeeCord git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:dca72c2:511
Server vgit:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:dca72c2:511

Transaction: class com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch
DB State: CLOSED - fatal: true
Error code: 0
SELECT COUNT(*) as c FROM plan_join_address WHERE INSTR(join_address, CHAR(0))
Unknown SQL Error code

---- Stacktrace ----
java.util.concurrent.CompletionException: com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch failed to execute and database could not be opened: SQL Failure: Plan Connection Pool-2 - Connection is not available, request timed out after 30000ms.
   java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
   java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
Caused by:
com.djrapitops.plan.exceptions.database.FatalDBException: com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch failed to execute and database could not be opened: SQL Failure: Plan Connection Pool-2 - Connection is not available, request timed out after 30000ms.
   com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:41)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$4(SQLDB.java:347)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:61)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:56)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$5(SQLDB.java:346)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
Caused by:
java.sql.SQLTransientConnectionException: Plan Connection Pool-2 - Connection is not available, request timed out after 30000ms.
   plan.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
   plan.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
   plan.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
   com.djrapitops.plan.storage.database.MySQLDB.getConnection(MySQLDB.java:167)
   com.djrapitops.plan.storage.database.queries.QueryStatement.executeQuery(QueryStatement.java:51)
   com.djrapitops.plan.storage.database.SQLDB.lambda$query$2(SQLDB.java:323)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:102)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:87)
   com.djrapitops.plan.storage.database.SQLDB.query(SQLDB.java:323)
   com.djrapitops.plan.storage.database.Database.queryOptional(Database.java:61)
   com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch.lambda$hasBadAddressIds$3(BadJoinAddressDataCorrectionPatch.java:120)
   com.djrapitops.plan.storage.database.SQLDB.lambda$queryWithinTransaction$3(SQLDB.java:327)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:96)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:91)
   com.djrapitops.plan.storage.database.SQLDB.queryWithinTransaction(SQLDB.java:327)
   com.djrapitops.plan.storage.database.transactions.Transaction.query(Transaction.java:209)
   com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch.hasBadAddressIds(BadJoinAddressDataCorrectionPatch.java:120)
   com.djrapitops.plan.storage.database.transactions.patches.BadJoinAddressDataCorrectionPatch.hasBeenApplied(BadJoinAddressDataCorrectionPatch.java:46)
   com.djrapitops.plan.storage.database.transactions.patches.Patch.shouldBeExecuted(Patch.java:54)
   com.djrapitops.plan.storage.database.transactions.Transaction.executeTransaction(Transaction.java:84)
   com.djrapitops.plan.storage.database.transactions.init.OperationCriticalTransaction.executeTransaction(OperationCriticalTransaction.java:36)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$4(SQLDB.java:347)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:61)
   com.djrapitops.plan.storage.database.DBAccessLock.performDatabaseOperation(DBAccessLock.java:56)
   com.djrapitops.plan.storage.database.SQLDB.lambda$executeTransaction$5(SQLDB.java:346)
   java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
   java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   java.base/java.lang.Thread.run(Thread.java:829)
   com.djrapitops.plan.storage.database.SQLDB.executeTransaction(SQLDB.java:336)
   com.djrapitops.plan.storage.database.SQLDB.setupDatabase(SQLDB.java:262)
   com.djrapitops.plan.storage.database.SQLDB.init(SQLDB.java:157)
   com.djrapitops.plan.storage.database.DBSystem.enable(DBSystem.java:103)
   com.djrapitops.plan.PlanSystem.enableSystems(PlanSystem.java:225)
   com.djrapitops.plan.PlanSystem.enableOtherThanCommands(PlanSystem.java:182)
   com.djrapitops.plan.PlanSystem.enable(PlanSystem.java:220)
   com.djrapitops.plan.PlanBungee.onEnable(PlanBungee.java:70)
   com.djrapitops.plan.commands.subcommands.PluginStatusCommands.lambda$onReload$0(PluginStatusCommands.java:72)
   java.base/java.lang.Thread.run(Thread.java:829)

### Plugin versions
5.5 2172 build

**Comment by AuroraLS3** [comment]
Do you have a lot of servers starting at the same time? That can cause high load on the database. You can start one at a time with a ladder reboot to reduce load

**Comment by waiching514** [comment]
I tried deleted all thing is same

**Comment by AuroraLS3** [comment]
Sorry for the delay, the database doesn't have enough connections or isn't responding

**Comment by AuroraLS3** [comment]
Please leave a comment if you're still having issues and I'll reopen this.
