### ISSUE TITLE
Network > Servers not showing players online graph

### ISSUE THREAD

**Issue by Ari24-cb24** [plan-player-analytics/Plan#2908]
### Describe the issue
When visiting `/network/serversOverview`, react tries to render the `PlayersOnlineGraph` component. This usually accepts `data` as a dictionary with the key `playersOnline` which works fine for the homepage analytics but not for `serversOverview` as here only the array with the actual data gets passed.

PlayersOnlineGraph.js
```js
useEffect(() => {
        if (!data) return;
        const playersOnlineSeries = {
            name: t('html.label.playersOnline'),
            type: 'areaspline',
            tooltip: tooltip.zeroDecimals,
            data: data.playersOnline,
            color: data.color,
            yAxis: 0
        }
```

since `data.playersOnline` is undefined, the LineGraph component simply renders "No Data to Display".

### Exceptions & Other Logs
None

### Plugin versions
Plan-Version: 5.5.2272

**Comment by AuroraLS3** [comment]
Thanks for the report, I'll fix this asap

**Comment by AuroraLS3** [comment]
Build will appear here in 15 minutes https://github.com/plan-player-analytics/Plan/actions/runs/4381640662
