### ISSUE TITLE
Error when trying to run the command to export my certificate

### ISSUE THREAD

**Issue by Ragemalik** [plan-player-analytics/Plan#2920]
Hello I am trying to set up SSL for my site. I was looking at the wiki and I am on step 4.2 on https://github.com/plan-player-analytics/Plan/wiki/SSL-Certificate-%28HTTPS%29-Set-Up and when I try run `> openssl pkcs12 -export \
-in /etc/letsencrypt/live/<domain>/fullchain.pem \
-inkey /etc/letsencrypt/live/<domain>/privkey.pem \
-out /etc/letsencrypt/live/<domain>/pkcs.p12 \
-name <alias> \
-passout pass:<password> \
-passin pass:<password>` I get a few errors in consoles saying some of these are not commands I've tried removing the backslashes tried making it a whole line of a command remove the > at the start removed the hyphens but no luck at all (I have replaced the stuff where I need to) I have openssl installed and I am using ubuntu 20.0.4

**Comment by AuroraLS3** [comment]
Could you send the error it gives

Here's the one liner in case it was the back slashes 
```
openssl pkcs12 -export  -in /etc/letsencrypt/live/<domain>/fullchain.pem  -inkey /etc/letsencrypt/live/<domain>/privkey.pem  -out /etc/letsencrypt/live/<domain>/pkcs.p12  -name <alias>  -passout pass:<password>  -passin pass:<password>
```

**Comment by Ragemalik** [comment]
Appreciate it my friend my site now has SSL!
