### ISSUE TITLE
Invalid join time

### ISSUE THREAD

**Issue by K0dziaK** [plan-player-analytics/Plan#2934]
### Describe the issue

For some reason the join date is 1970 year which causes regular players malfunction
![obraz_2023-03-22_231500072](https://user-images.githubusercontent.com/32880560/227050569-eeb370c0-348e-4f11-a883-d2de49b69e91.png)
![obraz_2023-03-22_231507308](https://user-images.githubusercontent.com/32880560/227050589-9d7847db-2b9b-45e7-b8f7-7ce335a37a04.png)

### Exceptions & Other Logs

```

```

### Plugin versions

Plan-5.5-build-2272

**Comment by AuroraLS3** [comment]
What type of server is this?

**Comment by AuroraLS3** [comment]
Okay the player metadata stored in the world data is probably bugged for some reason
