### ISSUE TITLE
Player Retention page [Custom locale files not updated automatically]

### ISSUE THREAD

**Issue by SageSphinx63920** [plan-player-analytics/Plan#2949]
### Describe the issue

On the player retention pages the plugin still shows the raw html objects like `html.label.retention.timeStep`

### Exceptions & Other Logs
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/69404127/227963614-bf6f5c27-3212-4799-a1a0-c29d8a0d82f5.png">

### Plugin versions

Plan: latest(2307)

**Comment by AuroraLS3** [comment]
Looks like the custom locale file was not updated with new lines
