### ISSUE TITLE
Typo Report

### ISSUE THREAD

**Issue by HyperfireRS** [plan-player-analytics/Plan#2979]
**Wiki page to modify**: Supported Plugins

### Suggested modifications
Vulcan Anticheat has a typo: it's spelled Vulkan with a K, not Vulcan with a C.

### Additional context
None

**Comment by Jaren8r** [comment]
No it's not..?

https://www.spigotmc.org/resources/vulcan-anti-cheat-advanced-cheat-detection-1-7-1-19-4.83626/
https://www.spigotmc.org/resources/plan-extension-vulcan.109400/

Both pages spell it as Vulcan.

**Comment by AuroraLS3** [comment]
Closing without changes :)

**Comment by Jaren8r** [comment]
@AuroraLS3 Whoops, I made a mistake. I assumed that the wiki was already changed by this issue (judging by the 👍 reaction), but i'm realizing i'm wrong by looking at the last edited date. I believe OP meant to say that Vulkan should be switched to Vulcan, and not the other way around.

**Comment by AuroraLS3** [comment]
Ah I see, sorted it out.
