### ISSUE TITLE
DBOpException-82d37f2caa

### ISSUE THREAD

**Issue by Haui1112** [plan-player-analytics/Plan#3002]
### Describe the issue
I imported the plan_player_time_active_day placeholder in tablist and it spammed my whole log with exceptions. Took me a second to find the culprit.

### Exceptions & Other Logs
```
82d37f2caa - Last occurred: 2023-05-01 Occurrences: 3
---- Context 3 ----
Plan v5.5 build 2307
Paper git-Paper-61 (MC: 1.19)
Server v1.19-R0.1-SNAPSHOT

Report this
Placeholder Request
player_time_active_day
6b350cd6-c38d-4c32-8f30-b5434da7935f
Error code: 0
SELECT plan_user_info.registered,banned,opped,uuid,join_address FROM plan_user_info JOIN plan_servers s on s.id=plan_user_info.server_id WHERE plan_user_info.user_id=(SELECT plan_users.id FROM plan_users WHERE plan_users.uuid=? LIMIT 1)
Unknown SQL Error code

---- Context 2 ----
Plan v5.5 build 2307
Paper git-Paper-61 (MC: 1.19)
Server v1.19-R0.1-SNAPSHOT

Report this
Placeholder Request
player_time_active_day
6b350cd6-c38d-4c32-8f30-b5434da7935f
Error code: 0
SELECT plan_user_info.registered,banned,opped,uuid,join_address FROM plan_user_info JOIN plan_servers s on s.id=plan_user_info.server_id WHERE plan_user_info.user_id=(SELECT plan_users.id FROM plan_users WHERE plan_users.uuid=? LIMIT 1)
Unknown SQL Error code

---- Context 1 ----
Plan v5.5 build 2307
Paper git-Paper-61 (MC: 1.19)
Server v1.19-R0.1-SNAPSHOT

Report this
Placeholder Request
player_time_active_day
6b350cd6-c38d-4c32-8f30-b5434da7935f
Error code: 0
SELECT plan_user_info.registered,banned,opped,uuid,join_address FROM plan_user_info JOIN plan_servers s on s.id=plan_user_info.server_id WHERE plan_user_info.user_id=(SELECT plan_users.id FROM plan_users WHERE plan_users.uuid=? LIMIT 1)
Unknown SQL Error code


```

### Plugin versions
Plan 5.5 build 2307
Tablist 5.7.0
PlaceholderAPI 2.11.3

### Additional information
I was trying to find interesting information to display on the tablist. Since Plan is able to do afk display, I figured I'd try others.

**Comment by AuroraLS3** [comment]
Exception stacktrace is missing from the file

**Comment by Haui1112** [comment]
Here's the file
[Uploading DataExtensionMethodCallException-6c30805907.txt…]()

**Comment by Haui1112** [comment]
I don't know what the issue was. Here it is again.
[DataExtensionMethodCallException-6c30805907.txt](https://github.com/plan-player-analytics/Plan/files/11399651/DataExtensionMethodCallException-6c30805907.txt)

**Comment by AuroraLS3** [comment]
It appears that Gringotts may have shut down during the method call which caused the exception

**Comment by Haui1112** [comment]
Interesting! Anything I can do to help? Hasn't happened again since I deleted the placeholder from tablist.

**Comment by AuroraLS3** [comment]
The exception is unrelated to the placeholder, I think this one can be safely ignored since it is essentially gringotts improperly handling InterruptedException (The correct action to InterruptedException is to interrupt the thread instead of throwing an exception as they did)

**Comment by AuroraLS3** [comment]
Oh sorry I didn't notice but you sent different error file than what you originally reported
Ticket title says `DBOpException-82d37f2caa` but you sent `DataExtensionMethodCallException-6c30805907`

**Comment by Haui1112** [comment]
Hm. I just sent you what I had. These two were in the folder. I assumed you needed these. Did I do anything wrong?

**Comment by AuroraLS3** [comment]
If the error isn't there anymore no worries. If it happens again feel free to open another ticket.
I just don't have enough information to know what the issue with the placeholder was
