### ISSUE TITLE
SunLight support

### ISSUE THREAD

**Issue by xGranolah** [plan-player-analytics/Plan#3033]
https://www.spigotmc.org/resources/sunlight-best-essentials-cmi-alternative.67733/

I think the plugin has great potential and should be supported by PA.

**Comment by AuroraLS3** [comment]
Please reopen the plug in suggestion with the correct template to include what kind of data you want to see from the plug in https://github.com/plan-player-analytics/Plan/issues/new?assignees=&labels=New+Data%2CDataExtensions%2CHelp+Wanted&projects=&template=plugin_request.yml
