### ISSUE TITLE
Reorder join addresses

### ISSUE THREAD

**Issue by sebastiaannnn** [plan-player-analytics/Plan#3037]
### I would like to be able to..

please add the ability to see the most joined domains from high to low, if you have over 100 different join domains its impossible to track with the current system. 

Link to discord suggestion including screenshots:
https://discord.com/channels/364107873267089409/364111201346781195/1111383900263034880

### Is your feature request related to a problem? Please describe.

Its currently not possible to check your domains, there are too much and you can't scale it. Its impossible to manage because the current circel one also resets

**Comment by AuroraLS3** [comment]
Could you send a copy of HOSTNAME_PIE.json and JOIN_ADDRESSES.json from /plugins/Plan/json_cache so that I can use the real world data to design a better viewer for this amount of data
