### ISSUE TITLE
Time is Wrong

### ISSUE THREAD

**Issue by SGirl-Zockt** [plan-player-analytics/Plan#3040]
### Describe the issue
At the Moment we have 17:30 but Plan say we have 16:57 time

### Exceptions & Other Logs

```
The Log folder is Empty
```

### Plugin versions
You have version 5.5 build 2391.

### Additional information
Server OS: Debian 10
MC Version: Paper 1.19.4
Server Clock is correct on my Time 17:30
I use Plan whit the External Webserver Use: Web files

**Comment by AuroraLS3** [comment]
You can increase the frequency Plan updates the files under Export config. By default the files are updated once per hour.
