### ISSUE TITLE
Liteban integration

### ISSUE THREAD

**Issue by corrysamu** [plan-player-analytics/Plan#3041]
### Describe the issue

it doesn't show the list of sanctions, it shows some old ones and not the new ones

### Exceptions & Other Logs

```

```

**Comment by AuroraLS3** [comment]
Have the new sanctions become visible after waiting?
Could you send some screen shots?
Are there any errors in Plan logs folder?

**Comment by corrysamu** [comment]
no have not appeared yet if you do not update since April 1, there is no error, plan and liteban are updated to the latest version
![image](https://github.com/plan-player-analytics/Plan/assets/100021699/5d67de79-7ccd-4102-a49b-d2d752446414)

**Comment by AuroraLS3** [comment]
Is the litebans extebsiob enabled for the server in the plan config?

**Comment by AuroraLS3** [comment]
Looks like the error is about multiple servers trying to update the litebans data at the same time. If you have multiple servers I recommend starting them one by one instead of all at once

**Comment by corrysamu** [comment]
I have 6 servers connected, at the next full reboot I will try to start them one at a time

**Comment by AuroraLS3** [comment]
Did that resolve the issue?

**Comment by corrysamu** [comment]
no, I have 6 servers connected to my proxy and I can't start 1 server at a time, I periodically restart the whole network

**Comment by AuroraLS3** [comment]
You can try disabling Litebans integration in the Plan config on the game servers and leaving it on in the proxy

**Comment by corrysamu** [comment]
this is already the case, liteban is only in the proxy, and in the config it is also like this

**Comment by AuroraLS3** [comment]
Root cause analysis of another ticket #3227 shows that the periodical extension data update task is not working on a proxy server, follow that issue for resolution to this
