### ISSUE TITLE
About the Japanese-language file

### ISSUE THREAD

**Issue by ZaemonGames** [plan-player-analytics/Plan#3074]
### I would like to be able to..

Web Server: No Certificate Exists -> Use HTTP Server
The Japanese in the log is incorrect.
存在ません→存在しません

### Is your feature request related to a problem? Please describe.

ConsoleLog

**Comment by AuroraLS3** [comment]
Is the given japanese text the correct translation? (I don't know japanese)

**Comment by lis2a** [comment]
lt is correct japanese.
