### ISSUE TITLE
[Plugin data table] sorting is incorrect

### ISSUE THREAD

**Issue by Jcodeerd** [plan-player-analytics/Plan#3079]
### Describe the issue

it looks like Buycraft/Litebans are sorted by characters and not actually chronologically
![image](https://github.com/plan-player-analytics/Plan/assets/68161666/2d0531f2-40cc-4486-b670-59e4ff83c2ad)

### Exceptions & Other Logs

n/a

### Plugin versions

Plan 5.5 build 2391

**Comment by AuroraLS3** [comment]
Looks like some shortcuts were taken when porting to React and the table sorting raw value is missing.

**Comment by AuroraLS3** [comment]
Turns out that the extension code for Buycraft was not utilizing the new APIs for table formatting so it was storing the formatted value in the database, preventing sorting
