### ISSUE TITLE
Data loading takes too much time

### ISSUE THREAD

**Issue by exosmium** [plan-player-analytics/Plan#3080]
### Description

When i've updated to new Plan version data loading on website board started to take from 10 seconds to couple of miuntes.

### Plugin versions
Last version: 5.5 build 2391

**Comment by AuroraLS3** [comment]
Are there any errors on the browser console (Ctrl+Shift+I > Console) when you open the page?

Which data is loading slowly?

**Comment by AuroraLS3** [comment]
Closing as stale

**Comment by exosmium** [comment]
Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/css/main.88bade62.css
URL карты кода: main.88bade62.css.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/main.798a6872.js
URL карты кода: main.798a6872.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/2445.f274daf8.chunk.js
URL карты кода: 2445.f274daf8.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/9930.f3644f74.chunk.js
URL карты кода: 9930.f3644f74.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/460.348ad76d.chunk.js
URL карты кода: 460.348ad76d.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/8023.e946b5a4.chunk.js
URL карты кода: 8023.e946b5a4.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/4032.15f230d3.chunk.js
URL карты кода: 4032.15f230d3.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/611.dfdaea63.chunk.js
URL карты кода: 611.dfdaea63.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/8619.83570ad2.chunk.js
URL карты кода: 8619.83570ad2.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/8596.b8ec8b71.chunk.js
URL карты кода: 8596.b8ec8b71.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/8197.c5d8d2cb.chunk.js
URL карты кода: 8197.c5d8d2cb.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/5193.8c660f6c.chunk.js
URL карты кода: 5193.8c660f6c.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/2457.3a21c3a6.chunk.js
URL карты кода: 2457.3a21c3a6.chunk.js.map

Ошибка карты кода: Error: request failed with status 404
URL ресурса: http://play.dynamitemc.ru:8804/static/js/8002.54606a35.chunk.js
URL карты кода: 8002.54606a35.chunk.js.map

**Comment by exosmium** [comment]
```
Object { stack: "B@http://play.dynamitemc.ru:8804/static/js/main.798a6872.js:2:1866917\n31243/xc.xhr</</s.onabort@http://play.dynamitemc.ru:8804/static/js/main.798a6872.js:2:1881971\n", message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest }
[main.798a6872.js:2:18595](http://play.dynamitemc.ru:8804/static/js/main.798a6872.js)
Object { status: undefined, message: "Request aborted", url: "/v1/extensionData?server=a1d34e3e-5d63-4ee4-a448-060cce93952a" }
[611.dfdaea63.chunk.js:1:2016](http://play.dynamitemc.ru:8804/static/js/611.dfdaea63.chunk.js)
Object { stack: "B@http://play.dynamitemc.ru:8804/static/js/main.798a6872.js:2:1866917\n31243/xc.xhr</</s.onabort@http://play.dynamitemc.ru:8804/static/js/main.798a6872.js:2:1881971\n", message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest }
[main.798a6872.js:2:18595](http://play.dynamitemc.ru:8804/static/js/main.798a6872.js)
Object { status: undefined, message: "Request aborted", url: "/v1/serverOverview?server=a1d34e3e-5d63-4ee4-a448-060cce93952a"``
```

**Comment by AuroraLS3** [comment]
ECONNABORTED suggests that a firewall or another piece of software blocked the request.

404 suggests that some file is missing - if you use export I suggest re-exporting,
if you use html customization, rebuild the bundle,
if you use neither, download and re-upload the jar again

**Comment by AuroraLS3** [comment]
If you use a reverse proxy there is some configuration error.

Another possibility is that Plan Webserver.Alternative_IP does not point to the correct address

**Comment by exosmium** [comment]
public_html folder is empty. is it okay?

**Comment by exosmium** [comment]
Nothing worked for me, i do not use export, i do not use custom html, i've redownloaded the jar. No reverse proxy and Webserver.Alternative_IP is disabled. Loading takes up to 1 minute and sometimes doesn't work at all. On firewall 8804 is open.

**Comment by AuroraLS3** [comment]
Alright I checked the page and it seems like the server is returning old timestamps, which may be leading to the issue.

Here are instructions how to synchronize system clock on the server to resolve the issue
https://github.com/plan-player-analytics/Plan/discussions/2389

In addition there were some errors related to MySQL connection being unstable. You can try to increase MySQL stability by reducing `Database.MySQL.Max_Lifetime` setting in the Plan config
