### ISSUE TITLE
Failed to start MySQL: Failed to initialize pool: Unknown system variable 'transaction_isolation' [MariaDB 11 breaks MySQL compatibilty]

### ISSUE THREAD

**Issue by jacklollz2** [plan-player-analytics/Plan#3091]
### Describe the issue
Plan Failed to initialize pool at launch.

### Exceptions & Other Logs
[19:15:39 ERROR]: [Plan] ----------------------------------------
[19:15:39 ERROR]: [Plan] Error: Failed to start MySQL: Failed to initialize pool: Unknown system variable 'transaction_isolation'
[19:15:39 ERROR]: [Plan] ----------------------------------------
[19:15:39 ERROR]: [Plan] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload

### Plugin versions
5.5 DEV build 2411

### Additional information
MariaDB v11
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode)
Oracle Linux 8

**Comment by AuroraLS3** [comment]
I think MariaDB 11 breaks compatibility with MySQL

**Comment by jacklollz2** [comment]
> I think MariaDB 11 breaks compatibility with MySQL

MariaDB is faster than MySQL anyway, I want proper support for it.
LuckPerms does a great job with MariaDB support.

**Comment by AuroraLS3** [comment]
I tried updating to MariaDB 11 on my local machine and it completely nuked itself so fixing this will take a while.

**Comment by AuroraLS3** [comment]
Debugging the exception, MySQL driver uses version string to determine which transaction_isolation variable to use:
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/45708b59-c85d-4353-bf82-4480c9fac4ca)
Unfortunately MariaDB now uses `tx_isolation` in version 11 and 11 > 8 so the MySQL Driver is incompatible with the MariaDB version.

**Comment by AuroraLS3** [comment]
I got the driver working, but MariaDB 11.0.2 inserts wrong data in a batch statement
```
INSERT INTO plan_world_times (
session_id,
world_id,
user_id,
server_id,
survival_time,
creative_time,
adventure_time,
spectator_time
) VALUES ( 
(SELECT plan_sessions.id FROM plan_sessions WHERE plan_sessions.user_id=(SELECT plan_users.id FROM plan_users WHERE plan_users.uuid=? LIMIT 1) AND plan_sessions.server_id=(SELECT plan_servers.id FROM plan_servers WHERE plan_servers.uuid=? LIMIT 1) AND session_start=? AND session_end=? LIMIT 1),
(SELECT plan_worlds.id FROM plan_worlds WHERE world_name=? AND plan_worlds.server_uuid=? LIMIT 1),
(SELECT plan_users.id FROM plan_users WHERE plan_users.uuid=? LIMIT 1),
(SELECT plan_servers.id FROM plan_servers WHERE plan_servers.uuid=? LIMIT 1),
?, ?, ?, ?)
```
It inserts same world_id for 2 different worlds which then fails just about every session related test.
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/40e169d5-140e-43e3-ace0-5a25a1488e18)

**Comment by AuroraLS3** [comment]
MariaDB 11 seems to not be production ready. I recommend sticking with LTS version 10.11.4

**Comment by AuroraLS3** [comment]
11.1.1 seems to work fine with unit tests.
