### ISSUE TITLE
Server shutdown causes AFK time to not track properly

### ISSUE THREAD

**Issue by heavenlyfiend43** [plan-player-analytics/Plan#3099]
### Describe the issue

When a player is AFK when the server is restarted or otherwise stops, their AFK time is not properly tracked as Plan doesn't track it as the player having logged out. Players also do not have logs generated of them being disconnected when they are AFK. This player logged in, immediately went AFK and stayed online and AFK for 5 hours until server restart disconnected them. However, there are no logs of any disconnect from them at any point.

### Exceptions & Other Logs
```
[Thu 04:11:05 INFO  Server/PlayerList] Hlokk logged in at ([world]6333.480445161834, 110.0, -8927.978245568382)
```
![image](https://github.com/plan-player-analytics/Plan/assets/122650997/e9ff8181-a3d0-4f31-a1cd-9be707ef3444)

### Plugin versions
Plan: 5.5-build-2391
AdvancedAFK-2.0-18

### Additional information
Server information
- Server: Purpur Build #2000
- Database: MySQL

Happy to provide additional logs/info as needed

**Comment by AuroraLS3** [comment]
The session data that is ongoing during a shutdown will be stored during next boot - I'll check if afk data is updated though
