### ISSUE TITLE
Plan fabric mod uses default refmap.json name, leading to clashes with other mods having the default name

### ISSUE THREAD

**Issue by onebeastchris** [plan-player-analytics/Plan#3106]
### Describe the issue
upon opening the jar with 7zip: 
![image](https://github.com/plan-player-analytics/Plan/assets/105284508/6f8777bd-0021-43cd-bc0d-5ac19a610329)

This causes issues with other mods that also for some reason have the default name; like up until now Geyser-Fabric (https://github.com/GeyserMC/Geyser/issues/3423). The fix would be setting the name to include the modid; thereby ensuring that the name of the refmap isnt the default. Thanks to LlamaLad7 and Benonardo from the fabric discord (https://ptb.discord.com/channels/507304429255393322/807617700734042122/1126930434949922907).

### Exceptions & Other Logs
e.g. https://paste.gg/p/anonymous/cd19bfb33a5d4c6e8d0aa8e90ba8131a

### Plugin versions
fabric mod

### Additional information
Bug was/will be fixed in Geyser here https://github.com/GeyserMC/Geyser/pull/3950/commits/3f991b16da046ed11881244df43cc2d576f9b2bd - replicating the same/setting the project name to something other than "fabric" for the fabric module should work aswell.

**Comment by AuroraLS3** [comment]
Thanks for the information, I appreciate it!
