### ISSUE TITLE
Plan Throwing Errors on Player Quit

### ISSUE THREAD

**Issue by bipedd** [plan-player-analytics/Plan#3112]
### Describe the issue

When players quit errors pop up in my console, see below

### Exceptions & Other Logs

plugins/Plan/logs:
 https://mclo.gs/Rg4t2nj

```
Console error: https://mclo.gs/TkUuVcG
```

### Plugin versions

Plan 5.5 Build 2391
### Additional information

Tried uninstalling the plugin and reinstalling, as well as regenerating folder

**Comment by AuroraLS3** [comment]
Duplicate of https://github.com/plan-player-analytics/Plan/issues/3098 - downgrade to paper 62
