### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by overload08** [plan-player-analytics/Plan#3141]
### I would like to be able to..

It would be nice to add capability to add comments on player page

### Is your feature request related to a problem? Please describe.

Nope

**Comment by overload08** [comment]
We have a discord server and both pseudo are not the same. 
I would like to add these discord pseudos to recognize them

**Comment by AuroraLS3** [comment]
You can use DiscordSRV to link users, Plan will show data from DiscordSRV

**Comment by overload08** [comment]
I'll try, thank's !
