### ISSUE TITLE
Placeholder Bug Report

### ISSUE THREAD

**Issue by Hamsterliebe** [plan-player-analytics/Plan#3174]
### Describe the issue

The Placeholder "%plan_top_playtime_total_10_value%" does not work. It dont gets parsed.

----

%plan_player_time_total% and %plan_top_playtime_total_1_value% dont have the same value, even tho there is only 1 player with a total time on over 1 day. (see https://media.discordapp.net/attachments/466241867797889054/1142625101473390611/image.png)

### Exceptions & Other Logs

```

```

### Plugin versions

5.5 build 2461

**Comment by AuroraLS3** [comment]
Fixed in 8356a0d52e624cb2317312d7b7d02d8d3865ac96
