### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by 7AGAM** [plan-player-analytics/Plan#3226]
### Describe the issue
I see fewer Total Players in the dashboard than there are in the database under plan_users.

### Plugin versions
5.5 build 2461

**Comment by AuroraLS3** [comment]
Could you send a screenshot of the whole page where this happens

**Comment by 7AGAM** [comment]
> Could you send a screenshot of the whole page where this happens

![Screenshot_20230924_112657_Samsung Internet.jpg](https://github.com/plan-player-analytics/Plan/assets/78796797/769dce23-4c33-4201-85b0-6d11d3fae6c1)

Total Players says 507. But in the database there are 623 entries in the plan_users table. So 623 users and sometimes the total player count also goes down.

**Comment by AuroraLS3** [comment]
- Are you using export? (I was hoping to see the whole screenshot from a PC to tell this)
- Are you sure that this is your panel and not another Plan instance running on the same host? (You can ensure this by changing `Network.Name` in the Plan config on bungee, the change should be reflected on the website after `/planproxy reload`)

**Comment by 7AGAM** [comment]
![Screenshot 2023-09-24 193516](https://github.com/plan-player-analytics/Plan/assets/78796797/48a3b462-2eb1-49f1-a021-081754824a03)

Sorry, here is a screenshot of the whole screen. I am sure that this is my panel because of my login datas.

**Comment by AuroraLS3** [comment]
I'm not really sure what is going on. Is `Thresholds.Remove_Inactive_Players_After` setting set as less than 90 days?

Does the number happen to be the same on one of the game servers? (If you switch to one from the compass) - Maybe the data was loaded on a /server page and then upon switching to /network page it didn't switch out the data to be of the whole network 🤔

Does the number become correct if you refresh the page?

**Comment by 7AGAM** [comment]
Thresholds.Remove_Inactive_Players_After is set to over 90. The number is not the same as on a game server. Updating doesn't help either.

**Comment by AuroraLS3** [comment]
One thing to try would be to clear the json cache - remove all files in `/plugins/Plan/cached_json`.

If that doesn't help, could you send me the result of these SQL queries:
```sql
SELECT COUNT(*) FROM plan_users;
SELECT COUNT(1) FROM plan_users;
SELECT COUNT(*) FROM plan_user_info;
SELECT COUNT(1) FROM plan_user_info;
```

**Comment by 7AGAM** [comment]
Nothing has changed.
These are the results of the Sql queries:

SELECT COUNT(*) FROM plan_users
507


SELECT COUNT(1) FROM plan_users

507


SELECT COUNT(*) FROM plan_user_info

556


SELECT COUNT(1) FROM plan_user_info
556


But is it normal that there are up to 625 ids in plan_users if SELECT COUNT(*) FROM plan_users
507 coming out?

**Comment by AuroraLS3** [comment]
Yes the id can vary since when players are removed the id keeps increasing anyway. You need to use `COUNT(*)` to tell how many entries are in a table.

I'll close this as solved since it was a misunderstanding on how databases store ids
