### ISSUE TITLE
ViaVersion not working

### ISSUE THREAD

**Issue by qbasty** [plan-player-analytics/Plan#3227]
### Describe the issue
https://cdn.discordapp.com/attachments/466241867797889054/1155844927025066025/ad9267cc942c6e117b29111a0f39e1ac.png
Both if it's installed on velocity or on paper.

### Exceptions & Other Logs

```

```

### Plugin versions

> planvelocity info
[16:24:34 INFO]: > Player Analytics
[16:24:34 INFO]: 
[16:24:34 INFO]:   Version: 5.6 build 2542
[16:24:34 INFO]:   Update Available: No
[16:24:34 INFO]:   Current Database: MySQL (OPEN)
[16:24:34 INFO]:   Connected to Proxy: Yes
[16:24:34 INFO]:   Server UUID: 4bf4c091-a358-48db-8cef-d47260e159f0
[16:24:34 INFO]: 
[16:24:34 INFO]: >

**Comment by AuroraLS3** [comment]
It appears that the query for the data is not returning data even though there is data in the database, so no worries, the data is still being gathered even though it is not showing up. Easier to fix at least

**Comment by AuroraLS3** [comment]
Okay so further looking into this it appears that proxy servers are affected, but a Paper server did update the data

**Comment by AuroraLS3** [comment]
Alright so the query looks for data in plan_user_info to know the server_id, but for proxy that data is not stored.
```
SELECT protocol_version, COUNT(1) as count" +
                " FROM plan_version_protocol" +
                " INNER JOIN plan_users on plan_version_protocol.uuid=plan_users.uuid" +
                " INNER JOIN plan_user_info on plan_user_info.user_id=plan_users.id" +
                " WHERE plan_user_info.server_id=(SELECT id FROM plan_servers WHERE uuid=?)" +
                " GROUP BY protocol_version
```
This is why game servers work but proxies don't
