### ISSUE TITLE
Not able to login to Plan web page due to "SQL Failure: Column 'permission_level' not found"

### ISSUE THREAD

**Issue by cloakfox** [plan-player-analytics/Plan#3230]
### Describe the issue
I can no longer access the analytics web page, it doesn't allow me to login, no exceptions or errors are displayed on the web page itself. (it's just unresponsive)

When trying to run "planbungee users" in the bungee console this error is show "[10:51:24 WARN] [Plan]: Error msg: "SQL Failure: Column 'permission_level' not found.""

### Exceptions & Other Logs
Entire error log: https://gist.github.com/cloakfox/a3a941f80958838d4bedb6c1f4d245a2

### Plugin versions
[10:57:57 INFO]:   Version: 5.5 build 2461
[10:57:57 INFO]:   Update Available: No
[10:57:57 INFO]:   Current Database: MySQL (OPEN)
[10:57:57 INFO]:   Connected to Proxy: Yes

### Additional information
This randomly happened, I think the database somehow got messed up, not sure how I managed to do that.

**Comment by AuroraLS3** [comment]
Version 5.6 removes the column on question. Make sure to update all servers possible
