### ISSUE TITLE
Players will be deleted.

### ISSUE THREAD

**Issue by 7AGAM** [plan-player-analytics/Plan#3241]
### Describe the issue
Yesterday I had 520 registered players and now suddenly only 479 and when I look under cached_json under players there are also 520 listed. I set "Remove_inactive_player_data_after" to 5000 days in the settings. The server doesn't exist yet. Why do I still have fewer players in the database?

### Plugin versions
Plan 5.5 build 2461

**Comment by AuroraLS3** [comment]
Any 5.4 versions have the old default value for the setting

**Comment by 7AGAM** [comment]
Ok I found one server which has 90 days to delete datas. Can I restore the deleted data?

**Comment by AuroraLS3** [comment]
If you have a backup yes

**Comment by 7AGAM** [comment]
I mean whether you can restore the data in the cached_json folder.

**Comment by AuroraLS3** [comment]
No that data is a view of the sql queries and doesn't include raw data to restore
