### ISSUE TITLE
Random 0 under the session value 

### ISSUE THREAD

**Issue by Josh65-2201** [plan-player-analytics/Plan#3252]
### Describe the issue

Under Server overview > Sessions there a random 0
![image](https://github.com/plan-player-analytics/Plan/assets/26977075/b44b6e79-e11e-4aab-8160-a1419a570f16)

### Exceptions & Other Logs

```

```

### Plugin versions

5.6 dev build 2574

**Comment by AuroraLS3** [comment]
Alright I'll take care of it - This happens when some component has a condition for showing it and it's a number instead of a boolean - I sometimes forget to convert it
