### ISSUE TITLE
Redesign Join Address visualization

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#3268]
### I would like to be able to..

Analyze what join addresses players are using, in order to:

- Track ad campaigns with specific address
- Track server lists with specific address
- See what addresses are bringing in most **new** vs **returning** players over time

In order to do this I would need to be able to:

- Filter by join address
- Differentiate between new and returning joins
- Compare different addresses
- Group multiple addresses together

The join address filter needs to be also added to Retention graph when grouping by Join Address.

This ticket replaces #2832

### Is your feature request related to a problem? Please describe.

After four test sessions it became quite apparent how broken the current join address visualization is
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/dcbb1892-bda0-4efd-924d-ab2d55d6a7d2)

The visualizer gives the impression that both visualizers use 'players' as the unit, but Join Addresses uses 'session count' and Latest Join Addresses uses 'players'

When you reach 10 or more Join Addresses the join address visualizer becomes unreadable due to the legend:
![image](https://github.com/plan-player-analytics/Plan/assets/24460436/600068de-e76c-4bd9-aebd-5ecf6a87ee24)

The server owner doesn't do anything with Latest Join Addresses, it's quite meaningless & its calculation time is slow. Only reason to even have it is to have a list of all join addresses being used.

----

The join address visualization is currently in this state because at the time of implementing it for the first time the UI did not have very good filtering capabilities.

**Comment by Nashlord** [comment]
Is there any chance this will ever happen? That would be amazing
