### ISSUE TITLE
Seeing wrong server in player analytics?

### ISSUE THREAD

**Issue by loshgg** [plan-player-analytics/Plan#3281]
Hi there,

I just went look at my server analytics and noticed the server I'm viewing is not mine. I'm unsure why this was happening as it was working fine before. I was using build 2461 and just updated to 2614 and that did not seem to help.

I did recently make my server a network using Bungee, so maybe that could be why? I did also install RedisBungee. Any help on this would be much appreciated!

**Comment by AuroraLS3** [comment]
You could try changing the web server port you're using - I've seen people on shared hosts ask about panel that isn't theirs on discord and usually the case is that it actually wasn't theirs 😅
