### ISSUE TITLE
Vulcan integration not working

### ISSUE THREAD

**Issue by freddycor** [plan-player-analytics/Plan#3321]
Hi, I'm writing here because I have a problem with Plan, precisely with Vulcan integration.

My Plan version is the last one 5.6, and Vulcan is on (2.7.7)
I'm on PaperSpigot 1.8.8 with Java11

The problem is that in Vulcan tab on Plan webpage it shows "no data"
![image](https://github.com/plan-player-analytics/Plan/assets/22725942/b45289c7-ac31-4ec4-81f8-6a4ac327e288)

Is there a way to fix it?

Thanks in advance

**Comment by freddycor** [comment]
I realised that I needed to enable "api" on Vulcan Config file

**Comment by AuroraLS3** [comment]
Vulcan Extension is also not maintained by me :)
