### ISSUE TITLE
Data is a day behind [in the calendar with negative timezone]

### ISSUE THREAD

**Issue by Subnet-Masked** [plan-player-analytics/Plan#3328]
### Describe the issue
On the web interface, the time beside the refresh button says the correct time but says "Yesterday", and on the calendar pages the data is a day behind as well. It is reporting data on the 24th, I installed the plugin on the 25th.

### Exceptions & Other Logs

```

```

### Plugin versions
5.6-2614

### Additional information

Timezone is America/New_York (Currently EST)

![image](https://github.com/plan-player-analytics/Plan/assets/55600371/ed553b45-bbd6-4800-b6bc-fb37f55282a8)

Output from timedatectl on the server
```
[subnet@mcserver ~]$ timedatectl
               Local time: Sun 2023-11-26 01:19:58 EST
           Universal time: Sun 2023-11-26 06:19:58 UTC
                 RTC time: Sun 2023-11-26 06:19:58
                Time zone: America/New_York (EST, -0500)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by AuroraLS3** [comment]
The calendar issue is a known bug, I haven't been able to sort it out yet https://github.com/plan-player-analytics/Plan/issues/1239

I guess the Today/Yesterday is using wrong time for start of day

**Comment by AuroraLS3** [comment]
I have new hypothesis that the browser timezone is moving the timestamp that's 00:00 UTC to the previous day

**Comment by AuroraLS3** [comment]
I'll close this as a duplicate, the hypothesis was incorrect and the original ticket has more discussion.
