### ISSUE TITLE
error when shutting down the server (purpur) saving data in (velocity)

### ISSUE THREAD

**Issue by sk98q** [plan-player-analytics/Plan#3330]
### Describe the issue

**I was on the server, I had played 39 minutes to the total time. The total time was 50 minutes.

I decided to install another plugin, and the total time flew off when the server was turned off. The player's data was not saved and reset to zero before the previous visits.**

### Exceptions & Other Logs

logs clear.

```
**logs clear. no create - server shutting in button "close"**
```

### Plugin versions

**latest**

### Additional information

server purpur (latest) 1.18.2

plugins:
LP
LiteBans

plugins instal:
essentials.
![image (1)](https://github.com/plan-player-analytics/Plan/assets/102253444/b0616ff8-9ae8-4ebc-bc21-66292c7cce29)

**Comment by AuroraLS3** [comment]
If storing sessions fails during shutdown they're saved next time the server starts - are there any errors during the next enable after shutdown?

**Comment by AuroraLS3** [comment]
Did the server that the player was on have Plan installed?

**Comment by AuroraLS3** [comment]
Closing as stale
