### ISSUE TITLE
Plan is not working with lastest Quests plugin (the quests module)

### ISSUE THREAD

**Issue by pjindras** [plan-player-analytics/Plan#3347]
### Describe the issue
I have the latest version of Quests plugin and unfortunately, it is not working with plan hook, even if its enabled.

### Exceptions & Other Logs
I can paste a full log if it's necessary, but there is no specific error, the issue must be definitely that the quests plugin had big changes in a new version.

### Plugin versions
PLAN v5.6 build 2614
Quests v5.0.0-rc.3-b437

### Additional information
I can provide all you need.

**Comment by AuroraLS3** [comment]
Quests has not released an API artifact for 5.0.0 in the Maven repository so I can't fix this until they make a full release
