### ISSUE TITLE
top_player_kills_total_{n}_value placeholder returning wrong value

### ISSUE THREAD

**Issue by nickynice1** [plan-player-analytics/Plan#3369]
### Describe the issue
I am using %plan_top_player_kills_total_{n}_value% on my server and only value I get is "0s". 

### Plugin versions
5.6 build 2614

**Comment by AuroraLS3** [comment]
Does anybody have player kills?

**Comment by nickynice1** [comment]
Yeah there are some players with kills. The strange this is that is says "0s". I don't understand where the "s" comes from.

**Comment by AuroraLS3** [comment]
It's probably a leftover from copying the code from top playtime placeholders
