### ISSUE TITLE
Sessions [show IP]

### ISSUE THREAD

**Issue by TeamPaml** [plan-player-analytics/Plan#3370]
### I would like to be able to..

We would like to see one new thing in the player report in the -Sessions- section that we could see, also the IP address through which the player connected at that time.
That is, we could see Server, Session Started, Length, Most played World, [we would also like to see the IP address they connected through at that time].

### Is your feature request related to a problem? Please describe.

This would speed up the resolution of reports and issues, and we'd be more accurate in banning for rule violations.

**Comment by TeamPaml** [comment]
I mean player machine IP.

**Comment by AuroraLS3** [comment]
Player IP is personally identifiable data according to GDPR and I don't want to deal with that (It would need either consent or legal basis for collection).

**Comment by TeamPaml** [comment]
Well we understand your reasons, so we can also secure this collection through other plugins and login, we just found it better to have everything in one place and tell the player right away that when he got banned he was connected through a different IP as usual, which could mean that someone else got on the account and we could solve it with an IP ban and not the whole nick because the player could have been innocent, but we accept your opinion and thank you for the quick reply and otherwise we are very happy with your plugins.
