### ISSUE TITLE
Server Set-Up Inaccuracy With Actual Required Acts

### ISSUE THREAD

**Issue by TwiteCrive** [plan-player-analytics/Plan#3372]
**Wiki page to modify**: https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up

### Suggested modifications

Change instructions from reloading the plugin to restarting the server. Reloading the plugin does _not_ actually allow access as described in Part 2 or Part 5, as per both my own personal experience and theitalianman's on Discord (where I found the solution for my problem), their messages surrounding [this messages](https://discord.com/channels/364107873267089409/364111201346781195/1186635851057344614) 

### Additional context

Alternative would be to fix the reload command, but the plugin still works you just have to restart instead so that's your decision.

**Comment by AuroraLS3** [comment]
If you're using pterodactyl a restart is required as stated in the pterodactyl section.

**Comment by crivvlo** [comment]
> If you're using pterodactyl a restart is required as stated in the pterodactyl section.

I'm not using Pterodactyl.

**Comment by AuroraLS3** [comment]
I am in a bad mood today and unable to receive any criticism, I'll consider this another time.

**Comment by AuroraLS3** [comment]
Another shot in the dark is that fabric was in use and bug #3392 caused the reload to be unavailable
