### ISSUE TITLE
Commands do not work

### ISSUE THREAD

**Issue by L3G1T1SM3** [plan-player-analytics/Plan#3392]
### Describe the issue

/plan and other plan related commands do not show in game, even with op privileges. Server is accessible and tracks playertime and stats as expected. 

No logs are had, and only feedback within server console is/in game:
"Unknown or incomplete command, see below for error
plan reload<--[HERE]"

### Exceptions & Other Logs

```

```

### Plugin versions

Statech modpack version 1.11.1, PlanFabric-5.5-build-2391, Java Version JDK 21, Fabric loader:0.14.22, Fabric installer: 0.11.2. Minecraft version 1.19.2
### Additional information

Tried commands from OP in game and from the server console.

**Comment by AuroraLS3** [comment]
I guess the fabric command api has changed

**Comment by AuroraLS3** [comment]
This can happen if:
- Fabric API isn't installed as a mod https://www.curseforge.com/minecraft/mc-mods/fabric-api
- Plan doesn't enable completely due to an error during the enable (This was fixed now)
