### ISSUE TITLE
Bedrock Client Latency Tracking via Geyser

### ISSUE THREAD

**Issue by DrHuckinJohn** [plan-player-analytics/Plan#3395]
### I would like to be able to..

I would like to be able to more accurately track/log Bedrock players' latency/ping like is done for Java players when running a Java+Geyser server. 

### Is your feature request related to a problem? Please describe.

On the server I administer, my player base is nearly 100% connecting through bedrock clients. I have no way of monitoring latency related issues because their ping only registers as 0ms on Plan.

**Comment by AuroraLS3** [comment]
Okay so I looked into it and Floodgate/Geyser would need to implement latency field on their side for Plan to get this data. Currently there is no way to get this data so I opened a ticket on Geyser side

**Comment by AuroraLS3** [comment]
There was a comment on the ticket:

> One thing that might work in the meantime would be to enable `forward-player-ping` in the Geyser config, that should properly forward the ping to the java server; but that can lead to Bedrock clients timing out more quickly.

**Comment by DrHuckinJohn** [comment]
> There was a comment on the ticket:
> 
> > One thing that might work in the meantime would be to enable `forward-player-ping` in the Geyser config, that should properly forward the ping to the java server; but that can lead to Bedrock clients timing out more quickly.

I saw that comment and enabled this in my Geyser config, am waiting to see how this works. My player base is a weekly club which meets on Mondays. Will know more this week. Thanks!

**Comment by DrHuckinJohn** [comment]
> Okay so I looked into it and Floodgate/Geyser would need to implement latency field on their side for Plan to get this data. Currently there is no way to get this data so I opened a ticket on Geyser side

Thank you. Also, to answer your question about my server setup:
Server: PaperMC 1.20.4
Plugins: Geyser-Spigot, Floodgate-Spigot, Multiverse-Core, Multiverse-Portals, Multiverse-Netherportals, Multiverse-Inventories, LuckPerms, Chunky, ChunkyBorders, CoreProtect, ViaVersion, ViaBackwards, TabTPS, Plan, BlueMap, DiscordSRV

**Comment by AuroraLS3** [comment]
Alright feel free to close this if the setting solves the issue and I'll put something on the wiki for others about it

**Comment by DrHuckinJohn** [comment]
> Alright feel free to close this if the setting solves the issue and I'll put something on the wiki for others about it

Using the `forward-player-ping` worked to pass through the bedrock client pings. If you are adding something to the wiki about it, I would note that poor internet connections will see frequent disconnects or connection issues with the setting as `true`. When testing on my home network, being farther away from the router caused frequent disconnects with the setting as true than false. Closing this issue. Thanks for the troubleshooting!
