### ISSUE TITLE
Server online graph drawn for Network page

### ISSUE THREAD

**Issue by Virtical** [plan-player-analytics/Plan#3404]
I've noticed that when launching the website after a prolonged pause, the overall online graph is generated incorrectly. Specifically, it uses data from one of the server modes. This can be easily corrected by refreshing the page, and then the correct overall online graph is generated.

I understand that this happens because the URL to which the JSON data for the overall online graph is sent does not contain the "server" parameter, which indicates a specific server. Therefore, the server may return default data or data based on some other factors.

Is it possible to solve this issue?

Details:
Plugin Version: 5.6 build 2614

**Comment by AuroraLS3** [comment]
The cache system probably is incorrectly looking for the online graph of network but picks a server file from the folder

**Comment by Virtical** [comment]
Can you tell me pls if this is an issue on our end, or is it a bug?

чт, 11 янв. 2024 г. в 19:29, Aurora Lahtela ***@***.***>:

**Comment by AuroraLS3** [comment]
Bug

**Comment by Virtical** [comment]
Thank you for the response; it would be greatly appreciated if you could resolve this issue ❤️
