### ISSUE TITLE
Export All Data of Specified Time

### ISSUE THREAD

**Issue by TheMattVid** [plan-player-analytics/Plan#3413]
### I would like to be able to..

I am looking to have a way to get an exported spreadsheet or text file that would list all players that logged in during a 1-week period and their total active play time for that 1-week period.

### Is your feature request related to a problem? Please describe.

I have a rank signup, with the requirements being 5 hours. Players who sign up and hit the 5 hours get the rank for the following week. I use the Ontime plugin, and it exports weekly report txt files automatically. I copy and paste that txt file into a spreadsheet, and then I have another sheet with the list of signed-up users that runs a vlookup on the data I pasted in. If I could get some exported data in the form of a csv even a txt file from Plan, I can delete Ontime once and for all.

**Comment by AuroraLS3** [comment]
Easiest way probably would be to add data export to the Player Table. This way Query page can be used to filter data as needed - or using dragging on the server calendar to select specific timeframe.

**Comment by AuroraLS3** [comment]
A build will appear here in 15 minutes https://github.com/plan-player-analytics/Plan/actions/runs/7599912753

There is now a CSV export on all data tables so you'll be able to select a week in the calendar by dragging and then the new export button is next to the search box on the table.

![export-demo](https://github.com/plan-player-analytics/Plan/assets/24460436/7016e3a7-a245-4b7b-b8bc-feb0546bbd51)

**Comment by TheMattVid** [comment]
Wow, I am grateful. You worked very quickly and provided a very intuitive solution!
