### ISSUE TITLE
Add Bug Report to Supported Plugins

### ISSUE THREAD

**Issue by ItsLeon15** [plan-player-analytics/Plan#3421]
**Wiki page to edit**: https://github.com/plan-player-analytics/Plan/wiki/Supported-Plugins
```
> **Bug Report**
> 
> Spigot
> - [Plugin page](https://www.spigotmc.org/resources/bug-report.110732/)
```

**Comment by AuroraLS3** [comment]
Might be a good idea to add a Table Provider method to your extension to list all the bug reports your plug in has on the website :)

**Comment by ItsLeon15** [comment]
> Might be a good idea to add a Table Provider method to your extension to list all the bug reports your plug in has on the website :)

Something like this?
![image](https://github.com/plan-player-analytics/Plan/assets/64979109/054861f7-e640-44bc-9acd-1ea3e878b449)

**Comment by AuroraLS3** [comment]
I was thinking more like

"Bug reporter", "Reported bug"
AuroraLS3, The axolotl at spawn has been killed

**Comment by ItsLeon15** [comment]
Oh, so something like this?

![image](https://github.com/plan-player-analytics/Plan/assets/64979109/e6e45ade-ec24-4b7b-a029-f1bc8ec27d28)

**Comment by AuroraLS3** [comment]
Yeah that sounds very useful :) Might be also good to have some sort of "Solved" thing if they've been addressed if you keep that kinda data

**Comment by ItsLeon15** [comment]
At the moment there are only two states, "**Archived**" and "**Active**" but I will add it in once I clean up the code a bit more.
