### ISSUE TITLE
FastLogin integration plugin didn't report the correct client status in Plan

### ISSUE THREAD

**Issue by Athar42** [plan-player-analytics/Plan#3485]
### Describe the issue
The FastLogin integration plugin didn't report the correct client status in Plan.
All the clients are reported "Unknown".

### Exceptions & Other Logs
Plan output on one of my test servers : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/d2b3b476-66cd-4ab7-9700-9e935ed7c593)

### Plugin versions
Plan : 5.6 DEV 2731 (for both Velocity and PaperMC servers)
FastLogin : 1.12-SNAPSHOT-a65a5f3 (build 1298)
Authme : 5.6.0 2614
AuthmeVelocity : 4.1.1

Quick setup summary is as follow : 
Proxy : Velocity
--> Connect to a lobby server (PaperMC)
----> Then connect to any game server from an In Game menu (loaded with FastLogin in "Proxy mode").
Not all server have PlaceholderAPI installed (but lobby has and it report the correct state, as noted below).

### Additional information
Using the following command : /papi parse NICKNAME %fastlogin_status%
get the correct output (here : Premium)

My 2cents : It seems that the FastLogin integration request the status right away at the player connection.
As stated on the GitHub page, this issue could be due to the fact that the request of account status is delayed in a proxied environment : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/ddbd990f-58a5-4739-a52b-0e889fac698c)

**Comment by AuroraLS3** [comment]
Thanks for the insight in how it might need to wait after login, I didn't know that ws the case so it should make it easier to fix it

**Comment by Athar42** [comment]
It's a simple guess, unsure if that's the cause of the behavior I witness here, but that's the best I came accross :D 

If any tests needed (testing a new build, or anything to track this bug), feel free to ask me :)

**Comment by AuroraLS3** [comment]
Please test this build https://github.com/plan-player-analytics/Plan/actions/runs/8213295818

It adds a 1 second wait before asking for the premium status.

**Comment by Athar42** [comment]
Little update, seems to look better, just a little one still fail so far.

So, most of my servers get correctly from : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/bd31246b-95ed-4285-8a1a-8763b558fdf4)

to

![image](https://github.com/plan-player-analytics/Plan/assets/44590042/3ad5dcff-7644-4c41-be3e-47e2a37d05ba)

But I still have a couple that didn't update correctly on the first login attempt like the lobby server.
Going back and forth from one server to another get the correct status.

So, seems fixed, but a greater delay might be needed :) (like 2, 3 or 5secs).

**Comment by AuroraLS3** [comment]
A Future is a concept in Java where another thread than calling thread is performing a task - in this case FastAPI is getting the premium status.

If the FastAPI api returned a future I would be able to "wait until this is done" rather than add an arbitrary amount if seconds to wait

**Comment by AuroraLS3** [comment]
I'll reopen this in case it's FastAPI clearing the premium status on player leave and Plan recording that afterwards

**Comment by Athar42** [comment]
> A Future is a concept in Java where another thread than calling thread is performing a task - in this case FastAPI is getting the premium status.
> 
> If the FastAPI api returned a future I would be able to "wait until this is done" rather than add an arbitrary amount of seconds to wait

Thanks for this info, I didn't knew it :)


I'll keep an eye here for any needed tests :)

**Comment by Athar42** [comment]
From the tests I made so far, it might be cleared on reconnection.

I think of that because when I join a server where I was previously set as "Premium", I get back to "Unknown" randomly.
But when I got set to "Premium" then go to another server, I still keep the "Premium" statut in PLAN.

If more tests needed, feel free to ask :)

**Comment by Athar42** [comment]
Just a little reply after the latest update : This new change seems to do the trick, I didn't revert, on my short testing, to "Unknown" status.

As usual, great job, thanks for that nice plugin !
