### ISSUE TITLE
Add a tunnel proxy (cloudflare)

### ISSUE THREAD

**Issue by Hitman477** [plan-player-analytics/Plan#3489]
### I would like to be able to..

Connect proxy cloudflare to hide ip and secure traffic

https://developers.cloudflare.com/api/operations/cloudflare-tunnel

### Is your feature request related to a problem? Please describe.

It will increase security of site-side part of a plugin

**Comment by AuroraLS3** [comment]
Can you not do this already? What is needed? I don't understand.

I've seen a lot of people already behind cloudflare proxy having Plan

**Comment by Vankka** [comment]
You can already use Plan with Cloudflare tunnel, just follow the instructions for a self hosted application [here](https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/) for step 4 see [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/)
