### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by vxkShelby** [plan-player-analytics/Plan#3497]
04.03 11:25:27 [Server] WARN [Plan] Downloading GeoLite2 requires accepting GeoLite2 EULA - see 'Data_gathering.Accept_GeoLite2_EULA' in the config.
04.03 11:25:27 [Server] ERROR [Plan] Failed to enable geolocation.

**Comment by AuroraLS3** [comment]
You can install dev release to fix this https://github.com/plan-player-analytics/Plan/releases/tag/5.6.2796

**Comment by vxkShelby** [comment]
tnx
