### ISSUE TITLE
Possible bug with user ping graph - No data available

### ISSUE THREAD

**Issue by Athar42** [plan-player-analytics/Plan#3498]
### Describe the issue
On a specific user (myself), the ping graph is empty.
While looking in the DB (mariaDB), the data is still there.

![image](https://github.com/plan-player-analytics/Plan/assets/44590042/adbeea7b-b734-48c4-a0fe-7e592d430375)

### Exceptions & Other Logs
No error displayed in the console (velocity), no files log too, nothing.

My account : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/6b5becf6-f209-401c-989e-3e6d9f2ad133)

Two other users : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/bfb4a00b-1aa9-42ac-bc07-dcd01fffd78f)

![image](https://github.com/plan-player-analytics/Plan/assets/44590042/cb790290-20a4-4b56-8ba5-81ec61c94630)

So the rendering is working, but for some weird reason, can't retrieve the datas for my account ?

```

```

### Plugin versions
Plan : 5.6 DEV 2731 (for both Velocity and PaperMC servers) (going to be updated to DEV 2796 tonight : Edit : updated : Didn't change anything :) ).
FastLogin : 1.12-SNAPSHOT-a65a5f3 (build 1298)
Authme : 5.6.0 2614
AuthmeVelocity : 4.1.1

Quick setup summary is as follow :
Proxy : Velocity
--> Connect to a lobby server (PaperMC)
----> Then connect to any game server from an In Game menu (loaded with FastLogin in "Proxy mode").
Not all server have PlaceholderAPI installed (but lobby has and it report the correct state, as noted below).

### Additional information
I tried to enable some "logging", but it just show the loading of the webpage without issue (return code HTTP 200), let me know what tests I can do :)

**Comment by AuroraLS3** [comment]
Could you check response for /v1/player request in Dev Tools Network tab (Ctrl+Shift+I), click the refresh icon on the player page after opening dev tools

You can right click the request to copy response body and send it here - there should be some ping data there to verify what's wrong

**Comment by Athar42** [comment]
Look what I just saw in the "console" part : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/6a41f122-7e8d-403e-83f4-d26b9551b96a)

Lead to : https://assets.highcharts.com/errors/12/
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/fc4b1e12-c516-465d-89e0-232ea6ff0e45)

Going to another user stats page, this error is not displayed (I have to fully refresh the page (simple F5) to get this back in the console when this "data bug" occur).

**Comment by AuroraLS3** [comment]
Aha I see, there's so much data that it expects it in [timestamp, y] format rather than {x: timestamp, y} format that it's currently being fed. Should be an easy fix

**Comment by Athar42** [comment]
Nice, happy to help enhanced this plugin by reporting the bugs I found :')

And yeah, I keep the last 31 Days (in the servers configs), so this could be a big DATA hole :D 
I don't think I miss it, but there is no "refresh query rate" for the ping (just an initial delay before starting to gather the data) ?

I've enought storage space for this, just wondering :)

**Comment by AuroraLS3** [comment]
Yeah that could be a good addition in the future (feel free to open a suggestion ticket). Currently the ping task timer is hardcoded to run every 2 seconds with a configurable start delay after player joins, and then it stores one value for 30 in-memory values, so one datapoint per minute.

**Comment by AuroraLS3** [comment]
There's going to be a build with a fix here in ~10 minutes https://github.com/plan-player-analytics/Plan/actions/runs/8160981921

**Comment by Athar42** [comment]
Works flawlessly, perfect !
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/f4962b8c-916c-45b4-9ea8-5435c9779b05)

(Now, I just wait on the "FastLogin" plugin integration fix and that'll be all for the bug discovered so far ahah :D )
