### ISSUE TITLE
%plan_join_address% seems not working :( Even in /plan ingame

### ISSUE THREAD

**Issue by bobhenl** [plan-player-analytics/Plan#3513]
### Describe the issue

Hello, placeholder isn't replaced, neither in /plan ingame

### Plugin versions

5.6 build 2816
### Additional information

Any, just it doesn't work, should I update

**Comment by AuroraLS3** [comment]
Seems like plan ingame might be bugged.

Correct placeholder is `%plan_player_join_address%` I might have typed it wrong in the change log
If you use /papi parse, use the command twice

**Comment by bobhenl** [comment]
Yeah, this one works! OK, then only in the /plan ingame
