### ISSUE TITLE
Duplicate world names

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#3559]
### Describe the issue

My SQLite database contains duplicate `world_name` entries in `plan_worlds`. Since this is a test server, I am not overly concerned, but I would like to correct the problem. In addition to `plan_worlds`, I see references to `world_id` values in `plan_world_times`. I could easily delete the offending records in both tables, but I would like to understand, if possible, when or how this occurred. No errors have ever been reported (insofar as I am aware).

### Plugin versions

```
> version
[08:08:51 INFO]: This server is running Paper version git-Paper-466 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a203544)
You are running the latest version
Previous version: git-Paper-464 (MC: 1.20.4)
> version Plan
[08:08:57 INFO]: Plan version 5.6 build 2820
[08:08:57 INFO]: Author: AuroraLS3
```

### Additional information

```
sql> select world_name "extremely_long_world_name",count(world_name) "count" from plan_worlds group by world_name ;
extremely_long_world_name  count     
-------------------------  ----------
world                      2         
world_blackdog             2         
world_blackdog_nether      2         
world_blackdog_the_end     1         
world_city                 2         
world_city_nether          1         
world_lobby                2         
world_luckyblock           2         
world_minigames            1         
world_nether               1         
world_parkour              1         
world_skyblock             2         
world_skyblock_nether      1         
world_the_end              1         
world_void                 2         
world_westeros             2         
world_whitedog             2         
world_yellowdog            2         
world_yellowdog_nether     1 
```

**Comment by SlimeDog** [comment]
I have database backups going back several years. The issue first appeared two years ago. The server was running MC-1.18.2 with Plan 5.4. The issue has (obviously) persisted since then.

I am not suggesting that Plan was responsible for the duplications. No doubt I did some SQL untoward database action, but I cannot recall at this remove.

Is it safe to delete the offending records?

**Comment by AuroraLS3** [comment]
The plan_worlds also contains a server_uuid column so if two servers have same world name there will be two entries. Before deleting, make sure that this is not the reason for the duplicates

**Comment by SlimeDog** [comment]
You are a marvel. I have two test servers, and `plan_worlds` contains entries for both. Issue resolved. Thanks for fast response.
