### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by tanhHeng** [plan-player-analytics/Plan#3604]
### Describe the issue

In the `Join address` section (also in some other sections which contain word "unknown"), unknown is translated as "位置"(means "location" in Eng) but it should be "未知", probably because the pinyin (pronunciation) of the two words is similar

### Plugin versions

5.6 Build 2820

**Comment by AuroraLS3** [comment]
@jhqwqmc Would you like to tackle this one? :)

**Comment by jhqwqmc** [comment]
Let me see
我看看

**Comment by jhqwqmc** [comment]
> @jhqwqmc Would you like to tackle this one? :)

https://github.com/plan-player-analytics/Plan/pull/3616
It should be caused by incorrect input of Chinese pinyin.
应该是中文拼音输入错误导致的
位置(wèi zhì) 未知(wèi zhī)
