### ISSUE TITLE
Add Skript support

### ISSUE THREAD

**Issue by ImMeowo** [plan-player-analytics/Plan#3606]
**Data to display**
Own stuff from player's scripts

**Link to API or Source Code**
https://github.com/SkriptLang/Skript

**Link to Project page or Downloads**
https://github.com/SkriptLang/Skript/releases

**Comment by AuroraLS3** [comment]
How does skript expose data to other plugins?

**Comment by Vankka** [comment]
I think OP wants to add 'custom' data to Plan with Skript(s), probably would involve quite a lot of work to implement

**Comment by AuroraLS3** [comment]
I don't want to make anything that involves writing some api in Skript

**Comment by ImMeowo** [comment]
I have a weird question but could you please delete this issue?
