### ISSUE TITLE
Add Servers Uptime Placeholders

### ISSUE THREAD

**Issue by Neocle** [plan-player-analytics/Plan#3647]
### I would like to be able to..

I'd like to have these two placeholders:
```
%plan_server_uptime:<server>%
%plan_server_average_uptime%
```

### Why?

The first placeholder (%plan_server_uptime:<server>%) would allow server owners to display the uptime of a specific server within their network, providing important information for maintenance purposes/to inform players.

The second one (%plan_server_average_uptime:<server>%) would display the average uptime of all servers/a sppecific one. This could help server owners to check the reliability of their network/server.

I think that these placeholders would be cool additions to your plugin and would be useful for users like me

### Is your feature request related to a problem? Please describe.

I would like to display my servers' uptimes in the TAB of the Hub.

**Comment by AuroraLS3** [comment]
Average uptime is probably too much to hope for, considering how heavy uptime calculation sql for one server is already (~5-10 seconds)
