### ISSUE TITLE
Display in calendar "bug" (out of window)

### ISSUE THREAD

**Issue by Athar42** [plan-player-analytics/Plan#3668]
### Describe the issue
It's me again 😋 
When you want to see all the session for a specific player (you click on "XX more"), mainly for monday, the "pop-in" box will be displayed under the left menu, like you can see on the below screenshots :

OK : 
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/5d96aef0-f660-468b-804c-0f6c73db9bf8)

Not OK :
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/38201249-7d03-4c2c-84cb-cacfad7359a2)

Also, might be not related, but this isn't translated to french for this part ? '^^
Week days are in english, same for the "more" statement, and some more. (for the date/time format, unsure if this is intended too)
![image](https://github.com/plan-player-analytics/Plan/assets/44590042/01c7c3d7-7466-4479-b87a-36745fcf3bef)

### Plugin versions
Plan : 5.6 build 2885

**Comment by AuroraLS3** [comment]
I guess z-index of sidebar is too high compared to the popup

**Comment by AuroraLS3** [comment]
The calendar is still a mess in terms of translation because the contents are translated in the backend and frontend doesn't translate everything there

**Comment by Athar42** [comment]
Clearly, the translation isn't a priority, I just use this bug report to also report this "as a bonus" :D

Nothing urgent for any of those bugs :) 

Thanks

**Comment by AuroraLS3** [comment]
So this unfortunately happens due to sidebar being rendered with `position: static` which to me seems to be rendered on top of other content regardless of `z-index` so I'm unable to change the popover in a way that it would render on top of the sidebar
