### ISSUE TITLE
Placeholders do not parse on Paper 1.21

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#3678]
### Describe the issue

None of the [listed placeholders](https://github.com/plan-player-analytics/Plan/wiki/PlaceholderAPI) I tried parsed on Paper 1.21. I didn't try them all, but quite a few; none parsed.

### Plugin versions

```
> version
[11:24:49 INFO]: This server is running Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-36-dd31654 (MC: 1.21)
> version Plan
[11:24:53 INFO]: Plan version 5.6 build 2883
[11:24:53 INFO]: Author: AuroraLS3
```

**Comment by AuroraLS3** [comment]
Did you add the extra stuff e.g %plan_{listed_placeholder}% or did you use /papi parse two times?

/papi parse runs on server thread and Plan can't replace first time on server thread due to potential of crashing the server with a database wait. Same thing occurs on all things where server thread is used.

You can add the placeholder to Plan config for it to be loaded when player joins

**Comment by SlimeDog** [comment]
> /papi parse runs on server thread and Plan can't replace first time on server thread due to potential of crashing the server with a database wait. Same thing occurs on all things where server thread is used.

That is the issue. I see the explanation in the wiki. Does the configuration entry need the percent-signs
```
Plugins:
    PlaceholderAPI:
        Enabled: true
        Load_these_placeholders_on_join: 
          %plan_player_death_count%
```
or without
```
Plugins:
    PlaceholderAPI:
        Enabled: true
        Load_these_placeholders_on_join: 
          plan_player_death_count
```

**Comment by SlimeDog** [comment]
Actually, the placeholder of issue could change after join, so maybe `Tracked_player_placeholders` is the better option?

**Comment by AuroraLS3** [comment]
With, and also needs to be a list so starting with `- `

The tracked placeholders setting puts the data on the extensions tab

**Comment by SlimeDog** [comment]
Thanks.
