### ISSUE TITLE
MySQL connection error caused chat to stop working

### ISSUE THREAD

**Issue by FaultyFunctions** [plan-player-analytics/Plan#3682]
### Describe the issue
The plugin ran into a MySQL connection error and then chat in-game did not work and would not send to anyone. DiscordSRV still worked in the background and in-game chat messages were being sent to Discord but weren't showing up in game because of this error. I messaged my server support and they said the MySQL database went down but I'm not sure why chat stopped working because Plan couldn't connect to the MySQL database.

### Exceptions & Other Logs
https://mclo.gs/pHCAeaK

### Plugin versions
Plan-5.6-build-2883

### Additional information
N/A

**Comment by AuroraLS3** [comment]
Logs say that InteractiveChat was trying to do a placeholder replacement for Plan which failed due to database connection being down, so it threw error instead of replacing the placeholder and InteractiveChat logged the error rather than send the chat message

**Comment by AuroraLS3** [comment]
I think a fix on Plan side is to catch more errors on placeholder request and show Error rather than throwing it to the other plugin that doesn't know to expect it

**Comment by AuroraLS3** [comment]
Fixed build will appear here in 10 minutes https://github.com/plan-player-analytics/Plan/actions/runs/9739796493

This doesn't fix your database issue though, just the chat not working when database is down.

**Comment by FaultyFunctions** [comment]
Awesome thank you so much! Yeah the database issue isn't Plan's fault at all. Thanks again!
