### ISSUE TITLE
Proxy HTTPS ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Mtn16** [plan-player-analytics/Plan#3691]
When HTTPS is activated from the proxy (KeyStore_path: proxy), the main page does not load and the following error is displayed in the browser console: Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR.
The login page works normally without any problems.

### Exceptions & Other Logs
(there are no files in the /plugins/Plan/logs directory.)

### Plugin versions
Latest version of Plan (5.6. build 2883)

![Image](https://github.com/plan-player-analytics/Plan/assets/104649436/c41dfa71-fe1d-400b-b205-d111ed9da9d1)

**Comment by AuroraLS3** [comment]
What is your reverse proxy config like and what is Plan alternative IP set as?

**Comment by Mtn16** [comment]
I do not have access to reverse proxy configuration, I can only connect domain to port. 
Alternative IP is set to domain.

**Comment by AuroraLS3** [comment]
In proxy mode Plan uses http 1.1 so if the reverse proxy tries to communicate using http 2 with Plan it will fail

**Comment by Mtn16** [comment]
Oh, okay. Am I able to switch it? (I mean in Plan)

**Comment by AuroraLS3** [comment]
Using a self signed cert instead of proxy mode will have Plan use http/2

**Comment by jakubhyza** [comment]
Hi there
I'm developer from the hosting where @Mtn16's server is hosted
Proxy uses http 1.1 for the communication with Plan and it seems to always return valid response.
JavaScript files shows without a problem when opened inside it's own tab or when loaded via fetch inside console. Error shows only when app is trying to import dynamic module. Other parts of the app (like fetching data) works without issue.
Also for some reason it starts to work correctly when Firefox dev tools are opened.

**Comment by AuroraLS3** [comment]
Does the Firefox dev tools have disable cache checkbox checked on the Network tab? Maybe it's a caching issue - if the proxy adds cache headers that can cause problems (it has at least in the past)

**Comment by jakubhyza** [comment]
We finally found the issue. It was caused by our firewall which classified this traffic as HTTP Flood attack. The problem was fixed and this ticket can be closed.

Really cool plugin BTW

**Comment by AuroraLS3** [comment]
Thanks!
