### ISSUE TITLE
The data download is very, very long 

### ISSUE THREAD

**Issue by notikj** [plan-player-analytics/Plan#3692]
### Describe the issue
Downloading data one way or another: Reviewing the player base, Player Retention, Player List, Geolocation and Making a request take a very long time to load. The download may take a couple of minutes.

### Plugin versions
Plan 5.6 build 2883

### Additional information
Tell me, please, how can I speed up the data download? https://imgur.com/a/F97qtIJ

Plan has been installed for more than a year, there are 500 thousand players in the database

**Comment by AuroraLS3** [comment]
Closing as duplicate of #3661
