### ISSUE TITLE
Placeholder: Players online

### ISSUE THREAD

**Issue by 0x1026** [plan-player-analytics/Plan#3693]
### I would like to be able to..

show how many players are online on that server using PlaceholderAPI.

`server_players_online` would be perfect!

### Is your feature request related to a problem? Please describe.

Nop.

**Comment by AuroraLS3** [comment]
Doesn't PAPI already have this built-in? 🤔

**Comment by 0x1026** [comment]
Not exactly, it's an external expansion: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#bungeecord

**Comment by AuroraLS3** [comment]
The information in that extension likely updates faster than Plan, which updates ~once per minute

**Comment by 0x1026** [comment]
I prefer updates every minute with %plan_server_players_online:survival%, than downloading a new expansion, sincerely imo
