### ISSUE TITLE
Error when opening the web interface

### ISSUE THREAD

**Issue by AMG6900** [plan-player-analytics/Plan#3712]
So I installed Plan on my minecraft server that is running paper on 1.21 and configured it. When i try to open the web interface I get this error.

{"error":"The required authorization heads were not present in the request."}

I'm using Plan 5.6 build 2883

Also I've got this error before when tried to use  the squaremap plugin.
Can someone help?

**Comment by AuroraLS3** [comment]
It sounds like something other than Plan intercepted the request - there is no such message programmed in Plan. I'd ask your host :)

**Comment by AuroraLS3** [comment]
If you're using cloudflare that could be a reason, they only allow specific ports when proxying https://developers.cloudflare.com/fundamentals/reference/network-ports/
