### ISSUE TITLE
Support CMI

### ISSUE THREAD

**Issue by Chaostarts** [plan-player-analytics/Plan#3735]
### Data to display

like EssentialsX

### Link to API or Source Code

CMI API - https://github.com/Zrips/CMI-API

### Link to Project page or Downloads

https://www.spigotmc.org/resources/cmi-298-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

**Comment by SonnenPingu** [comment]
Oh, that would be great.
Then you can display that too :D

**Comment by Chevels** [comment]
Hello,
I was just coming to propose CMI too^^

**Comment by ThisNightFox** [comment]
I would also like to have CMI support

**Comment by PythonChicken123** [comment]
Same here, I have CMI and would also like CMI intergration.

**Comment by Highrii** [comment]
+1

**Comment by YannicHock** [comment]
I think I could take this on, as I would like to start contributing to this repo. I have used Plan for quite a while now and I think it is time to give back a little. This looks like a good fit for a first contribution.

After a first look into the CMI-API it offers a lot more data then just the data requested here. Would there any other data than Jail, Mute, Homes and Balance be usefull in plan? If so which data?

**Comment by AuroraLS3** [comment]
I'm not familiar with CMI - hopefully some of the +1 commenters can weigh in

**Comment by AuroraLS3** [comment]
You can link your work here once you feel like it's all good and I'll fork it to the plan-player-analytics org so that I can publish the artifact in the maven repository reliably. :)

**Comment by YannicHock** [comment]
First Version, just copying the functionality of the EssentialsX-Extention, is done and the pull requests are created
[Plan](https://github.com/plan-player-analytics/Plan/pull/3815)
[CMI-Extension](https://github.com/plan-player-analytics/Extension-template/pull/153)

I hope this is acceptable work - If anyone here has Ideas as to which data of CMI is also desirable, I will happy to add it in the future.
