### ISSUE TITLE
 Show the TPS data of a server to a player.

### ISSUE THREAD

**Issue by SonnenPingu** [plan-player-analytics/Plan#3738]
### I would like to be able to..

The users should be able to see how the TPS of the server is without seeing RAM/memory/CPU.

So that if someone complains about the server lagging again, you can say look in Plan, it's not the server.

### Is your feature request related to a problem? Please describe.

It is designed to prevent users from seeing CPU/RAM and hard disk memory.

But really only TPS and Ping.

**Comment by AuroraLS3** [comment]
Currently the permission is PAGE_SERVER_PERFORMANCE_GRAPHS which has no subsections since the data endpoint returns all data for the browser.

To change this sub-permissions would need to be added and data coming from the endpoint limited.
