### ISSUE TITLE
Data gradually disappearing from my stats

### ISSUE THREAD

**Issue by nuttapillar** [plan-player-analytics/Plan#3751]
### Describe the issue

Hi, I have noticed over a year ago that some players were completely disappearing from my Stats page. And recently I have noticed that even more are gone now. And some players from years ago, who I know played on the server a lot, are only showing like 45mins.

I'm not sure what log would be relevant to something that's been gradually happening for over a year it seems.

### Exceptions & Other Logs

```

```

### Plugin versions

Plan-5.6-build-2883.jar
### Additional information

I just occasionally look at the stats list, and notice some older players are nolonger on there.

**Comment by nuttapillar** [comment]
Also, my total AFK time is listed as 2 hours, but I probably get that much after only a few days. It should be hundreds of hours by now.

**Comment by AuroraLS3** [comment]
Check your config under Time Thresholds settings there are data removal thresholds.

If you have plan.ignore.afk permission your afk time is not recorded.

**Comment by nuttapillar** [comment]
Thanks, I'll try that. Can I restore the data from the server files somehow? I dislike that data has seemed to have disappeared

**Comment by AuroraLS3** [comment]
Not really :/

**Comment by nuttapillar** [comment]
Why would deleting data be the default option?

**Comment by AuroraLS3** [comment]
Around the time the deletion stuff was implemented the plugin was way more unoptimized so it was done to speed it up.

I guess the default deletion thresholds could be looked at again
