### ISSUE TITLE
在 Velocity 中， Web 端显示的时间不正确

### ISSUE THREAD

**Issue by Minecraft0122** [plan-player-analytics/Plan#3801]
### 描述问题

在 Velocity 群组服中使用 Plan ， Web 中显示的时间并不正确，时间大约晚了9个小时。
我已确认我的服务器设置的系统时间正确无误，并且在查看其他服务器数据时，没有发现时间错误

### 异常与其他日志

我没有错误日志，因为这个错误并不会使 Plan 报错
![image](https://github.com/user-attachments/assets/97f52723-db75-4fe0-bf7f-ca4dd2a19af1)

```
```
### 插件版本

Plan版本：Plan-5.6-build-2883

**Comment by AuroraLS3** [comment]
You can set the timezone under Formatting.Dates.TimeZone in Plan config

**Comment by Minecraft0122** [comment]
> 您可以在 Plan config 中的 Formatting.Dates.TimeZone 下设置时区

我已更改时区，但这并没有用

我发现我的服务器无法访问任何非中国大陆的iP地址，会不会是这个原因？

**Comment by Minecraft0122** [comment]
> 您可以在 Plan config 中的 Formatting.Dates.TimeZone 下设置时区

我已尝试这样做（设置为"UTC+8"）并重启代理服务器，但这并没有用

在我修改成"server"并重启服务器后，时间不知为何又被同步回来了

感谢您的回复

**Comment by AuroraLS3** [comment]
So the formats it supports is "UTC" (just that) or "GMT+8" or some country/city combinations, but I don't have a list of those so easier with GMT+-number

**Comment by Minecraft0122** [comment]
我也尝试这样做了，但是并没有用
又由于一些其他的原因，我删除并重新创建了数据库，在我这么做之后，这个问题被解决了
感谢你的帮助
