### ISSUE TITLE
Türkiye/Turkey doesn't show up on geolocations map as highlighted

### ISSUE THREAD

**Issue by ComradeCaro** [plan-player-analytics/Plan#3843]
### Describe the issue

When I look at my geolocations map in Plan Turkey doesn't show up highlighted like other geolocations likely due to the name change from Turkey to Türkiye

### Exceptions & Other Logs

```

```

### Plugin versions

5.6, build 2883
### Additional information

![image](https://github.com/user-attachments/assets/e6d1359e-9c29-462f-9650-83fe1d642065)
![image](https://github.com/user-attachments/assets/a55513aa-9d7c-4efd-87fe-cfccdc3d3809)

**Comment by AuroraLS3** [comment]
Gotta update the geocode mapping I guess
