### ISSUE TITLE
Map error in Geolocations

### ISSUE THREAD

**Issue by winter0203** [plan-player-analytics/Plan#3901]
### Describe the issue
The country partition in Geolocations is incorrect, and Taiwan is incorrectly listed as a country

### Plugin versions
5.6 build 2883

### Additional information

Official map of China:https://www.gov.cn/xhtml/2016gov/images/guoqing/bigmap.jpg
The United Nations list of countries does not recognize Taiwan as a state, and Taiwan belongs to China
https://www.un.org/en/about-us/member-states#gotoC

**Comment by winter0203** [comment]
![Screenshot_2024-12-25-10-06-26-601_com microsoft emmx](https://github.com/user-attachments/assets/eeee3e52-493c-485a-85b9-4a3fd6aeeb94)
error map

**Comment by sp-dust** [comment]
👍

**Comment by AuroraLS3** [comment]
Taiwan has a separate IP range and ISO-3166 alpha 3 code so it is shown as separate.

**Comment by winter0203** [comment]
> Taiwan has a separate IP range and ISO-3166 alpha 3 code so it is shown as separate.

The same is true for Hong Kong and Macau, but you didn't list them separately? Even if you want to list Taiwan separately, you should indicate that it is a region of China

**Comment by AuroraLS3** [comment]
Which IPs are listed separately is decided by MaxMind who maintain the GeoLite 2 Country database.

**Comment by AuroraLS3** [comment]
I consider this outside the scope of Plan, same as previous ticket on the topic #3813
