### ISSUE TITLE
Embed HTML on other websites

### ISSUE THREAD

**Issue by lukeeexd** [plan-player-analytics/Plan#506]
Hey,

I've a suggestion for statistics for embedding some of the stats shown on Plan on a website. 
So say for my mc website, I could embed a "module" with say players online, total play time etc on my website.

**Comment by Rsl1122** [comment]
I think that would require writing some sort of script and make Plan return data at some address - While certainly possible I don't have enough know how yet (I most likely will get that know how in the next 6 months).

At the moment if I started working on this it would be me figuring it out slowly, so instead I'll wait for the course on javascript first and then reconsider.

If someone decides to add such functionality I'll be happy to merge it though.
(JSON data responses & scripts to embed on the external page)

**Comment by Rsl1122** [comment]
With 5.0 this is now possible to include the stats on other websites by using the same JSON endpoints Plan uses for the data. - Login might be required if HTTPS is in use.

https://github.com/plan-player-analytics/Plan/blob/master/Plan/json-endpoints.md
