### ISSUE TITLE
[Plugin Suggestions] DataExtension suggestions

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#583]
> This issue is no longer in use, and is only kept until the suggestions have been processed.
>
> If you would like to suggest new plugins, use the [Plugin Suggestion-template](https://github.com/plan-player-analytics/Plan/issues/new?template=plugin_request.md)

### Support added

Plugin | Status | Plugin page | Source code | Original issue
-- | -- | -- | -- | --
AdvancedBan | **Merged** - #688 | [Link](https://www.spigotmc.org/resources/advancedban.8695/) | [Link](https://github.com/DevLeoko/AdvancedBan) | #214 
CoreProtect | **Merged** bdcf7c9dc060ed3e88b99e9f1eb146bf3fd6223a | [Link](https://www.spigotmc.org/resources/coreprotect.8631/) | [Link](http://minerealm.com/community/viewtopic.php?f=32&t=16534) | #578
DKBans | **Merged** 37a69b60d939f54f2176c0efe669c205141d462f | [Link](https://www.spigotmc.org/resources/dkbans-bansystem-playermanagement-json-mysql-sqlite-mongodb-bukkit-bungeecord.52570/) |  [Link](https://github.com/DevKrieger/DKBans/) | *Comments*
DKCoins | **Merged** 02e2b29d01f9541d9bae50bfade3fd97873f7f32 | [Link](https://www.spigotmc.org/resources/dkcoins-coinsystem-mysql-sqlite-mongodb-json-german-english.39159/) | [Link](https://github.com/DevKrieger/DKCoins) | *Comments*
Essentials Eco | **Merged** 774fe394155d1eeb51f69bf1f04dcd9f6bb404ca | [Link](https://www.spigotmc.org/resources/essentialsx.9089/) | [Link](https://github.com/drtshock/Essentials) | #125 
FactionsUUID | **Merged** | [Link](https://www.spigotmc.org/resources/factionsuuid.1035/) | [Link](https://github.com/drtshock/Factions) | *Comments*
GriefDefender | **Merged** de0e71333c91c8ba43bc73a4f37bfe654a6dfeb7 | [Link](https://www.spigotmc.org/resources/griefdefender.68900/) | [Link](https://github.com/bloodmc/GriefDefenderAPI) | *Discord*
Heroes | **Merged** | [Link](https://www.spigotmc.org/resources/%E2%9A%94-heroes-the-most-powerful-race-class-and-skill-rpg-plugin.24734/) | [Link](http://nexus.hc.to/content/repositories/pub_releases/) | *Comments*
LuckPerms | **Merged** - #742 | [Link](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) | [Link](https://github.com/lucko/LuckPerms) | #125 
mcMMO Overhaul | **Merged** ed52d62133c93d59c972236db7aa368706c99c05 | [Link](https://www.spigotmc.org/resources/official-mcmmo-overhaul.64348/) | [Link](https://github.com/mcMMO-Dev/mcMMO) | *Comments* / #904 
MinigamesLib | **Merged** d9bf729f40293519833083173b23c66a7bd28e52 | [Link](https://www.spigotmc.org/resources/minigameslib.23844/) | [Link](https://github.com/MysticCity/MinigamesAPI) | #343 
Nucleus | **Merged** - #723 | [Link](https://jd.nucleuspowered.org/) | [Link](https://github.com/NucleusPowered/Nucleus) | *Comments*
NuVotifier | **Merged** b073b23832d22ab4e40b0ffebdf37742361b0a5d | [Link](https://www.spigotmc.org/resources/nuvotifier.13449/) | [Link](https://github.com/parallelblock/NuVotifier) | #731 
PlotSquared | **Merged** | [Link](https://www.spigotmc.org/resources/plotsquared.1177/) | [Link](https://github.com/IntellectualSites/PlotSquared) | #479
React | **Merged** | [Link](https://www.spigotmc.org/resources/react-smart-server-performance.21057/) | [Link](https://github.com/VolmitSoftware/React/issues/363) | *Discord*
SavageFactions | **Merged** | [Link](https://www.spigotmc.org/resources/savagefactions-a-free-factionsuuid-fork.52891/) | [Link](https://github.com/illyria-io/illyriaFactions) | *Comments* 

### No support

Plugin | Status | Plugin page | Source code | Original issue
-- | -- | -- | -- | --
AuthMe | **No UUIDs** | [Link](https://www.spigotmc.org/resources/authmereloaded.6269/) | [Link](https://github.com/AuthMe/AuthMeReloaded) | #533
Bank | **No API** | [Link](https://www.spigotmc.org/resources/bank-new-loans-system-with-interest.3556/) | Unavailable | #578
BungeeAdminTools | **Dead** | [Link](https://www.spigotmc.org/resources/bungee-admin-tools-premium-edition.37880/) | [Link](https://github.com/alphartdev/BungeeAdminTools) | #570
CMI | **API not distributed**, uses Eclipse for building | [Link](https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/) | [Link](https://github.com/Zrips/CMI-API) | #578 
EpicSpawners | **No data to display** | [Link](https://www.spigotmc.org/resources/epicspawnerslite-the-almost-ultimate-spawner-plugin.49957/) | [Link](https://www.songoda.com/wiki/epicspawners#api) | #535
LuckyBlocks | **No API** | [Link](https://www.spigotmc.org/resources/luckyblocks-leaderheads-and-proquests-support.28454/) | Unavailable | *Comments*
LagMonitor | No API | [Link](https://www.spigotmc.org/resources/lagmonitor.21348/) | [Link](https://github.com/games647/LagMonitor) | #503 
MinecraftMarket | **Dead** | [Link](https://www.minecraftmarket.com/) | [Link](https://github.com/MinecraftMarket/MinecraftMarket-Plugin) | #590 
PlayerPoints | **Unmaintained plugin** | [Link](https://dev.bukkit.org/projects/playerpoints) | [Link](https://github.com/Mitsugaru/PlayerPoints) | #576
Residence | Requires Dev Copy | [Link](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-12.11480/) | [Link](https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-12.11480/) | *Comments*
ShopGUI+ | **No easy data access** | [Link](https://www.spigotmc.org/resources/shopgui-admin-gui-shop-plugin.6515/) | [Link](https://gist.github.com/brcDev/15f7b9587dca52442904d331a026a8c8) | #658 
SkillAPI | Dead plugin | [Link](https://www.spigotmc.org/resources/skillapi.4824/) | [Link](https://github.com/Eniripsa96/SkillAPI) | #574
Skript | **No easy data access** | [Link](https://skunity.com/) | [Link](https://github.com/SkriptLang/Skript) | *Comments*
SkyBlockEarth | **No API** | [Link](https://www.spigotmc.org/resources/skyblockearth-1-8-x-1-13-x.61976/) | [Link](https://gitlab.com/Songoda/SkyBlock/blob/master/src/main/java/me/goodandevil/skyblock/api/SkyBlockAPI.java) | #853 
Spartain AntiCheat | Needs Manual API installation | [Link](https://www.spigotmc.org/resources/spartan-anticheat-hack-blocker-machine-learning.25638/) | [Link](https://www.spigotmc.org/resources/spartan-anticheat-hack-blocker-machine-learning.25638/) | #578
StrikePractice 2 | Needs Manual API installation | [Link](https://www.spigotmc.org/resources/strikepractice-2-%E2%80%93-queues-sumo-tournaments-pvp-bots-best-of-rounds-mysql.46906/) | [Link (Download)](https://goo.gl/NJajnL) | *Comments*
----

### Possible reasons for not adding plugins

1. Source code is unavailable / API is not public
2. Source code is unavailable / "Public" API can not be used without purchasing the plugin
3. Plan already supports data that can be easily pulled from the plugin's API
4. Plugin has no data that can be displayed
5. Plugin has no way to access data easily
6. Plugin has no long term data storage

**Comment by Grand-Trizmo** [comment]
Luck Perms https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/  https://javadoc.io/doc/me.lucko.luckperms/luckperms-api/4.2

**Comment by Rsl1122** [comment]
Made the list alphabetic so that it is easier to read - Luck Perms is already included.

**Comment by Frerduro** [comment]
Residence: https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-12.11480/

**Comment by DeCarvalho83** [comment]
[Heroes Premium ](https://www.spigotmc.org/resources/⚔-heroes-the-most-powerful-race-class-and-skill-rpg-plugin.24734/)
But it also has a free option

[API ](http://nexus.hc.to/content/repositories/pub_releases/)

**Comment by MajorSkillage** [comment]
Add support for Votifier directly.

**Comment by maxlehot1234** [comment]
Are you able to add these type of stats?

Mined Blocks
Tokens (TokenEnchant)
Prestige (EzPrestiges)
Luckyblocks (https://www.spigotmc.org/resources/luckyblocks-leaderheads-and-proquests-support.28454/)

These things will be nice to have on players "stats" page

tHANK YOU ;)

**Comment by Rsl1122** [comment]
@maxlehot1234 

> **a spigot link and a link to the source code/API.**

**Comment by SlimeDog** [comment]
SavageFactions, a 1.13.x-compatible fork of FactionsUUID, please.
https://www.spigotmc.org/resources/savagefactions-a-free-factionsuuid-fork.52891/
https://www.spigotmc.org/resources/factionsuuid.1035/

**Comment by Damdamdu95** [comment]
Can you add [StrikePractice 2 – Queues, Sumo, Tournaments, PvP Bots, Best of Rounds, MySQL](https://www.spigotmc.org/resources/strikepractice-2-%E2%80%93-queues-sumo-tournaments-pvp-bots-best-of-rounds-mysql.46906/) please ? The API is in the Spigot resource.

**Comment by killianperez** [comment]
Possible to add [Skript](https://github.com/SkriptLang/Skript/releases)please ? And choose custom variable and expression to display on Plan? Thanks, Killian

Source code: [Here](https://github.com/SkriptLang/Skript)
Website: [Here](https://skunity.com/)
API doc: [Here](http://en.njol.ch/projects/skript/API)

**Comment by MG-100** [comment]
Can you add DKperms and DKbans for the Plan panel?

**Comment by Rsl1122** [comment]
@MG-100 please read the bold sentence at the top of the first comment and update your suggestion accordingly.

**Comment by doitliketyler** [comment]
mcMMO Overhaul
Project: https://www.spigotmc.org/resources/official-mcmmo-overhaul.64348/
Source: https://github.com/mcMMO-Dev/mcMMO

**Comment by PixelmonPRO** [comment]
GriefPrevention Sponge
Projeсt: https://ore.spongepowered.org/blood/GriefPrevention
Sourсe: https://github.com/MinecraftPortCentral/GriefPrevention

**Comment by MG-100** [comment]
DKBans
Project: https://www.spigotmc.org/resources/dkbans-bansystem-playermanagement-json-mysql-sqlite-mongodb-bukkit-bungeecord.52570/
Source: https://github.com/DevKrieger/DKBans/

**Comment by MG-100** [comment]
DKCoins
Project: https://www.spigotmc.org/resources/dkcoins-coinsystem-mysql-sqlite-mongodb-json-german-english.39159/
Source: https://github.com/DevKrieger/DKCoins

**Comment by redstonedesigner** [comment]
https://github.com/plan-player-analytics/Plan/issues/1227

**Comment by PixelmonPRO** [comment]
GTS
Project: https://ore.spongepowered.org/NickImpact/GTS
Source: https://github.com/NickImpact/GTS

CarrotShop
Project: https://ore.spongepowered.org/Carrot/CarrotShop
Source: https://github.com/TheoKah/CarrotShop

AdamantineShield
Project: https://forums.spongepowered.org/t/adamantineshield-v0-4-1-action-logging-and-rollback-for-sponge/20679
Source: https://github.com/Karanum/AdamantineShield
