### ISSUE TITLE
Punchcard should start with 12am and not 1am. Also 0am needs to be 12am

### ISSUE THREAD

**Issue by BrainStone** [plan-player-analytics/Plan#712]
### Describe the bug

The puncard currently starts at 1am. Which means playing at midnight, the punch card puts you at the end of the next day:

![grafik](https://user-images.githubusercontent.com/4106544/44810763-109d6600-abd3-11e8-8293-7c3a8288a60a.png)

Note I was logging in at 11pm and at 12am (1 hour appart), yet it put the dot on the next day.

Also midnight is 12am and not 0am.

### Server information

**Plan Version:** 4.4.5
**Server:** BungeeCord git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178 git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178
**Database:** MySQL

**Operating SubSystem:** Linux (amd64) version 4.9.0-8-amd64
**Java Version:** 1.8.0_171, Oracle Corporation
**Java VM Version:** OpenJDK 64-Bit Server VM version 25.171-b11, Oracle Corporation
**Java VM Flags:** [-Xms921M, -Xmx1843M, -XX:+UseG1GC, -XX:+UnlockExperimentalVMOptions, -XX:MaxGCPauseMillis=100, -XX:+DisableExplicitGC, -XX:TargetSurvivorRatio=90, -XX:G1NeuSizePercent=50, -XX:G1MaxNeuSizePercent=80, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1MixedGCLiveThresholdPercent=50, -XX:+AggressiveOpts, -XX:+AlwaysPreTouch]

**Comment by Rsl1122** [comment]
The start of the punchcard I a currently dependent on the timezone chosen.

**Comment by BrainStone** [comment]
So it could even start at something like 7am?

I mean the times should be timezone adjusted but not the lables.

**Comment by Rsl1122** [comment]
Yes. It's because HighCharts is in charge of the labels and moves the times around based on the timezones (Technically the dates on the punchcard are from 1st of January 1970)

**Comment by BrainStone** [comment]
I’ll see if this can be corrected

**Comment by Rsl1122** [comment]
12 AM requires special formatting function to be specified instead of built in formatting.

http://www.php.net/manual/en/function.strftime.php seems to put it as 0 am
