### ISSUE TITLE
Adding a way to change to a particular time zone

### ISSUE THREAD

**Issue by Flaming-Dorito** [plan-player-analytics/Plan#718]
### Is your feature request related to a problem? Please describe.

All the times on the analytics are completely different from my local time because the server isn't hosted near where I live. The only 2 options we currently have for time zones is using the local time of where the server is hosted and the UTC time. 

### Describe the solution you'd like

I'd like if a feature could be added that allows us to change the time zone to a particular time zone.

**Comment by Martinc4321** [comment]
Hello, I'm interested in this issue. May I try to fix it ?
