### ISSUE TITLE
Feature request: BentoBox/BSkyBlock support

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#722]
Please add reporting for BentoBox and the bSkyBlock/bAcidIsland addons (1.13.x replacements for aSkyBlock/AcidIsland). No idea as to the API changes required.

https://github.com/BentoBoxWorld

**Comment by Rsl1122** [comment]
@Poslovitch seemed to be interested in adding Plan hook to BentoBox itself - I don't know how it turned out. It might be delayed until the PluginData rework has been done on Plan end (https://github.com/Rsl1122/Plan-PlayerAnalytics/issues/638)

How is it going Poslovitch? :)

Have a nice day. :D

**Comment by Poslovitch** [comment]
I disagree : BentoBox is not released yet, and I don't want to get reports from plugin developers that complain about API breaking changes.

I'm working on a "Hooks API" on BentoBox. Plan will be one of the plugins that'll be supported by default with it. Addons will have the ability to register their custom data in a much easier way.

Wait and see, that's what I love to say these days.

**Comment by Rsl1122** [comment]
Alright.

All the good things take time :)

**Comment by Rsl1122** [comment]
I think this issue might have been forgotten. @Poslovitch How would you like to go about this? (Include in Plan or include in Bentobox?)

**Comment by SlimeDog** [comment]
Thanks.

**Comment by Poslovitch** [comment]
@Rsl1122 both are suitable solutions. I'd prefer to have it built-in in BentoBox though. 
I'll investigate that tonight.

**Comment by Poslovitch** [comment]
I had a look at the ASkyBlock extension (https://github.com/plan-player-analytics/Extension-ASkyBlock/tree/master/src/main/java/com/djrapitops/extension). I like how the API works, however, is there a simple, straight-forward way for me to test my extension without having to set up a full Plan installation?

**Comment by Rsl1122** [comment]
It is possible to test against implementation errors <https://github.com/plan-player-analytics/Extension-ASkyBlock/blob/master/src/test/java/com/djrapitops/extension/ExtensionImplementationTest.java>

Unfortunately there is no way to view how it looks without an installation

**Comment by SlimeDog** [comment]
I can report on "how it looks" when the code is in place. Plenty of test servers out here.

**Comment by Rsl1122** [comment]
I started work on this in https://github.com/plan-player-analytics/Extension-BentoBox

I like the API of BentoBox, it appears very flexible. I ran into some trouble trying to find the rigth Strings for add on request, as I don't know what add-ons to need for the metadata (and what they provide)

Best I could find was [searching the repositories for `registerRequestHandler`](https://github.com/search?q=org%3ABentoBoxWorld+registerRequestHandler&type=Code), but it doesn't include any island related things (BSkyBlock doesn't register any request handlers for example)

----

@Poslovitch could you help me out by pointing me towards how to check if the player has an island in BSkyBlock (as an example)

**Comment by Poslovitch** [comment]
> could you help me out by pointing me towards how to check if the player has an island in BSkyBlock (as an example).

The main API (which all gamemodes use) is provided by BentoBox (and you therefore need not rely on addon requests).

In your case, what you are looking for is part of the [IslandsManager](https://github.com/BentoBoxWorld/BentoBox/blob/develop/src/main/java/world/bentobox/bentobox/managers/IslandsManager.java) and the [PlayersManager](https://github.com/BentoBoxWorld/BentoBox/blob/develop/src/main/java/world/bentobox/bentobox/managers/PlayersManager.java).

More specifically, if you want to check if the player has an island, you need to use to methods.
- `IslandsManager#hasIsland(...)` returns true if the player **owns** an island.
- `IslandsManager#inTeam(...)` returns true if the player is **in a team** (i.e. he is member on an island but does not own it).

**Comment by Rsl1122** [comment]
Thanks :)

**Comment by Poslovitch** [comment]
Thanks for getting things started with that Extension. I feel ashamed I haven't started it before... My excuses.

**Comment by Rsl1122** [comment]
Alright, I got something similar to the ASkyBlock Extension done for AcidIsland, BSkyBlock, CaveBlock and SkyGrid - just to confirm, can those names be used to get the `GameModeAddon` for those plugins from `AddOnManager` ([in this manner](https://github.com/plan-player-analytics/Extension-BentoBox/blob/master/src/main/java/com/djrapitops/extension/BentoBoxExtension.java#L82))?

----

Here is a test build 
[Plan-5.0 dev build 383.jar.zip](https://github.com/plan-player-analytics/Plan/files/4112105/Plan-5.0.dev.build.383.jar.zip)

I didn't have time to test it today, but I'll do so some time next week.

**Comment by Poslovitch** [comment]
Your Implementation looks good.
