### ISSUE TITLE
Request an option to manually update player ban status

### ISSUE THREAD

**Issue by CypherPhyre** [plan-player-analytics/Plan#729]
### Is your feature request related to a problem? Please describe.
I recently had to ban two players from my server for breaking server rules. One shows the (Banned) status and the other only shows (Inactive) when viewed on the Player List Activity Index. Both were banned less than 30 seconds apart.

### Describe the solution you'd like
I would like a command option to manually change the players status in regards to bans or a way to force a status update if it is not caught automatically as this throws off the overall Player to Server stats.

**Comment by Rsl1122** [comment]
Was this on the `/players` page or `/server` page?

For players page, follow issue #707

For server page, you can try increasing Analysis Periodic Refresh setting in the config.

**Comment by CypherPhyre** [comment]
On both. AutoRefreshPeriod: 30 Also, the bans occurred 4 days ago now. The server has been restarted many times since as well as the plugin itself being reloaded. Refreshing the pages has no effect on this. They do not share the same IP only a common geolocation of being from the UK.

**Comment by Rsl1122** [comment]
Added a task here
https://github.com/plan-player-analytics/Plan/projects/13
