### ISSUE TITLE
Feature request: Enable #include in HTML

### ISSUE THREAD

**Issue by SlimeDog** [plan-player-analytics/Plan#775]
It would be a nice feature to support (the equivalent of) #include. Use case:

I have some content in my heavily-customized Plan server.html, that I would like to appear in multiple places (six, to be precise). In normal HTML, I would use a #include, but that does not work with the generated HTML of Plan.

With advise from RSL, I converted to HTML5 and tried OBJECT code, but the objects are read too late in the stream to work.

**Comment by Rsl1122** [comment]
Note: Chrome will be removing imports in 2019, which provide a similar functionality as html5 object tag. 

https://bugs.chromium.org/p/chromium/issues/detail?id=766694

(Does not make this infeasible, just a note so that I won't use that when doing this)

**Comment by Rsl1122** [comment]
I think the redesign has better chances of working with include as less content is created on the Java side.

I am closing this issue as it is unfortunately not possible to add this as a feature due to extra maintenance it might bring in the future.
