### ISSUE TITLE
Record IP's players join from

### ISSUE THREAD

**Issue by BiGUNMAN** [plan-player-analytics/Plan#783]
A few servers (such as my own) use various subdomains to measure success of advertisements. For example, I have mcsl.(server).com, to measure how much players come from the MCSL server list. Then for a seperate advertisement campaign, I might have another subdomain, such as youtuber.(server).com. 

Recording and displaying what IP's people join from (on bungeecord) would be incredibly useful for determining where your players are coming from.

**Comment by Rsl1122** [comment]
I would imagine would also be useful on a bukkit/sponge server too, although I am unsure if it is doable there.

As far as I know, it is possible to change spawn location based on the IP connected from, so this is doable on Bungeecord. I just don't know how that was done yet.

----

If anyone has more info on how to do this, advice is appreciated. :)

**Comment by BiGUNMAN** [comment]
It's the following bungeecord method `player.getPendingConnection().getVirtualHost().getHostString();`

**Comment by DeepRobin** [comment]
But ips must be removed after some time, because GDPR.

**Comment by Rsl1122** [comment]
@DeepRobin IPs are appropriately anonymized to not count as personal data.

**Comment by DeepRobin** [comment]
@Rsl1122 Yeah, i know, because of this i deleted my comment 👍 . I haven't read the issue fully

**Comment by Rsl1122** [comment]
Information from a duplicate ticket

### Describe the solution you'd like

Added server address information to each session

The subdomain can be obtained with `AsyncPlayerPreLoginEvent` `event.getAddress().getHostName()`

### Additional context

Suggested on discord by AndGK#0001

> Hey, I have a suggestion. Can you add a feature to track what subdomain users use to join server for the first time? Say I have mc1.server.com and mc2.server.com. User joins using mc2.server.com for the first time then save that and record to statistics and display which subdomain gets more unique life-time joins.
This is the code one of papermc users made to track that, but its not unique joins and just writes down number of joins to a file, this may save you some time though
