### ISSUE TITLE
Rewrite event handling to be pipeline based

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#817]
### Is your feature request related to a problem? Please describe.

Current event listening system places multiple Runnables to be processed by `Processing`, which consists of non-critical and critical executors.
Because each runnable saves a single thing, dependencies such as user - session can cause exceptions in cases where execution order is wrong.

### Describe the solution you'd like

I would like an event mediator, that holds the events until processed. These events should be custom objects that hold the time they occurred. This will also help in mitigation of #758 (Bot attacks)

The events could have "Epoch ms to process" variable. This would allow addition of a delay for processing that is configurable.
With the addition of a delay, batch processing of some events by type would become possible.

This addition may require changes to the current `SessionCache` that handles Session entries and other places that call `System.currentTimeMillis()`, as they would now have to rely on the time given by the event.
Most current processing already does.

### Additional context

The current processing system has proven itself to be reliable, and should **not** be gutted during this addition, instead utilizing it after the mediator for execution.

For example this exception is caused because of flaws in the current system
https://pastebin.com/mNGwFXV5

**Comment by Rsl1122** [comment]
Evaluating this again.

There have been changes in the way data is sent to the database (see the issue 818 above) - now data is saved with Transactions based a single database ExecutorService. This prevents issues mentioned above.

----

An issue exists though, where the gathering code is duplicated for each platform even though the events are almost the same for Bukkit, Sponge & Nukkit, and Bungee & Velocity respectively.

Abstraction of the events would be one option, where each platform wraps their event to a common interface and fires the events using event mediator (New thing to add).

## What problem does it solve? (is this really useful)

- Listener classes are doing more than one thing (Example: PlayerJoinEvent causes JSONCache invalidation, storage of new data, session start, extension data update and player page export)
- Duplicate code exists in platform modules (the listener logic)

### Pros

- Asynchronous processing of all events
- Potential for batch processing (is this useful?)
- Potential for moving acting code closer to the affected class (eg. SessionCache has a method that listens for PlayerJoinEvents)
  - Needs some oversight to avoid issues that come from unambiguous execution order
- Less duplicate code in each platform's listener classes
  - Easier changes to event listeners (not very common)

### Cons

- Additional event processing channel (+complexity) on all platforms
- Small memory usage increase
