### ISSUE TITLE
Player Action Statistics

### ISSUE THREAD

**Issue by MildKid** [plan-player-analytics/Plan#824]
### Describe the feature you'd like
I'd love to have a way to track and visualize specific player statistics over time such as "distance walked", "logs mined", "passive mobs killed," etc.  

### Describe alternatives you've considered
I've used the Vanilla scoreboard system but it's rather clunky and not easy to use.  I imagine there are already plugins that do this but I couldn't find any and it would be nice to have accessible from the Plan interface.

I'm unsure if this idea is similar to the "Insights" or "Actions" systems mentioned elsewhere.

**Comment by Rsl1122** [comment]
Hello,
I saw a stats plugin earlier that had these, but unfortunately the generic name means that it is impossible to find at a moments notice. 

----

I think this falls under "nice to have" data, here is an image of ideas that came up during last data refactoring.
![Example](https://camo.githubusercontent.com/8fcf91837afaf833bdb4f2492a5bae7a4a2ad320/687474703a2f2f7075752e73682f414268716b2f666138636264313630332e6a7067)

During this refactoring I wanted to find data that is not just for the sake of having data, but something that can be deduced from the data collected.

What I think might be useful data in line with your suggestion:

- Distance walked per session, could be used to improve player retention calculations
- Number of messages sent during a session, could be used to improve activity index calculations
- Other, what?

I'm still on the edge on these two though, as I don't want Plan to become "knows everything your players do"-plugin as these could be used against staff if not deemed "active enough".

Numbers hide people.

*Sorry, it's late, I'm rambling again..*

----

> ***Why epic***
> *`p: #` is a Story Point estimate for implementing this issue. This issue contains large number of smaller issues, or can be extended to cover more and more things indefinitely. If you would like to help lower the Story Point rating, please list and prioritize the individual features that would generate the most value to you.*

**Comment by Rsl1122** [comment]
Closing as 'Out of scope' because there are too many things that would fit this feature and so it's pretty impossible to start working on this. If you would like you can open new issues about a single statistic at a time
