### ISSUE TITLE
Last play session's Average ping

### ISSUE THREAD

**Issue by ConfuseN** [plan-player-analytics/Plan#864]
### Is your feature request related to a problem? Please describe.

I would like to use PLAN to verify players pings for administrative purposes/anticheat

### Describe the solution you'd like

The ability to see the players ping in their last play session would be useful, especially for counter acting the claim of "i was lagging, not hacking" in regards to anticheat false positives.

### Describe alternatives you've considered

If getting the average ping in the last session is to hard, the ping before the player quits could be useful too. Can't really think of another alternative

### Additional context

For example, today I had a new player play for 9 minutes, in that time my anticheat picked up on him and I banned him. Since he was new I was able to see his average ping for the 9 minutes he played. He claimed he was lagging, however PLAN says otherwise.

However if he wasn't a new player, I wouldn't have been able to use PLAN to determine if he was lagging since the average ping would account for all his play-sessions.

**Comment by Rsl1122** [comment]
Per session ping is doable with quite small amount of code :)
