### ISSUE TITLE
Optionally store / show full IP address

### ISSUE THREAD

**Issue by fjeddy** [plan-player-analytics/Plan#896]
Hello,

Hiding the last 4 digits of the IP is a good thing, without a doubt. But it should also be optional, configurable through the config files.

I don't disagree with the fact that the IP's should be anonymized, but it should be at the server owners discretion, not the creators of Plan Analytics.

I want to use Plan Analytics for the information stored in MySQL, I have no interest in your web-panel or anything driven and run outside the actual data collection itself. It's the data I want, nothing else. Tho, the IP being removed at store, hinders me from using this the way I intend, as I need and want to run my own analysis and queries around the IP before I anonymize it myself.

I might be missing something, and this is already optional, if that's the case, then please enlighten me :)

**Comment by Rsl1122** [comment]
Please see `Data_gathering.Geolocations` as well as `Display_options.Show_player_IPs`

**Comment by Rsl1122** [comment]
IP anonymization is on by default due to GDPR (European General Data Protection Regulation)

**Comment by fjeddy** [comment]
Right, and as I mentioned, then it shouldn't. But instead, be optional, aka, if I want to turn it on, I should be able to.

`Data_gathering.Geolocations` is related to your free maxmind database.
`Display_options.Show_player_IPs` is related to your web-panel. And of no interest.

**Comment by Rsl1122** [comment]
`ip_hash` is a SHA256 hash of the unanonymized IP.

**Comment by fjeddy** [comment]
Right, which doesn't help me, considering SHA256 can't be decrypted. It would be great if you commented on my actual concern / question here tho, not answer trivial questions i'm not asking.

To repeat myself: Respecting GDPR (If you actually have European users, you assume everyone is European) and the option to anonymize the IP or not should be a feature the server owner / user can enable / disable at their own discretion. Not something forced down your throat.

As a reference, I would recommend that you look into the largest open source analytics software out there, Matomo, or Piwik if you will.

**Comment by Rsl1122** [comment]
It's of course doable, but currently it's built into the collection system and the IP is anonymized the second it's placed in the `GeoInfo` object.

I can look into it at some point.

**Comment by fjeddy** [comment]
Great :)

As a side note: There is a limited number of available IPv4 addresses in the world. Creating a complete database with all of them, converted to SHA256, is not even remotely hard to do. Hence, in many ways, the IP isn't anonymized at all, it just looks like it for the regular user.

**Comment by Rsl1122** [comment]
IP hashes have been removed from the database.
