### ISSUE TITLE
set performance data collection (tps, etc) custom interval 

### ISSUE THREAD

**Issue by mechcalvin** [plan-player-analytics/Plan#910]
### Is your feature request related to a problem? Please describe.
now it is set to 1 sec, it affect the server performance

### Describe the solution you'd like
it can be customize for longer interval for better server performance

**Comment by Rsl1122** [comment]
This one will require more work than what I expected.

I'll have to do some math on calculating the TPS from diff between multiple seconds since CraftBukkit uses a manual calculation that relies on a per-second interval.

Pushed back due to the complexity increase

**Comment by Rsl1122** [comment]
Recent gathering task optimizations have made making this change easier, but also less necessary.

The optimized task doesn't show up in Paper Timings, so I think the underlying issue in this request is resolved. I'll close this issue, but if you think it should still be implemented, please give some arguments for it and I'll re-open the issue.

**Comment by mechcalvin** [comment]
The other reason is that it makes the mysql table enormously large within a short peroid of time

**Comment by Rsl1122** [comment]
The gathering period is 1 second, but the storage period is 60 seconds. What size do you consider enormously large?

**Comment by mechcalvin** [comment]
Didn't know that, I haven't used this since couple of months due to this problem, but I remember i had over 100K+ entries after a month for single type of data.

say 1 minute record, a day will create 60 x 24 = 1440 entries for tps, i have 3 servers connected by bungeecord, so 4320 entries for a day, a month will have 129600, a year will have 1.5 M... and that's just for tps

**Comment by Rsl1122** [comment]
I'd estimate 1.5M entries as 1800 Mb

**Comment by Rsl1122** [comment]
You can reduce the storage of the time series data in the Pla config under `Time.Thresholds.Remove_x_after`
