### ISSUE TITLE
wrong config file

### ISSUE THREAD

**Issue by tonnic** [plan-player-analytics/Plan#922]
### Additional information

**Frequency of occurrence**: <>

**Other:**

**Comment by tonnic** [comment]
It creates a config for PixelmonGym.

9:36:28 PM CONSOLE: [INFO] Processing critical unprocessed tasks. (0)
9:36:28 PM CONSOLE: [INFO] Processing complete.
9:36:28 PM CONSOLE: [INFO] Player Analytics Disabled.
9:36:28 PM CONSOLE: [ERROR] Error was caught by com.djrapitops.plan.PlanSponge
9:36:28 PM CONSOLE: value for Plugin.Logging.Debug has a bad value: 'null'
9:36:28 PM CONSOLE: [ERROR] CRITICAL error triggered a plugin shutdown.
9:36:28 PM CONSOLE: [INFO] Processing critical unprocessed tasks. (0)
9:36:28 PM CONSOLE: [INFO] Processing complete.
9:36:28 PM CONSOLE: [INFO] Player Analytics Disabled.
9:36:28 PM CONSOLE: [ERROR] Plugin Failed to Initialize Correctly. If this issue is caused by config settings you can use /plan reload
9:36:28 PM CONSOLE: [ERROR] This error should be reported at https://github.com/Rsl1122/Plan-PlayerAnalytics/issues
9:36:28 PM CONSOLE: [INFO] Processing critical unprocessed tasks. (0)
9:36:28 PM CONSOLE: [INFO] Processing complete.
9:36:28 PM CONSOLE: [INFO] Player Analytics Disabled.

**Comment by Rsl1122** [comment]
The fix for this issue is to start using Asset API on Sponge.

Unfortunately the file access classes are a convoluted mess and need a larger refactor to fix this.

Pushed back due to complexity increase.

**Comment by 2iguys** [comment]
I am also having a similar issue. where it created the config from Maintenance instead of its own.
