### ISSUE TITLE
Move CI out of Travis CI

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#926]
### Is your feature request related to a problem? Please describe.

Recently Travis CI was acquired by Idera. A lot of the staff was gutted this week. [More](https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/)
Since the future development of Travis appears unclear, I feel like moving to another service some time in the future.

### Describe the solution you'd like

CircleCI provides a free CI service for open source projects

### Describe alternatives you've considered

- Azure dev pipelines

### Required work:

- Configuration
- MySQL installation
- Selenium installation
- Env variables

**Comment by RoboMWM** [comment]
AppVeyor is also an option, provides free hosting of artifacts too.

**Comment by Rsl1122** [comment]
Good shout, I'll put that into consideration as well.

**Comment by Rsl1122** [comment]
Moved to high priority due to recent service outage

**Comment by Rsl1122** [comment]
Today all java 7 and 8 based builds are experiencing build failures due to them using a jdk install script outside their control - that updated and broke things.

Work on this should be started asap.
