### ISSUE TITLE
Link to ore on Sponge for updates

### ISSUE THREAD

**Issue by AuroraLS3** [plan-player-analytics/Plan#936]
### Is your feature request related to a problem? Please describe.
Ore guidelines state:

> ### Update Checking
>
> Checking for updates should be performed using the provided Ore API. Your plugin may not link anywhere but Ore when directing users of your plugin to download new versions. --

### Describe the solution you'd like

Extend VersionCheckSystem to check updates from Ore on Sponge.

**Comment by rymiel** [comment]
Given that only release versions are uploaded to Ore, should the sponge version checker disregard the "show dev updates" option?
