### ISSUE TITLE
Error after using /planbungee reload

### ISSUE THREAD

**Issue by MicleBrick** [plan-player-analytics/Plan#955]
Ran the /planbungee reload command, encountered this error message whenever doing `/planbungee servers`: "Database is CLOSED - Please try again a bit later." Required a restart to fix. Hikari threw a bunch of database is closed exceptions.

**Comment by Rsl1122** [comment]
The error message is correct, although it does not tell why the database was closed.

When the database is closed the queries passed after the close will error out.
