### ISSUE TITLE
Player search query feature

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#963]
### Is your feature request related to a problem? Please describe.

It is currently not easy to find data about a group of players, for example players who joined after a certain date. (See #940)

### Describe the solution you'd like

`/search` page that has the following filters:

- Data date `Before date` & `After date`
- Registered between `Before date` & `After date`
- Name / Nickname contains name
- Geolocation
- (#638 In Plugin defined groups) 
- Possibility to sort the results

Data that should be presented:

- Player name
- Playtime (Active/total) & other session info (such as activity index) during the Data date range
- Groups the player is in (+ geolocation)
- Register & Last seen date

### Additional context

Current analysis is limited to the server side, so finding data about a specific player group would resource intensive.
The search should update the page only when a request is made. (No live search)

**Comment by tonnic** [comment]
Under performance you can see how many people were logged in at any point in the graph. Would be great to see who those players were at the time as well. Can help if performance significantly drops and then you can talk to or query the players what happened

**Comment by Rsl1122** [comment]
Designing the different filters..
Oh boy this is going to be a beast to write code & SQL for

![kuva](https://user-images.githubusercontent.com/24460436/77358926-74f2be00-6d53-11ea-81a2-cf3077c595e9.png)

----

During this design process I realized that search and this feature are two different things.
The thing I've outlined in the original comment is more like a Query, and that's why there is no search bar in the design - as searching for a single user should be achieved in a different way. Currently the /players page search box is the best method, and the same search box will be available for the results. This feature will be for understanding groups of players with specific information.

To make it simple for the user to adjust their query in case of 0 results, some feedback should be presented.

----

I think the most simple way to create this feature would be to write a `Filter` that returns a `Set<UUID>`. These sets could then be conjoined together to get a final set of UUIDs to show data for. The data would be queried with an SQL that has `uuid IN ('uuid1', 'uuid2')` as the filter.

This way the feedback for each filter is available as set size and filters that produce an empty set return early - This would also speed up the queries as most expensive queries can be executed last.

**Comment by Rsl1122** [comment]
# Progress update

- [x] Data date Before date & After date (view selector)

## Filters

- [x] Registered between Before date & After date
- [x] Played between filter
- [x] Operators / non operators filter
- [x] Banned / non banned filter 
- [ ] Name / Nickname contains name
- [ ] Geolocation
- [ ] In Plugin defined groups

## Results

- [x] Possibility to sort the results
- [x] Player names
- [x] Session info during the Data date range
  - [x] Playtime
  - [x] Session count
  - [x] Activity index
  - [ ] Active playtime
- [ ] Plugin groups the player is in
- [x] geolocation
- [x] Register & Last seen date

## Usability

- [x] Sharing the query results with others
  - [ ] Cleaning up old query result files
- [ ] Editing a previous query
- [ ] Seeing the player match process of different filters
- [x] Adding new filters dynamically
- [ ] Removing filters
- [ ] Moving filter order
- [ ] Preventing incorrect values from being entered in the query
- [ ] Giving context when selecting a date
  - [ ] Use a graph for selecting a date! (Keep in mind that session data might exist beyond players online data)
- [ ] Comparing two slightly different queries is difficult (Each query needs to be remade from scratch)
- [ ] Access to query page from other pages
  - [ ] Links in the sidebar
  - [ ] Assess 'Query with this selection' -button to graphs with time selectors?

## Given requirements

- [x] Find playtime of different players within a certain timeframe
- [x] Possible to sort by playtime (highest to lowest)
- [ ] Find information about staff
  - [x] Find information about operators
  - [ ] Find information about players with staff ranks

## Bugs

- [ ] View selector dates are flipped when making the query (The date on the right is used for "data after" date)
- [ ] Date formatter formats 01012016 as 32/12/2015
- [ ] It is possible to perform query with incorrect form entries
- [ ] Empty query results in an "Query expired" error
- [ ] Error box is displayed improperly

**Comment by Rsl1122** [comment]
Current state of the results page (Pretty much consists of copy-pasted queries with a WHERE clause modification to use the filters and view instead)

![image](https://user-images.githubusercontent.com/24460436/105019807-31d6a980-5a4f-11eb-8b70-bee81874ed9e.png)

**Comment by TheMattVid** [comment]
This looks amazing, thanks for all the hard work! Will/can there be a display of the amount of non-afk time between our specified time range?

**Comment by Rsl1122** [comment]
Hi @TheMattVid 
Playtime in this image was swapped to Active Playtime a bit after the image was taken.
You can test this feature with https://github.com/plan-player-analytics/Plan/releases/tag/5.2.902 by going to /query on the panel.

All feedback appreciated :)

**Comment by TheMattVid** [comment]
Slightly related question, is it possible to get active playtime to show in the calendar view on the player activity page rather than the total playtime?

**Comment by Rsl1122** [comment]
> Slightly related question, is it possible to get active playtime to show in the calendar view on the player activity page rather than the total playtime?
It's a task to swap them https://github.com/plan-player-analytics/Plan/projects/13#card-46264969

Probably, but I'll do other things first

**Comment by Rsl1122** [comment]
A gif showcasing the view selection with help of the players online graph (Observe how the time fields change when graph view is changed)
![plan-query-view-select](https://user-images.githubusercontent.com/24460436/106261345-1f682700-622a-11eb-87d6-6dd4d9f3d164.gif)
