### ISSUE TITLE
How to change Timezone?

### ISSUE THREAD

**Issue by TempelGames** [plan-player-analytics/Plan#978]
Hello,

On the web-page is the time incorrect for my Country. 
How i can change the Timezone?

Thanks

**Comment by Rsl1122** [comment]
Currently only server timezone or UTC (GMT+0) are available with the setting `Time.User_server_timezone`
https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Configuration#time

**Comment by TempelGames** [comment]
Time.User_server_timezone is true. But sadly its not working in Germany.

**Comment by Rsl1122** [comment]
Is your server's timezone set to Germany's timezone?

If you decide to change your server's timezone, please note that the timezone is affected by timezone of JVM, which is determined when the java process starts.

**Comment by TempelGames** [comment]
How i can set it to Germanys timezone?

Sorry but i am very confused xD

**Comment by Rsl1122** [comment]
That depends on your server's operating system (Ubuntu / Debian / Windows Server / etc)

**Comment by TempelGames** [comment]
I use Ubuntu 14.06. Can i change it in the Terminal?

**Comment by Rsl1122** [comment]
This should help: https://askubuntu.com/questions/3375/how-to-change-time-zone-settings-from-the-command-line

**Comment by TempelGames** [comment]
Thank you so much :)
