### ISSUE TITLE
Safari on iOS fails to open login prompt

### ISSUE THREAD

**Issue by Rsl1122** [plan-player-analytics/Plan#982]
### Describe the bug

Safari on iOS fails to open login prompt due to `;` in HTTP headers

https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/system/webserver/RequestHandler.java#L107

### Additional information

Reintroduced by accident in 4.7.0 when adding login bruteforce prevention

**Comment by Aurelien30000** [comment]
I can confirm this issue, if you need more confirmations ^^.
Without wanting to offend you, is it possible to know when do you solve this bug because it has been bothering me for quite some time now, I should have reported it to you earlier, but seeing it in the list, I jumped at the chance ;)

Sorry in advance for my english, i wrote it with a translator :/

**Comment by Rsl1122** [comment]
Next release, although I'm not sure when that will be.
If I feel like going on a bug bashing spree it might come as 4.7.3, if not then on 4.8.0 with the DataExtension API.

**Comment by Rsl1122** [comment]
Here is a dev version with the fix (Built from the commit above).
You can test to see if it works.

[Plan-4.7.2#982.zip](https://github.com/plan-player-analytics/Plan/files/3009780/Plan-4.7.2.982.zip)

**Comment by Aurelien30000** [comment]
I'll let you know, thank you very much :)

**Comment by Aurelien30000** [comment]
Unfortunately it doesn't work :/ Same error with different browsers.

**Comment by Rsl1122** [comment]
Could you check if 4.6.2 has this issue

**Comment by Aurelien30000** [comment]
Yep, i'am testing :)

**Comment by Aurelien30000** [comment]
In this version, i'ts working ! Just a little question, do i need to send your beta version on all my servers even if my site is on BungeeCord ?

**Comment by Rsl1122** [comment]
The attempted fix was for browser headers, so only on Bungee is needed.

**Comment by Aurelien30000** [comment]
Ok, so I summarize the results ;)
5.6.2 - **Functional**
5.7.2 / 5.7.2-b01 - **non-functional**

If you need help, I can offer you my services, in my abilities of course :p

**Comment by Rsl1122** [comment]
I found two more instances of `;` next to the `WWW-Authenticate` header, one of them was the default one (So makes sense that it didn't work)

Here is a build from the commit above
[Plan-4.7.2#982.zip](https://github.com/plan-player-analytics/Plan/files/3012059/Plan-4.7.2.982.zip)

**Comment by Aurelien30000** [comment]
Great ! I’ll test your build this afternoon because i’am currently at work :)

**Comment by Aurelien30000** [comment]
Awesome ! It is perfectly functional on any IOS browser, I thank you very much :)

Ps: Can I keep this version with the correction while waiting for the "official" release without any problem ?

**Comment by Rsl1122** [comment]
Yes this version is usable.
