### ISSUE TITLE
Plan does not load correctly on KCauldron (Bukkit Remake)

### ISSUE THREAD

**Issue by g0d-gam3** [plan-player-analytics/Plan#983]
### Describe the bug
When PLan is put on KCauldron in the Plugins folder Plan will say its loading, but never load and not generate any configs. The only command available is /plan <name>

### Server information
KCauldron
MC Version 1.7.10
Latest Plan Version

### Additional information
KCauldron was built of bukkit and can run Spigot Plugins normally, so I believe Plan just is not picking that it should run as if it was on a spigot/bukkit server.

**Frequency of occurrence**: <>

**Other:**

**Comment by Rsl1122** [comment]
Try updating special source
https://github.com/DiscordSRV/DiscordSRV/wiki/FAQ#fix-for-kcauldron

**Comment by g0d-gam3** [comment]
That worked perfectly, thank you <3

**Comment by Rsl1122** [comment]
I added a KCauldron section to the Bukkit Set-up tutorial since this kind of issue pops up from time to time.

https://github.com/plan-player-analytics/Plan/wiki/Bukkit-Set-Up#kcauldron
