### ISSUE TITLE
Wrong color in graphics

### ISSUE THREAD

**Issue by yaroslav4167** [plan-player-analytics/Plan#992]
![WGeG](https://user-images.githubusercontent.com/18057310/55653060-a2b2c000-57ed-11e9-9dde-0f857f8089ae.png)

**Comment by Rsl1122** [comment]
This is because the tps graph can have 3 different colors based on how high the value is.
HighCharts shows the default color since the base color is not set.

I can try if it is possible to have both base color and multiple colors set, but I doubt it.

**Comment by yaroslav4167** [comment]
Draw 3 lines next to the TPS =)
![Yh5E](https://user-images.githubusercontent.com/18057310/55659536-705f8d80-5802-11e9-9981-c0e3d9cc9d51.png)

**Comment by Rsl1122** [comment]
Off topic answer: Set them up to the same mysql.

**Comment by Rsl1122** [comment]
It was not possible to draw 3 lines, but it was possible to set a base color.
Now the label has the color of high threshold.
