### ISSUE TITLE
UUID are not converted into player name.

### ISSUE THREAD

**Issue by Aurelien30000** [plan-player-analytics/Plan#994]
### Describe the bug

In a player page analytic, in the session category, player kill names are not with name but with uuid : 

![Capture](https://user-images.githubusercontent.com/43724816/55671313-43a58780-588f-11e9-9c69-e94780028a48.PNG)

### Server information

Plan version 5.8.0 release, Paper-Spigot linked to Bungee.

### Exceptions & Other Logs

No presence

### Additional information

No presence

**Frequency of occurrence**: <a>
Everytime

**Other:**
/

**Comment by Rsl1122** [comment]
Caused by wrong method call in 
https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/java/com/djrapitops/plan/utilities/html/graphs/calendar/PlayerCalendar.java#L124

Supposed to call `PlayerKill#getVictimName` but calls `PlayerKill#getVictim`
