### ISSUE TITLE
I can't join!

### ISSUE THREAD

**Issue by Juan123321** [plan-player-analytics/Plan#996]
Every time i try to go in my server with this plugin.
people arn't able to join, so can't me.
Every thing is frozen when I try to write something in console, console is just frozen

![e](https://user-images.githubusercontent.com/49380205/55693186-4c6f8980-5973-11e9-853c-d3d0451ce77d.PNG)

**Comment by Rsl1122** [comment]
Could you send more information about your server?

Here are my suggested steps for debugging (I don't have much info, so these are shots in the dark):

- Update to latest version of the plugin (4.8.1) if not already
- In Plan config under `Plugins` disable all integrations
- Enable debug setting in the Config, start the server and after a bit send the output file in /plugins/Plan/logs (This is to see if the plugin is stuck on something)

**Comment by Juan123321** [comment]
Here are my server details!

1.8.8 Spigot

and the version of Plan is 4.8.1

**Comment by Rsl1122** [comment]
Try changing `Database.Type` to h2 (or Mysql if you have one) 1.8 has been having issues with sqlite lately.

**Comment by Juan123321** [comment]
I went in config and I can't find Database.Type. and I don't know my Mysql.

please help

**Comment by Rsl1122** [comment]
https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/config.yml#L28

**Comment by Juan123321** [comment]
Thanks it worked!
